"""behaviour.py — util.behaviour. Query/report front-end for `cfg_behaviour_class`/
`cfg_behaviour_rule` (escalations #715/#732/#733).

Read-only — content is written by the one-off migration scripts
(`bootstrap_behaviour_rules_v1_20260818.py` and its cycle-2/3/... siblings), not this module. This
closes a completeness gap found live during #733's structural read-through: the operational-
behaviour system had three build cycles (37 rules, 5 classes) and no supporting PS entry point —
only reachable via raw sqlite3/ad-hoc Python — exactly what
`development.every-interactive-module-needs-ps-script` (added the same cycle) exists to catch.

CLI (module path: iba.app.lib.behaviour, invoked as `python -m iba.app.lib.behaviour`):
    python -m iba.app.lib.behaviour list [--class=chat|terminal|sqlite|documentation|llm_output|development]
"""

from __future__ import annotations

import pathlib
import sys

from . import reportkit
from .cfg import Cfg
from .db import Db


def write_list_report(cfg: Cfg, db: Db, path: pathlib.Path,
                       class_filter: str | None = None) -> tuple[pathlib.Path, int]:
    classes = db.conn.execute(
        "SELECT class, description, authoritative_doc FROM cfg_behaviour_class "
        "WHERE inactive=0 ORDER BY class").fetchall()
    lines = ["# Operational-behaviour rules — live report", "",
             "_Generated by `python -m iba.app.lib.behaviour list` (`Behaviour.ps1 -Action "
             "List`) — source of truth is `cfg_behaviour_class`/`cfg_behaviour_rule`, not this "
             "file. Regenerate rather than hand-edit._", ""]
    total = 0
    seen_any_class = False
    for c in classes:
        if class_filter and c["class"] != class_filter:
            continue
        seen_any_class = True
        rules = db.conn.execute(
            "SELECT rule_key, rule_text, source, enforced_by FROM cfg_behaviour_rule "
            "WHERE class=? AND active=1 ORDER BY id", (c["class"],)).fetchall()
        total += len(rules)
        lines += [f"## `{c['class']}` ({len(rules)} rule(s))", "",
                  c["description"], "",
                  f"**Authoritative doc:** {c['authoritative_doc'] or '_none set_'}", ""]
        if not rules:
            lines.append("_no active rules_")
        for r in rules:
            lines += [f"- **{r['rule_key']}** — {r['rule_text']}",
                      f"  - source: {r['source']}",
                      f"  - enforced_by: {r['enforced_by'] or '_not set_'}"]
        lines.append("")

    if class_filter and not seen_any_class:
        lines.append(f"_no active class named '{class_filter}'_")

    reportkit.archive_before_write(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    text = "\n".join(lines).rstrip() + "\n"
    path.write_text(text, encoding="utf-8")
    return path, total


def main() -> int:
    cfg = Cfg()
    db = Db(cfg)
    argv = sys.argv[1:]
    if len(argv) >= 1 and argv[0] == "list":
        class_filter = None
        for a in argv[1:]:
            if a.startswith("--class="):
                class_filter = a.split("=", 1)[1]
        path = pathlib.Path(cfg.required_setting("behaviour.list_report_path"))
        out, total = write_list_report(cfg, db, path, class_filter)
        print(f"  {total} active behaviour rule(s) -> {out}")
        return 0
    print("usage: python -m iba.app.lib.behaviour list [--class=<class>]")
    return 1


if __name__ == "__main__":
    sys.exit(main())
