"""cataloguereport.py — structural report over `wa_obs_question_catalogue` (bible_research.db),
deliberately scoped to that ONE table (no joins to `finding`/`finding_question_link`/etc. — this is
a review of the catalogue's own shape, not a findings report). Built 2026-08-29, escalation #1007
(second half of the catalogue-tool thread — the first half, extraction + table consolidation, is
BUILD.md secs 200-206; this is the "structured report, no findings" the researcher asked for on
top of that).

Content follows directly from the table's own `cfg_column.use` notes (already on file, written
during #1007's earlier phases) — every structural problem named there is surfaced here as an actual
section, not just described in prose: the status/deleted lifecycle disagreement, the two competing
section-naming schemes (`Section N` vs `Tn`), the tier/component gaps, question_code prefix sprawl,
and date_added format inconsistency. Purpose (researcher, verbatim): "to evaluate and augment the
questions and structure around it."

Reads `bible_research.db` directly via `cfg.database_path('bible_research')` (the same cross-
database pattern `lib/prosestore.py` already uses) — `reportkit`'s scaffold machinery still reads
its own config (`cfg_report`/`cfg_report_section`) off `cfg.conn` (iba.db), since that's where
every report's config lives regardless of which database its DATA comes from.
"""

from __future__ import annotations

import pathlib
import re
import sqlite3

from . import reportkit

_TABLE = "wa_obs_question_catalogue"


def _tbl(headers, rows):
    L = ["| " + " | ".join(headers) + " |", "| " + " | ".join("---" for _ in headers) + " |"]
    for r in rows:
        L.append("| " + " | ".join(str(c) if c is not None else "" for c in r) + " |")
    return L


def _question_code_prefix(code: str) -> str:
    m = re.match(r"^([A-Za-z]+)", code or "")
    return m.group(1) if m else "(none)"


def _date_added_format(d: str) -> str:
    d = d or ""
    if re.match(r"^\d{8}$", d):
        return "YYYYMMDD"
    if re.match(r"^\d{4}-\d{2}-\d{2}", d):
        return "ISO-8601"
    return "other"


def write_report(cfg, path: pathlib.Path) -> pathlib.Path:
    conn = sqlite3.connect(cfg.database_path("bible_research"))
    conn.row_factory = sqlite3.Row
    q = lambda sql, p=(): conn.execute(sql, p).fetchall()

    total = q(f"SELECT COUNT(*) n FROM {_TABLE}")[0]["n"]
    all_rows = q(f"SELECT * FROM {_TABLE} ORDER BY obs_id")

    # ── overview ────────────────────────────────────────────────────────────────────────────────
    status_ct = q(f"SELECT status, COUNT(*) c FROM {_TABLE} GROUP BY status ORDER BY c DESC")
    deleted_ct = q(f"SELECT deleted, COUNT(*) c FROM {_TABLE} GROUP BY deleted")
    live = q(f"SELECT COUNT(*) n FROM {_TABLE} WHERE status='active' AND deleted=0")[0]["n"]

    intro = [
        "> Generated by `report.obs_catalogue`. A structural review of `wa_obs_question_catalogue` "
        "ON ITS OWN — no join to `finding`/`finding_question_link`/any other table. Purpose: "
        "evaluate and augment the catalogue's own questions and structure, per the researcher's "
        "own framing of escalation #1007.", "",
        f"- rows, total: **{total}**",
        f"- **live** (status='active' AND deleted=0 — the set actually in use): **{live}**",
    ]

    sections: dict[str, list[str]] = {}

    sections["overview"] = (
        ["**Lifecycle breakdown** — `status` and `deleted` are two separate lifecycle markers on "
         "this table and do not agree (see Lifecycle conflicts below for the exact rows):", ""]
        + _tbl(["status", "count"], [[r["status"], r["c"]] for r in status_ct])
        + [""]
        + _tbl(["deleted", "count"], [[r["deleted"], r["c"]] for r in deleted_ct]))

    # ── lifecycle conflicts ─────────────────────────────────────────────────────────────────────
    conflict_active_deleted = q(
        f"SELECT obs_id, question_code, section, catalogue_version, review_note FROM {_TABLE} "
        f"WHERE status='active' AND deleted=1 ORDER BY obs_id")
    conflict_other_live = q(
        f"SELECT obs_id, question_code, section, status FROM {_TABLE} "
        f"WHERE status!='active' AND deleted=0 ORDER BY obs_id")
    conflict_lines = [
        f"**{len(conflict_active_deleted)}** row(s) marked `status='active'` but `deleted=1` — "
        f"soft-deleted yet still labelled active. Every one of these needs a decision: either "
        f"`status` should be corrected off `'active'`, or `deleted` should be cleared if the "
        f"question is meant to be live.", ""]
    conflict_lines += _tbl(
        ["obs_id", "question_code", "section", "catalogue_version", "review_note (truncated)"],
        [[r["obs_id"], r["question_code"], r["section"], r["catalogue_version"],
          ((r["review_note"] or "")[:120] + ("…" if r["review_note"] and
                                             len(r["review_note"]) > 120 else ""))]
         for r in conflict_active_deleted])
    conflict_lines.append("")
    conflict_lines.append(
        f"**{len(conflict_other_live)}** row(s) marked non-active `status` but `deleted=0` — the "
        f"reverse conflict (checked for completeness; none found is a real, reportable outcome, "
        f"not a gap in this report)." if not conflict_other_live else
        f"**{len(conflict_other_live)}** row(s) marked non-active `status` but `deleted=0`:")
    if conflict_other_live:
        conflict_lines.append("")
        conflict_lines += _tbl(["obs_id", "question_code", "section", "status"],
                              [[r["obs_id"], r["question_code"], r["section"], r["status"]]
                               for r in conflict_other_live])
    sections["lifecycle_conflicts"] = conflict_lines

    # ── naming schemes ──────────────────────────────────────────────────────────────────────────
    section_ct = q(f"SELECT section, COUNT(*) c FROM {_TABLE} GROUP BY section ORDER BY section")
    tier_ct = q(f"SELECT tier, COUNT(*) c FROM {_TABLE} GROUP BY tier ORDER BY tier")
    version_ct = q(f"SELECT catalogue_version, COUNT(*) c FROM {_TABLE} GROUP BY catalogue_version "
                  f"ORDER BY c DESC")

    prefix_ct: dict[str, int] = {}
    date_fmt_ct: dict[str, int] = {}
    for r in all_rows:
        prefix_ct[_question_code_prefix(r["question_code"])] = (
            prefix_ct.get(_question_code_prefix(r["question_code"]), 0) + 1)
        fmt = _date_added_format(r["date_added"])
        date_fmt_ct[fmt] = date_fmt_ct.get(fmt, 0) + 1

    naming_lines = [
        f"**`section`** — {len(section_ct)} distinct free-text values, two competing naming "
        f"schemes running side by side (`Section N — ...` vs `Tn — ...`), plus a handful of bare "
        f"topic labels (`leviticus`, `redemption`) and word-specific `*Extensions` groups:", ""]
    naming_lines += _tbl(["section", "count"], [[r["section"], r["c"]] for r in section_ct])
    naming_lines.append("")
    null_tier_n = next((r["c"] for r in tier_ct if r["tier"] is None), 0)
    naming_lines.append(f"**`tier`** — null on {null_tier_n} of {total} rows (tiering was only "
                       f"ever applied to the restructured T0–T7 portion):")
    naming_lines.append("")
    naming_lines += _tbl(["tier", "count"], [[r["tier"], r["c"]] for r in tier_ct])
    naming_lines.append("")
    naming_lines.append("**`question_code` prefix** — the varied prefixes the catalogue accreted "
                       "from (`T`/`Q` are the restructured T0–T7 majority; the rest are older "
                       "families still in the table):")
    naming_lines.append("")
    naming_lines += _tbl(["prefix", "count"],
                        sorted(prefix_ct.items(), key=lambda x: -x[1]))
    naming_lines.append("")
    naming_lines.append("**`catalogue_version`** — free text, no single versioning convention:")
    naming_lines.append("")
    naming_lines += _tbl(["catalogue_version", "count"], [[r["catalogue_version"], r["c"]]
                                                          for r in version_ct])
    naming_lines.append("")
    naming_lines.append("**`date_added` format** — mixed formats, so the column will not sort "
                       "correctly as text without normalising first:")
    naming_lines.append("")
    naming_lines += _tbl(["format", "count"], sorted(date_fmt_ct.items(), key=lambda x: -x[1]))
    sections["naming_schemes"] = naming_lines

    # ── tier structure — the live (status='active', deleted=0), tiered set, for review ────────────
    tiered = q(
        f"SELECT tier, component_code, component_title, prompt_seq, question_code, question_text, "
        f"review_note FROM {_TABLE} WHERE status='active' AND deleted=0 AND tier IS NOT NULL "
        f"ORDER BY tier, component_code, prompt_seq, obs_id")
    tier_lines = [
        f"**{len(tiered)}** live, tiered questions (status='active', deleted=0, tier IS NOT NULL) "
        f"— the structured T0–T7 core, grouped by tier then component, in prompt sequence. This is "
        f"the set to review question-by-question.", ""]
    cur_tier = cur_component = None
    for r in tiered:
        if r["tier"] != cur_tier:
            if cur_tier is not None:
                tier_lines.append("")
            cur_tier = r["tier"]
            cur_component = None
            tier_lines.append(f"### {cur_tier}")
            tier_lines.append("")
        comp_key = (r["component_code"], r["component_title"])
        if comp_key != cur_component:
            if cur_component is not None:
                tier_lines.append("")
            cur_component = comp_key
            label = f"{r['component_code']} — {r['component_title']}" if r["component_code"] \
                else "(no component_code)"
            tier_lines.append(f"**{label}**")
            tier_lines.append("")
        note = f" _(review note on file)_" if r["review_note"] else ""
        tier_lines.append(f"- `{r['question_code']}` (seq {r['prompt_seq']}): "
                         f"{r['question_text']}{note}")
    tier_lines.append("")
    sections["tier_structure"] = tier_lines

    # ── unclassified — live, untiered questions, the integration candidates ───────────────────────
    untiered = q(
        f"SELECT section, question_code, question_text, scope FROM {_TABLE} "
        f"WHERE status='active' AND deleted=0 AND tier IS NULL ORDER BY section, question_code")
    unclass_lines = [
        f"**{len(untiered)}** live questions with no `tier` assignment — every one of these is a "
        f"candidate for integrating into the T0–T7 structure (or a deliberate exception, but that "
        f"decision has not been recorded anywhere on the row itself):", ""]
    unclass_lines += _tbl(["section", "question_code", "scope", "question_text"],
                         [[r["section"], r["question_code"], r["scope"], r["question_text"]]
                          for r in untiered])
    sections["unclassified"] = unclass_lines

    L = reportkit.render_scaffold(cfg.conn, "report.obs_catalogue", sections, intro=intro)

    # No CSV pairing here (researcher correction, 2026-08-29) -- a verbatim wa_obs_question_
    # catalogue dump already exists via the governed table.export mechanism (table_export.
    # output_dir -> Workflow/schema/bible_research/wa_obs_question_catalogue.csv). Writing a
    # second copy under this report's own export/ folder would just be a duplicate destination
    # for the same table, which is exactly what table_export.output_dir exists to prevent.
    return reportkit.write_report(cfg.conn, "report.obs_catalogue", path, L)
