"""clusterreport.py — evaluate/review the `cluster` taxonomy and its `cluster_strong` assignment
coverage. Built 2026-08-11, replacing an ad hoc script that wrote CSVs straight to `iba/app/
reports/` outside the app's own reporting mechanism (researcher-caught governance violation,
same session) — this is the config-governed replacement, same shape as registryreport.py/
strongreport.py.

Scoped by `strong.origin` ('word' | 'backfill', bootstrap_strong_origin_column_20260811.py):
cluster/meaning relevance applies to 'word'-origin strongs only — a registry word's own,
deliberately-onboarded codes. 'backfill'-origin strongs (onboarded by raw.backfill_meaning's
book-scoped completeness sweep, independent of any word) are out of scope for cluster mapping
entirely — they exist to support lexical resolution, not as inner-being study subjects — and are
reported as an explicit count, never included in the gap list.
"""

from __future__ import annotations

import pathlib

from . import reportkit


def _tbl(headers, rows):
    L = ["| " + " | ".join(headers) + " |", "| " + " | ".join("---" for _ in headers) + " |"]
    for r in rows:
        L.append("| " + " | ".join(str(c) if c is not None else "" for c in r) + " |")
    return L


def write_report(cfg, path: pathlib.Path) -> pathlib.Path:
    conn = cfg.conn
    q = lambda sql, p=(): conn.execute(sql, p).fetchall()

    n_clusters = q("SELECT COUNT(*) n FROM cluster WHERE deleted=0")[0]["n"]
    n_word = q("SELECT COUNT(*) n FROM strong WHERE deleted=0 AND origin='word'")[0]["n"]
    n_backfill = q("SELECT COUNT(*) n FROM strong WHERE deleted=0 AND origin='backfill'")[0]["n"]
    n_assigned = q(
        "SELECT COUNT(*) n FROM strong s WHERE s.deleted=0 AND s.origin='word' AND EXISTS "
        "(SELECT 1 FROM cluster_strong cs WHERE cs.strong=s.strongNumber AND cs.deleted=0)"
    )[0]["n"]
    n_gap = n_word - n_assigned

    intro = [
        "> Generated by `report.cluster`. Cluster taxonomy + strong-assignment coverage, scoped to "
        "`strong.origin='word'` — cluster/meaning relevance does not apply to `origin='backfill'` "
        "codes (book-scoped completeness sweep, independent of any word; used only for lexical "
        "resolution, never a cluster-mapping subject).", "",
        f"- clusters (taxonomy): **{n_clusters}**",
        f"- `strong` rows, `origin='word'`: **{n_word}**",
        f"- of those, with a cluster assignment: **{n_assigned}** "
        f"({100*n_assigned/n_word:.0f}%)" if n_word else "- with a cluster assignment: 0",
        f"- of those, **without** a cluster assignment (the real allocation gap): **{n_gap}**",
        f"- `strong` rows, `origin='backfill'` (out of scope, informational only): **{n_backfill}**",
    ]

    sections: dict[str, list[str]] = {}

    clusters = q("SELECT cluster_code, short_name, description FROM cluster WHERE deleted=0 "
                "ORDER BY cluster_code")
    sections["clusters"] = (
        [f"**{len(clusters)}** clusters:", ""]
        + _tbl(["cluster_code", "short_name", "description"],
              [[r["cluster_code"], r["short_name"], r["description"]] for r in clusters]))

    by_cluster = q(
        "SELECT cs.cluster_code, cl.short_name, COUNT(*) n FROM cluster_strong cs "
        "JOIN cluster cl ON cl.cluster_code=cs.cluster_code AND cl.deleted=0 "
        "JOIN strong s ON s.strongNumber=cs.strong AND s.deleted=0 AND s.origin='word' "
        "WHERE cs.deleted=0 GROUP BY cs.cluster_code ORDER BY n DESC")
    sections["by_cluster"] = (
        ["**Word-origin strong count per cluster:**", ""]
        + _tbl(["cluster_code", "short_name", "word-origin strongs assigned"],
              [[r["cluster_code"], r["short_name"], r["n"]] for r in by_cluster]))

    gap = q(
        "SELECT s.strongNumber, s.stepGloss, s.stepTransliteration, s.language, s.count "
        "FROM strong s WHERE s.deleted=0 AND s.origin='word' AND NOT EXISTS "
        "(SELECT 1 FROM cluster_strong cs WHERE cs.strong=s.strongNumber AND cs.deleted=0) "
        "ORDER BY s.count DESC LIMIT 200")
    sections["gap_list"] = (
        [f"**{len(gap)}** shown (of {n_gap} total, ordered by usage `count`, capped at 200) — "
         f"word-origin `strong` rows with no cluster assignment yet (the LLM-allocation target):", ""]
        + _tbl(["strongNumber", "stepGloss", "stepTransliteration", "language", "count"],
              [[r["strongNumber"], r["stepGloss"], r["stepTransliteration"], r["language"],
                r["count"]] for r in gap]))

    L = reportkit.render_scaffold(conn, "report.cluster", sections, intro=intro)

    cluster_strong_joined = q(
        "SELECT cs.strong, s.stepGloss, s.language, cs.cluster_code, cl.short_name, cs.source, "
        "cs.created_at FROM cluster_strong cs "
        "JOIN strong s ON s.strongNumber=cs.strong "
        "JOIN cluster cl ON cl.cluster_code=cs.cluster_code "
        "WHERE cs.deleted=0 ORDER BY cs.strong, cs.cluster_code")
    strong_without_cluster = q(
        "SELECT s.strongNumber, s.stepGloss, s.stepTransliteration, s.language, s.count "
        "FROM strong s WHERE s.deleted=0 AND s.origin='word' AND NOT EXISTS "
        "(SELECT 1 FROM cluster_strong cs WHERE cs.strong=s.strongNumber AND cs.deleted=0) "
        "ORDER BY s.language, s.strongNumber")
    reportkit.write_csv_pairing(conn, "report.cluster", path.parent / "export",
                                row_filter={"cluster_strong": cluster_strong_joined,
                                           "strong_without_cluster": strong_without_cluster})
    path = reportkit.write_report(conn, "report.cluster", path, L)
    return path
