"""clusterreport.py — evaluate/review the `cluster` taxonomy and its `cluster_strong` assignment
coverage. Built 2026-08-11, replacing an ad hoc script that wrote CSVs straight to `iba/app/
reports/` outside the app's own reporting mechanism (researcher-caught governance violation,
same session) — this is the config-governed replacement, same shape as registryreport.py/
strongreport.py.

Scoped by `strong.origin` ('word' | 'backfill', bootstrap_strong_origin_column_20260811.py):
cluster/meaning relevance applies to 'word'-origin strongs only — a registry word's own,
deliberately-onboarded codes. 'backfill'-origin strongs (onboarded by raw.backfill_meaning's
book-scoped completeness sweep, independent of any word) are out of scope for cluster mapping
entirely — they exist to support lexical resolution, not as inner-being study subjects — and are
reported as an explicit count, never included in the gap list.
"""

from __future__ import annotations

import pathlib
import re

from . import reportkit


_STEM_SUFFIXES_DEFAULT = ["ically", "iously", "ously", "ingly", "edness", "fulness", "tion",
                          "sion", "ness", "ings", "ing", "edly", "ed", "ly", "ies", "es", "s",
                          "able", "ible", "tive", "ive", "ful", "ous", "al", "ic"]
_STEM_PREFIX_LEN_DEFAULT = 4
_STEM_TOP_N_DEFAULT = 10


def _tbl(headers, rows):
    L = ["| " + " | ".join(headers) + " |", "| " + " | ".join("---" for _ in headers) + " |"]
    for r in rows:
        L.append("| " + " | ".join(str(c) if c is not None else "" for c in r) + " |")
    return L


# ── gloss stemming (grouping aid for "top meanings by cluster") ────────────────────────────────
# One-pass longest-suffix strip, then a short config-driven prefix as the group key — deliberately
# not a real stemmer (Porter etc.): this is a REPORT grouping aid for a human to read, not a
# correctness-critical mechanism, so a simple heuristic that visibly does the job (grace/gracious/
# graciously -> one group) beats a heavier dependency. Both the suffix list and prefix length are
# `cfg_setting` (module `report`), not hard-coded — governance.rules_must_be_config_driven.
def _stem_key(gloss: str, suffixes: list[str], prefix_len: int) -> str:
    w = re.sub(r"^to\s+", "", (gloss or "").strip().lower())   # verb-infinitive marker, common in stepGloss
    w = re.sub(r"[^a-z]", "", w)
    if not w:
        return ""
    for suf in sorted(suffixes, key=len, reverse=True):        # longest match first (ously before ly)
        if w.endswith(suf) and len(w) - len(suf) >= 3:
            w = w[: -len(suf)]
            break
    return w[:prefix_len] if len(w) > prefix_len else w


def write_report(cfg, path: pathlib.Path) -> pathlib.Path:
    conn = cfg.conn
    q = lambda sql, p=(): conn.execute(sql, p).fetchall()

    n_clusters = q("SELECT COUNT(*) n FROM cluster WHERE deleted=0")[0]["n"]
    n_word = q("SELECT COUNT(*) n FROM strong WHERE deleted=0 AND origin='word'")[0]["n"]
    n_backfill = q("SELECT COUNT(*) n FROM strong WHERE deleted=0 AND origin='backfill'")[0]["n"]
    n_assigned = q(
        "SELECT COUNT(*) n FROM strong s WHERE s.deleted=0 AND s.origin='word' AND EXISTS "
        "(SELECT 1 FROM cluster_strong cs WHERE cs.strong=s.strongNumber AND cs.deleted=0)"
    )[0]["n"]
    n_gap = n_word - n_assigned

    intro = [
        "> Generated by `report.cluster`. Cluster taxonomy + strong-assignment coverage, scoped to "
        "`strong.origin='word'` — cluster/meaning relevance does not apply to `origin='backfill'` "
        "codes (book-scoped completeness sweep, independent of any word; used only for lexical "
        "resolution, never a cluster-mapping subject).", "",
        f"- clusters (taxonomy): **{n_clusters}**",
        f"- `strong` rows, `origin='word'`: **{n_word}**",
        f"- of those, with a cluster assignment: **{n_assigned}** "
        f"({100*n_assigned/n_word:.0f}%)" if n_word else "- with a cluster assignment: 0",
        f"- of those, **without** a cluster assignment (the real allocation gap): **{n_gap}**",
        f"- `strong` rows, `origin='backfill'` (out of scope, informational only): **{n_backfill}**",
    ]

    sections: dict[str, list[str]] = {}

    clusters = q("SELECT cluster_code, short_name, description FROM cluster WHERE deleted=0 "
                "ORDER BY cluster_code")
    sections["clusters"] = (
        [f"**{len(clusters)}** clusters:", ""]
        + _tbl(["cluster_code", "short_name", "description"],
              [[r["cluster_code"], r["short_name"], r["description"]] for r in clusters]))

    by_cluster = q(
        "SELECT cs.cluster_code, cl.short_name, COUNT(*) n FROM cluster_strong cs "
        "JOIN cluster cl ON cl.cluster_code=cs.cluster_code AND cl.deleted=0 "
        "JOIN strong s ON s.strongNumber=cs.strong AND s.deleted=0 AND s.origin='word' "
        "WHERE cs.deleted=0 GROUP BY cs.cluster_code ORDER BY n DESC")
    sections["by_cluster"] = (
        ["**Word-origin strong count per cluster:**", ""]
        + _tbl(["cluster_code", "short_name", "word-origin strongs assigned"],
              [[r["cluster_code"], r["short_name"], r["n"]] for r in by_cluster]))

    gap = q(
        "SELECT s.strongNumber, s.stepGloss, s.stepTransliteration, s.language, s.count "
        "FROM strong s WHERE s.deleted=0 AND s.origin='word' AND NOT EXISTS "
        "(SELECT 1 FROM cluster_strong cs WHERE cs.strong=s.strongNumber AND cs.deleted=0) "
        "ORDER BY s.count DESC LIMIT 200")
    sections["gap_list"] = (
        [f"**{len(gap)}** shown (of {n_gap} total, ordered by usage `count`, capped at 200) — "
         f"word-origin `strong` rows with no cluster assignment yet (the LLM-allocation target):", ""]
        + _tbl(["strongNumber", "stepGloss", "stepTransliteration", "language", "count"],
              [[r["strongNumber"], r["stepGloss"], r["stepTransliteration"], r["language"],
                r["count"]] for r in gap]))

    # ── cluster summary — every origin (not word-only, unlike the sections above): strong/span/
    # lexical/verse counts per cluster, + top-10 meanings grouped by a rough English-gloss stem so
    # derivational family members (grace/gracious/graciously) count as one line, not three
    # (2026-08-12, researcher request, same session as the cluster-assign module). `verse_lexical`
    # already carries one row per (span, code) — joining it directly gives span/lexical/verse
    # counts without re-parsing `span.strong_variant` text.
    suffixes = cfg.setting("report.cluster_stem_suffixes", _STEM_SUFFIXES_DEFAULT)
    prefix_len = int(cfg.setting("report.cluster_stem_prefix_len", _STEM_PREFIX_LEN_DEFAULT))
    top_n = int(cfg.setting("report.cluster_top_meanings", _STEM_TOP_N_DEFAULT))

    counts = q(
        "SELECT cs.cluster_code, cl.short_name, COUNT(DISTINCT cs.strong) strong_n, "
        "COUNT(DISTINCT vl.span_id) span_n, COUNT(vl.id) lexical_n, "
        "COUNT(DISTINCT vl.verse_id) verse_n FROM cluster_strong cs "
        "JOIN cluster cl ON cl.cluster_code=cs.cluster_code AND cl.deleted=0 "
        "LEFT JOIN verse_lexical vl ON vl.strong=cs.strong AND vl.deleted=0 "
        "WHERE cs.deleted=0 GROUP BY cs.cluster_code ORDER BY strong_n DESC")

    summary_lines = [
        "**Every cluster, every origin** (unlike the word-origin-only sections above) — strong "
        "count, span/lexical/verse coverage (via `verse_lexical`), and the top "
        f"{top_n} meanings per cluster, English-gloss-stemmed so derivational family members "
        "(grace/gracious/graciously) group as one line rather than compete separately. `freq` = "
        "summed STEP `count` across the group's member codes.", ""]
    summary_lines += _tbl(
        ["cluster_code", "short_name", "strongs", "spans", "lexicals", "verses"],
        [[r["cluster_code"], r["short_name"], r["strong_n"], r["span_n"], r["lexical_n"],
          r["verse_n"]] for r in counts])
    summary_lines.append("")

    for r in counts:
        members = q("SELECT DISTINCT s.strongNumber, s.stepGloss, s.count FROM cluster_strong cs "
                   "JOIN strong s ON s.strongNumber=cs.strong AND s.deleted=0 "
                   "WHERE cs.deleted=0 AND cs.cluster_code=?", (r["cluster_code"],))
        groups: dict[str, dict] = {}
        for m in members:
            key = _stem_key(m["stepGloss"], suffixes, prefix_len) or m["strongNumber"]
            g = groups.setdefault(key, {"glosses": set(), "codes": [], "freq": 0})
            g["glosses"].add((m["stepGloss"] or "").strip())
            g["codes"].append(m["strongNumber"])
            g["freq"] += int(m["count"]) if m["count"] and str(m["count"]).isdigit() else 0
        top = sorted(groups.values(), key=lambda g: -g["freq"])[:top_n]
        summary_lines.append(f"### {r['cluster_code']} {r['short_name']} — top {len(top)} meanings")
        summary_lines.append("")
        summary_lines += _tbl(
            ["meanings (stem-grouped)", "codes", "freq"],
            [[", ".join(sorted(g["glosses"])), ", ".join(sorted(g["codes"])), g["freq"]]
             for g in top])
        summary_lines.append("")
    sections["cluster_summary"] = summary_lines

    L = reportkit.render_scaffold(conn, "report.cluster", sections, intro=intro)

    cluster_strong_joined = q(
        "SELECT cs.strong, s.stepGloss, s.language, cs.cluster_code, cl.short_name, cs.source, "
        "cs.created_at FROM cluster_strong cs "
        "JOIN strong s ON s.strongNumber=cs.strong "
        "JOIN cluster cl ON cl.cluster_code=cs.cluster_code "
        "WHERE cs.deleted=0 ORDER BY cs.strong, cs.cluster_code")
    strong_without_cluster = q(
        "SELECT s.strongNumber, s.stepGloss, s.stepTransliteration, s.language, s.count "
        "FROM strong s WHERE s.deleted=0 AND s.origin='word' AND NOT EXISTS "
        "(SELECT 1 FROM cluster_strong cs WHERE cs.strong=s.strongNumber AND cs.deleted=0) "
        "ORDER BY s.language, s.strongNumber")
    reportkit.write_csv_pairing(conn, "report.cluster", path.parent / "export",
                                row_filter={"cluster_strong": cluster_strong_joined,
                                           "strong_without_cluster": strong_without_cluster})
    path = reportkit.write_report(conn, "report.cluster", path, L)
    return path
