"""registryreport.py — evaluate/review the `word_registry`: a summary, its join to `strong` (via
`word_strong`), and a sense report grouping registry words by the gloss/broad meaning their strong
carries. Built 2026-07-23 per escalation #272 (the registry had no evaluation report at all).
"""

from __future__ import annotations

import pathlib

from . import reportkit


def _tbl(headers, rows):
    L = ["| " + " | ".join(headers) + " |", "| " + " | ".join("---" for _ in headers) + " |"]
    for r in rows:
        L.append("| " + " | ".join(str(c) if c is not None else "" for c in r) + " |")
    return L


def write_report(cfg, path: pathlib.Path) -> pathlib.Path:
    conn = cfg.conn
    q = lambda sql, p=(): conn.execute(sql, p).fetchall()

    total = q("SELECT COUNT(*) n FROM word_registry WHERE deleted=0")[0]["n"]
    by_status = q("SELECT status, COUNT(*) n FROM word_registry WHERE deleted=0 "
                 "GROUP BY status ORDER BY n DESC")
    by_source = q("SELECT source, COUNT(*) n FROM word_registry WHERE deleted=0 "
                 "GROUP BY source ORDER BY n DESC")
    no_strong = q("SELECT COUNT(*) n FROM word_registry wr WHERE wr.deleted=0 AND NOT EXISTS "
                 "(SELECT 1 FROM word_strong ws WHERE ws.word_id=wr.id AND ws.deleted=0)")[0]["n"]

    intro = [
        "> Generated by `report.registry`. Evaluate/review `word_registry`: a summary, its join "
        "to `strong` via `word_strong`, and a sense report grouping registry words by the gloss "
        "their strong carries.", "",
        f"- `word_registry` rows: **{total}**",
        f"- with no `word_strong` link at all: **{no_strong}** ({100*no_strong/total:.0f}%)"
        if total else "- with no word_strong link: 0",
    ]

    sections: dict[str, list[str]] = {}

    S = ["**By status:**", ""] + _tbl(["status", "rows"], [[r["status"], r["n"]] for r in by_status])
    S += ["", "**By source:**", ""] + _tbl(["source", "rows"], [[r["source"], r["n"]] for r in by_source])
    sections["summary"] = S

    # registry word joined to every strong it holds (word_strong), with that strong's own gloss —
    # the "join with the strong related to registry word" ask.
    by_strong = q(
        "SELECT wr.word registry_word, wr.status, s.strongNumber, s.stepGloss, s.language, s.count "
        "FROM word_registry wr "
        "JOIN word_strong ws ON ws.word_id=wr.id AND ws.deleted=0 "
        "JOIN strong s ON s.strongNumber=ws.strong AND s.deleted=0 "
        "WHERE wr.deleted=0 "
        "ORDER BY wr.word, s.strongNumber")
    sections["by_strong"] = (
        [f"**{len(by_strong)}** registry-word/strong pairs:", ""]
        + _tbl(["registry word", "status", "strong", "stepGloss", "language", "count"],
              [[r["registry_word"], r["status"], r["strongNumber"], r["stepGloss"],
                r["language"], r["count"]] for r in by_strong]))

    # sense report: registry.word -> strong gloss, GROUPED BY the gloss itself — the only actual
    # "sense/broad meaning" signal the DB holds (there is no separate semantic-category taxonomy
    # to group by; strong_sense.head / strong.stepGloss ARE the sense). Ordered by gloss so every
    # registry word sharing a sense clusters together.
    sense = q(
        "SELECT COALESCE(ss.head, s.stepGloss) gloss, wr.word registry_word, s.strongNumber "
        "FROM word_registry wr "
        "JOIN word_strong ws ON ws.word_id=wr.id AND ws.deleted=0 "
        "JOIN strong s ON s.strongNumber=ws.strong AND s.deleted=0 "
        "LEFT JOIN strong_sense ss ON ss.strong=s.strongNumber AND ss.deleted=0 "
        "WHERE wr.deleted=0 "
        "ORDER BY gloss, wr.word")
    sections["sense_report"] = (
        [f"**{len(sense)}** rows — `registry.word` -> strong gloss, grouped by gloss/sense so "
         f"words sharing a broad meaning cluster together:", ""]
        + _tbl(["gloss (sense)", "registry word", "strong"],
              [[r["gloss"], r["registry_word"], r["strongNumber"]] for r in sense]))

    L = reportkit.render_scaffold(conn, "report.registry", sections, intro=intro)

    joined = q(
        "SELECT wr.word registry_word, wr.status, wr.source, s.strongNumber, s.stepGloss, "
        "s.language, s.count, ss.head sense_head "
        "FROM word_registry wr "
        "LEFT JOIN word_strong ws ON ws.word_id=wr.id AND ws.deleted=0 "
        "LEFT JOIN strong s ON s.strongNumber=ws.strong AND s.deleted=0 "
        "LEFT JOIN strong_sense ss ON ss.strong=s.strongNumber AND ss.deleted=0 "
        "WHERE wr.deleted=0 "
        "ORDER BY wr.word")
    reportkit.write_csv_pairing(conn, "report.registry", path.parent / "export",
                                row_filter={"word_registry": joined})
    path = reportkit.write_report(conn, "report.registry", path, L)
    return path
