"""schemareport.py — the IBA app's own DATA-schema snapshot, one of the four "missing reports"
from PLAN-reports-config-governance-v1-20260722.md §3.4. There was no equivalent of the Bible-study
side's `DBSchema.json`/`build_dbschema.py` for the IBA app's 17 data tables (only `cfgreport.py` §8
documents the config-governed tables). Introspects the live DB directly (`PRAGMA table_info` /
`foreign_key_list` / `index_list`) — no CSV pairing: this report already *is* the schema, a CSV of
it would just be the same information reformatted.
"""

from __future__ import annotations

import pathlib

from . import reportkit

# the app's own data tables — everything that isn't a cfg_* config-store table. Kept as an explicit
# list (not "every non-cfg_ table") so a genuinely new data table gets a deliberate decision to add
# it here, the same discipline REPORT_STEPS/QUALITY_CHECK_REPORT_PATH already apply elsewhere.
DATA_TABLES = (
    "candidate_seed", "escalation", "lemma_inventory", "passage", "run", "span", "span_candidate",
    "strong", "strong_lexicon", "strong_meaning_tree", "strong_sense", "strong_verse",
    "validation_result", "verse", "verse_passage", "word_registry", "word_strong",
)


def _tbl(headers, rows):
    L = ["| " + " | ".join(headers) + " |", "| " + " | ".join("---" for _ in headers) + " |"]
    for r in rows:
        L.append("| " + " | ".join(str(c) if c is not None else "" for c in r) + " |")
    return L


def write_report(cfg, path: pathlib.Path) -> pathlib.Path:
    conn = cfg.conn
    live = {r[0] for r in conn.execute(
        "SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'cfg_%' "
        "AND name NOT LIKE 'sqlite_%'")}
    missing = [t for t in DATA_TABLES if t not in live]
    extra = sorted(live - set(DATA_TABLES))

    counts = {t: conn.execute(f'SELECT COUNT(*) FROM "{t}"').fetchone()[0]
             for t in DATA_TABLES if t in live}

    intro = [
        "> Generated by `report.schema_overview`. Introspects the live DB directly — always "
        "current, never hand-maintained.", "",
        f"- data tables: **{len(DATA_TABLES)}** known, **{len(live)}** live",
    ]

    sections: dict[str, list[str]] = {}

    S = _tbl(["table", "rows"], [[t, counts.get(t, "—")] for t in DATA_TABLES])
    if missing:
        S += ["", f"**In `DATA_TABLES` but not live** (schemareport.py's list is stale): "
                 + ", ".join(missing)]
    if extra:
        S += ["", f"**Live but not in `DATA_TABLES`** (a new table — add it to "
                 f"`schemareport.DATA_TABLES` deliberately): " + ", ".join(extra)]
    sections["overview"] = S

    S = []
    for t in DATA_TABLES:
        if t not in live:
            continue
        S.append(f"### {t} ({counts.get(t, 0)} row(s))")
        S.append("")
        cols = list(conn.execute(f'PRAGMA table_info("{t}")'))
        fks = {r[3]: f"{r[2]}.{r[4]}" for r in conn.execute(f'PRAGMA foreign_key_list("{t}")')}
        idx = [r[1] for r in conn.execute(f'PRAGMA index_list("{t}")')]
        S += _tbl(["column", "type", "pk", "notnull", "fk"], [
            [c[1], c[2], "✓" if c[5] else "", "✓" if c[3] else "", fks.get(c[1], "")]
            for c in cols])
        if idx:
            S.append(f"indexes: {', '.join(idx)}")
        S.append("")
    sections["tables"] = S

    L = reportkit.render_scaffold(conn, "report.schema_overview", sections, intro=intro)
    reportkit.write_report(conn, "report.schema_overview", path, L)
    return path
