"""seedreport.py — analysis of `candidate_seed`, one of the four "missing reports" from
PLAN-reports-config-governance-v1-20260722.md §3.1. Broader than `candidate.validate` (which is
error/exception-focused): the whole-seed picture — counts by decision/layer/role, tag-length and
per-lemma distribution, the busiest lemmas, and an open-vs-resolved trend over time. First-cut
content, per the researcher's 2026-07-22 agreement (§9.3) — expected to be expanded once built.
"""

from __future__ import annotations

import pathlib

from . import reportkit


def _tbl(headers, rows):
    L = ["| " + " | ".join(headers) + " |", "| " + " | ".join("---" for _ in headers) + " |"]
    for r in rows:
        L.append("| " + " | ".join(str(c) if c is not None else "" for c in r) + " |")
    return L


def write_report(cfg, path: pathlib.Path) -> pathlib.Path:
    conn = cfg.conn
    q = lambda sql, p=(): conn.execute(sql, p).fetchall()

    total = q("SELECT COUNT(*) n FROM candidate_seed WHERE deleted=0")[0]["n"]
    by_decision = q("SELECT decision, COUNT(*) n FROM candidate_seed WHERE deleted=0 "
                    "GROUP BY decision ORDER BY n DESC")
    by_layer = q("SELECT layer, COUNT(*) n FROM candidate_seed WHERE deleted=0 "
                "GROUP BY layer ORDER BY n DESC")
    by_role = q("SELECT COALESCE(ib_referent_type, '(none)') role, COUNT(*) n FROM candidate_seed "
               "WHERE deleted=0 GROUP BY role ORDER BY n DESC")

    intro = [
        f"> Generated by `report.seed_candidate`. Read-only whole-seed picture — broader than "
        f"`candidate.validate` (which is error/exception-focused).", "",
        f"- total active `candidate_seed` rows: **{total}**",
    ]

    sections: dict[str, list[str]] = {}

    S = ["**By decision:**", ""] + _tbl(["decision", "rows"], [[r["decision"], r["n"]] for r in by_decision])
    S += ["", "**By layer:**", ""] + _tbl(["layer", "rows"], [[r["layer"], r["n"]] for r in by_layer])
    S += ["", "**By role (`ib_referent_type`):**", ""] + _tbl(
        ["role", "rows"], [[r["role"], r["n"]] for r in by_role])
    sections["summary"] = S

    tag_len = q("SELECT (LENGTH(tag) - LENGTH(REPLACE(tag, ' ', '')) + 1) words, COUNT(*) n "
              "FROM candidate_seed WHERE deleted=0 AND tag IS NOT NULL AND tag<>'' "
              "GROUP BY words ORDER BY words")
    per_lemma = q("SELECT n_rows, COUNT(*) n_lemmas FROM (SELECT lemma_key, COUNT(*) n_rows "
                 "FROM candidate_seed WHERE deleted=0 GROUP BY lemma_key) GROUP BY n_rows "
                 "ORDER BY n_rows")
    S = ["**Tag word-count distribution:**", ""] + _tbl(
        ["words in tag", "rows"], [[r["words"], r["n"]] for r in tag_len])
    S += ["", "**Rows per `lemma_key` (how many senses a lemma has split into):**", ""] + _tbl(
        ["rows for this lemma", "lemma count"], [[r["n_rows"], r["n_lemmas"]] for r in per_lemma])
    sections["distribution"] = S

    top = q("SELECT lemma_key, COUNT(*) n FROM candidate_seed WHERE deleted=0 "
           "GROUP BY lemma_key ORDER BY n DESC LIMIT 30")
    sections["top_lemmas"] = _tbl(["lemma_key", "rows"], [[r["lemma_key"], r["n"]] for r in top])

    over_time = q("SELECT substr(assessed_at,1,10) day, "
                 "SUM(CASE WHEN decision='exception' THEN 1 ELSE 0 END) open_exception, "
                 "SUM(CASE WHEN decision<>'exception' THEN 1 ELSE 0 END) resolved "
                 "FROM candidate_seed WHERE deleted=0 AND assessed_at IS NOT NULL "
                 "GROUP BY day ORDER BY day")
    sections["over_time"] = _tbl(
        ["day (assessed_at)", "open (exception)", "resolved (other decision)"],
        [[r["day"], r["open_exception"], r["resolved"]] for r in over_time])

    L = reportkit.render_scaffold(conn, "report.seed_candidate", sections, intro=intro)

    joined = q("SELECT cs.*, li.gloss AS lemma_gloss FROM candidate_seed cs "
              "LEFT JOIN lemma_inventory li ON li.lemma_key=cs.lemma_key AND li.deleted=0 "
              "WHERE cs.deleted=0")
    reportkit.write_csv_pairing(conn, "report.seed_candidate", path.parent / "export",
                                row_filter={"candidate_seed": joined})
    reportkit.write_report(conn, "report.seed_candidate", path, L)
    return path
