"""spanreport.py — analysis of the span layer (`span` + `span_candidate`), one of the four
"missing reports" from PLAN-reports-config-governance-v1-20260722.md §3.3. Span coverage per book,
confirmed (`span`) vs candidate (`span_candidate`) counts, morph-code distribution. First-cut
content, expected to be expanded once built (§9.3).
"""

from __future__ import annotations

import pathlib

from . import reportkit


def _tbl(headers, rows):
    L = ["| " + " | ".join(headers) + " |", "| " + " | ".join("---" for _ in headers) + " |"]
    for r in rows:
        L.append("| " + " | ".join(str(c) if c is not None else "" for c in r) + " |")
    return L


def write_report(cfg, path: pathlib.Path) -> pathlib.Path:
    conn = cfg.conn
    q = lambda sql, p=(): conn.execute(sql, p).fetchall()

    total_spans = q("SELECT COUNT(*) n FROM span WHERE deleted=0")[0]["n"]
    total_candidates = q("SELECT COUNT(*) n FROM span_candidate WHERE deleted=0")[0]["n"]
    verses_covered = q("SELECT COUNT(DISTINCT verse_id) n FROM span WHERE deleted=0")[0]["n"]

    intro = [
        "> Generated by `report.span_analysis`. Read-only coverage picture across the span layer.",
        "",
        f"- total `span` rows: **{total_spans}**",
        f"- total `span_candidate` rows: **{total_candidates}**",
        f"- verses with at least one span: **{verses_covered}**",
    ]

    sections: dict[str, list[str]] = {}

    by_book = q("""
        SELECT substr(v.osisId, 1, instr(v.osisId, '.') - 1) book,
               COUNT(DISTINCT sp.id) spans,
               COUNT(DISTINCT sc.id) candidates
        FROM verse v
        JOIN span sp ON sp.verse_id = v.id AND sp.deleted = 0
        LEFT JOIN span_candidate sc ON sc.span_id = sp.id AND sc.deleted = 0
        WHERE v.deleted = 0
        GROUP BY book
        ORDER BY spans DESC
    """)
    sections["by_book"] = _tbl(
        ["book", "spans", "candidate spans"],
        [[r["book"], r["spans"], r["candidates"]] for r in by_book])

    morph = q("SELECT COALESCE(morph_code, '(none)') morph_code, COUNT(*) n FROM span "
            "WHERE deleted=0 GROUP BY morph_code ORDER BY n DESC LIMIT 40")
    sections["morph_distribution"] = _tbl(
        ["morph_code", "rows"], [[r["morph_code"], r["n"]] for r in morph])

    particle = q("SELECT is_particle, COUNT(*) n FROM span WHERE deleted=0 GROUP BY is_particle")
    sections["particle_split"] = _tbl(
        ["is_particle", "rows"], [["yes" if r["is_particle"] else "no", r["n"]] for r in particle])

    L = reportkit.render_scaffold(conn, "report.span_analysis", sections, intro=intro)

    reportkit.write_csv_pairing(conn, "report.span_analysis", path.parent / "export")
    reportkit.write_report(conn, "report.span_analysis", path, L)
    return path
