"""strongreport.py — analysis of the meaning-parse layer (`strong` + `strong_lexicon` +
`strong_sense` + `strong_meaning_tree`), one of the four "missing reports" from
PLAN-reports-config-governance-v1-20260722.md §3.2. Parse coverage (which `strong` rows have no
sense/meaning-tree row yet — a gap list), sense-count distribution, lexicon-field completeness.
First-cut content, expected to be expanded once built (§9.3).
"""

from __future__ import annotations

import pathlib

from . import reportkit


def _tbl(headers, rows):
    L = ["| " + " | ".join(headers) + " |", "| " + " | ".join("---" for _ in headers) + " |"]
    for r in rows:
        L.append("| " + " | ".join(str(c) if c is not None else "" for c in r) + " |")
    return L


def write_report(cfg, path: pathlib.Path) -> pathlib.Path:
    conn = cfg.conn
    q = lambda sql, p=(): conn.execute(sql, p).fetchall()

    total = q("SELECT COUNT(*) n FROM strong WHERE deleted=0")[0]["n"]
    with_sense = q("SELECT COUNT(DISTINCT strong) n FROM strong_sense WHERE deleted=0")[0]["n"]
    with_tree = q("SELECT COUNT(DISTINCT lemma_key) n FROM strong_meaning_tree "
                 "WHERE deleted=0")[0]["n"]
    with_lexicon = q("SELECT COUNT(*) n FROM strong_lexicon WHERE deleted=0 "
                    "AND (lsj IS NOT NULL OR mounce IS NOT NULL)")[0]["n"]

    intro = [
        "> Generated by `report.strong_meaning`. Parse coverage across the meaning layer — "
        "which `strong` entries have a sense/meaning-tree row, and which don't.", "",
        f"- `strong` rows: **{total}**",
        f"- with a `strong_sense` row: **{with_sense}** ({100*with_sense/total:.0f}%)"
        if total else "- with a `strong_sense` row: 0",
        f"- with a `strong_meaning_tree` row: **{with_tree}** ({100*with_tree/total:.0f}%)"
        if total else "- with a `strong_meaning_tree` row: 0",
        f"- with lexicon detail (`lsj`/`mounce`): **{with_lexicon}** ({100*with_lexicon/total:.0f}%)"
        if total else "- with lexicon detail: 0",
    ]

    sections: dict[str, list[str]] = {}

    gap = q("SELECT s.strongNumber, s.stepGloss, s.count FROM strong s WHERE s.deleted=0 "
           "AND NOT EXISTS (SELECT 1 FROM strong_sense ss WHERE ss.strong=s.strongNumber "
           "AND ss.deleted=0) ORDER BY s.count DESC LIMIT 200")
    sections["gap_list"] = (
        [f"**{len(gap)}** shown (of the full gap set, ordered by usage `count`, capped at 200) "
         f"— `strong` rows with no `strong_sense` row yet:", ""]
        + _tbl(["strongNumber", "stepGloss", "count"],
              [[r["strongNumber"], r["stepGloss"], r["count"]] for r in gap]))

    dist = q("SELECT n_senses, COUNT(*) n_lemmas FROM (SELECT lemma_key, COUNT(*) n_senses "
            "FROM strong_meaning_tree WHERE deleted=0 GROUP BY lemma_key) GROUP BY n_senses "
            "ORDER BY n_senses")
    sections["sense_distribution"] = _tbl(
        ["senses (strong_meaning_tree rows)", "lemma count"],
        [[r["n_senses"], r["n_lemmas"]] for r in dist])

    # against every strong row, not just existing strong_lexicon rows — a strong entry with no
    # strong_lexicon row at all is the same as "neither", not invisible (found while reviewing
    # this report's own first output: strong_lexicon has 1506 rows but strong has 3463 — nearly
    # 2000 rows would have been silently uncounted by a strong_lexicon-only query).
    both = q("SELECT COUNT(*) n FROM strong s JOIN strong_lexicon sl ON sl.strong=s.strongNumber "
           "AND sl.deleted=0 WHERE s.deleted=0 AND sl.lsj IS NOT NULL "
           "AND sl.mounce IS NOT NULL")[0]["n"]
    lsj_only = q("SELECT COUNT(*) n FROM strong s JOIN strong_lexicon sl ON sl.strong=s.strongNumber "
               "AND sl.deleted=0 WHERE s.deleted=0 AND sl.lsj IS NOT NULL "
               "AND sl.mounce IS NULL")[0]["n"]
    mounce_only = q("SELECT COUNT(*) n FROM strong s JOIN strong_lexicon sl "
                   "ON sl.strong=s.strongNumber AND sl.deleted=0 WHERE s.deleted=0 "
                   "AND sl.lsj IS NULL AND sl.mounce IS NOT NULL")[0]["n"]
    neither = q("SELECT COUNT(*) n FROM strong s WHERE s.deleted=0 AND NOT EXISTS "
              "(SELECT 1 FROM strong_lexicon sl WHERE sl.strong=s.strongNumber "
              "AND sl.deleted=0 AND (sl.lsj IS NOT NULL OR sl.mounce IS NOT NULL))")[0]["n"]
    sections["lexicon_completeness"] = _tbl(
        ["lsj", "mounce", "strong rows"],
        [["✓", "✓", both], ["✓", "", lsj_only], ["", "✓", mounce_only], ["(none)", "(none)", neither]])

    L = reportkit.render_scaffold(conn, "report.strong_meaning", sections, intro=intro)

    sense_joined = q("SELECT ss.*, s.stepGloss FROM strong_sense ss "
                    "LEFT JOIN strong s ON s.strongNumber=ss.strong AND s.deleted=0 "
                    "WHERE ss.deleted=0")
    tree_joined = q("SELECT smt.*, s.stepGloss FROM strong_meaning_tree smt "
                   "LEFT JOIN strong s ON s.strongNumber=smt.lemma_key AND s.deleted=0 "
                   "WHERE smt.deleted=0")
    reportkit.write_csv_pairing(conn, "report.strong_meaning", path.parent / "export",
                                row_filter={"strong_sense": sense_joined,
                                           "strong_meaning_tree": tree_joined})
    reportkit.write_report(conn, "report.strong_meaning", path, L)
    return path
