"""strongreport.py — analysis of the meaning-parse layer (`strong` + `strong_lexicon` +
`strong_sense` + `strong_meaning_tree`), one of the four "missing reports" from
PLAN-reports-config-governance-v1-20260722.md §3.2. Parse coverage (which `strong` rows have no
sense/meaning-tree row yet — a gap list), sense-count distribution, lexicon-field completeness.
First-cut content, expected to be expanded once built (§9.3).
"""

from __future__ import annotations

import pathlib

from . import reportkit


def _tbl(headers, rows):
    L = ["| " + " | ".join(headers) + " |", "| " + " | ".join("---" for _ in headers) + " |"]
    for r in rows:
        L.append("| " + " | ".join(str(c) if c is not None else "" for c in r) + " |")
    return L


def write_report(cfg, path: pathlib.Path) -> pathlib.Path:
    conn = cfg.conn
    q = lambda sql, p=(): conn.execute(sql, p).fetchall()

    total = q("SELECT COUNT(*) n FROM strong WHERE deleted=0")[0]["n"]
    with_sense = q("SELECT COUNT(DISTINCT strong) n FROM strong_sense WHERE deleted=0")[0]["n"]
    with_tree = q("SELECT COUNT(DISTINCT lemma_key) n FROM strong_meaning_tree "
                 "WHERE deleted=0")[0]["n"]

    # joined against every strong row, not just existing strong_lexicon rows — a strong entry
    # with no strong_lexicon row at all is the same as "neither", not invisible. with_lexicon is
    # derived from this same breakdown (both+lsj_only+mounce_only) rather than a second,
    # independent un-joined query against strong_lexicon, so the intro figure and the
    # lexicon_completeness table below can never structurally disagree (escalation #275: they
    # happened to already match on live data, 1506, but via two different queries — one of them
    # not join-safe against a future orphan/duplicate strong_lexicon row).
    both = q("SELECT COUNT(*) n FROM strong s JOIN strong_lexicon sl ON sl.strong=s.strongNumber "
           "AND sl.deleted=0 WHERE s.deleted=0 AND sl.lsj IS NOT NULL "
           "AND sl.mounce IS NOT NULL")[0]["n"]
    lsj_only = q("SELECT COUNT(*) n FROM strong s JOIN strong_lexicon sl ON sl.strong=s.strongNumber "
               "AND sl.deleted=0 WHERE s.deleted=0 AND sl.lsj IS NOT NULL "
               "AND sl.mounce IS NULL")[0]["n"]
    mounce_only = q("SELECT COUNT(*) n FROM strong s JOIN strong_lexicon sl "
                   "ON sl.strong=s.strongNumber AND sl.deleted=0 WHERE s.deleted=0 "
                   "AND sl.lsj IS NULL AND sl.mounce IS NOT NULL")[0]["n"]
    neither_lexicon = q("SELECT COUNT(*) n FROM strong s WHERE s.deleted=0 AND NOT EXISTS "
              "(SELECT 1 FROM strong_lexicon sl WHERE sl.strong=s.strongNumber "
              "AND sl.deleted=0 AND (sl.lsj IS NOT NULL OR sl.mounce IS NOT NULL))")[0]["n"]
    with_lexicon = both + lsj_only + mounce_only

    # #274: strongs with NEITHER a strong_sense row NOR any lexicon detail — the true dead-ends
    # of the meaning-parse layer, not visible from the sense-gap and lexicon-gap counts separately.
    neither_meaning_nor_lexicon = q(
        "SELECT COUNT(*) n FROM strong s WHERE s.deleted=0 "
        "AND NOT EXISTS (SELECT 1 FROM strong_sense ss WHERE ss.strong=s.strongNumber AND ss.deleted=0) "
        "AND NOT EXISTS (SELECT 1 FROM strong_lexicon sl WHERE sl.strong=s.strongNumber "
        "AND sl.deleted=0 AND (sl.lsj IS NOT NULL OR sl.mounce IS NOT NULL))")[0]["n"]

    intro = [
        "> Generated by `report.strong_meaning`. Parse coverage across the meaning layer — "
        "which `strong` entries have a sense/meaning-tree row, and which don't.", "",
        f"- `strong` rows: **{total}**",
        f"- with a `strong_sense` row: **{with_sense}** ({100*with_sense/total:.0f}%)"
        if total else "- with a `strong_sense` row: 0",
        f"- with a `strong_meaning_tree` row: **{with_tree}** ({100*with_tree/total:.0f}%)"
        if total else "- with a `strong_meaning_tree` row: 0",
        f"- with lexicon detail (`lsj`/`mounce`): **{with_lexicon}** ({100*with_lexicon/total:.0f}%)"
        if total else "- with lexicon detail: 0",
        f"- with **neither** a `strong_sense` row **nor** lexicon detail: "
        f"**{neither_meaning_nor_lexicon}** ({100*neither_meaning_nor_lexicon/total:.0f}%)"
        if total else "- with neither a strong_sense row nor lexicon detail: 0",
    ]

    sections: dict[str, list[str]] = {}

    gap = q("SELECT s.strongNumber, s.stepGloss, s.count FROM strong s WHERE s.deleted=0 "
           "AND NOT EXISTS (SELECT 1 FROM strong_sense ss WHERE ss.strong=s.strongNumber "
           "AND ss.deleted=0) ORDER BY s.count DESC LIMIT 200")
    sections["gap_list"] = (
        [f"**{len(gap)}** shown (of the full gap set, ordered by usage `count`, capped at 200) "
         f"— `strong` rows with no `strong_sense` row yet:", ""]
        + _tbl(["strongNumber", "stepGloss", "count"],
              [[r["strongNumber"], r["stepGloss"], r["count"]] for r in gap]))

    dist = q("SELECT n_senses, COUNT(*) n_lemmas FROM (SELECT lemma_key, COUNT(*) n_senses "
            "FROM strong_meaning_tree WHERE deleted=0 GROUP BY lemma_key) GROUP BY n_senses "
            "ORDER BY n_senses")
    sections["sense_distribution"] = _tbl(
        ["senses (strong_meaning_tree rows)", "lemma count"],
        [[r["n_senses"], r["n_lemmas"]] for r in dist])

    # #274: the aggregate table above groups lemmas by sense COUNT only, with no gloss and no
    # registry linkage — this is the same distribution, but per registered word: which word,
    # which strong/gloss it maps to, and how many senses that lemma has. Scoped to registry-linked
    # strongs only (the aggregate table above already covers the full, un-scoped lemma set).
    by_registry = q(
        "SELECT wr.word registry_word, s.strongNumber, "
        "COALESCE(ss.head, s.stepGloss) gloss, "
        "(SELECT COUNT(*) FROM strong_meaning_tree smt WHERE smt.lemma_key=s.strongNumber "
        "AND smt.deleted=0) n_senses "
        "FROM word_strong ws "
        "JOIN word_registry wr ON wr.id=ws.word_id AND wr.deleted=0 "
        "JOIN strong s ON s.strongNumber=ws.strong AND s.deleted=0 "
        "LEFT JOIN strong_sense ss ON ss.strong=s.strongNumber AND ss.deleted=0 "
        "WHERE ws.deleted=0 "
        "ORDER BY wr.word, s.strongNumber")
    sections["sense_by_registry"] = (
        [f"**{len(by_registry)}** registry-word/strong pairs — the sense distribution (with gloss) "
         f"scoped to strongs actually linked to a registered word, vs. the full lemma set above:", ""]
        + _tbl(["registry word", "strong", "gloss", "senses"],
              [[r["registry_word"], r["strongNumber"], r["gloss"], r["n_senses"]]
               for r in by_registry]))

    # with_lexicon/neither_lexicon computed above (single source of truth shared with the intro
    # summary, escalation #275) — this table just presents the same numbers, plus an explicit
    # reconciling total so the intro figure and this breakdown can never look mismatched.
    sections["lexicon_completeness"] = _tbl(
        ["lsj", "mounce", "strong rows"],
        [["✓", "✓", both], ["✓", "", lsj_only], ["", "✓", mounce_only],
         ["(none)", "(none)", neither_lexicon]]) + [
        "", f"**Total: {total}** ({with_lexicon} with some lexicon detail + "
            f"{neither_lexicon} with none = {with_lexicon + neither_lexicon})."]

    L = reportkit.render_scaffold(conn, "report.strong_meaning", sections, intro=intro)

    sense_joined = q("SELECT ss.*, s.stepGloss FROM strong_sense ss "
                    "LEFT JOIN strong s ON s.strongNumber=ss.strong AND s.deleted=0 "
                    "WHERE ss.deleted=0")
    tree_joined = q("SELECT smt.*, s.stepGloss FROM strong_meaning_tree smt "
                   "LEFT JOIN strong s ON s.strongNumber=smt.lemma_key AND s.deleted=0 "
                   "WHERE smt.deleted=0")
    reportkit.write_csv_pairing(conn, "report.strong_meaning", path.parent / "export",
                                row_filter={"strong_sense": sense_joined,
                                           "strong_meaning_tree": tree_joined})
    path = reportkit.write_report(conn, "report.strong_meaning", path, L)
    return path
