#!/usr/bin/env python
"""Claude Code Stop hook: surfaces the IBA escalation backlog assigned to Claude before a turn
ends, so it can't just be forgotten the way #1312/#1314 were (see
iba/docs/escalation-operational-friction-review-v1-20260831.md, Addendum 3 -- both sat open for
hours across multiple sessions because nothing mechanically re-checked; a written/memory rule had
already failed to catch it once).

Design choice, deliberately conservative: blocks the stop ONCE per turn (never loops -- Claude
Code sets `stop_hook_active: true` on the retry after a block, checked below, so this can never
trap a turn) rather than not blocking at all. A non-blocking `additionalContext` alone would not
actually make Claude say anything new this turn -- the response is already generated by the time
Stop fires -- which would not meet the actual ask (open items addressed BEFORE control returns,
not just quietly logged for next time).

Deliberately does NOT filter by type/age: real backlog data checked while building this (2026-08-
31) showed genuine multi-session work (e.g. #1306) sitting at next_action_assigned_to='Claude'
alongside the kind of forgotten item this exists to catch -- there is no clean field to
distinguish "abandoned by Claude this turn" from "legitimately still in progress across sessions"
without guessing. The reason text handles that distinction instead: it tells Claude to
acknowledge/triage what's open, not to treat every item as something that must be fully resolved
this turn. If this turns out too noisy in practice, narrowing the query (by type, or by an
age/session cutoff) is the next step -- not silently dropping the check.

Never blocks on its own failure -- a DB lock, a missing file, a query error all fall through to
"allow the stop," because a broken check must not become a new way to get stuck (the exact kind of
self-inflicted friction iba/docs/escalation-operational-friction-review-v1-20260831.md's Defect 1
was about, for the escalation CLI itself)."""
import json
import os
import sqlite3
import sys


def main() -> None:
    try:
        payload = json.load(sys.stdin)
    except Exception:
        payload = {}

    if payload.get("stop_hook_active"):
        print(json.dumps({}))
        return

    project_dir = (
        payload.get("cwd")
        or os.environ.get("CLAUDE_PROJECT_DIR")
        or os.getcwd()
    )
    db_path = os.path.join(project_dir, "iba", "app", "db", "iba.db")

    try:
        if not os.path.isfile(db_path):
            print(json.dumps({}))
            return
        conn = sqlite3.connect(db_path, timeout=2)
        conn.row_factory = sqlite3.Row
        rows = conn.execute(
            "SELECT id, type, state, next_action, short_description FROM escalation "
            "WHERE next_action_assigned_to='Claude' "
            "AND state IN ('raised','in-progress','re-assigned','on-hold') "
            "ORDER BY id"
        ).fetchall()
        conn.close()
    except Exception:
        # The check itself breaking must never become a new reason to get stuck.
        print(json.dumps({}))
        return

    if not rows:
        print(json.dumps({}))
        return

    lines = [
        f"#{r['id']} ({r['type']}, {r['state']}/{r['next_action']}): {r['short_description']}"
        for r in rows
    ]
    reason = (
        f"Escalation backlog check (automatic, not a memory rule): {len(rows)} open item(s) "
        f"currently assigned to Claude (next_action_assigned_to='Claude') in iba.db:\n"
        + "\n".join(lines)
        + "\n\nBefore finishing this turn, for each one: either (1) it's genuinely ongoing "
        "multi-session work already in motion and just needs a one-line acknowledgement of why "
        "it's untouched this turn -- fine to leave as-is -- or (2) if it's actually actionable "
        "right now, DO the cycle (cfg_behaviour_rule 'claude-held-item-must-progress-or-bounce-"
        "back'), don't just mention it: complete the work and move it forward (ready_for_approval), "
        "or write a comment and reassign it to the Researcher. Merely naming an item as 'open' "
        "without doing one of those two things is not enough -- that already happened once "
        "(2026-08-31) and produced no actual progress."
    )
    print(json.dumps({"decision": "block", "reason": reason}))


if __name__ == "__main__":
    main()
