s|verse-analysis/psalms/wa-family-analyses-INDEX|verse-analysis/psalms/_family-analyses/wa-family-analyses-INDEX|g
s|verse-analysis/psalms/wa-family-analysis-|verse-analysis/psalms/_family-analyses/wa-family-analysis-|g
s|verse-analysis/psalms/wa-ib-characteristic-|verse-analysis/psalms/_model/wa-ib-characteristic-|g
s|verse-analysis/psalms/wa-ib-char-family-vs-cluster|verse-analysis/psalms/_model/wa-ib-char-family-vs-cluster|g
s|verse-analysis/psalms/wa-psalms-characteristic-model|verse-analysis/psalms/_model/wa-psalms-characteristic-model|g
s|verse-analysis/psalms/wa-psalms-db-integrity|verse-analysis/psalms/_model/wa-psalms-db-integrity|g
s|verse-analysis/psalms/wa-characteristic-restructure|verse-analysis/psalms/_model/wa-characteristic-restructure|g
s|verse-analysis/psalms/wa-evidence-261|verse-analysis/psalms/_model/wa-evidence-261|g
s|verse-analysis/psalms/wa-investigation-|verse-analysis/psalms/_model/wa-investigation-|g
s|verse-analysis/psalms/wa-psalms-reread|verse-analysis/psalms/_reread/wa-psalms-reread|g
s|verse-analysis/psalms/wa-reread-automation|verse-analysis/psalms/_reread/wa-reread-automation|g
s|verse-analysis/psalms/wa-psalms-intervention|verse-analysis/psalms/_reread/wa-psalms-intervention|g
s|verse-analysis/psalms/wa-psalms-pilots|verse-analysis/psalms/_reread/wa-psalms-pilots|g
s|verse-analysis/psalms/wa-psalm-004-pilot|verse-analysis/psalms/_reread/wa-psalm-004-pilot|g
s|verse-analysis/psalms/wa-ib-relevance-screen|verse-analysis/psalms/_reread/wa-ib-relevance-screen|g
s|outputs/data/ib_char_877_meanings_for_family|verse-analysis/psalms/_model/ib_char_877_meanings_for_family|g
s|outputs/data/ib_characteristic_legacy_29_export|verse-analysis/psalms/_model/ib_characteristic_legacy_29_export|g
s|outputs/data/ib_characteristic_v2_book19|verse-analysis/psalms/_model/ib_characteristic_v2_book19|g
s|outputs/data/char-seed-extension-read-emergent-19|verse-analysis/psalms/_model/char-seed-extension-read-emergent-19|g
s|outputs/data/ot-lemmas-unmatched|research/investigations/ot-lemmas-unmatched|g
s|outputs/data/ib-judgement-|research/investigations/ib-judgement-|g
s|outputs/data/audit-word-onboarding-worklist|research/investigations/audit-word-onboarding-worklist|g
s|outputs/data/lemma-inventory-master-no-particles|research/discovery/lemma-inventory-master-no-particles|g
s|outputs/data/registry-synonyms-curated|research/discovery/registry-synonyms-curated|g
