"""word_strong_span_report.py — SUPERSEDED 2026-08-09, kept for history only. This ad-hoc
prototype was promoted the same day into a real registered report — use that instead:

    iba\\app\\ps\\WordRegistrySpan-Report.ps1 -Word <word>

(step `report.word_registry_span`, generator `iba/app/lib/wordregistryspanreport.py`, registered
via `iba/app/migration/bootstrap_word_registry_span_report.py`; see BUILD.md §85 / GOVERNANCE.md
§36). Output now files to `iba/app/verse-analysis/word_registry/`, not `iba/app/reports/`.

--- original docstring below, for history ---

word -> linked Strong's -> parse meaning -> unique spans (distinct surface applications) ->
example verse text.

Not a registered cfg_step/cfg_report work-package step — this was a one-off analysis tool per
governance.oneoff_report_dir, built at the researcher's request 2026-08-09.

Chain:
  word_registry (word)
    -> word_strong (word_id -> strong, exact code incl. suffix)
         -> strong (gloss/transliteration/language/count)
         -> strong_meaning_parsed (lemma_key = strong; structured sense breakdown, "parse meaning")
         -> verse_lexical (strong match, deleted=0) -> span (surface = the actual inflected
              text form tagged) -> verse (reference/text, for one example per unique surface)

"Unique span" here = distinct span.surface values tagged with that Strong's number — i.e. the
different English/target-text realisations ("applications") STEP's morphology assigned that
lemma across its NT occurrences, not distinct resolved_sense (checked: resolved_sense is
effectively fixed per Strong's in this data, so surface diversity is the real story here).

Usage:
    python -m iba.app.tools.word_strong_span_report --word fear
    python -m iba.app.tools.word_strong_span_report --word fear --out iba/app/reports/custom.md
"""
from __future__ import annotations

import argparse
import datetime
import pathlib
import re
import sqlite3
import sys


def _base_strong(strong: str) -> str | None:
    """H3372G -> H3372 (sub-entry suffix stripped); returns None if strong has no suffix."""
    m = re.match(r"^([HG]\d{4})([A-Z]+)$", strong)
    return m.group(1) if m else None


def build_report(db_path: str, word: str) -> str:
    conn = sqlite3.connect(db_path)
    conn.row_factory = sqlite3.Row
    cur = conn.cursor()

    cur.execute(
        "SELECT * FROM word_registry WHERE deleted=0 AND lower(word)=lower(?)", (word,)
    )
    reg = cur.fetchone()
    if reg is None:
        raise SystemExit(f"no active word_registry entry found for word={word!r}")

    cur.execute(
        "SELECT DISTINCT strong FROM word_strong WHERE word_id=? AND deleted=0 ORDER BY strong",
        (reg["id"],),
    )
    strongs = [r["strong"] for r in cur.fetchall()]

    lines: list[str] = []
    lines.append(f"# {reg['word']} — linked Strong's, parse meaning, span analysis")
    lines.append("")
    lines.append(f"*Generated by `word_strong_span_report.py` — {datetime.date.today().isoformat()}*")
    lines.append("")
    lines.append(f"- registry id: {reg['id']}")
    lines.append(f"- status: {reg['status']}")
    lines.append(f"- source: {reg['source']}")
    lines.append(f"- linked Strong's: {len(strongs)}")
    lines.append("")

    if not strongs:
        lines.append("No Strong's linked to this registry word — nothing to analyse.")
        return "\n".join(lines)

    for strong in strongs:
        cur.execute(
            "SELECT stepGloss, stepTransliteration, language, count FROM strong "
            "WHERE strongNumber=? AND deleted=0",
            (strong,),
        )
        srow = cur.fetchone()
        lines.append(f"## {strong}" + (f" — {srow['stepGloss']}" if srow and srow["stepGloss"] else ""))
        lines.append("")
        if srow:
            lines.append(
                f"transliteration: *{srow['stepTransliteration']}* &nbsp;|&nbsp; "
                f"language: {srow['language']} &nbsp;|&nbsp; STEP total count: {srow['count']}"
            )
        else:
            lines.append("*(no `strong` row for this code — not yet onboarded)*")
        lines.append("")

        # parse meaning — structured sense breakdown. Suffix sub-entries (e.g. H3372G) usually
        # have no rows of their own — the meaning tree lives under the base lemma (H3372) and is
        # shared across its sub-entries (mirrors the base-fallback noted on verse_lexical.ambiguity_note
        # elsewhere, e.g. H8193 shared with H8193J). Fall back to the base lemma when the exact
        # suffixed code has no rows, and say so.
        cur.execute(
            "SELECT sense_code, gloss, row_type FROM strong_meaning_parsed "
            "WHERE lemma_key=? AND deleted=0 ORDER BY sort",
            (strong,),
        )
        senses = cur.fetchall()
        fallback_base = None
        if not senses:
            base = _base_strong(strong)
            if base:
                cur.execute(
                    "SELECT sense_code, gloss, row_type FROM strong_meaning_parsed "
                    "WHERE lemma_key=? AND deleted=0 ORDER BY sort",
                    (base,),
                )
                senses = cur.fetchall()
                if senses:
                    fallback_base = base

        lines.append("**Parse meaning:**")
        lines.append("")
        if fallback_base:
            lines.append(f"*(no rows under {strong} itself — base lemma {fallback_base}'s meaning tree, shared across its sub-entries)*")
            lines.append("")
        if senses:
            for s in senses:
                code = s["sense_code"] or ""
                gloss = s["gloss"] or ""
                lines.append(f"- {code} {gloss}".strip())
        else:
            lines.append("*(no `strong_meaning_parsed` rows for this lemma or its base)*")
        lines.append("")

        # unique spans = distinct surface forms tagged with this strong, with one example verse each
        cur.execute(
            """
            SELECT s.surface, COUNT(*) n
            FROM verse_lexical vl
            JOIN span s ON s.id = vl.span_id
            WHERE vl.strong = ? AND vl.deleted = 0
            GROUP BY s.surface
            ORDER BY n DESC, s.surface ASC
            """,
            (strong,),
        )
        surfaces = cur.fetchall()
        lines.append(f"**Unique spans (distinct surface applications): {len(surfaces)}**")
        lines.append("")
        if not surfaces:
            lines.append("*(no `verse_lexical` occurrences for this Strong's yet — not built in any processed book)*")
        else:
            for srf in surfaces:
                cur.execute(
                    """
                    SELECT v.reference, v.text
                    FROM verse_lexical vl
                    JOIN span s ON s.id = vl.span_id
                    JOIN verse v ON v.id = vl.verse_id
                    WHERE vl.strong = ? AND vl.deleted = 0 AND s.surface = ?
                    ORDER BY v.id LIMIT 1
                    """,
                    (strong, srf["surface"]),
                )
                ex = cur.fetchone()
                lines.append(f"- **\"{srf['surface']}\"** ({srf['n']}x) — e.g. *{ex['reference']}*: \"{ex['text']}\"")
        lines.append("")

    conn.close()
    return "\n".join(lines)


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--word", required=True)
    ap.add_argument("--db", default="iba/app/db/iba.db")
    ap.add_argument("--out")
    args = ap.parse_args()

    report = build_report(args.db, args.word)

    if args.out:
        out_path = pathlib.Path(args.out)
    else:
        today = datetime.date.today().strftime("%Y%m%d")
        slug = args.word.lower().replace(" ", "-")
        out_path = pathlib.Path(f"iba/app/reports/{slug}-strong-span-analysis-{today}.md")

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(report, encoding="utf-8")
    print(f"written: {out_path}")


if __name__ == "__main__":
    main()
