"""export_md.py — render the prototype's JSON "tables" as markdown for review.

Reads only the tables build_prototype.py wrote. Nothing is recomputed here, so what
you read is what is in the tables.

Every claim is checkable against STEP directly:
    lexicon entry  http://localhost:8989/rest/module/getInfo/ESV_th//H7965G//
    its verses     http://localhost:8989/rest/search/masterSearch/strong=H7965G|version=ESV_th

Usage:
    python iba/prototype/export_md.py --word peace
"""

from __future__ import annotations

import argparse
import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
B = "http://localhost:8989"


def esc(s) -> str:
    return str(s if s is not None else "").replace("|", "\\|").replace("\n", " ").strip()


def clip(s, n) -> str:
    s = esc(s)
    return s if len(s) <= n else s[: n - 1] + "…"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--word", required=True)
    ap.add_argument("--verses", type=int, default=12, help="how many verses to show spans for")
    a = ap.parse_args()

    d = ROOT / "iba" / "prototype" / "data" / a.word
    T = {n: json.loads((d / f"{n}.json").read_text(encoding="utf-8"))
         for n in ("word", "term", "sense", "word_term", "term_related", "verse",
                   "sense_verse", "span", "_parse_check")}
    schema = json.loads((d / "_schema.json").read_text(encoding="utf-8"))

    term_by_id = {t["term_id"]: t for t in T["term"]}
    verse_by_id = {v["verse_id"]: v for v in T["verse"]}
    sense_by_id = {s["sense_id"]: s for s in T["sense"]}
    spans_by_verse: dict[int, list] = {}
    for s in T["span"]:
        spans_by_verse.setdefault(s["verse_id"], []).append(s)

    L: list[str] = []
    w = T["word"][0]
    L += [f"# Prototype tables — `{w['word']}`", "",
          "> Generated by `iba/prototype/export_md.py` from the JSON tables "
          "`build_prototype.py` wrote. **Nothing is recomputed here** — this is what is in the "
          "tables.", ">",
          "> **Check any row against STEP directly:**", ">",
          f"> - lexicon entry — `{B}/rest/module/getInfo/ESV_th//H7965G//`",
          f"> - its verses — `{B}/rest/search/masterSearch/strong=H7965G|version=ESV_th`", ""]

    L += ["## The model", "", "```", schema["model"], "```", "",
          "| table | grain | rows |", "|---|---|---|"]
    for k, v in schema["grain"].items():
        L.append(f"| `{k}` | {v} | {schema['counts'].get(k, 0):,} |")
    L += ["", "**Foreign keys**", "", "| from | to | |", "|---|---|---|"]
    for fk in schema["foreign_keys"]:
        L.append(f"| `{fk['from']}` | `{fk['to']}` | {esc(fk.get('note',''))} |")
    L += [""]

    # ── the claim to check ──────────────────────────────────────────────────
    splits = sorted({t["base"] for t in T["term"] if t["★ shares_base_with_other_terms"]})
    multi = [t for t in T["term"] if t["sense_count"] > 1]
    L += ["---", "", "## ★ The claim to check", "",
          "**The term is the set of codes sharing a definition TREE — not the base code.**", "",
          "- `A`/`B`/`C` suffixes = **homonyms** — different lemmas sharing consonants. "
          "Each has its **own** tree.",
          "- `G`/`H`/`I`/`J`… = **senses** — one lemma. They **share** one tree.",
          "- The **head** (the first line of `mediumDef`) is *this code's* meaning. "
          "The **tree** (the rest) is *the lemma's* full range.", "",
          f"In this pull: **{len(T['term'])} terms** from {len(set(t['base'] for t in T['term']))} "
          f"bases · **{len(splits)} bases split into homonyms** ({', '.join(splits) or 'none'}) · "
          f"**{len(multi)} term(s) carry more than one sense**.", ""]

    if splits:
        L += ["### The homonym splits — the thing to check", "",
              "Each base below produced **more than one term** because its codes carry "
              "**different trees**. If STEP shows one lemma here, the model is wrong.", ""]
        for base in splits:
            L += [f"**`{base}`**", "", "| term | codes | head of the first code | tree (first 90 chars) |",
                  "|---|---|---|---|"]
            for t in [x for x in T["term"] if x["base"] == base]:
                first = sense_by_id[[s["sense_id"] for s in T["sense"]
                                     if s["term_id"] == t["term_id"]][0]]
                L.append(f"| `{t['strongs']}` | {', '.join(f'`{c}`' for c in t['sense_codes'])} | "
                         f"{clip(first['★ meaning'], 46)} | {clip(t['tree'], 90) or '_(none)_'} |")
            L += [""]

    if multi:
        L += ["### The multi-sense lemmas — one term, several meanings", ""]
        for t in multi:
            L += [f"**`{t['strongs']}`** — {t['sense_count']} senses, one shared tree", "",
                  f"> tree: {clip(t['tree'], 240)}", "",
                  "| sense code | head — **the span's meaning** | gloss | occurs |",
                  "|---|---|---|---|"]
            for s in [x for x in T["sense"] if x["term_id"] == t["term_id"]]:
                L.append(f"| `{s['strongs']}` | **{clip(s['★ meaning'], 40)}** | {clip(s['gloss'], 26)} "
                         f"| {s['occurrence_count']:,} |")
            L += [""]

    # ── the tables ──────────────────────────────────────────────────────────
    L += ["---", "", "## `word`", "", "| word_id | word | source | status |", "|---|---|---|---|",
          f"| {w['word_id']} | {esc(w['word'])} | {esc(w['source'])} | {esc(w['status'])} |", ""]

    L += ["## `term` — the LEMMA · holds the tree", "",
          "| term_id | strongs | base | lexicon | senses | sense codes | homonym split? | tree |",
          "|---|---|---|---|---|---|---|---|"]
    for t in sorted(T["term"], key=lambda x: x["strongs"]):
        L.append(f"| {t['term_id']} | `{t['strongs']}` | `{t['base']}` | {t['lexicon']} | "
                 f"{t['sense_count']} | {', '.join(f'`{c}`' for c in t['sense_codes'])} | "
                 f"{'**yes**' if t['★ shares_base_with_other_terms'] else ''} | "
                 f"{clip(t['tree'], 70) or '_(none)_'} |")
    L += [""]

    L += ["## `sense` — the SUB-GLOSS · holds the head · **this is the span's meaning**", "",
          "| sense_id | strongs | → term | head | gloss | script | translit | occurs |",
          "|---|---|---|---|---|---|---|---|"]
    for s in sorted(T["sense"], key=lambda x: x["strongs"]):
        L.append(f"| {s['sense_id']} | `{s['strongs']}` | `{term_by_id[s['term_id']]['strongs']}` | "
                 f"**{clip(s['★ meaning'], 40)}** | {clip(s['gloss'], 24)} | {esc(s['script_form'])} | "
                 f"{esc(s['transliteration'])} | {s['occurrence_count']:,} |")
    L += [""]

    L += ["## `word_term` — the edge", "", f"{len(T['word_term'])} rows — this word to each term.",
          "", "| word_id | term_id | term |", "|---|---|---|"]
    for e in T["word_term"]:
        L.append(f"| {e['word_id']} | {e['term_id']} | `{term_by_id[e['term_id']]['strongs']}` |")
    L += [""]

    L += ["## `term_related`", "",
          f"{len(T['term_related']):,} rows. **This is the signal cluster assignment compares "
          "against.** Sample:", "",
          "| → term | related | gloss | script | translit |", "|---|---|---|---|---|"]
    for r in T["term_related"][:25]:
        L.append(f"| `{term_by_id[r['term_id']]['strongs']}` | `{esc(r['related_strongs'])}` | "
                 f"{clip(r['gloss'], 26)} | {esc(r['script_form'])} | {esc(r['transliteration'])} |")
    L += ["", f"_… {len(T['term_related']) - 25:,} more_", ""]

    # ── sense_verse: what STEP's search SAID, in full ───────────────────────
    sv_by_sense: dict[int, list] = {}
    for r in T["sense_verse"]:
        sv_by_sense.setdefault(r["sense_id"], []).append(r)
    check = {p["sense_id"]: p for p in T["_parse_check"]}
    dis = [p for p in T["_parse_check"] if not p["★ agrees"]]

    L += ["---", "", "## ★ `sense_verse` — THE VERSES, per sense", "",
          f"{len(T['sense_verse']):,} rows. **This is what STEP's search returned** — one row per "
          "(sense, verse). Every list below is directly checkable:", "",
          f"> `{B}/rest/search/masterSearch/strong=<code>|version=ESV_th`", "",
          "**The parse check.** `sense_verse` is what the SOURCE said; `span.sense_id` is what our "
          "parse of the interlinear found. They must agree — where they do not, the parse is losing "
          "occurrences silently.", "",
          f"**{len(T['_parse_check']) - len(dis)} of {len(T['_parse_check'])} senses agree.**"
          + ("" if not dis else f" ⚠ **{len(dis)} DISAGREE — listed below.**"), ""]
    if dis:
        L += ["| sense | STEP returned | parse found | missed | e.g. |", "|---|---|---|---|---|"]
        for p in sorted(dis, key=lambda x: -x["missed"]):
            L.append(f"| `{p['strongs']}` | {p['verses_step_returned']} | "
                     f"{p['verses_span_parse_found']} | **{p['missed']}** | "
                     f"{', '.join(p['missed_examples'])} |")
        L += [""]

    L += ["| sense | meaning | STEP verses | parse | agree? |", "|---|---|---|---|---|"]
    for s in sorted(T["sense"], key=lambda x: -len(sv_by_sense.get(x["sense_id"], []))):
        p = check.get(s["sense_id"], {})
        L.append(f"| `{s['strongs']}` | **{clip(s['★ meaning'], 30)}** | "
                 f"{p.get('verses_step_returned', 0)} | {p.get('verses_span_parse_found', 0)} | "
                 f"{'yes' if p.get('★ agrees') else '**NO**'} |")
    L += [""]

    L += ["### The verse list for every sense", "",
          "Check any of these against STEP's `masterSearch` for that code.", ""]
    for s in sorted(T["sense"], key=lambda x: -len(sv_by_sense.get(x["sense_id"], []))):
        rows = sv_by_sense.get(s["sense_id"], [])
        if not rows:
            continue
        refs = [verse_by_id[r["verse_id"]]["reference"] for r in rows]
        L += [f"**`{s['strongs']}`** — {clip(s['★ meaning'], 44)} — **{len(refs)} verses** "
              f"(term `{term_by_id[s['term_id']]['strongs']}`)", "",
              "> " + " · ".join(refs), ""]

    L += ["---", "", "## `verse`", "",
          f"{len(T['verse']):,} rows — every verse any of this word's senses occurs in.", "",
          "| verse_id | osis_id | reference | text |", "|---|---|---|---|"]
    for v in T["verse"]:
        L.append(f"| {v['verse_id']} | `{v['osis_id']}` | {esc(v['reference'])} | "
                 f"{clip(v['text'], 90)} |")
    L += [""]

    # ── spans + the backtrack ───────────────────────────────────────────────
    rich = sorted(T["verse"], key=lambda v: -sum(1 for s in spans_by_verse.get(v["verse_id"], [])
                                                 if s["sense_id"]))[: a.verses]
    L += ["---", "", "## `span` — one row per WORD of a verse · **names its sense**", "",
          f"{len(T['span']):,} rows total. **Every word of every verse is tagged** — that is what "
          "one `masterSearch.strong` call returns.", "",
          f"Below: the {len(rich)} verses carrying the most held senses. "
          "`→ sense` is **the backtrack**: the span names a sense, and reaches the term through it. "
          "A blank `→ sense` means the span names a code this word does not hold — another lemma "
          "in the same verse.", ""]
    for v in rich:
        spans = sorted(spans_by_verse.get(v["verse_id"], []), key=lambda s: s["word_index"])
        held = [s for s in spans if s["sense_id"]]
        L += [f"### {v['reference']} — `{v['osis_id']}`", "", f"> {clip(v['text'], 300)}", "",
              f"{len(spans)} spans, {len(held)} held.", "",
              "| # | surface | strongs | morph | particles | → sense | **the span's meaning** | → term |",
              "|---|---|---|---|---|---|---|---|"]
        for s in spans:
            se = sense_by_id.get(s["sense_id"]) if s["sense_id"] else None
            te = term_by_id[se["term_id"]] if se else None
            L.append(f"| {s['word_index']} | {esc(s['surface'])} | `{esc(s['strongs'])}` | "
                     f"`{esc(s['morph_code'])}` | {', '.join(f'`{p}`' for p in s['particles'])} | "
                     f"{'`' + se['strongs'] + '`' if se else ''} | "
                     f"{'**' + clip(se['★ meaning'], 34) + '**' if se else ''} | "
                     f"{'`' + te['strongs'] + '`' if te else ''} |")
        L += [""]

    out = ROOT / "iba" / "prototype" / f"tables-{a.word}.md"
    out.write_text("\n".join(L).rstrip() + "\n", encoding="utf-8")
    print(f"wrote {out.relative_to(ROOT)}  ({out.stat().st_size/1024:.0f} KB, {len(L)} lines)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
