"""Strand overview for one cluster, reproducing the M01 (fear) candidate pull.

Reproduces fear-strand-candidate-v2-20261001.md §1-§3A for any cluster code:
  - web pull (cluster hits x every OTHER cluster in the verse, filter <> code) -> CSV + SQL
  - vocabulary hits per Strong's
  - per Strong's: verses, divine party (T7) within 5 words, negator within 2 words before
  - links to other clusters: verses, near (<=3 words), commonest near pairs + example refs
  - surfaces: root -> surfaces, surface -> roots
Counts only, no reading. iba.db opened read-only.

Usage: python strand-overview-v1-20261002.py M25 life-death [outdir]
"""
import csv, sqlite3, sys, os
from collections import Counter, defaultdict

code, slug = sys.argv[1], sys.argv[2]
out = sys.argv[3] if len(sys.argv) > 3 else os.path.dirname(os.path.abspath(__file__))
tag = '20261002'
db = sqlite3.connect('file:iba/app/db/iba.db?mode=ro', uri=True)

WEB_SQL = f"""WITH CL_hits AS (
  SELECT vl.id AS vl_id, vl.verse_id, vl.position AS cl_position,
         vl.strong AS cl_strong, vl.surface AS cl_surface
  FROM verse_lexical vl
  JOIN cluster_strong cs ON cs.strong = vl.strong AND cs.cluster_code = '{code}' AND cs.deleted = 0
  JOIN cluster mc ON mc.cluster_code = cs.cluster_code AND mc.deleted = 0
  WHERE vl.deleted = 0
),
other_m_hits AS (
  SELECT vl.verse_id, vl.position AS other_position, vl.strong AS other_strong,
         vl.surface AS other_surface, cs.cluster_code AS other_cluster_code,
         c.short_name AS other_cluster_name
  FROM verse_lexical vl
  JOIN cluster_strong cs ON cs.strong = vl.strong AND cs.deleted = 0
  JOIN cluster c ON c.cluster_code = cs.cluster_code AND c.deleted = 0
  WHERE vl.deleted = 0
    AND cs.cluster_code <> '{code}'
    AND vl.verse_id IN (SELECT verse_id FROM CL_hits)
)
SELECT
  v.reference,
  m.cl_strong, ms.stepGloss AS cl_gloss, m.cl_surface, m.cl_position,
  o.other_strong, os.stepGloss AS other_gloss, o.other_surface,
  o.other_cluster_code, o.other_cluster_name, o.other_position,
  ABS(m.cl_position - o.other_position) AS distance
FROM CL_hits m
JOIN verse v ON v.id = m.verse_id
JOIN other_m_hits o ON o.verse_id = m.verse_id
LEFT JOIN strong ms ON ms.strongNumber = m.cl_strong
LEFT JOIN strong os ON os.strongNumber = o.other_strong
ORDER BY v.reference, m.cl_position, o.other_position;
"""

with open(f'{out}/{slug}-web-pull-query-v1-{tag}.sql', 'w', encoding='utf-8') as f:
    f.write(WEB_SQL)
cur = db.execute(WEB_SQL)
cols = [d[0] for d in cur.description]
web = cur.fetchall()
with open(f'{out}/{slug}-web-pull-v1-{tag}.csv', 'w', encoding='utf-8', newline='') as f:
    w = csv.writer(f); w.writerow(cols); w.writerows(web)

# all cluster hits (incl. verses with no other-cluster word)
hits = db.execute(f"""
SELECT vl.verse_id, v.reference, vl.position, vl.strong, s.stepGloss, vl.surface
FROM verse_lexical vl
JOIN cluster_strong cs ON cs.strong = vl.strong AND cs.cluster_code = ? AND cs.deleted = 0
JOIN verse v ON v.id = vl.verse_id
LEFT JOIN strong s ON s.strongNumber = vl.strong
WHERE vl.deleted = 0""", (code,)).fetchall()
verse_ids = {h[0] for h in hits}
t7 = {r[0] for r in db.execute("SELECT strong FROM cluster_strong WHERE cluster_code='T7' AND deleted=0")}
ctx = defaultdict(list)  # verse_id -> [(position, strong, is_negator)]
for vid, pos, st, neg in db.execute(
        f"SELECT verse_id, position, strong, is_negator FROM verse_lexical WHERE deleted=0 AND verse_id IN ({','.join(map(str, verse_ids))})"):
    ctx[vid].append((pos, st, neg))

L = []
p = L.append
p(f'# {code} strand overview — counts only (reproduces the M01 fear pull)\n')
p(f'Generated by `strand-overview-v1-{tag}.py {code} {slug}` from iba.db (read-only). No reading yet.\n')
multi = Counter(h[0] for h in hits)
p(f'## 1. What was run\n')
p(f'- {code} hits: **{len(hits)}** over **{len(verse_ids)} verses**; {sum(1 for n in multi.values() if n > 1)} verses hold two or more {code} words.')
p(f'- Web pull (`<> \'{code}\'`): {len(web)} rows over {len({r[0] for r in web})} verses → `{slug}-web-pull-v1-{tag}.csv`.\n')

p('## 2. Vocabulary\n')
p('| Strong | Gloss | Hits | Verses | Divine party ≤5 words (verses) | Negator ≤2 before (verses) |')
p('| --- | --- | --- | --- | --- | --- |')
by_strong = defaultdict(list)
for h in hits: by_strong[(h[3], h[4])].append(h)
for (st, gl), hs in sorted(by_strong.items(), key=lambda kv: -len(kv[1])):
    vs = {h[0] for h in hs}
    div = {h[0] for h in hs if any(o[1] in t7 and abs(o[0] - h[2]) <= 5 for o in ctx[h[0]])}
    neg = {h[0] for h in hs if any(o[2] == 1 and 0 < h[2] - o[0] <= 2 for o in ctx[h[0]])}
    p(f'| {st} | {gl} | {len(hs)} | {len(vs)} | {len(div)} | {len(neg)} |')
p('\nDivine party = any T7 Party-Divine Strong\'s. Negator = `verse_lexical.is_negator`. Both approximate (pointers only).\n')

p('## 3. Links to other clusters ("near" = within 3 words)\n')
p('| Cluster | Name | Verses | Near verses | Commonest near pairs (example refs) |')
p('| --- | --- | --- | --- | --- |')
cl = defaultdict(lambda: {'v': set(), 'near': set(), 'pairs': Counter(), 'refs': defaultdict(list)})
for r in web:
    ref, cs_, cg, csf, cp, os_, og, osf, oc, on, op, d = r
    e = cl[(oc, on)]; e['v'].add(ref)
    if d <= 3:
        e['near'].add(ref); k = f'{cg} + {og}'; e['pairs'][k] += 1
        if len(e['refs'][k]) < 3 and ref not in e['refs'][k]: e['refs'][k].append(ref)
for (oc, on), e in sorted(cl.items(), key=lambda kv: -len(kv[1]['v'])):
    top = '; '.join(f"{k} {n} ({', '.join(e['refs'][k])})" for k, n in e['pairs'].most_common(3))
    p(f'| {oc} | {on} | {len(e["v"])} | {len(e["near"])} | {top} |')

p('\n## 3A. Surfaces\n')
surf = Counter((h[3], h[5]) for h in hits)
p(f'- {len(hits)} hits carry **{len({h[5] for h in hits})} distinct surfaces**.\n')
p('### 3A.1 One root, several renderings (every surface; example refs for the rarer ones)\n')
refs = defaultdict(list)
for h in hits:
    if len(refs[(h[3], h[5])]) < 4: refs[(h[3], h[5])].append(h[1])
for (st, gl), hs in sorted(by_strong.items(), key=lambda kv: -len(kv[1])):
    items = sorted(((s, n) for (k, s), n in surf.items() if k == st), key=lambda x: -x[1])
    p(f'**{st} "{gl}" ({len(hs)} hits)**')
    p('- ' + ' · '.join(f'{s} ({n})' if n >= 5 else f'{s} ({n}: {", ".join(refs[(st, s)])})' for s, n in items))
    p('')
p('### 3A.2 One English word, many roots\n')
p('| Surface | Strong\'s behind it |'); p('| --- | --- |')
roots = defaultdict(set)
for h in hits: roots[(h[5] or '').lower()].add(h[3])
for s, rs in sorted(roots.items(), key=lambda kv: -len(kv[1])):
    if len(rs) >= 3: p(f'| {s} | {len(rs)} ({", ".join(sorted(rs))}) |')

with open(f'{out}/{slug}-strand-overview-data-v1-{tag}.md', 'w', encoding='utf-8') as f:
    f.write('\n'.join(L) + '\n')
print('\n'.join(L[:12]))
