"""Group A (desire, craving, longing): one decision per verse (#1993, item F). Read beside the worksheet
m18-group-A-worksheet-v1-20261009.md. Format: reference: (decision, place, reason). Used by m18-group-register-build-v1-20261009.py."""
D = {
 # coveting: the commandment, and see-covet-take
 'Exo 20:17': ('a', '10.6 Coveting', 'The commandment: "You shall not covet your neighbor\'s house; you shall not covet your neighbor\'s wife ... or anything that is your neighbor\'s". The object is always the neighbour\'s.'),
 'Deu 5:21': ('a', '10.6 Coveting', 'Deuteronomy uses two verbs: "covet" (the wife) and "desire" (the house and the rest).'),
 'Rom 13:9': ('a', '10.6 Coveting', '"You shall not covet ... are summed up in this word: You shall love your neighbor as yourself." The answer to coveting is a love for the same neighbour.'),
 'Rom 7:7': ('a', '10.6 Coveting', '"I would not have known what it is to covet if the law had not said, You shall not covet." The command names the desire.'),
 'Rom 7:8': ('a', '10.6 Coveting', '"sin, seizing an opportunity through the commandment, produced in me all kinds of covetousness". The named desire is seized and multiplied.'),
 'Jos 7:21': ('b', '10.6 Coveting', 'In 10.11 for hiding. Not said: Achan\'s own order, "when I saw ... then I coveted them and took them", the same three acts as Gen 3:6.'),
 'Mic 2:2': ('b', '10.6 Coveting', 'In 10.0 and Ch 11 (2:1-3) for devising. Not said: "They covet fields and seize them": coveting straight into taking, and the oppression of "a man and his inheritance".'),
 'Deu 7:25': ('a', '10.6 Coveting', '"You shall not covet the silver or the gold that is on them ... lest you be ensnared by it": the gold on an idol as a snare.'),
 'Exo 34:24': ('a', '13.1 Delight (or 10.6 Coveting)', '"no one shall covet your land, when you go up to appear before the Lord your God three times in the year": God guards from others\' coveting what is left behind for worship.'),
 'Pro 12:12': ('a', '10.6 Coveting', '"Whoever is wicked covets the spoil of evildoers, but the root of the righteous bears fruit": taking against growing.'),
 'Act 20:33': ('a', '10.6 Coveting', 'Paul: "I coveted no one\'s silver or gold or apparel", with "these hands ministered to my necessities" and "It is more blessed to give than to receive" (20:34-35).'),
 # desire that owns, leads, deceives, picks its teachers
 '1Pe 4:3': ('a', '10.6 Wanting that owns', '"the time that is past suffices for doing what the Gentiles want to do, living in sensuality, passions"; 4:2 "no longer for human passions but for the will of God".'),
 'Rom 6:12': ('a', '10.6 Wanting that owns', '"Let not sin therefore reign in your mortal body, to make you obey its passions": desire as the thing obeyed under a ruler.'),
 'Eph 4:22': ('a', '10.6 Wanting that owns', '"your old self ... corrupt through deceitful desires", then "renewed in the spirit of your minds" (4:23): desires that deceive.'),
 '1Th 4:5': ('a', '10.6 Wanting that owns', '"not in the passion of lust like the Gentiles who do not know God": lust set beside not knowing God.'),
 '1Pe 1:14': ('a', '10.6 Wanting that owns', '"do not be conformed to the passions of your former ignorance": passions joined to ignorance.'),
 '2Pe 1:4': ('a', '10.6 Wanting that owns', '"partakers of the divine nature, having escaped from the corruption that is in the world because of sinful desire".'),
 'Jude 16': ('a', '10.6 Wanting that owns', '"grumblers, malcontents, following their own sinful desires; ... loud-mouthed boasters": desire followed as a leader.'),
 'Jude 18': ('carried', '10.6 (Jude 16; 2Pe 3:3)', '"scoffers, following their own ungodly passions": same phrase as 2Pe 3:3.'),
 '2Pe 3:3': ('a', '10.6 Wanting that owns', '"scoffers will come ... following their own sinful desires", saying "Where is the promise of his coming?" (3:4).'),
 '2Ti 4:3': ('a', '10.6 Wanting that owns', '"having itching ears they will accumulate for themselves teachers to suit their own passions": desire choosing what it hears.'),
 '2Ti 3:6': ('a', '10.6 Wanting that owns', '"led astray by various passions, always learning and never able to arrive at a knowledge of the truth" (3:6-7).'),
 'Joh 8:44': ('a', '10.6 Wanting that owns', '"You are of your father the devil, and your will is to do your father\'s desires": desires as an inheritance from a father.'),
 '1Jo 2:17': ('a', '10.6 Wanting that owns', '"the desires of the flesh and the desires of the eyes and pride of life" (2:16), "the world is passing away along with its desires, but whoever does the will of God abides forever".'),
 'Jam 1:14': ('b', '10.6 Wanting that owns', 'In Ch 12 (held). Not said in 10.6: "lured and enticed by his own desire", the hunter\'s or fisher\'s bait, before 1:15.'),
 'Mar 4:19': ('carried', '10.6 (Luk 8:14)', '"the desires for other things enter in and choke the word": Mark\'s form of Luk 8:14, woven today.'),
 '1Ti 6:10': ('a', '10.6 Possessions', '"the love of money is a root of all kinds of evils. It is through this craving that some have wandered away from the faith and pierced themselves with many pangs".'),
 '1Ti 6:9': ('confirmed', '10.6, 10.7', 'In 10.6 and 10.7. Sound.'),
 '1Ti 5:11': ('route C', '', 'Church order for widows; "their passions draw them away from Christ, they desire to marry". Kept as data.'),
 'Pro 1:22': ('a', '10.6 Delight', '"How long ... will scoffers delight in their scoffing and fools hate knowledge?": delight set on scoffing, against Wisdom\'s call (1:23).'),
 # longing for people
 'Phili 1:8': ('a', '10.6 A person', '"how I yearn for you all with the affection of Christ Jesus", with "I hold you in my heart" (1:7).'),
 '2Ti 1:4': ('a', '10.6 A person', '"As I remember your tears, I long to see you, that I may be filled with joy": longing out of memory.'),
 'Phili 2:26': ('a', '10.6 A person', '"he has been longing for you all and has been distressed because you heard that he was ill": longing and distress for their distress.'),
 '1Th 3:6': ('a', '10.6 A person', '"long to see us, as we long to see you", and "in all our distress and affliction we have been comforted" (3:7).'),
 '2Cor 9:14': ('a', '10.6 A person', '"they long for you and pray for you, because of the surpassing grace of God upon you".'),
 'Phili 4:1': ('a', '10.6 A person', '"whom I love and long for, my joy and crown, stand firm thus in the Lord".'),
 'Rom 15:23': ('a', '10.6 A person', '"I have longed for many years to come to you", hindered (15:22), still held.'),
 '2Cor 7:7': ('a', '10.6 A person; Ch 11 sec 6', '"your longing, your mourning, your zeal for me": the longing told by Titus comforted Paul.'),
 'Gen 31:30': ('a', '10.6 A person', 'Laban: "you longed greatly for your father\'s house, but why did you steal my gods?" Jacob: "Because I was afraid" (31:31).'),
 'Luk 16:21': ('a', '10.6 Unmet', 'Lazarus "desired to be fed with what fell from the rich man\'s table": a want at another\'s gate, unanswered.'),
 'Luk 15:16': ('a', '10.6 Unmet', 'The younger son "longing to be fed with the pods that the pigs ate, and no one gave him anything", then "when he came to himself" (15:17).'),
 # desire for a person: sight, beauty, the servant, teshuqah
 'Deu 21:11': ('a', '10.6 Through the eye', '"you see among the captives a beautiful woman, and you desire to take her": the start of the case whose end (21:14) is already in 10.6.'),
 'Psa 45:11': ('a', '10.6 A person', '"the king will desire your beauty", after "forget your people and your father\'s house" (45:10).'),
 'Song 2:3': ('a', '10.6 A person', '"With great delight I sat in his shadow, and his fruit was sweet to my taste": desire as rest and taste.'),
 'Song 5:16': ('a', '10.6 A person', '"he is altogether desirable. This is my beloved and this is my friend".'),
 'Isa 53:2': ('a', '10.6 Through the eye', '"he had no form or majesty that we should look at him, and no beauty that we should desire him", then "despised and rejected" (53:3): the eye found nothing to desire.'),
 'Eze 23:6': ('a', '10.6 Through the eye', '"desirable young men, horsemen riding on horses": she lusted after them (23:5).'),
 'Eze 23:12': ('carried', '10.6 (Eze 23:6, 14)', 'Same phrase; with 23:14 "She saw men portrayed on the wall".'),
 'Eze 23:23': ('a', '10.6 Unmet, and wanting against God', '"desirable young men" again, now the ones who judge her (23:24).'),
 'Jer 5:8': ('a', '10.6 As heat', '"They were well-fed, lusty stallions, each neighing for his neighbor\'s wife", after "When I fed them to the full, they committed adultery" (5:7).'),
 'Gen 3:16': ('a', '10.6 A person; Ch 11 sec 4', '"Your desire shall be for your husband, and he shall rule over you."'),
 'Gen 4:7': ('b', '10.6 Wanting that owns; Ch 11 sec 4', 'In 10.0. Not said: "sin is crouching at the door. Its desire is for you, and you must rule over it": the same word as Gen 3:16 and Song 7:10.'),
 'Song 7:10': ('a', '10.6 A person; Ch 11 sec 4', '"I am my beloved\'s, and his desire is for me."'),
 # wilderness craving
 'Num 11:34': ('a', '10.6 Unmet, and wanting against God', '"the name of that place was called Kibroth-hattaavah, because there they buried the people who had the craving": a place named for a craving.'),
 'Psa 78:29': ('a', '10.6 Unmet, and wanting against God', '"they ate and were well filled, for he gave them what they craved. But before they had satisfied their craving" (78:29-30): filled, and the craving not satisfied.'),
 'Psa 78:30': ('confirmed', '10.6', 'In 10.6. Now set with 78:29.'),
 'Psa 106:14': ('a', '10.6 Unmet, and wanting against God', '"they had a wanton craving in the wilderness, and put God to the test" after "they soon forgot his works; they did not wait for his counsel" (106:13); "he gave them what they asked, but sent a wasting disease among them" (106:15).'),
 '1Cor 10:6': ('a', '10.6 Unmet, and wanting against God', '"these things took place as examples for us, that we might not desire evil as they did".'),
 # desire for God, his word, his day
 'Psa 119:131': ('a', '10.6 Aimed at God; Ch 11 sec 4 (panting)', '"I open my mouth and pant, because I long for your commandments."'),
 'Psa 119:174': ('a', '10.6 Aimed at God', '"I long for your salvation, O Lord, and your law is my delight", with "I have chosen your precepts" (119:173).'),
 'Psa 19:10': ('a', '10.6 Aimed at God', '"More to be desired are they than gold, even much fine gold; sweeter also than honey": worth and taste.'),
 'Psa 38:9': ('b', '10.6 Aimed at God', 'In 10.11. Not said in 10.6: "O Lord, all my longing is before you", in sickness and abandonment (38:8, 11).'),
 'Heb 11:16': ('a', '10.6 Wanting and death', '"they desire a better country, that is, a heavenly one", and "if they had been thinking of that land ... they would have had opportunity to return" (11:15).'),
 'Mat 13:17': ('a', '10.6 Aimed at God', '"many prophets and righteous people longed to see what you see, and did not see it".'),
 'Luk 17:22': ('a', '10.6 Aimed at God', '"you will desire to see one of the days of the Son of Man, and you will not see it", with "Do not go out or follow them" (17:23).'),
 'Amo 5:18': ('a', '10.6 Aimed at God', '"Woe to you who desire the day of the Lord! ... It is darkness, and not light": a wanted thing misread.'),
 'Jer 17:16': ('a', '10.6 Aimed at God', 'Jeremiah: "nor have I desired the day of sickness". The prophet disowns wanting the disaster he announces.'),
 'Heb 6:11': ('a', '10.6 A person', '"we desire each one of you to show the same earnestness to have the full assurance of hope until the end".'),
 # God's desire
 'Psa 132:13': ('a', '13.1 Delight', '"For the Lord has chosen Zion; he has desired it for his dwelling place".'),
 'Psa 132:14': ('a', '13.1 Delight', '"This is my resting place forever; here I will dwell, for I have desired it."'),
 'Psa 68:16': ('a', '13.1 Delight', '"Why do you look with hatred, O many-peaked mountain, at the mount that God desired for his abode?": the mountains pictured as looking with envy.'),
 'Deu 7:7': ('a', '13.1 Choosing', '"It was not because you were more in number ... that the Lord set his love on you and chose you, for you were the fewest", "but it is because the Lord loves you" (7:8).'),
 'Deu 10:15': ('a', '13.1 Choosing', '"the Lord set his heart in love on your fathers and chose their offspring", then "Circumcise therefore the foreskin of your heart" (10:16).'),
 'Hos 10:10': ('a', '13.1 Delight (He does what pleases him)', '"When I please, I will discipline them".'),
 'Luk 22:15': ('a', '13.1 Delight', 'Jesus: "I have earnestly desired to eat this Passover with you before I suffer".'),
 'Job 14:15': ('b', '13.1 Delight', 'In Ch 2 (14:13-15). Not said: Job hopes that God "would long for the work of your hands".'),
 'Isa 27:2': ('a', '13.1 Delight', '"A pleasant vineyard, sing of it! I, the Lord, am its keeper; every moment I water it ... I have no wrath" (27:2-4).'),
 'Jer 12:10': ('a', '13.1 Delight', '"they have made my pleasant portion a desolate wilderness ... desolate, it mourns to me ... but no man lays it to heart" (12:10-11).'),
 'Jer 3:19': ('a', '13.1 Delight', '"How I would set you among my sons, and give you a pleasant land ... And I thought you would call me, My Father": his hope for them, then "as a treacherous wife" (3:20).'),
 'Isa 42:14': ('confirmed', '13.1 Jealousy', 'In 13.1 Jealousy. Panting noted for Ch 11 sec 4.'),
 'Psa 91:14': ('a', '13.1 Delight', '"Because he holds fast to me in love, I will deliver him": God speaking of the one who clings to him.'),
 # desire's end and object
 'Pro 10:24': ('a', '10.6 Evil desire', '"What the wicked dreads will come upon him, but the desire of the righteous will be granted": dread and desire set against each other.'),
 'Pro 19:22': ('a', '10.6 A person', '"What is desired in a man is steadfast love."'),
 'Pro 18:1': ('a', '10.6 Evil desire', '"Whoever isolates himself seeks his own desire; he breaks out against all sound judgment."'),
 'Pro 21:26': ('a', '10.6 Evil desire', '"All day long he craves and craves, but the righteous gives and does not hold back": the verse after 21:25.'),
 'Psa 140:8': ('confirmed', '10.10', 'In 10.10 Plotting. Sound.'),
 'Pro 11:6': ('a', '10.6 Wanting that owns', '"the treacherous are taken captive by their lust": the word glossed desire, here the captor.'),
 'Psa 5:9': ('a', 'Ch 12 The heart as the source', '"their inmost self is destruction; their throat is an open grave": the same word, hawwah, as the inner self.'),
 'Psa 52:7': ('a', '10.6 Possessions', '"the man who would not make God his refuge, but trusted in the abundance of his riches and sought refuge in his own destruction!"'),
 'Psa 52:2': ('confirmed', '10.5', 'In 10.5. Sound.'),
 'Pro 17:4': ('a', '10.2', '"An evildoer listens to wicked lips, and a liar gives ear to a mischievous tongue": what one listens to shows what one is.'),
 'Job 6:30': ('route C', '', '"Cannot my palate discern the cause of calamity?": the M18 word means calamity.'),
 'Job 30:13': ('route C', '', '"they promote my calamity": calamity.'),
 'Psa 55:11': ('route C', '', '"ruin is in its midst": ruin.'),
 'Psa 91:3': ('route C', '', '"the deadly pestilence".'),
 'Psa 94:20': ('route C', '', '"wicked rulers ... who frame injustice by statute": the word means destruction.'),
 # greed
 'Jer 6:13': ('a', '10.6 Possessions', '"everyone is greedy for unjust gain; and from prophet to priest, everyone deals falsely. They have healed the wound of my people lightly, saying, Peace, peace" (6:13-14).'),
 'Jer 8:10': ('carried', '10.6 (Jer 6:13)', 'Same words as Jer 6:13.'),
 'Hab 2:9': ('a', '10.6 Possessions', '"Woe to him who gets evil gain for his house, to set his nest on high, to be safe from the reach of harm!"; "you have forfeited your life" (2:10).'),
 'Eze 22:12': ('a', '10.6 Possessions', '"you ... make gain of your neighbors by extortion; but me you have forgotten".'),
 'Job 20:20': ('a', '10.6 Possessions', '"Because he knew no contentment in his belly, he will not let anything in which he delights escape him".'),
 'Pro 23:3': ('a', '10.6 Possessions', '"Do not desire his delicacies, for they are deceptive food", after "put a knife to your throat if you are given to appetite" (23:2).'),
 'Pro 23:6': ('a', '10.6 Possessions', '"do not desire his delicacies, for he is like one who is inwardly calculating. Eat and drink! he says to you, but his heart is not with you" (23:6-7).'),
 'Pro 24:1': ('a', '10.6 Jealousy and envy', '"Be not envious of evil men, nor desire to be with them, for their hearts devise violence" (24:1-2).'),
 'Pro 21:20': ('a', '10.6 Possessions', '"Precious treasure and oil are in a wise man\'s dwelling, but a foolish man devours it."'),
 # what is desired taken away; pleasant things
 'Eze 24:16': ('a', '10.6 Taken away', '"I am about to take the delight of your eyes away from you at a stroke; yet you shall not mourn or weep" ... "at evening my wife died" (24:18). The sign that 24:21, 25 (in 10.6) explain.'),
 'Lam 1:10': ('a', '10.6 Taken away', '"The enemy has stretched out his hands over all her precious things", "she has seen the nations enter her sanctuary".'),
 'Isa 64:11': ('a', '10.6 Taken away', '"all our pleasant places have become ruins. Will you restrain yourself at these things, O Lord?" (64:11-12).'),
 'Isa 32:12': ('a', '10.6 Taken away', '"Beat your breasts for the pleasant fields", said to "you complacent women" (32:11).'),
 'Amo 5:11': ('a', '10.6 Taken away', '"because you trample on the poor ... you have planted pleasant vineyards, but you shall not drink their wine": pleasure built on oppression, withheld.'),
 'Deu 28:32': ('a', '10.6 Taken away', '"your eyes look on and fail with longing for them all day long, but you shall be helpless": longing for children taken.'),
 'Psa 39:11': ('a', '10.6 Taken away', '"When you discipline a man with rebukes for sin, you consume like a moth what is dear to him; surely all mankind is a mere breath!"'),
 '2Ch 21:20': ('a', 'Ch 2 What death is', '"he departed with no one\'s regret": a death no one desired back.'),
 'Hag 2:7': ('a', '13.1 Delight', '"the treasures of all nations shall come in, and I will fill this house with glory", "The silver is mine" (2:8).'),
 'Ecc 12:5': ('b', '10.6 Wanting and death', 'In 10.12 for the fears of age. Not said: "desire fails, because man is going to his eternal home".'),
 'Job 36:20': ('a', 'Ch 2 Wanting to die', 'Elihu: "Do not long for the night, when peoples vanish in their place."'),
 'Job 7:2': ('a', 'Ch 11 sec 4 (panting); Ch 2 Life weighed', '"Like a slave who longs for the shadow, and like a hired hand who looks for his wages, so I am allotted months of emptiness".'),
 'Job 5:5': ('a', 'Ch 11 sec 4 (panting)', '"the thirsty pant after his wealth": panting as greed.'),
 'Ecc 1:5': ('a', '13.4 Nature; Ch 11 sec 4 (panting)', '"the sun ... hastens to the place where it rises": the same verb as pant, for the sun.'),
 'Joe 1:20': ('a', '13.4 Nature', '"Even the beasts of the field pant for you because the water brooks are dried up".'),
 # aims
 'Rom 15:20': ('a', '10.7 Setting the heart (aims)', '"I make it my ambition to preach the gospel, not where Christ has already been named, lest I build on someone else\'s foundation".'),
 '2Cor 5:9': ('a', '10.7 Setting the heart (aims)', '"whether we are at home or away, we make it our aim to please him", before "we must all appear before the judgment seat of Christ" (5:10).'),
 '1Th 4:11': ('a', '10.7 Setting the heart (aims)', '"aspire to live quietly, and to mind your own affairs, and to work with your hands".'),
 '1Ti 3:1': ('a', '10.7 Setting the heart (aims)', '"If anyone aspires to the office of overseer, he desires a noble task."'),
 # confirmed / carried
 'Phili 1:23': ('confirmed', 'Ch 2, 10.7', 'In Ch 2 and 10.7. Sound.'),
 '2Cor 5:2': ('confirmed', '10.6, Ch 2, 10.1', 'In 10.6. Sound.'),
 'Jam 4:2': ('confirmed', '10.6', 'In 10.6. Sound.'),
 '2Sa 23:15': ('confirmed', '10.6, 10.7', 'In 10.6 and 10.7. Sound.'),
 '1Ch 11:17': ('carried', '10.6 (2Sa 23:15)', 'Parallel of 2Sa 23:15.'),
 'Isa 1:29': ('confirmed', '10.6, 10.7', 'In 10.6 and 10.7. Sound.'),
 'Gen 3:6': ('confirmed', '10.6', 'Woven in 10.6 earlier today.'),
 'Psa 106:24': ('confirmed', '10.5, 10.7, Ch 11', 'Cited four times. Sound.'),
 # route C: things, buildings, kings
 'Lam 2:17': ('route C', '', 'The M18 word is "carried out" (his word); already in 13.1 Purposing.'),
 'Dan 11:37': ('route C', '', '"the one beloved by women": a god\'s name or title; the king\'s self-magnifying is in 10.7 with 11:36.'),
 '2Ch 32:27': ('route C', '', 'Hezekiah\'s treasuries ("costly vessels").'),
 '1Ki 20:6': ('route C', '', 'Ben-hadad\'s demand, "whatever pleases you": the elders\' "Do not listen or consent" (20:8) is already in 10.7.'),
 'Eze 26:12': ('route C', '', '"your pleasant houses": things plundered.'),
 'Jer 25:34': ('route C', '', '"you shall fall like a choice vessel": a simile.'),
 '2Ch 36:10': ('route C', '', '"the precious vessels of the house of the Lord" taken.'),
 '2Ch 36:19': ('route C', '', '"destroyed all its precious vessels".'),
 'Isa 2:16': ('route C', '', '"all the beautiful craft".'),
 'Dan 11:8': ('route C', '', '"their precious vessels of silver and gold".'),
 'Nah 2:9': ('route C', '', '"all precious things" plundered.'),
 '1Ki 9:1': ('route C', '', '"all that Solomon desired to build": a building list.'),
 '1Ki 9:19': ('route C', '', 'As 1Ki 9:1.'),
 '2Ch 8:6': ('route C', '', 'As 1Ki 9:19.'),
 'Joe 3:5': ('route C', '', '"my rich treasures": taken things.'),
 'Hos 9:6': ('route C', '', '"their precious things of silver".'),
 'Isa 44:9': ('a', 'Ch 12 Idols taken inside', '"the things they delight in do not profit. Their witnesses neither see nor know": delight set on idols, beside 44:15-20 woven today.'),
 'Psa 17:12': ('route C', '', '"like a lion eager to tear": a simile for the enemy.'),
 'Zep 2:1': ('route C', '', '"O shameless nation": the word here means shame, not longing.'),
}
