# -*- coding: utf-8 -*-
import json

data = json.load(open('research/VE-lexical/faculty-map-build/inventory.json'))
sl = data[1032:1376]

# Decision map keyed by Strong's. value = (faculty_list, basis, confidence, taxonomy_flag)
D = {
"H2603A": (["affect","volition"], "be gracious / show mercy / plead: gracious favour disposition (affect) enacted as bestowing grace (volition)", "med", ""),
"H2604": (["affect","volition"], "Aramaic 'be gracious / show mercy / plea': gracious disposition + bestowal", "med", ""),
"H2616A": (["affect"], "cha.sad 'be kind/merciful': kindness as affective disposition of steadfast loyal love", "med", ""),
"H2616B": (["affect"], "cha.sad homonym glossed 'to shame' but senses are 'merciful'; classified by attested senses = kindness/loyal-love affect", "low", "homograph_guard"),
"H2617A": (["affect","relational_capacity"], "che.sed 'steadfast love/kindness': loyal covenant love = affective bond + relational loyalty capacity", "med", "candidate"),
"H2617B": (["affect","relational_capacity"], "che.sed sub-entry (senses steadfast love/kindness): loyal-love affect + relational loyalty", "low", "candidate"),
"H2620": (["volition"], "cha.sah 'to seek refuge/take refuge': act of trust-as-commitment, turning to take shelter = volition", "low", ""),
"H2622": ([], "cha.sut 'refuge/shelter': place/state of protection = THING", "high", ""),
"H2623": (["affect","relational_capacity"], "cha.sid 'pious/godly/merciful': the loyal-loving (chesed) person = affective loyal-love disposition", "low", "candidate"),
"H2626": ([], "cha.sin 'mighty': attribute of strength = STATE", "high", ""),
"H2627": ([], "chas.sir 'lacking/wanting': deficiency = STATE", "high", ""),
"H2630": ([], "cha.san 'to hoard': storing up = physical/transfer ACT", "high", ""),
"H2632": ([], "che.sen 'authority/power': abstract power = THING/STATE", "high", ""),
"H2633": ([], "cho.sen 'wealth/treasure/abundance': possessions = THING", "high", ""),
"H2634": ([], "cha.son 'strong': attribute of strength = STATE", "high", ""),
"H2654A": (["affect"], "cha.phets 'to delight in': emotion of delight = affect", "high", ""),
"H2655": (["affect"], "cha.phets 'delighting/to delight in': affective delight (willing shade, core delight)", "high", ""),
"H2656": (["affect"], "che.phets 'pleasure/delight/desired': affective pleasure and desire", "high", ""),
"H2659": (["affect","conscience"], "cha.pher 'be ashamed/disgraced/confounded': shame = affect with conscience-before-standard aspect", "med", ""),
"H2729": (["affect"], "cha.rad 'to tremble/be afraid': fear emotion = affect", "high", ""),
"H2730": (["affect"], "cha.red 'trembling': fear/trembling = affect", "high", ""),
"H2731": (["affect"], "cha.ra.dah 'trembling/panic': fear = affect", "high", ""),
"H2734": (["affect"], "cha.rah 'to be incensed/angry/burned': anger emotion = affect", "high", ""),
"H2740": (["affect"], "cha.ron 'burning anger/wrath': anger = affect", "high", ""),
"H2750": (["affect"], "cho.ri 'burning/heat of anger, fierce': anger heat = affect", "high", ""),
"H2778A": ([], "cha.raph 'to taunt/mock/reproach': verbal act against another = speech ACT toward external pole", "med", ""),
"H2781": (["affect"], "cher.pah 'reproach/disgrace/taunt' as experienced = shame/disgrace affect", "low", ""),
"H2790A": (["cognition"], "cha.rash 'to plow/devise': in 'devise' sense = scheming/planning cognition (homograph with plow=physical)", "low", "homograph_guard"),
"H2790B": ([], "cha.resh 'be quiet/silent/peace': silence = STATE/act of keeping silent", "med", ""),
"H2803G": (["cognition","creativity"], "cha.shav 'to devise: design/skillfully': designing = cognition + creative origination of design", "med", "candidate"),
"H2803H": (["cognition"], "cha.shav 'to devise: count/calculate/regarded': reckoning = cognition", "high", ""),
"H2803I": (["cognition","creativity"], "cha.shav 'to devise: devise/planned': devising plans = cognition + creativity", "med", "candidate"),
"H2803J": (["cognition"], "cha.shav 'to devise: think/counted': thinking/reckoning = cognition", "high", ""),
"H2808": (["cognition"], "chesh.bon 'explanation/scheme/thought': product of cognition", "med", ""),
"H2810": (["cognition","creativity"], "chish.sha.von 'invention/machines/schemes': devised contrivance = cognition + creativity", "low", "candidate"),
"H2814": ([], "cha.shah 'be silent/keep quiet': act/state of silence", "med", ""),
"H2836A": (["affect"], "cha.shaq 'to desire/love/longed': desire/love emotion = affect", "high", ""),
"H2836B": (["affect"], "cha.shaq homonym 'to connect' but senses love/desired/heart: classified by attested senses = desire affect", "low", "homograph_guard"),
"H2837": (["affect"], "che.sheq 'desire/longed for': desire = affect", "high", ""),
"H2844A": (["affect"], "chat 'terror/dread/fear': fear emotion = affect", "high", ""),
"H2847": (["affect"], "chit.tah 'terror': fear = affect", "high", ""),
"H2849": (["affect"], "chat.chat 'terror(s)': fear = affect", "high", ""),
"H2851": (["affect"], "chit.tit 'terror': fear = affect", "high", ""),
"H2865": (["affect"], "cha.tat 'to be dismayed/terrified/broken': dismay/fear emotion = affect", "high", ""),
"H2866": (["affect"], "cha.tat 'terror/calamity': in terror sense = affect (calamity shade is event)", "low", ""),
"H2868": (["affect"], "te.ev 'be good/glad' (Aramaic): glad = affective pleasure", "med", ""),
"H2889": ([], "ta.hor 'pure/clean': ritual/moral purity STATE", "high", ""),
"H2890": ([], "te.hor 'pureness/purer': purity STATE", "high", ""),
"H2891": ([], "ta.her 'be pure/cleansed/cleanse': becoming/making clean = STATE/ritual act", "high", ""),
"H2892A": ([], "to.har 'purity/purifying': purity STATE", "high", ""),
"H2892B": ([], "to.har 'clearness/purifying': purity STATE", "high", ""),
"H2893": ([], "to.ho.rah 'purifying/cleansing/cleanness': purity STATE/ritual act", "high", ""),
"H2895": (["affect"], "tov 'be pleasing/merry/good/well': merry/pleasing = affective gladness", "med", ""),
"H2896A": (["affect","moral_evaluation"], "tov 'good/pleasant/better': value-judgement good-vs-better = moral_evaluation; pleasant shade = affect", "med", ""),
"H2930A": ([], "ta.me 'to defile/unclean': ritual/moral impurity STATE / defiling act", "high", ""),
"H2931": ([], "ta.me 'unclean/defiled': impurity STATE", "high", ""),
"H2932": ([], "tum.ah 'uncleanness': impurity STATE", "high", ""),
"H2938": (["perception"], "ta.am 'to perceive/taste': sensory perception (taste) = perception", "high", ""),
"H2954": (["cognition"], "ta.phash 'be insensitive/fat (of heart)': dullness of mind = impaired cognition", "low", ""),
"H2973": (["cognition","moral_evaluation"], "ya.al 'be foolish/lack sense': folly = defect of cognition; carries moral_evaluation vs wisdom standard", "med", ""),
"H2974": (["volition"], "ya.al 'be willing/pleased/content/persisted': willingness/resolve = volition", "med", ""),
"H2976": (["affect"], "ya.ash 'to despair/hopeless/vain': despair emotion = affect", "high", ""),
"H3013": (["affect"], "ya.gah 'to suffer/afflicted/torment': suffering/grief = affect", "med", ""),
"H3015": (["affect"], "ya.gon 'sorrow/grief/sighing': sorrow emotion = affect", "high", ""),
"H3016": (["affect"], "ya.gor 'fearing/afraid': fear = affect", "high", ""),
"H3025": (["affect"], "ya.gor 'to fear/afraid/dread': fear = affect", "high", ""),
"H3027W": ([], "yad 'hand: owner/rule': hand/possession-rule = THING (body part / metonym)", "high", ""),
"H3029": ([], "ye.da 'to praise/give thanks' (Aramaic): thanksgiving/praise = expressive ACT", "med", ""),
"H3033": (["affect"], "ye.di.dut 'beloved': belovedness implying love = affect", "low", ""),
"H3034": ([], "ya.dah 'to give thanks/acknowledge/confess': verbal confession/thanks = speech ACT", "med", ""),
"H3045": (["cognition","perception"], "ya.da 'to know': knowing = cognition; experiential knowing also perception", "high", ""),
"H3175": (["volition"], "ya.chil 'waiting/wait': hopeful waiting = patient volition/expectant trust", "low", ""),
"H3176G": (["volition"], "ya.chal 'to wait: wait': expectant waiting = volition (sustained orientation)", "low", ""),
"H3176H": (["affect","volition"], "ya.chal 'to wait: hope': hope = expectant affect + volitional orientation", "med", ""),
"H3190": (["affect"], "ya.tav 'be good/well/pleased': pleased/good = affective gladness", "med", ""),
"H3201": ([], "ya.khol 'be able/can/could': capability/modal = STATE", "high", ""),
"H3286": ([], "ya.eph 'to faint/weary/exhausted': physical exhaustion = bodily STATE", "high", ""),
"H3289": (["cognition"], "ya.ats 'to advise/counsel/counselor': giving counsel = cognition (deliberation)", "high", ""),
"H3336": (["volition"], "ye.tser 'intention/plan/purpose': formed intent/purpose = volition", "med", ""),
"H3349": (["volition"], "yiq.qe.hah 'obedience/obey': obedience = volitional submission", "low", ""),
"H3372G": (["affect"], "ya.re 'to fear: revere/afraid/fear': fear/reverence emotion = affect", "high", ""),
"H3372H": (["affect"], "ya.re 'to fear: revere/awesome': reverent fear = affect", "high", ""),
"H3373": (["affect"], "ya.re 'afraid/fearing': fear = affect", "high", ""),
"H3374": (["affect"], "yir.ah 'fear/awe': fear/awe = affect", "high", ""),
"H3401": ([], "ya.riv 'opponent/adversary/contend': an adversary = PERSON", "high", ""),
"H3444": ([], "ye.shu.ah 'salvation/deliverance': deliverance = event/STATE acted by another", "high", ""),
"H3476": (["moral_evaluation"], "yo.sher 'uprightness/upright': moral rectitude vs standard = moral_evaluation", "high", ""),
"H3477G": (["moral_evaluation"], "ya.shar 'upright: right/honest': moral uprightness = moral_evaluation", "high", ""),
"H3477I": (["moral_evaluation"], "ya.shar 'upright: straight/safe': entry is upright/right family = moral_evaluation (literal straight = physical)", "low", "homograph_guard"),
"H3483": (["moral_evaluation"], "ye.sha.rah 'uprightness': moral rectitude = moral_evaluation", "high", ""),
"H3510": (["affect"], "ka.av 'to pain/grieved': pain/grief = affect (also physical pain shade)", "med", ""),
"H3511": (["affect"], "ke.ev 'pain/distress': pain/distress = affect", "med", ""),
"H3512A": (["affect"], "ka.ah 'be disheartened/brokenhearted/afraid': disheartenment = affect", "med", ""),
"H3512B": (["affect"], "ka.eh 'disheartened/brokenhearted': dejection = affect", "med", ""),
"H3513H": ([], "ka.ved 'to honor: heavy/hardened/harden': heavy/hardened sense = STATE (weight/hardness)", "low", "homograph_guard"),
"H3513I": ([], "ka.ved 'to honor: many/multiply/abounding': abundance = quantity STATE", "med", "homograph_guard"),
"H3513J": ([], "ka.ved 'to honor: dull/stopped': dullness of ear/eye = impaired physical STATE", "low", "homograph_guard"),
"H3519": (["affect"], "ka.vod 'glory/honor/glorious': as esteem-regard = affect, but largely an attribute", "low", ""),
"H3520A": ([], "ka.vod 'glorious/stately': attribute of splendour = STATE", "high", ""),
"H3520B": ([], "ke.vud.dah 'riches/stately': wealth/splendour = THING", "high", ""),
"H3581B": ([], "ko.ach 'strength/power/might': physical/abstract strength = STATE", "high", ""),
"H3616": (["affect"], "ka.leh 'longing': longing = affective desire", "high", ""),
"H3631": ([], "kil.la.von 'failing/destruction': failing/wasting = STATE/event", "high", ""),
"H3637": (["affect","conscience"], "ka.lam 'be humiliated/ashamed/blush': shame/humiliation = affect + conscience-before-standard", "med", ""),
"H3639": (["affect","conscience"], "ke.lim.mah 'shame/dishonor/disgrace': shame = affect + conscience", "med", ""),
"H3640": (["affect","conscience"], "ke.lim.mut 'shame': shame = affect + conscience", "med", ""),
"H3665": (["volition"], "ka.na 'be humble/subdued/humbled': being humbled/subduing self = volitional submission (often externally subdued)", "low", ""),
"H3688": (["cognition"], "ka.sal 'be stupid/foolish': stupidity/folly = defect of cognition", "med", ""),
"H3690": (["volition"], "kis.lah 'confidence/folly': confidence-as-trust = volitional reliance (folly shade mixed)", "low", ""),
"H3700": (["affect"], "ka.saph 'to long/longed/eager': longing = affective desire", "high", ""),
"H3707": (["affect"], "ka.as 'to provoke/anger/provoked': anger = affect", "high", ""),
"H3708B": (["affect"], "ka.a.s 'vexation/provocation/grief': vexation/grief = affect", "high", ""),
"H3722A": ([], "kip.per 'to atone/make atonement': cultic atonement = ritual ACT", "high", ""),
"H3722B": ([], "ka.phar 'to cover/make atonement': covering/atoning = ritual/physical ACT", "high", ""),
"H3725": ([], "kip.pu.rim 'atonement': the atonement = ritual event/THING", "high", ""),
"H3735": (["affect"], "ke.ra 'be distressed/anxious' (Aramaic): anxiety/distress = affect", "med", ""),
"H3772H": ([], "ka.rat 'to cut: make [covenant]': covenant-making = legal/relational ACT producing a covenant THING", "med", ""),
"H3807": ([], "ka.tat 'to crush/beat to pieces': physical crushing = physical ACT", "high", ""),
"H3811": (["affect"], "la.ah 'be weary/wearied': weariness as dispiritedness = affect (also physical fatigue shade)", "low", ""),
"H3820A": (["cognition","conscience","perception","volition"], "lev 'heart': inner-being SEAT operating thought, conscience, perception, will", "high", ""),
"H3821": (["cognition","conscience","perception","volition"], "lev 'heart' (Aramaic): inner-being seat of mind/conscience/perception/will", "med", ""),
"H3823A": (["affect","cognition"], "la.vav 'to encourage/understanding/heart': denominative of heart = to hearten (affect) / understanding (cognition)", "low", ""),
"H3824": (["cognition","conscience","perception","volition"], "le.vav 'heart/mind': inner-being seat of mind/conscience/perception/will", "high", ""),
"H3825": (["cognition","conscience","perception","volition"], "le.vav 'heart/mind' (Aramaic): inner-being seat operating the faculties", "med", ""),
"H3826": (["cognition","conscience","perception","volition"], "lib.bah 'heart': inner-being seat operating the faculties", "med", ""),
"H3868": ([], "luz 'be devious/perverse': moral crookedness = STATE/quality", "low", ""),
"H3891": ([], "la.zut 'perversity/devious': crookedness = STATE/quality", "med", ""),
"H3908": ([], "la.chash 'charm/whispered prayer': whispered incantation = speech/ritual ACT", "high", ""),
"H3960": ([], "la.shan 'to slander': slandering = speech ACT against another", "high", ""),
"H3981": ([], "ma.a.mats 'power/force': strength/force = STATE/attribute", "high", ""),
"H4007": (["affect"], "mab.bat 'expectation/hope': hope/expectation = affective-volitional expectancy", "low", ""),
"H4009": (["volition"], "miv.tach 'confidence/trust/reliance': trust-as-reliance = volition (commitment)", "med", ""),
"H4010": (["affect"], "mav.li.git 'cheer/joy': cheer/joy = affect", "med", ""),
"H4032": (["affect"], "ma.gor 'terror': fear = affect", "high", ""),
"H4034": (["affect"], "me.go.rah 'fear/dreads': fear = affect", "high", ""),
"H4035": (["affect"], "me.gu.rah 'fear' (senses barn/fears; homonym): in fear sense = affect", "low", "homograph_guard"),
"H4064": ([], "mad.veh 'disease': illness = bodily STATE", "high", ""),
"H4093": (["cognition"], "mad.da 'knowledge/learning/thoughts': knowledge = cognition", "high", ""),
"H4110": ([], "ma.ha.lal 'praise': praise = expressive ACT/object", "med", ""),
"H4156": (["cognition"], "mo.e.tsah 'counsel/devices': counsel/devising = cognition", "med", ""),
"H4157": (["affect"], "mu.a.qah 'distress/crushing burden': distress = affect", "med", ""),
"H4164": (["affect"], "mu.tsaq 'constraint/anguish/cramping': anguish = affect (also physical constraint shade)", "low", ""),
"H4172A": (["affect"], "mo.rah 'fear/terror/dread': fear = affect", "high", ""),
"H4172B": (["affect"], "mo.ra 'fear/terror/dread': fear = affect", "high", ""),
"H4209": (["cognition"], "me.zim.mah 'plot/purpose/intents/vile deeds': scheming/intent = cognition (purposing)", "med", ""),
"H4210": ([], "miz.mor 'melody/Psalm': a song = THING/artefact", "high", ""),
"H4241": ([], "mich.yah 'recovery/reviving/preserve life': preservation of life = event/STATE", "high", ""),
"H4261": (["affect"], "mach.mad 'desire/delight/beloved/pleases': desire/delight = affect", "high", ""),
"H4263": (["affect"], "mach.mal 'compassion/yearning': compassion/yearning = affect", "high", ""),
"H4268": ([], "mach.s.seh 'refuge/shelter': place of protection = THING", "high", ""),
"H4284": (["cognition"], "ma.cha.sha.vah 'plot/thoughts/plans/plots': thoughts/plans = cognition", "high", ""),
"H4288": (["affect"], "me.chit.tah 'terror/horror/ruin': terror = affect (ruin shade is event)", "med", ""),
"H4297": ([], "mut.teh 'perversion/injustice': perverting of justice = STATE/wrongdoing", "high", ""),
"H4339": (["moral_evaluation"], "me.shar 'uprightness/equity/right': equity/uprightness = moral_evaluation", "high", ""),
"H4341": (["affect"], "makh.ov 'pain/sorrow/sorrows': pain/sorrow = affect", "high", ""),
"H4357": ([], "mikh.lah 'perfection': completeness = STATE", "high", ""),
"H4468": ([], "mam.la.khut 'kingdom': realm = THING/institution", "high", ""),
"H4470": (["affect"], "me.mer 'bitterness': bitterness of soul = affect", "low", ""),
"H4472": (["affect"], "mam.ror 'bitterness': emotional/experiential bitterness = affect", "low", ""),
"H4474": ([], "mim.shal 'dominion/rulers/authority': rule/authority = THING/STATE", "high", ""),
"H4475": ([], "mem.sha.lah 'dominion/authority': rule = THING/STATE", "high", ""),
"H4486": (["cognition"], "man.da 'knowledge/reason' (Aramaic): knowledge/reason = cognition", "high", ""),
"H4494": ([], "ma.no.ach 'resting/resting place/rest': place/state of rest = THING/STATE", "high", ""),
"H4496H": ([], "me.nu.chah 'resting/rest/resting place': rest = STATE/place", "high", ""),
"H4553": (["affect"], "mis.ped 'mourning/lamentation/wailing': mourning = affect (grief), expressed", "med", ""),
"H4581": ([], "ma.oz 'security/stronghold/refuge/protection': stronghold = THING/place", "high", ""),
"H4603": ([], "ma.al 'be unfaithful/committed treachery/broke': act of treachery/breach = ACT/RECORD of wrongdoing", "med", ""),
"H4604": ([], "ma.al 'unfaithfulness/treachery/faithlessness': the breach = RECORD/STATE of wrongdoing", "med", ""),
"H4617": ([], "ma.a.neh 'answer/purpose': a reply = speech THING/product", "med", ""),
"H4620": (["affect"], "ma.a.tse.vah 'torment': torment = affect (anguish)", "med", ""),
"H4637": (["affect"], "ma.a.ra.tsah 'terror/terrifying': fear = affect", "med", ""),
"H4652": (["affect"], "miph.la.ah 'wonder/wondrous works': wonder/marvel = affect (amazement); largely wondrous works = deeds", "low", ""),
"H4683": ([], "mats.tsah 'strife/fight': conflict = external event/ACT", "high", ""),
"H4689": (["affect"], "ma.tsoq 'distress/anguish': distress = affect", "high", ""),
"H4691": (["affect"], "me.tsu.qah 'distress/anguish': distress = affect", "high", ""),
"H4695": ([], "mats.tsut 'strife/contend': conflict = external event", "high", ""),
"H4712": (["affect"], "me.tsar 'distress/pangs/terror': distress = affect (also straits/physical shade)", "med", ""),
"H4723B": (["affect"], "miq.veh 'hope/abiding': hope = affective-volitional expectancy", "low", ""),
"H4744": ([], "miq.ra 'assembly/convocation': gathering = event/THING", "high", ""),
"H4751": (["affect"], "mar 'bitter/bitterness/deeply': bitterness of soul = affect (corrected from cur moral_evaluation)", "low", ""),
"H4766": ([], "mar.veh 'abundance/increase': quantity = STATE", "high", ""),
"H4768": ([], "mar.bit 'greatness/majority/descendants': magnitude/quantity = STATE (cur cognition wrong)", "med", ""),
"H4771": ([], "mar.go.a 'rest': rest = STATE/place", "high", ""),
"H4774": ([], "mar.ge.ah 'repose': repose = STATE", "high", ""),
"H4775": (["volition"], "ma.rad 'to rebel/rebelled': rebellion = volitional refusal/defiance of authority", "med", ""),
"H4776": (["volition"], "me.rad 'rebellion': rebellion = volitional defiance", "low", ""),
"H4777": (["volition"], "me.red 'rebellion': rebellion = volitional defiance", "low", ""),
"H4780": (["volition"], "mar.dut 'rebellious': rebelliousness = volitional defiance disposition", "low", ""),
"H4786": (["affect"], "mo.rah 'bitterness/bitter': bitterness of soul = affect", "low", ""),
"H4787": (["affect"], "mor.rah 'bitterness': emotional bitterness = affect", "low", ""),
"H4791": ([], "ma.rom 'height/heights': elevation = physical THING/place", "high", ""),
"H4798": (["affect"], "mar.ze.ach 'mourning': mourning = affect (grief)", "low", ""),
"H4805H": (["volition"], "me.ri 'rebellion/rebellious': rebellion = volitional defiance (bitter shade)", "med", ""),
"H4808": ([], "me.ri.vah 'provocation/strife/quarreled': strife/quarrel = external conflict event", "high", ""),
"H4820": ([], "mir.mah 'deceit/deceitful/deceitfully': the act of deceiving = speech/ACT of treachery", "low", ""),
"H4835": ([], "me.ru.tsah 'oppression/violence': violence/oppression = external ACT", "high", ""),
"H4843": (["affect"], "ma.rar 'to provoke/bitter/bitter distress/rage': to be/make bitter, rage = affect", "med", ""),
"H4844": ([], "ma.ror 'bitterness/bitter herbs': literal bitter herbs/taste = THING/physical (homonym)", "low", "homograph_guard"),
"H4849": (["moral_evaluation"], "mir.sha.at 'wickedness/wicked woman': wickedness vs standard = moral_evaluation", "med", ""),
"H4862": (["affect"], "mish.a.lah 'petition/desires': desires/petition = affect (desire); request shade = speech", "low", ""),
"H4867": ([], "mish.bar 'wave/breakers': sea waves = physical THING (M01 metaphor, lemma = wave)", "med", ""),
"H4885": (["affect"], "ma.s.vo.s 'rejoicing/joy/mirth/gladness': joy = affect", "high", ""),
"H4889": ([], "mash.chit 'destruction/destroy/corruption': destruction = event/ACT", "high", ""),
"H4892": ([], "mash.chet 'destruction/destroying': destruction = event/ACT", "high", ""),
"H4893A": ([], "mish.chat 'mutilation/marred': disfigurement = physical STATE", "high", ""),
"H4893B": ([], "ma.she.chat 'corruption/mutilation': corruption/disfigurement = STATE", "high", ""),
"H4895": (["affect"], "mas.te.mah 'hatred': hatred = affect", "high", ""),
"H4896": ([], "mish.tar 'rule': rule/dominion = THING/STATE", "high", ""),
"H4910": ([], "ma.shal 'to rule/ruler/rules': governing = ACT/role, external authority", "high", ""),
"H4915B": ([], "mo.shel 'dominion/rule': dominion = THING/STATE", "high", ""),
"H4924B": ([], "mish.man 'fatness/richest parts/stout/fat': fatness/richness = physical STATE/THING", "high", ""),
"H4926": (["perception"], "mish.ma 'hearing/hear': hearing = perception", "high", ""),
"H4937A": ([], "mish.an 'support': prop/support = THING", "high", ""),
"H4937B": ([], "mish.en 'support': prop/support = THING", "high", ""),
"H4941G": (["moral_evaluation"], "mish.pat 'justice: judgement/judgments': judgement/justice = moral_evaluation", "high", ""),
"H4941H": (["moral_evaluation"], "mish.pat 'justice/right/just': justice = moral_evaluation", "high", ""),
"H4941I": (["moral_evaluation"], "mish.pat 'justice: rule/law/prescribed': ordinance/legal standard = moral_evaluation", "med", ""),
"H4941J": (["moral_evaluation"], "mish.pat 'justice: custom/manner/way': in justice family; custom shade weaker but entry = justice", "low", "homograph_guard"),
"H4951": ([], "mis.rah 'dominion/government': government/rule = THING/STATE", "high", ""),
"H4974": ([], "me.tom 'soundness': wholeness/health = bodily STATE", "high", ""),
"H5000": (["affect"], "na.eh 'lovely/fitting/becoming': loveliness/aesthetic value = affect (cur perception removed)", "low", ""),
"H5006": ([], "na.ats 'to spurn/despise/spurned': spurning = ACT of contempt toward external pole", "low", ""),
"H5007A": ([], "ne.a.tsah 'contempt/disgrace': contempt/disgrace = STATE/treatment", "low", ""),
"H5007B": ([], "ne.a.tsah 'contempt/blasphemies/revilings': reviling = speech ACT", "med", ""),
"H5008": ([], "na.aq 'to groan': groaning = vocal/physical expression = ACT", "med", ""),
"H5009": (["affect"], "ne.a.qah 'groan/groaning': groaning as expressed distress = affect (suffering)", "low", ""),
"H5012": ([], "na.va 'to prophesy/prophesied': prophesying = speech ACT", "high", ""),
"H5016": ([], "ne.vu.ah 'prophecy': a prophecy = speech THING/message", "high", ""),
"H5017": ([], "ne.vu.ah 'prophesying' (Aramaic): prophesying = speech ACT", "high", ""),
"H5034B": ([], "na.vel 'to wither/lost heart/withers': withering = physical decay STATE", "low", ""),
"H5039": (["moral_evaluation"], "ne.va.lah 'folly/outrageous thing': moral outrage/disgraceful folly vs standard = moral_evaluation", "med", ""),
"H5040": ([], "nav.lut 'lewdness': shamelessness conduct = STATE (cur affect doubtful)", "low", ""),
"H5065": ([], "na.ga.s 'to oppress/hard pressed/taskmasters': oppressing/driving = external ACT", "high", ""),
"H5068": (["volition"], "na.dav 'be willing/willingly/freewill offerings': willingness/voluntary giving = volition", "high", ""),
"H5069": (["volition"], "ne.dav 'be willing/freely offers' (Aramaic): willingness = volition", "high", ""),
"H5074": ([], "na.dad 'to wander/fled/fugitive': wandering/fleeing = physical movement ACT", "high", ""),
"H5076": ([], "ne.dud 'tossing/toss': restlessness/sleeplessness = physical STATE", "low", ""),
"H5079": ([], "nid.dah 'impurity/menstrual': ritual impurity = STATE", "high", ""),
"H5081G": (["volition"], "na.div 'noble: willing/generous': willing/generous disposition = volition", "med", ""),
"H5081H": ([], "na.div 'noble/prince': a noble person = PERSON/rank (cur volition wrong)", "med", ""),
"H5082": ([], "ne.di.vah 'honor': honor = attribute/STATE", "high", ""),
"H5098": ([], "na.ham 'to groan': groaning = vocal ACT of pain", "med", ""),
"H5099": ([], "na.ham 'roaring': roaring of lion/sea = physical sound event", "med", ""),
"H5117": ([], "nu.ach 'to rest/rested/leave': resting/settling = physical/state ACT", "high", ""),
"H5118": ([], "nu.ach 'rest/resting place/relief': rest = STATE/place", "high", ""),
"H5136": (["affect"], "nush 'be sick/despair': in sense 'despair' = affect (sickness shade physical)", "low", ""),
"H5144A": (["volition"], "na.zar 'to dedicate/abstain/separates/consecrated': consecration/abstaining = volitional setting-apart", "low", ""),
"H5150": (["affect"], "ni.chum 'comfort/compassion/comforting': comfort/compassion = affect", "high", ""),
"H5162G": (["affect"], "na.cham 'to be sorry: comfort/comforted': comforting = affect", "high", ""),
"H5162H": (["affect","volition"], "na.cham 'to be sorry: relent/regret': relenting/regret = affect (sorrow) + change of resolve = volition", "med", ""),
"H5164": (["affect"], "no.cham 'repentance/compassion': compassion/relenting = affect", "med", ""),
"H5165": (["affect"], "ne.cha.mah 'comfort': comfort = affect", "high", ""),
"H5183A": ([], "na.chat 'quietness/quiet/finds': quietness/calm = STATE", "high", ""),
"H5201": (["affect"], "na.tar 'to keep anger/grudge/keepers': bearing a grudge = sustained resentment affect", "low", ""),
"H5206": ([], "ni.dah 'filth/became filthy': filth/impurity = STATE", "high", ""),
"H5207": (["affect"], "ni.cho.ach 'soothing/pleasing/aroma': pleasing/soothing = affect (pleasingness)", "low", ""),
"H5222": ([], "ne.kheh 'smitten/wretches': stricken ones = STATE/PERSON afflicted", "high", ""),
"H5223": ([], "na.kheh 'crippled/contrite': crippled = physical STATE (contrite shade weak)", "low", "homograph_guard"),
"H5228": (["moral_evaluation"], "na.kho.ach 'straightforward/right/uprightness/honest': moral uprightness/honesty = moral_evaluation", "med", ""),
"H5229": (["moral_evaluation"], "ne.kho.chah 'upright/right/uprightness': moral rectitude = moral_evaluation", "high", ""),
"H5273A": (["affect"], "na.im 'pleasant/lovely': pleasantness = affect (delightfulness)", "med", ""),
"H5273B": (["affect"], "na.im 'musical/pleasant/lovely': pleasantness = affect", "low", ""),
"H5276": (["affect"], "na.em 'be pleasant/beauty/delight': pleasantness/delight = affect", "med", ""),
"H5278": (["affect"], "no.am 'pleasantness/favor/gracious': pleasantness/favour = affect", "med", ""),
"H5282": (["affect"], "na.a.man 'pleasantness/pleasant': pleasantness = affect", "low", ""),
"H5301": ([], "na.phach 'to breathe/blow/boiling': breathing/blowing = physical ACT (cur perception wrong)", "med", ""),
"H5307K": (["affect"], "na.phal 'to fall: angry/fell/anger': 'face fell = angry/dejected' sense = affect", "low", "homograph_guard"),
"H5314": ([], "na.phash 'be refreshed/refreshed': refreshment = physical/restorative STATE", "med", ""),
"H5315G": (["affect","volition"], "ne.phesh 'soul/heart': inner-being seat carrying desire/appetite (affect) and willing self (volition)", "med", ""),
"H5315H": ([], "ne.phesh 'soul: life/breath': here = life/vitality = STATE (biological life)", "med", "homograph_guard"),
"H5315I": ([], "ne.phesh 'soul: myself/himself': reflexive self = PERSON/pronoun usage", "med", "homograph_guard"),
"H5315J": ([], "ne.phesh 'soul: person/people': a person/people count = PERSON", "high", "homograph_guard"),
"H5315K": ([], "ne.phesh 'soul: animal/creature': a living creature = animate being/THING", "high", "homograph_guard"),
"H5315L": (["affect"], "ne.phesh 'soul: appetite/desire': appetite/desire = affect (craving)", "med", ""),
"H5315M": ([], "ne.phesh 'soul: dead/bodies': a corpse = physical THING", "high", "homograph_guard"),
"H5315N": ([], "ne.phesh 'soul: neck': body part = physical THING", "high", "homograph_guard"),
"H5327A": ([], "na.tsah 'to struggle/quarreled/fight/strive': strife/fighting = external conflict ACT", "high", ""),
"H5329": ([], "na.tsach 'to conduct/perpetual': directing music / perpetuity = ACT/STATE", "med", ""),
"H5331": ([], "ne.tsach 'perpetuity/forever/always': duration = STATE/time concept", "high", ""),
"H5352": (["conscience"], "na.qah 'to clear/free/innocent/leave unpunished': being innocent/cleared = conscience (guiltlessness)", "med", ""),
"H5355A": (["conscience"], "na.qi 'innocent/guiltless/free': innocence = conscience", "high", ""),
"H5355B": (["conscience"], "na.qi 'innocent/guiltless/free': innocence = conscience", "high", ""),
"H5356A": (["conscience"], "niq.qa.von 'innocence': innocence = conscience", "high", ""),
"H5356B": ([], "qe.ha.von 'bluntness' (sense innocence; homonym): primary 'bluntness' = physical STATE", "low", "homograph_guard"),
"H5375O": (["volition"], "na.sa 'to lift: trust / lift up the soul': trust/long-for sense = volition (trust-as-commitment) with longing affect", "low", "homograph_guard"),
"H5397": ([], "ne.sha.mah 'breath/breathed/blast': breath = physical/life STATE", "high", ""),
"H5414G": ([], "na.tan 'to give/gave/given': giving = transfer ACT", "high", ""),
"H5475": (["cognition"], "sod 'counsel/council/secret/company': confidential counsel/deliberation = cognition (also council group)", "med", ""),
"H5493G": ([], "sur 'to turn aside: remove/removed': removing = physical ACT", "high", ""),
"H5493H": (["volition"], "sur 'to turn aside: depart/turned away': turning away from the way = volitional departure (physical shade)", "low", "homograph_guard"),
"H5493I": (["volition"], "sur 'to turn aside: turn aside': turning aside from the way/evil = volitional deviation (physical shade)", "low", "homograph_guard"),
"H5494": ([], "sur 'degenerate/turn away': moral degeneracy = STATE of decline", "low", ""),
"H5529": (["cognition"], "se.khel 'folly': folly = defect of cognition", "med", ""),
"H5530": (["cognition"], "sa.khal 'fool/stupid/foolish': folly/stupidity = defect of cognition", "med", ""),
"H5531A": (["cognition"], "sikh.lut 'folly': folly = defect of cognition", "med", ""),
"H5531B": (["cognition"], "sikh.lut 'folly/foolishness': folly = defect of cognition", "med", ""),
"H5539": (["affect"], "sa.lad 'to rejoice/exult': joy/exultation = affect", "med", ""),
"H5545": ([], "sa.lach 'to forgive/forgiven/pardon': forgiving = act of pardon (God's) = ACT", "low", ""),
"H5546": ([], "sal.lach 'forgiving': attribute of one who pardons = STATE/act", "low", ""),
"H5547": ([], "se.li.chah 'forgiveness': act/STATE of pardon", "low", ""),
"H5557": ([], "sa.laph 'to pervert/overthrows/subverts/ruin': perverting/overthrowing = ACT of distortion", "med", ""),
"H5558": ([], "se.leph 'crookedness/perverseness': moral crookedness = STATE/quality", "med", ""),
"H5594": (["affect"], "sa.phad 'to mourn/lament/mourned': mourning = affect (grief)", "high", ""),
"H5627": (["volition"], "sa.rah 'revolt/rebellion/wrongdoing': revolt/turning away = volitional defiance/apostasy", "low", ""),
"H5647G": ([], "a.vad 'to serve/served/became subject': serving = ACT (also relational service)", "med", ""),
"H5647H": ([], "a.vad 'to serve: minister/do': service/ministering = ACT", "med", ""),
"H5647I": ([], "a.vad 'to serve: labour/laborer/works': labour = physical ACT", "high", ""),
"H5647J": ([], "a.vad 'to serve: burden/burdened': being burdened with labour = STATE/physical", "high", ""),
"H5648": ([], "a.vad 'to make/done/works' (Aramaic): making/doing = ACT", "high", ""),
"H5656G": ([], "a.vo.dah 'service/slavery/servitude': service/servitude = STATE/THING", "high", ""),
"H5656H": ([], "a.vo.dah 'service: ministry/attend': service = ACT/role", "high", ""),
"H5656I": ([], "a.vo.dah 'service: work/labor/cultivate': labour = ACT", "high", ""),
"H5657": ([], "a.vud.dah 'service': service = STATE/THING", "med", ""),
"H5659": ([], "av.dut 'slavery': slavery = STATE", "high", ""),
"H5690": (["affect"], "a.gav 'lust/lustful talk': lust = affect (sensual desire)", "med", ""),
"H5691": (["affect"], "a.ga.vah 'lust': lust = affect (desire)", "low", ""),
"H5719": ([], "a.din 'voluptuous/pleasures': luxuriousness = STATE/quality", "low", ""),
"H5727": (["affect"], "a.dan 'to luxuriate/delighted': delighting/luxuriating = affect (delight)", "med", ""),
"H5730B": (["affect"], "ed.nah 'delight/delicacies/delights': delight = affect", "med", ""),
"H5749A": ([], "ud 'to return/ensnare' (homonym): ensnare/restore = ACT", "low", "homograph_guard"),
"H5749B": ([], "ud 'to testify/warned/give warning': testifying/warning = speech ACT", "med", ""),
"H5753A": ([], "a.vah 'to twist/perverted/bowed down': twisting/bending = physical/moral distortion ACT", "med", ""),
"H5753B": ([], "a.vah 'to pervert/acted perversely/wrong': acting perversely = ACT of wrongdoing", "med", ""),
"H5760": ([], "a.vil 'unjust one/ungodly': an unjust person = PERSON/moral type", "low", ""),
"H5765": ([], "a.val 'to act unjustly/deals corruptly': acting unjustly = ACT of wrongdoing", "med", ""),
"H5766A": ([], "a.vel 'injustice/wrong/iniquity': injustice/iniquity = RECORD/STATE of wrongdoing", "high", ""),
"H5766B": ([], "av.lah 'injustice/wrong/wickedness': injustice = RECORD/STATE of wrongdoing", "high", ""),
"H5767": ([], "av.val 'unjust/unrighteous': an unjust one = PERSON/moral type", "low", ""),
"H5771G": ([], "a.von 'iniquity: crime/iniquities/guilt': iniquity = RECORD of wrongdoing", "high", ""),
"H5771H": ([], "a.von 'iniquity: guilt/guilty': here 'guilt' = recorded culpability = RECORD (objective, not the conscience-feeling)", "med", "homograph_guard"),
"H5771I": ([], "a.von 'iniquity: punishment/chastisement': punishment for iniquity = external consequence", "high", ""),
"H5779": (["cognition"], "uts 'to plan/take counsel': planning/counsel = cognition", "med", ""),
"H5781": ([], "uq 'to totter': tottering/swaying = physical movement STATE", "med", ""),
"H5782": ([], "ur 'to rouse/stir up/awake': rousing/awakening = ACT", "med", ""),
"H5794": ([], "e.zuz 'strength/strong/power': strength = STATE/attribute", "high", ""),
"H5797": ([], "oz 'strength/power/might': strength = STATE/attribute", "high", ""),
"H5807": ([], "e.zuz 'strength': strength = STATE/attribute", "high", ""),
"H5810": ([], "a.zaz 'be strong/prevail/bold': being strong/prevailing = STATE/physical-prevailing ACT", "high", ""),
"H5932": ([], "al.vah 'iniquity/unjust': iniquity = RECORD/STATE of wrongdoing", "high", ""),
"H5943": ([], "il.lay 'Most High [God]' (Aramaic): divine title = PERSON/name", "high", ""),
"H5951": (["affect"], "a.li.tsut 'exultation/rejoicing': exultation/joy = affect", "med", ""),
"H5956": ([], "a.lam 'to conceal/hidden/hide/ignore': concealing/hiding = ACT", "med", ""),
"H5965": (["affect"], "a.las 'to rejoice/enjoyment/delight': joy/delight = affect", "high", ""),
"H5999": (["affect"], "a.mal 'trouble/toil/mischief': the trouble/misery shade = affect (felt hardship); toil shade = physical", "low", ""),
}

out = []
missing = []
for it in sl:
    s = it['s']
    if s not in D:
        missing.append(s)
        continue
    fac, basis, conf, flag = D[s]
    out.append({
        "s": s,
        "t": it['t'],
        "faculty": fac,
        "basis": basis,
        "confidence": conf,
        "taxonomy_flag": flag,
    })

if missing:
    print("MISSING decisions for:", missing)
else:
    with open('research/VE-lexical/faculty-map-build/map-batch4.json','w',encoding='utf-8') as f:
        json.dump(out, f, ensure_ascii=False, indent=2)
    print("WROTE", len(out), "records")

# stats
from collections import Counter
fc = Counter()
none_ct = 0
for r in out:
    if not r['faculty']:
        none_ct += 1
    for f in r['faculty']:
        fc[f] += 1
flagc = Counter(r['taxonomy_flag'] if r['taxonomy_flag'] else 'none' for r in out)
confc = Counter(r['confidence'] for r in out)
print("none count:", none_ct)
print("faculty dist:", dict(fc))
print("taxonomy_flag tally:", dict(flagc))
print("confidence tally:", dict(confc))
