"""cfg_helper.py -- export each config json to a configuration component helper (.md).

One helper per component, written beside its json (wide/enums.json -> wide/enums.md).
The helper is GENERATED, never authored: it is a read of the json, so it cannot drift
from it. To change a helper, change the component and regenerate.

What a helper answers, in this order:
    what does this component configure
    which code does it serve
    what OPTIONS does it set        -- the values a snippet reads
    what CHECKS does it declare     -- what a snippet must enforce
    what is in it                   -- the items, so the content can be relooked at
    what is unresolved              -- RECONCILE + open questions

Read-only. Never touches a json.

Usage:
    python iba/scripts/cfg_helper.py                 # all components
    python iba/scripts/cfg_helper.py --check         # stale/missing helpers, write nothing
"""

from __future__ import annotations

import argparse
import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
CONFIG = ROOT / "config"

MARKER_DEFAULTS = "_envelope_defaults"
MARKER_COMMENT = "_comment"

# nodes that are not rule lists
NOT_RULES = {"meta", "sections", "layout", "file_hashes", "last_change",
             "not_a_seed_file", "implemented_by", "counts", "tables", "views",
             "triggers", "retired_tables"}


def expand(items: list) -> list:
    """Apply `_envelope_defaults` positionally, as the kernel does."""
    out, defaults = [], {}
    for it in items:
        if not isinstance(it, dict):
            continue
        if MARKER_DEFAULTS in it:
            defaults = it[MARKER_DEFAULTS]
            continue
        if MARKER_COMMENT in it:
            continue
        out.append({**defaults, **it})
    return out


def rule_nodes(doc: dict) -> dict[str, list]:
    """Any top-level array of envelope-bearing objects is a rule list."""
    out = {}
    for node, value in doc.items():
        if node in NOT_RULES or not isinstance(value, list):
            continue
        if not any(isinstance(x, dict) and ("id" in x or MARKER_DEFAULTS in x)
                   for x in value):
            continue
        out[node] = expand(value)
    return out


def esc(s) -> str:
    """A cell that will not break the table."""
    if s is None:
        return ""
    return str(s).replace("|", "\\|").replace("\n", " ").strip()


def trim(s, n: int) -> str:
    s = esc(s)
    return s if len(s) <= n else s[: n - 1].rstrip() + "…"


def spec_options(spec: dict) -> list[str]:
    """The option keys a snippet would read off this item's spec."""
    if not isinstance(spec, dict):
        return []
    skip = {"cites", "implements", "reconcile", "canonical", "note", "status_note"}
    return [k for k in spec if k not in skip and not k.startswith("★")
            and not k.startswith("⚠")]


def render(path: pathlib.Path, doc: dict, version: str) -> str:
    rel = str(path.relative_to(CONFIG)).replace("\\", "/")
    code = (doc.get("utility_code") or doc.get("process_code")
            or doc.get("section") or doc.get("register_code") or path.stem)
    name = doc.get("name") or doc.get("config_name") or code
    tier = doc.get("tier")
    meta = doc.get("meta") or {}
    nodes = rule_nodes(doc)
    items = [it for v in nodes.values() for it in v]

    L = [f"# {code} — configuration component helper", ""]
    L += [f"> **Component:** `config/{rel}`"
          + (f" · tier {tier}" if tier else "")
          + f" · {len(items)} item(s) · config_version {version}", ""]
    L += ["> GENERATED by `iba/scripts/cfg_helper.py` — a read of the json, so it cannot "
          "drift from it. **Do not edit this file**; change the component and regenerate.", ""]
    if name and name != code:
        L += [f"**{name}**", ""]

    # ── what it configures ───────────────────────────────────────────────────
    L += ["## What it configures", ""]
    L += [meta.get("purpose") or "_No `meta.purpose` declared._", ""]
    for key in ("boundary", "nodes"):
        v = meta.get(key)
        if isinstance(v, dict):
            L += [f"**{key.capitalize()}**", ""]
            for k, s in v.items():
                L += [f"- `{k}` — {esc(s)}"]
            L += [""]

    # ── code it serves ───────────────────────────────────────────────────────
    L += ["## Code it serves", ""]
    impl = doc.get("implemented_by")
    served = []
    if isinstance(impl, dict):
        served = [f"- `{k}` — {esc(v)}" for k, v in impl.items()]
    elif isinstance(impl, str):
        served = [f"- {esc(impl)}"]
    # a snippet named on an item is also code this component serves
    for it in items:
        s = it.get("spec") or {}
        for k in ("implemented_by", "written_by", "runner", "script"):
            if isinstance(s.get(k), str):
                served.append(f"- `{s[k]}` — via `{it.get('id')}`")
    if served:
        L += sorted(set(served)) + [""]
    else:
        L += ["_Not declared._ No `implemented_by` on the component and no snippet named "
              "on any item — so nothing records which code this configures.", ""]

    # ── options ──────────────────────────────────────────────────────────────
    if doc.get("section") == "enums":
        # For a vocabulary component the values ARE the options. Naming the key
        # `values` and stopping would hide the only content that matters.
        L += ["## Options it sets", "",
              "Each vocabulary and the values it permits. A field bound to one of these "
              "accepts nothing else.", ""]
        for it in items:
            vals = (it.get("spec") or {}).get("values") or []
            plain = [v["value"] if isinstance(v, dict) else v for v in vals]
            undescribed = [v for v in vals if not isinstance(v, dict) or not v.get("description")]
            warn = (f"  ⚠ {len(undescribed)} value(s) carry no description"
                    if undescribed else "")
            L += [f"- **`{it.get('id')}`** ({len(plain)}) — "
                  + ", ".join(f"`{v}`" for v in plain) + warn]
        L += [""]
    else:
        L += ["## Options it sets", "",
              "The values a snippet reads. One row per item that carries any.", ""]
        rows = []
        for node, its in nodes.items():
            for it in its:
                opts = spec_options(it.get("spec") or {})
                if opts:
                    rows.append(f"| `{it.get('id')}` | {esc(it.get('subject'))} | "
                                f"{', '.join(f'`{o}`' for o in opts)} |")
        if rows:
            L += ["| item | subject | option keys |", "|---|---|---|"] + rows + [""]
        else:
            L += ["_None — this component declares no options._", ""]

    # ── checks ───────────────────────────────────────────────────────────────
    L += ["## Checks it declares", "",
          "What a snippet must enforce. `axis` C = deterministic code, I = needs the model.", ""]
    rows = []
    for node, its in nodes.items():
        for it in its:
            v = it.get("validation")
            if not isinstance(v, dict):
                continue
            rows.append(
                f"| `{it.get('id')}` | {esc(v.get('check'))} | {esc(v.get('axis'))} | "
                f"{esc(v.get('severity'))} | {esc(v.get('enforcement'))} | "
                f"{esc(it.get('status'))} |")
    if rows:
        L += ["| item | check | axis | severity | enforcement | status |",
              "|---|---|---|---|---|---|"] + rows + [""]
    else:
        L += ["_None — this component declares no checks._", ""]

    # ── the content ──────────────────────────────────────────────────────────
    L += ["## Items", ""]
    for node, its in nodes.items():
        L += [f"### `{node}` — {len(its)} item(s)", ""]
        L += ["| id | kind | subject | status | intent |", "|---|---|---|---|---|"]
        for it in its:
            L.append(f"| `{it.get('id')}` | {esc(it.get('kind'))} | "
                     f"{esc(it.get('subject'))} | {esc(it.get('status'))} | "
                     f"{trim(it.get('intent'), 150)} |")
        L += [""]

    # ── unresolved ───────────────────────────────────────────────────────────
    L += ["## Unresolved", ""]
    any_open = False
    recon = [it for it in items if it.get("status") == "RECONCILE"]
    if recon:
        any_open = True
        L += [f"**{len(recon)} RECONCILE** — value contested; dependent modules refuse to run.", ""]
        for it in recon:
            L += [f"- `{it.get('id')}` → {esc((it.get('spec') or {}).get('reconcile') or 'no decision named')}"]
        L += [""]
    inactive = [it for it in items if it.get("status") == "INACTIVE"]
    if inactive:
        any_open = True
        L += [f"**{len(inactive)} INACTIVE** — defined and correct, nothing runs it yet.", ""]
        for it in inactive:
            L += [f"- `{it.get('id')}`"]
        L += [""]
    opens = meta.get("open")
    if isinstance(opens, list) and opens:
        any_open = True
        L += [f"**{len(opens)} open question(s)**", ""]
        for o in opens:
            if isinstance(o, dict):
                L += [f"- **`{o.get('id')}`** — {esc(o.get('issue'))}"]
                if o.get("recommendation"):
                    L += [f"  - _recommendation:_ {esc(o['recommendation'])}"]
                if o.get("resolve_by"):
                    L += [f"  - _resolve by:_ {esc(o['resolve_by'])}"]
        L += [""]
    if not any_open:
        L += ["_Nothing outstanding._", ""]

    return "\n".join(L).rstrip() + "\n"


def render_register(path: pathlib.Path, doc: dict, version: str) -> str:
    """DBSchema/*.json is captured data, not rules -- it has no envelope items."""
    rel = str(path.relative_to(CONFIG)).replace("\\", "/")
    c = doc.get("counts", {})
    L = [f"# {doc.get('database', path.stem)} — configuration component helper", ""]
    L += [f"> **Component:** `config/{rel}` · captured data · config_version {version}", ""]
    L += ["> GENERATED by `iba/scripts/cfg_helper.py`. **Do not edit**; regenerate.", ""]
    L += ["## What it configures", "",
          "Nothing. This component is **captured data, not rules** — an observation of a live "
          "schema, carrying no rule envelope. The rules governing it are in "
          "`config/utility/DBSchema_maintenance.json`.", ""]
    L += ["## Code it serves", "", "- `iba/scripts/build_dbschema.py` — writes and rebuilds it", ""]
    L += ["## What it holds", "",
          f"- database: `{doc.get('database_path')}`",
          f"- schema_version: **{doc.get('schema_version')}** (captured {doc.get('exported_date')})",
          ""]
    if c:
        L += ["| object | count |", "|---|---|"]
        L += [f"| {k} | {v:,} |" for k, v in c.items()]
        L += [""]
    described = sum(1 for t in doc.get("tables", {}).values()
                    for col in t["columns"] if col.get("description"))
    L += [f"- descriptions: {described:,}/{c.get('columns', 0):,} columns", ""]
    L += ["## Unresolved", "",
          "This file is a **structured report living in the configurator** — measurement "
          "(row counts, profiles) is stale the moment it is written, and a target database "
          "has no measurements at all. Reworking it into a lightweight component is open.", ""]
    return "\n".join(L).rstrip() + "\n"


def render_reconciliations(path: pathlib.Path, doc: dict, version: str) -> str:
    """A DECISION register, not a rulebook -- its items carry no envelope.

    Rendering it through the rule template produces a table of empty columns: it has
    `concept` / `decision` / `decision_status`, not kind / subject / status / intent.
    """
    items = doc.get("items") or []
    L = ["# reconciliations — configuration component helper", ""]
    L += [f"> **Component:** `config/wide/reconciliations.json` · {len(items)} decision(s) "
          f"· config_version {version}", ""]
    L += ["> GENERATED by `iba/scripts/cfg_helper.py`. **Do not edit**; regenerate.", ""]
    L += ["## What it configures", "", (doc.get("meta") or {}).get("purpose", ""), ""]
    L += ["## Code it serves", "",
          "None directly. The kernel skips this file (`cfg_kernel.py` `load()`): a decision "
          "is not a rule. It gates other components — an item left unresolved keeps the rules "
          "that cite it at RECONCILE, and dependent modules refuse to run.", ""]
    L += ["## Decisions to make", "",
          "Each is a ratify-or-overrule call. `decision_status` uses `enum.decision_status`, "
          "not `enum.status`.", ""]
    L += ["| id | concept | status | recommended |", "|---|---|---|---|"]
    for it in items:
        L.append(f"| `{it.get('id')}` | {trim(it.get('concept'), 60)} | "
                 f"{esc(it.get('decision_status'))} | "
                 f"{trim(it.get('recommended') or it.get('decision'), 90)} |")
    L += [""]
    open_ = [it for it in items if it.get("decision_status") != "RULED"]
    L += ["## Unresolved", "",
          f"**{len(open_)} of {len(items)}** still open — each blocks whatever cites it."
          if open_ else "_All ruled._", ""]
    for it in open_:
        L += [f"- **`{it.get('id')}`** — {trim(it.get('concept'), 150)}"]
    return "\n".join(L).rstrip() + "\n"


def render_manifest(path: pathlib.Path, doc: dict) -> str:
    L = ["# _manifest — configuration component helper", ""]
    L += [f"> **Component:** `config/_manifest.json` · config_version "
          f"{doc.get('config_version')}", ""]
    L += ["> GENERATED by `iba/scripts/cfg_helper.py`. **Do not edit**; regenerate.", ""]
    L += ["## What it configures", "", doc.get("meta", {}).get("purpose", ""), ""]
    env = doc.get("meta", {}).get("envelope", {})
    if env:
        L += ["## The envelope every item carries", "",
              "| field | required | means |", "|---|---|---|"]
        for k, v in env.items():
            if not isinstance(v, dict):
                continue
            L.append(f"| `{k}` | {'yes' if v.get('required') else 'no'} | "
                     f"{trim(v.get('description'), 130)} |")
        L += [""]
    L += ["## Components declared", "", "| file | status | kind |", "|---|---|---|"]
    for section, entries in (doc.get("sections") or {}).items():
        if section == "deleted" or not isinstance(entries, list):
            continue
        for e in entries:
            if isinstance(e, dict) and "file" in e:
                L.append(f"| `{e['file']}` | {esc(e.get('status'))} | "
                         f"{esc(e.get('kind'))} |")
    L += [""]
    opens = doc.get("meta", {}).get("open") or []
    L += ["## Unresolved", "", f"**{len(opens)} open question(s)**", ""]
    for o in opens:
        if isinstance(o, dict):
            L += [f"- **`{o.get('id')}`** — {trim(o.get('issue'), 220)}"]
    L += [""]
    return "\n".join(L).rstrip() + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true",
                    help="report missing/stale helpers; write nothing")
    a = ap.parse_args()

    version = json.loads((CONFIG / "_manifest.json").read_text(encoding="utf-8"))["config_version"]
    stale = []
    for p in sorted(CONFIG.rglob("*.json")):
        if "archive" in p.parts or p.name == "_change_log.jsonl":
            continue
        doc = json.loads(p.read_text(encoding="utf-8"))
        if p.name == "_manifest.json":
            md = render_manifest(p, doc)
        elif p.parent.name == "DBSchema":
            md = render_register(p, doc, version)
        elif doc.get("section") == "reconciliations":
            md = render_reconciliations(p, doc, version)
        else:
            md = render(p, doc, version)

        out = p.with_suffix(".md")
        rel = str(out.relative_to(CONFIG)).replace("\\", "/")
        if a.check:
            if not out.exists() or out.read_text(encoding="utf-8") != md:
                stale.append(rel)
            continue
        out.write_text(md, encoding="utf-8")
        n = md.count("\n")
        print(f"  {rel:44} {n:>4} lines")

    if a.check:
        if stale:
            print(f"{len(stale)} helper(s) missing or stale -- regenerate:")
            for s in stale:
                print(f"  {s}")
            return 1
        print("all helpers current")
    return 0


if __name__ == "__main__":
    sys.exit(main())
