"""probe_step_api.py — dump the FULL raw response of each STEP API, unmodified.

Purpose: see what STEP actually gives us, so the config can bind the right API to
the right call. The client reads only some of each response; everything it ignores
is invisible from the code, and that is exactly what this exposes.

Read-only. Calls STEP, writes dumps. Never touches the DB.

Routes and connection come from iba/config/utility/step.json — nothing here is
hard-coded except the list of fields the CURRENT client reads, which is what the
'read by client?' column is diffed against.

Usage:
    python iba/scripts/probe_step_api.py                      # ruach/spirit, all 4
    python iba/scripts/probe_step_api.py --strong H5315 --word soul
    python iba/scripts/probe_step_api.py --out outputs/step-api-probe-20260716
"""

from __future__ import annotations

import argparse
import json
import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[2] / "scripts"))
sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[2] / "scripts" / "analytics"))

from analytics.step_client import StepClient, load_step_config  # noqa: E402

ROOT = pathlib.Path(__file__).resolve().parents[2]

# What the CURRENT client extracts, per API. Everything else in a response is
# returned by STEP and thrown away — the point of this probe.
READ_BY_CLIENT = {
    "module.getInfo": {
        "vocabInfos[].strongNumber", "vocabInfos[].stepGloss", "vocabInfos[].count",
        "vocabInfos[].accentedUnicode", "vocabInfos[].stepTransliteration",
        "vocabInfos[].mediumDef", "vocabInfos[].lsjDefs", "vocabInfos[].shortDefMounce",
        "vocabInfos[].rawRelatedNumbers", "vocabInfos[].freqList",
        "vocabInfos[].relatedNos[].strongNumber", "vocabInfos[].relatedNos[].matchingForm",
        "vocabInfos[].relatedNos[].gloss", "vocabInfos[].relatedNos[].stepTransliteration",
    },
    "search.masterSearch.strong": {
        "total", "results[].osisId", "results[].key", "results[].preview",
    },
    "search.masterSearch.text": {
        "total", "results[].osisId", "results[].key", "results[].preview",
    },
    "search.masterSearch.meanings": {
        "total", "definitions", "strongHighlights",
    },
}


def walk(node, prefix="", out=None):
    """Every key path in a response, with its type and a sample value."""
    out = {} if out is None else out
    if isinstance(node, dict):
        for k, v in node.items():
            walk(v, f"{prefix}.{k}" if prefix else k, out)
    elif isinstance(node, list):
        if node:
            walk(node[0], f"{prefix}[]", out)
        else:
            out.setdefault(prefix, {"type": "list(empty)", "sample": "[]", "n": 0})
    else:
        e = out.setdefault(prefix, {"type": type(node).__name__, "sample": None, "n": 0})
        e["n"] += 1
        if e["sample"] is None and node not in (None, ""):
            s = str(node).replace("\n", " ")
            e["sample"] = s[:110] + ("…" if len(s) > 110 else "")
    return out


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--strong", default="H7307", help="Strong's to probe (default ruach)")
    ap.add_argument("--word", default="spirit", help="English word to probe")
    ap.add_argument("--out", default="outputs/step-api-probe-20260716")
    a = ap.parse_args()

    out_dir = ROOT / a.out
    out_dir.mkdir(parents=True, exist_ok=True)
    c = StepClient()
    c.preflight()

    resolved = c._resolved_strong(a.strong)
    print(f"probe: {a.strong} -> resolved {resolved} | word {a.word!r}")
    print(f"out:   {out_dir.relative_to(ROOT)}\n")

    calls = [
        ("module.getInfo", c._route("module.getInfo", strong=a.strong), None),
        ("search.masterSearch.strong",
         c._route("search.masterSearch.strong", strong=resolved), None),
        ("search.masterSearch.text",
         c._route("search.masterSearch.text", text=a.word), None),
        ("search.masterSearch.meanings",
         c._route("search.masterSearch.meanings", text=a.word), None),
    ]

    index = ["# STEP API surface — raw probe", "",
             f"> Probe: `{a.strong}` (resolved `{resolved}`) · word `{a.word}` · "
             f"version `{c.version}` · {c.base}",
             "> Generated by `iba/scripts/probe_step_api.py`. Full raw responses are the "
             "`.json` files beside this one — unmodified, exactly as STEP returned them.", "",
             "**`read?`** = does `scripts/analytics/step_client.py` currently extract it. "
             "A `no` means STEP gives us this and we throw it away.", ""]

    for api, route, _ in calls:
        print(f"  {api:32} {route}")
        raw = c._get_json(route)
        fn = out_dir / f"{api.replace('.', '_')}.json"
        fn.write_text(json.dumps(raw, indent=2, ensure_ascii=False), encoding="utf-8")

        keys = walk(raw)
        read = READ_BY_CLIENT.get(api, set())
        n_read = sum(1 for k in keys if k in read)
        print(f"  {'':32} -> {fn.name}  ({fn.stat().st_size:,} bytes, "
              f"{len(keys)} key paths, {n_read} read, {len(keys) - n_read} ignored)")

        index += [f"## `{api}`", "",
                  f"`{route}`", "",
                  f"Raw: [`{fn.name}`]({fn.name}) — {fn.stat().st_size:,} bytes · "
                  f"**{len(keys)} key paths · {n_read} read · {len(keys) - n_read} ignored**", "",
                  "| key path | type | read? | sample |", "|---|---|---|---|"]
        for k in sorted(keys):
            e = keys[k]
            mark = "yes" if k in read else "**no**"
            sample = str(e["sample"] or "").replace("|", "\\|")
            index.append(f"| `{k}` | {e['type']} | {mark} | {sample} |")
        index.append("")

    (out_dir / "00-INDEX.md").write_text("\n".join(index), encoding="utf-8")
    print(f"\nwrote {out_dir.relative_to(ROOT)}/00-INDEX.md")
    return 0


if __name__ == "__main__":
    sys.exit(main())
