"""Apply DIR-20260514-002 (M39-A) and DIR-20260514-003 (M39-B) — Phase 7 mapping.

Per wa-sessionb-cluster-instruction-v1_9 §10.3 (per-sub-group segmentation pattern):
each directive is its own transaction (failure-radius isolation).

Directive sources:
  - Sessions/Session_Clusters/M39/wa-cluster-M39-dir-002-A-mapping-v1-20260514.md
  - Sessions/Session_Clusters/M39/wa-cluster-M39-dir-003-B-mapping-v1-20260514.md

Operations per directive:
  Op 1 — verse_context_group context_description UPDATE (REFINE decisions)
  Op 2 — verse_context group_id UPDATE (P-status verses → assigned VCG)

No NEW VCGs in either directive → no vcg_term INSERTs.

Schema deviations from directive text (applied per actual schema):
  - verse_context_group.subgroup_code   → actual: group_code
  - verse_context_group.core_description → actual: context_description
"""
import sqlite3, sys, os, json, argparse
from datetime import datetime, timezone

try:
    sys.stdout.reconfigure(encoding="utf-8")
except Exception:
    pass

DB = "database/bible_research.db"

DIRECTIVES = {
    "DIR-20260514-002": {
        "segment": "M39-A",
        "directive_file": "Sessions/Session_Clusters/M39/wa-cluster-M39-dir-002-A-mapping-v1-20260514.md",
        "report_file": "Sessions/Session_Clusters/M39/WA-M39-A-group-mapping-applied-v1-20260514.md",
        "vcg_refines": [
            # (vcg_id, new_context_description)
            (340,
             "Term designates the constitutional inner character of graciousness — not merely a disposition but the settled identity of God as gracious; the self-declaration of Exo 34:6 and its echoes establish graciousness as what God constitutively is, the inner ground from which all favour and mercy flow"),
            (561,
             "Term names the human experience of ra.tsah — the inner act of seeking, receiving, or extending acceptance and favour; includes divine favour sought in prayer (Psa 40:13), interpersonal favour received (Gen 33:10), favour misdirected toward the unworthy (Psa 49:13; 62:4), favour withdrawn (Psa 77:7), and favour remembered as the ground of hope (Psa 85:1)"),
            (1119,
             "Term names the concrete acts of divine grace-giving — God giving what the recipient cannot earn or generate: from the supreme grace-act of giving the Son (Rom 8:32) through preservation of life (Act 27:24), spiritual understanding (1Cor 2:12), promise-fulfilment (Gal 3:18), eschatological honour (Phili 2:9), and comprehensive forgiveness (Col 2:13); distinct from 5470-002 (human forgiveness) and 888-001 (grace as disposition)"),
            (1121,
             "Term names grace as the sovereign, unmerited divine disposition toward humanity — the freely given, transforming gift through which God justifies, saves, calls, and sustains, supremely displayed in Christ; logically exclusive of merit (Rom 11:6 — \"if it is by grace, it is no longer on the basis of works; otherwise grace would no longer be grace\")"),
            (1123,
             "Term names grace as relational favour — the disposition of goodwill between persons or between a person and God, which opens access, creates loyalty, and reflects the character of the one granting it; includes the corrupted political-favour form (Act 24:27; 25:3; 25:9 — favour as political currency withheld from justice) alongside the genuine relational-standing form"),
            (1126,
             "Term names the divine relational favour bestowed on a person — the inner-relational disposition of God toward those he knows by name (Exo 33:12), which creates standing (Gen 6:8 — Noah), protection, and access, and which is sought, recognised, and treasured; the OT Hebrew form of the grace-dynamic, distinct from charis (888-003) in being tied to election, preservation, and covenant-knowing"),
            (1127,
             "Term names relational favour between persons — the inner-relational disposition of goodwill one person seeks and receives from another, which creates access, loyalty, and life; includes the seeking posture (Gen 18:3; Rut 2:2), the received favour (Est 5:2), and the recognition that favour does not follow merit (Ecc 9:11)"),
            (1641,
             "Term names the two-sided act of grace: (i) God's inner disposition of grace as the ground of his response to the supplicant — the character from which mercy flows (Psa 51:1; 86:15); and (ii) the human cry for grace as the inner posture generated by that disposition — the plea of dependence directed upward to God from weakness, affliction, loneliness, or sin (Psa 4:1; 6:2; 31:9; 37:26); the term's most extensive use is as supplication (72 verses predominantly as the human cry for grace), with the secondary register of human generosity (Psa 37:21; 37:26) as the propagation of received grace"),
            (3087,
             "Term names grace in its Spirit-endowed capacity form — the charisma as the spiritual capacity God gives to each person for the building up of the community (1Cor 12:4–31), and supremely the free gift of eternal life (Rom 6:23); distinct from charis (888-001 — grace as disposition) in naming grace specifically as received inner equipping for community service; the charismata are distributed differentially by the Spirit (Rom 12:6) and are irrevocable (Rom 11:29)"),
        ],
        "vc_assigns": [
            # (vr_id, mti_term_id, target_group_id)
            (117146, 795,  560),
            (92213,  984,  1641),
            (167037, 889,  1128),
            (167044, 889,  1128),
            (167048, 889,  1128),
            (167049, 889,  1127),
            (167022, 889,  1127),
            (24847,  889,  1128),
            (167001, 5470, 1119),
            (166982, 888,  1123),
            (166996, 5470, 1119),
            (166971, 888,  1123),
            (166972, 888,  1123),
            (166973, 888,  1123),
            (166993, 5470, 1119),
            (166994, 5470, 1119),
        ],
    },
    "DIR-20260514-003": {
        "segment": "M39-B",
        "directive_file": "Sessions/Session_Clusters/M39/wa-cluster-M39-dir-003-B-mapping-v1-20260514.md",
        "report_file": "Sessions/Session_Clusters/M39/WA-M39-B-group-mapping-applied-v1-20260514.md",
        "vcg_refines": [
            (1587,
             "Term names the two-pole goodness characteristic of tov: (i) goodness as heart-quality — the inner moral excellence located in the heart before the act (1Ki 8:18 — \"you did well that it was in your heart\"), persisting through affliction (Psa 119:71), affirmed by God in right action (2Ki 10:30); and (ii) affective gladness-at-good — the heart merry or satisfied in contexts of festive wellbeing, pleasure, and communal celebration (Judg 16:25; Est 1:10; Song 4:10); the two poles are united in tov as the term for what is genuinely good in the inner person"),
            (2837,
             "Term names the heart being glad or merry — the inner state of lightness and well-being expressed in festive eating, drinking, and communal celebration; with somatic consequences: the glad heart heals (\"a joyful heart is good medicine,\" Pro 17:22) and the crushed spirit destroys (\"a crushed spirit dries up the bones\") — the goodness characteristic has a physical dimension"),
            (2838,
             "Term names moral goodness and doing good: the inner moral orientation from which right action flows; goodness as the ground of divine acceptance (Gen 4:7 — \"if you do well, will you not be accepted?\"), requiring sustained intentional exercise (Psa 36:3 — \"he has ceased to act wisely and do good\"), and extending goodness outward toward others and community"),
            (2839,
             "Term names the inner state of being pleased or finding something good — the approval, satisfaction, or favour that the inner person extends toward a person, course of action, or situation; includes the volitional-preference idiom (\"what seems good to you\" / \"whatever seems best\" — 1Sa 24:4; 2Sa 18:4; 2Sa 3:19), divine moral approval of human speech (Deu 18:17), royal approval (Neh 2:6), and communal endorsement (Jos 22:33)"),
        ],
        "vc_assigns": [
            (4188,  542, 1587),
            (4189,  542, 1587),
            (4190,  542, 1587),
            (59830, 632, 2839),
            (59831, 632, 2839),
            (59832, 632, 2839),
            (59833, 632, 2838),
            (4197,  542, 1587),
            (59838, 632, 2839),
            (4198,  542, 1587),
            (59836, 632, 2838),
            (12533, 632, 2838),
            (12542, 632, 2838),
            (12560, 632, 2838),
        ],
    },
}


def apply_directive(conn, directive_id, spec, now_utc, live):
    """Apply one directive as a single transaction. Returns dict of outcomes."""
    segment = spec["segment"]
    vcg_refines = spec["vcg_refines"]
    vc_assigns = spec["vc_assigns"]

    print(f"\n{'=' * 60}")
    print(f"  {directive_id} — segment {segment}")
    print(f"{'=' * 60}")
    print(f"  Op 1: {len(vcg_refines)} verse_context_group context_description UPDATEs")
    print(f"  Op 2: {len(vc_assigns)} verse_context group_id UPDATEs")

    # Pre-flight (every reference resolves)
    for vcg_id, _desc in vcg_refines:
        r = conn.execute("SELECT id FROM verse_context_group WHERE id=? AND COALESCE(delete_flagged,0)=0",
                         (vcg_id,)).fetchone()
        if not r:
            raise SystemExit(f"❌ [{directive_id}] verse_context_group id={vcg_id} not found / deleted")

    for vr_id, mti_id, target_gid in vc_assigns:
        vc = conn.execute("""SELECT id, group_id, is_relevant
                             FROM verse_context
                             WHERE verse_record_id=? AND mti_term_id=?
                               AND COALESCE(delete_flagged,0)=0""",
                          (vr_id, mti_id)).fetchone()
        if not vc:
            raise SystemExit(f"❌ [{directive_id}] vc row (vr={vr_id}, mti={mti_id}) not found")
        tg = conn.execute("SELECT id FROM verse_context_group WHERE id=? AND COALESCE(delete_flagged,0)=0",
                          (target_gid,)).fetchone()
        if not tg:
            raise SystemExit(f"❌ [{directive_id}] target group_id={target_gid} not found")
    print(f"  ✓ Pre-flight passed: all refs resolve")

    if not live:
        return {"mode": "dry-run"}

    # Live apply — single transaction per directive
    try:
        for vcg_id, new_desc in vcg_refines:
            conn.execute(
                "UPDATE verse_context_group SET context_description=? WHERE id=?",
                (new_desc, vcg_id)
            )
        for vr_id, mti_id, target_gid in vc_assigns:
            cur = conn.execute("""UPDATE verse_context
                                  SET group_id=?
                                  WHERE verse_record_id=? AND mti_term_id=?
                                    AND COALESCE(delete_flagged,0)=0""",
                               (target_gid, vr_id, mti_id))
            if cur.rowcount != 1:
                raise SystemExit(
                    f"❌ [{directive_id}] UPDATE verse_context (vr={vr_id}, mti={mti_id}) "
                    f"affected {cur.rowcount} rows (expected 1)"
                )
        conn.commit()
    except Exception:
        conn.rollback()
        raise

    # COMPLETION CONFIRMATION
    print(f"\n  COMPLETION CONFIRMATION for {directive_id}:")

    # Q1 — Sample VCG description spot-check
    for vcg_id, expected_desc in vcg_refines[:2]:
        r = conn.execute("SELECT id, group_code, context_description FROM verse_context_group WHERE id=?",
                         (vcg_id,)).fetchone()
        match = r["context_description"] == expected_desc
        marker = "✓" if match else "❌"
        print(f"    {marker} vcg {r['id']} ({r['group_code']}): context_description {'matches' if match else 'MISMATCH'}")
        if not match:
            raise SystemExit(f"❌ [{directive_id}] VCG {vcg_id} desc mismatch after write")

    # Q2 — verse_context group_id assignments
    assigned = 0
    for vr_id, mti_id, target_gid in vc_assigns:
        r = conn.execute("""SELECT group_id FROM verse_context
                            WHERE verse_record_id=? AND mti_term_id=?""",
                         (vr_id, mti_id)).fetchone()
        if r and r["group_id"] == target_gid:
            assigned += 1
    print(f"    Q2: {assigned}/{len(vc_assigns)} verse_context rows have target group_id")
    if assigned != len(vc_assigns):
        raise SystemExit(f"❌ [{directive_id}] assignment mismatch")

    # Q3 — Remaining P-status in this sub-group
    remaining_p = conn.execute("""
        SELECT COUNT(*) c
        FROM verse_context vc
        JOIN mti_terms mt ON mt.id = vc.mti_term_id
        JOIN mti_term_subgroup mts ON mts.mti_term_id = mt.id AND COALESCE(mts.delete_flagged,0)=0
        JOIN cluster_subgroup cs ON cs.id = mts.cluster_subgroup_id
        WHERE cs.cluster_code='M39' AND cs.subgroup_code=?
          AND vc.is_relevant=1 AND vc.group_id IS NULL
    """, (segment,)).fetchone()["c"]
    print(f"    Q3: Remaining P-status (is_relevant=1, group_id NULL) in {segment}: {remaining_p}")

    return {
        "mode": "live",
        "vcg_refines": len(vcg_refines),
        "vc_assigns": len(vc_assigns),
        "remaining_p_in_segment": remaining_p,
    }


def write_application_report(directive_id, spec, outcome, now_utc):
    """Write the per-directive application report."""
    lines = [
        f"# WA-{spec['segment']}-group-mapping-applied-v1-20260514",
        "",
        f"**Directive:** {directive_id}",
        f"**Segment:** {spec['segment']}",
        f"**Source directive:** [{spec['directive_file']}]({os.path.relpath(spec['directive_file'])})",
        f"**Applied:** {now_utc}",
        f"**Mode:** {outcome['mode']}",
        "",
        "## Operations applied",
        "",
        f"- Op 1 — `verse_context_group` `context_description` UPDATE: **{outcome.get('vcg_refines', 0)}** rows",
        f"- Op 2 — `verse_context` `group_id` UPDATE: **{outcome.get('vc_assigns', 0)}** rows",
        f"- No NEW VCGs → no `vcg_term` INSERTs",
        "",
        "## Post-state",
        "",
        f"- Remaining P-status verses in {spec['segment']} (is_relevant=1, group_id IS NULL): **{outcome.get('remaining_p_in_segment', '?')}** (expected 0)",
        "",
        "## Schema deviations from directive text",
        "",
        "Intent applied per actual schema. Surface for AI's future reference:",
        "",
        "| Directive said | Actual column |",
        "|---|---|",
        "| `verse_context_group.subgroup_code` | `group_code` |",
        "| `verse_context_group.core_description` | `context_description` |",
    ]
    with open(spec["report_file"], "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    print(f"\n  Report → {spec['report_file']}")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--live", action="store_true")
    args = ap.parse_args()

    now_utc = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    ts = datetime.now().strftime("%Y%m%dT%H%M%S")

    conn = sqlite3.connect(DB)
    conn.row_factory = sqlite3.Row

    print(f"MODE: {'LIVE' if args.live else 'DRY-RUN'}")
    print(f"Cluster: M39")
    print(f"Phase: 7 (group-verse mapping application)")
    print(f"Segmentation: per-sub-group (M39-A then M39-B; M39-BOUNDARY deferred per Phase 8/15)")

    # Backup
    if args.live:
        backup_dir = "backups/row_backups"
        os.makedirs(backup_dir, exist_ok=True)
        backup_path = os.path.join(backup_dir, f"M39_dir002_003_mapping_pre_{ts}.json")
        pre_state = {
            "timestamp": now_utc,
            "directives": ["DIR-20260514-002", "DIR-20260514-003"],
            "vcg_pre": [
                dict(r) for r in conn.execute(
                    "SELECT id, group_code, context_description FROM verse_context_group "
                    "WHERE id IN (340,561,1119,1121,1123,1126,1127,1641,3087,1587,2837,2838,2839)"
                )
            ],
            "vc_pre": [
                dict(r) for r in conn.execute("""
                    SELECT id, verse_record_id, mti_term_id, group_id, is_relevant
                    FROM verse_context
                    WHERE (verse_record_id, mti_term_id) IN (
                      (117146,795),(92213,984),(167037,889),(167044,889),(167048,889),
                      (167049,889),(167022,889),(24847,889),(167001,5470),(166982,888),
                      (166996,5470),(166971,888),(166972,888),(166973,888),(166993,5470),
                      (166994,5470),
                      (4188,542),(4189,542),(4190,542),(59830,632),(59831,632),(59832,632),
                      (59833,632),(4197,542),(59838,632),(4198,542),(59836,632),(12533,632),
                      (12542,632),(12560,632)
                    )
                """)
            ],
        }
        with open(backup_path, "w", encoding="utf-8") as f:
            json.dump(pre_state, f, indent=2, ensure_ascii=False)
        print(f"\nPre-state backup → {backup_path}")
        print(f"  VCG rows snapshotted: {len(pre_state['vcg_pre'])}")
        print(f"  VC rows snapshotted: {len(pre_state['vc_pre'])}")

    # Apply each directive as its own transaction (failure-radius isolation)
    for directive_id, spec in DIRECTIVES.items():
        outcome = apply_directive(conn, directive_id, spec, now_utc, args.live)
        if args.live:
            write_application_report(directive_id, spec, outcome, now_utc)

    # Cluster-wide H2 check (only if live)
    if args.live:
        h2 = conn.execute("""
            SELECT COUNT(*) c
            FROM verse_context vc
            JOIN mti_terms mt ON mt.id = vc.mti_term_id
            WHERE mt.cluster_code='M39'
              AND mt.status IN ('extracted','extracted_thin')
              AND vc.is_relevant=1 AND vc.group_id IS NULL
        """).fetchone()["c"]
        print(f"\n  Cluster-wide H2 (relevant verses without group_id, all M39): {h2}")

    conn.close()
    if not args.live:
        print("\n[DRY-RUN] No changes. Re-run with --live.")
    else:
        print(f"\n[LIVE] Both directives applied.")


if __name__ == "__main__":
    main()
