"""Read-only: render the live state of the verse-lexical study to ONE page (verse-analysis/_STATE.md).

Aligned to the LIVE lexical-analysis method (2026-07-02, method doc
`Workflow/Instructions/wa-verse-analysis-method-v1-20260702.md`): the page is driven by
`verse.process_marker` (Phase-1 completion markers), `ve_lexical` (the lexical store) and the
`lexical_prose_chapter` prose sections (Phase-2 chapter readings) — NOT the retired fan-out
(`ib_observation`), which is demoted to a one-line legacy pointer (memory
`project_ib_observation_folds_into_ve_lexical`).

    python scripts/_assess_study_state.py            # -> verse-analysis/_STATE.md
    python scripts/_assess_study_state.py --stdout    # print instead

Marker legend: ✓ analysed (process_marker set) · ⚠ B-BLOCKED (spans missing) ·
◐ A-REVIEW (processed, needs review) · ○ present but unmarked.
Do not hand-edit the output — re-run to refresh.
"""
import sqlite3, os, argparse, json, datetime, re

DB = os.path.join('database', 'bible_research.db')
OUT = os.path.join('verse-analysis', '_STATE.md')

POETIC_TAG = 'poetic-lexical'   # marker substring identifying the poetic chapter-driven pipeline


def marker_state(pm):
    """Classify a process_marker into a single-char state + kind."""
    if pm is None:
        return '○', 'unmarked'
    if pm.startswith('B-BLOCKED'):
        return '⚠', 'blocked'
    if pm.startswith('A-REVIEW'):
        return '◐', 'review'
    return '✓', 'analysed'


def term_of(pm):
    """The track label for a prose (non-poetic) marker, e.g. 'ruthlessness-sanitychecked-2026' -> 'ruthlessness'."""
    if not pm:
        return '(unmarked)'
    # strip a trailing ISO-ish date, then take the leading token
    base = re.sub(r'-?\d{6,8}$', '', pm)
    return base.split('-')[0] or pm


def main():
    ap = argparse.ArgumentParser(); ap.add_argument('--stdout', action='store_true'); a = ap.parse_args()
    today = datetime.date.today()
    conn = sqlite3.connect(DB); conn.row_factory = sqlite3.Row; c = conn.cursor()
    L = []
    def w(s=''): L.append(s)

    # ---- Phase-2 map: (book_short, chapter) -> prose_section id --------------------------------
    phase2 = {}
    for r in c.execute("""SELECT ps.id id, ps.heading heading, ps.metadata_json md
                          FROM prose_section ps JOIN prose_section_type t ON t.id = ps.section_type_id
                          WHERE t.code = 'lexical_prose_chapter' AND COALESCE(ps.delete_flagged,0) = 0
                          ORDER BY ps.id""").fetchall():
        book = chap = None
        try:
            m = json.loads(r['md'] or '{}'); book = m.get('book'); chap = m.get('chapter')
        except Exception:
            pass
        if book is None or chap is None:  # fall back to parsing "Psalm N" from the heading
            mm = re.search(r'Psalm\s+(\d+)', r['heading'] or '')
            if mm: book, chap = 'Psa', int(mm.group(1))
        if book is not None and chap is not None:
            phase2[(book, int(chap))] = r['id']

    # ---- all marked verses (Phase-1) ----------------------------------------------------------
    rows = c.execute("""SELECT v.reference ref, v.verse_num vn, v.chapter ch, v.genre genre,
                               v.process_marker pm, b.short_code book, b.name book_name, b.book_order bo
                        FROM verse v JOIN books b ON b.id = v.book_id
                        WHERE v.process_marker IS NOT NULL
                        ORDER BY b.book_order, v.chapter, v.verse_num""").fetchall()

    poetic = [r for r in rows if r['pm'] and POETIC_TAG in r['pm']]
    prose  = [r for r in rows if not (r['pm'] and POETIC_TAG in r['pm'])]

    n_analysed = sum(1 for r in rows if marker_state(r['pm'])[1] == 'analysed')
    n_blocked  = sum(1 for r in rows if marker_state(r['pm'])[1] == 'blocked')
    n_review   = sum(1 for r in rows if marker_state(r['pm'])[1] == 'review')
    chapters   = sorted(set((r['book'], r['ch']) for r in poetic))
    books_seen = sorted(set(r['book_name'] for r in rows))

    ve_total = c.execute("SELECT count(*) FROM ve_lexical WHERE COALESCE(delete_flagged,0)=0").fetchone()[0]
    ve_g1 = c.execute("SELECT count(*) FROM ve_lexical WHERE COALESCE(delete_flagged,0)=0 AND gate='1-primary'").fetchone()[0]
    ve_g2 = c.execute("SELECT count(*) FROM ve_lexical WHERE COALESCE(delete_flagged,0)=0 AND gate='2-relevant'").fetchone()[0]

    # ---- header + headline --------------------------------------------------------------------
    w(f"# STUDY STATE — verse-lexical (generated {today.isoformat()})")
    w()
    w("> Generated by `scripts/_assess_study_state.py` from the DB (the single source of truth). "
      "Driven by the **live lexical method** — `verse.process_marker` (Phase-1), `ve_lexical` (the "
      "lexical store) and `lexical_prose_chapter` prose (Phase-2 chapter readings). "
      "Do not hand-edit; re-run to refresh.")
    w()
    w("**Marker legend:** `✓` analysed · `⚠` B-BLOCKED (spans missing) · `◐` A-REVIEW (needs review) · `○` present, unmarked.")
    w()
    w("## Headline")
    w(f"- **{n_analysed} verses analysed** (Phase-1 marked) across **{len(chapters)} chapters** and "
      f"**{len(books_seen)} books** ({', '.join(books_seen)}).")
    w(f"- **{len(phase2)} chapter readings filed** (Phase-2, `lexical_prose_chapter`).")
    w(f"- **{n_blocked} blocked** (⚠ spans missing) · **{n_review} needing review** (◐).")
    w(f"- **{ve_total} `ve_lexical` rows** — {ve_g1} gate-1 (tagged term) · {ve_g2} gate-2 (relevant content span).")
    w()

    # ---- NEXT ACTION (derived) ----------------------------------------------------------------
    w("## ▶ NEXT ACTION")
    w("*Derived from state — Phase-1 chapters whose Phase-2 reading is not yet filed, and any blocked verses.*")
    w()
    pending = []
    for (bk, ch) in chapters:
        cv = [r for r in poetic if r['book'] == bk and r['ch'] == ch]
        blocked = sum(1 for r in cv if marker_state(r['pm'])[1] == 'blocked')
        if (bk, ch) not in phase2 and blocked == 0:
            pending.append((bk, ch))
    if pending:
        for bk, ch in pending:
            w(f"- **{bk} {ch}** — Phase-1 complete, **Phase-2 reading pending** → write "
              f"`wa-psalm{ch}-inner-being-reading-*.md`, then file (`_apply_file_chapter_lexical_prose_v1_...`).")
    else:
        w("- No Phase-1 chapter is waiting on its Phase-2 reading.")
    blocked_refs = [r['ref'] for r in rows if marker_state(r['pm'])[1] == 'blocked']
    if blocked_refs:
        w(f"- **Blocked (backfill needed):** {', '.join(blocked_refs)}")
    w()

    # ---- POETIC chapter-driven grid -----------------------------------------------------------
    w("## Poetic chapter-driven pipeline")
    w("*The live Psalter work. Phase-1 = per-verse lexical marked; Phase-2 = whole-chapter reading filed.*")
    w()
    w("| Book | Ch | verses marked | Phase 1 | Phase 2 (prose id) | blocked |")
    w("|---|---|---|---|---|---|")
    for (bk, ch) in chapters:
        cv = [r for r in poetic if r['book'] == bk and r['ch'] == ch]
        marked = sum(1 for r in cv if marker_state(r['pm'])[1] == 'analysed')
        blocked = sum(1 for r in cv if marker_state(r['pm'])[1] == 'blocked')
        p2 = phase2.get((bk, ch))
        p1cell = '✓' if marked and not blocked else ('⚠' if blocked else '—')
        p2cell = f"✓ ({p2})" if p2 else "⬜ pending"
        w(f"| {bk} | {ch} | {marked}/{len(cv)} | {p1cell} | {p2cell} | {blocked or ''} |")
    w()

    # ---- PER-VERSE marker tick-lines ----------------------------------------------------------
    w("## Per-verse markers (analysed verses)")
    w("*One line per analysed chapter — the marker beside every verse present in the DB.*")
    w()
    for (bk, ch) in chapters:
        cv = sorted([r for r in poetic if r['book'] == bk and r['ch'] == ch], key=lambda r: r['vn'])
        ticks = " ".join(f"{r['vn']}{marker_state(r['pm'])[0]}" for r in cv)
        p2 = phase2.get((bk, ch))
        p2note = f"Phase 2: ✓ ({p2})" if p2 else "Phase 2: ⬜ pending"
        w(f"- **{bk} {ch}** — {ticks} · {p2note}")
    w()

    # ---- PROSE term-driven pipeline -----------------------------------------------------------
    if prose:
        w("## Prose term-driven pipeline")
        w("*Verses marked by the prose (term-driven) build, grouped by track.*")
        w()
        by_term = {}
        for r in prose:
            by_term.setdefault(term_of(r['pm']), []).append(r)
        for term in sorted(by_term):
            g = sorted(by_term[term], key=lambda r: (r['bo'], r['ch'], r['vn']))
            refs = ", ".join(f"{r['ref']}{marker_state(r['pm'])[0]}" for r in g)
            w(f"- **{term}** ({len(g)} verses) — {refs}")
        w()

    # ---- LEGACY fan-out pointer ---------------------------------------------------------------
    try:
        obs_n = c.execute("SELECT count(*) FROM ib_observation").fetchone()[0]
        obs_open = c.execute("SELECT count(*) FROM ib_observation WHERE status IN ('open','needs-corroboration')").fetchone()[0]
        w("## Legacy — retired fan-out")
        w(f"- `ib_observation` holds **{obs_n} observations** ({obs_open} open/needs-corroboration) from the "
          "retired D1–D13 verse-fan-out. **Transitional** — folding into `ve_lexical` "
          "(memory `project_ib_observation_folds_into_ve_lexical`); not the live tracker. "
          "Prior generator output is in git history if the detail is needed.")
        w()
    except sqlite3.OperationalError:
        pass

    w("---")
    w("_Method: `Workflow/Instructions/wa-verse-analysis-method-v1-20260702.md`. "
      "Poetic pipeline tracker: `verse-analysis/_reports/wa-psalms-chapter-readings-PROGRESS.md`._")

    out = "\n".join(L)
    if a.stdout:
        print(out)
    else:
        with open(OUT, 'w', encoding='utf-8') as fh:
            fh.write(out)
        print(f"wrote {OUT} — {n_analysed} analysed verses, {len(chapters)} chapters, "
              f"{len(phase2)} Phase-2 readings, {n_blocked} blocked")
    conn.close()


if __name__ == '__main__':
    main()
