"""Read-only: render the ENTIRE live state of the verse-fanout study to ONE page.

The "mission control" view — generated from the DB (ib_observation + verse_analysis_progress),
so it is always current and can never drift or be forgotten. Read this instead of re-reading
the sprawl. Run anytime:

    python scripts/_assess_study_state.py            # -> verse-analysis/_STATE.md
    python scripts/_assess_study_state.py --stdout    # print instead

Sections: headline counts · FAN-OUT PLAN (what to read next & what it closes) ·
OPEN THREADS by track · STALE (open & not revisited) · BY TRACK rollup · RECENTLY RESOLVED.
"""
import sqlite3, os, argparse, re, datetime

DB = os.path.join('database', 'bible_research.db')
OUT = os.path.join('verse-analysis', '_STATE.md')
STALE_DAYS = 7

DIM = {  # code -> name (from wa-IB-verse-dimensions-catalogue-[current])
 'D1':'Identity','D2':'Source','D3':'Seat/bearer','D4':'Operation','D5':'Object','D6':'Manner',
 'D7':'Process','D8':'Impact','D9':'Coupling','D10':'Valence','D11':'Discovery','D12':'Hidden','D13':'Cohabitation'}

VERSE_RE = re.compile(r'\b([1-3]?[A-Z][a-z]{2,3})\s+(\d+):(\d+)\b')

def dlabel(code): return f"{code} {DIM.get(code, '?')}"

def age_days(ts, today):
    if not ts: return None
    try: return (today - datetime.date.fromisoformat(str(ts)[:10])).days
    except Exception: return None

def main():
    ap = argparse.ArgumentParser(); ap.add_argument('--stdout', action='store_true'); a = ap.parse_args()
    today = datetime.date.today()
    conn = sqlite3.connect(DB); conn.row_factory = sqlite3.Row; c = conn.cursor()
    L=[]
    def w(s=''): L.append(s)

    obs = c.execute("SELECT * FROM ib_observation ORDER BY origin_verse, operation, dimension").fetchall()
    openobs = [o for o in obs if o['status'] in ('open','needs-corroboration')]
    by_status = {}
    for o in obs: by_status[o['status']] = by_status.get(o['status'],0)+1

    w(f"# STUDY STATE — verse-fanout (generated {today.isoformat()})")
    w()
    w("> Generated by `scripts/_assess_study_state.py` from the DB (the single source of truth). "
      "Do not hand-edit. Re-run to refresh. **This page replaces re-reading the sprawl.**")
    w()
    # headline
    verses = c.execute("SELECT count(DISTINCT origin_verse) n FROM ib_observation").fetchone()['n']
    tracks = c.execute("SELECT count(DISTINCT operation) n FROM ib_observation").fetchone()['n']
    w("## Headline")
    w(f"- **{len(obs)} observations** across **{verses} analysed verses** and **{tracks} tracks**.")
    w(f"- status: " + " · ".join(f"**{by_status.get(s,0)} {s}**" for s in ['resolved','needs-corroboration','open','silent']))
    stale = [o for o in openobs if (age_days(o['created'], today) or 0) >= STALE_DAYS]
    w(f"- **{len(openobs)} OPEN THREADS** to resolve · **{len(stale)} stale** (open ≥{STALE_DAYS}d — revisit risk).")
    w()

    # FAN-OUT PLAN — aggregate reconsider_at verse targets -> what each closes
    w("## ▶ FAN-OUT PLAN — read these next (each closes the listed open threads)")
    w("*The single most useful view: what to do next, and why. Ranked by how many open threads it touches.*")
    w()
    targets = {}  # ref -> list of (id, operation, dim)
    for o in openobs:
        for m in VERSE_RE.finditer(o['reconsider_at'] or ''):
            ref = f"{m.group(1)} {m.group(2)}:{m.group(3)}"
            if ref == o['origin_verse']: continue
            targets.setdefault(ref, []).append(o)
    ranked = sorted(targets.items(), key=lambda kv: -len(kv[1]))
    if ranked:
        w("| read this verse | closes / advances | tracks |")
        w("|---|---|---|")
        for ref, os_ in ranked[:20]:
            ids = ", ".join(f"#{o['id']} {dlabel(o['dimension'])}" for o in os_[:6])
            trks = ", ".join(sorted(set(o['operation'] for o in os_)))
            w(f"| **{ref}** | {ids} | {trks} |")
    else:
        w("_no verse-specific reconsider targets among open threads._")
    w()

    # OPEN THREADS grouped by track (operation)
    w("## OPEN THREADS — by track")
    w("*Every unresolved observation. The claim is truncated; full text in `ib_observation`.*")
    w()
    ops = sorted(set(o['operation'] for o in openobs))
    for op in ops:
        group = [o for o in openobs if o['operation']==op]
        w(f"### {op} ({len(group)} open)")
        w("| # | dimension | claim | go to (reconsider_at) | origin | age |")
        w("|---|---|---|---|---|---|")
        for o in sorted(group, key=lambda o:(o['status']!='needs-corroboration', -(age_days(o['created'],today) or 0))):
            claim = (o['narrative'] or '')[:90].replace('\n',' ')
            ad = age_days(o['created'], today); agetag = f"{ad}d" + ("⚠" if ad and ad>=STALE_DAYS else "") if ad is not None else ""
            w(f"| #{o['id']} | {dlabel(o['dimension'])} | {claim}… | {o['reconsider_at'] or '—'} | {o['origin_verse']} | {agetag} |")
        w()

    # BY TRACK rollup (all observations, resolved+open)
    w("## BY TRACK — rollup (all observations)")
    w("| track | resolved | open/needs-corrob | silent | total |")
    w("|---|---|---|---|---|")
    alltr = sorted(set(o['operation'] for o in obs))
    for op in alltr:
        g=[o for o in obs if o['operation']==op]
        r=sum(1 for o in g if o['status']=='resolved'); op_=sum(1 for o in g if o['status'] in ('open','needs-corroboration')); s=sum(1 for o in g if o['status']=='silent')
        w(f"| {op} | {r} | {op_} | {s} | {len(g)} |")
    w()

    # BY ORIGIN VERSE — every verse that has observations (so any verse is findable)
    w("## BY ORIGIN VERSE — every analysed verse + its observations")
    w("*Each verse that has captured observations, with status counts and the tracks it opened.*")
    w("| verse | tracks opened | resolved | open/needs-corrob | silent | total |")
    w("|---|---|---|---|---|---|")
    verses_obs = {}
    for o in obs: verses_obs.setdefault(o['origin_verse'], []).append(o)
    def vkey(ref):  # rough canonical sort: book order unknown, so sort by ref text
        return ref
    for v_ in sorted(verses_obs, key=vkey):
        g = verses_obs[v_]
        trk = ", ".join(sorted(set(o['operation'] for o in g)))
        r = sum(1 for o in g if o['status']=='resolved')
        op_ = sum(1 for o in g if o['status'] in ('open','needs-corroboration'))
        s = sum(1 for o in g if o['status']=='silent')
        w(f"| **{v_}** | {trk} | {r} | {op_} | {s} | {len(g)} |")
    w()

    # VERSE PROGRESS
    w("## VERSE PROGRESS (verse_analysis_progress)")
    rows=c.execute("SELECT reference,marker,xref_verse,ref_by_obs,ref_dims FROM verse_analysis_progress ORDER BY marker DESC, reference").fetchall()
    focus=[r for r in rows if r['marker'] and 'progress' in r['marker'].lower()]
    w(f"- **Focus verses (analysis in progress):** " + (", ".join(r['reference'] for r in focus) or "—"))
    w(f"- **Cross-referenced (pulled into focus, pending):** {sum(1 for r in rows if r['xref_verse'])} verses.")
    w()

    # STALE
    if stale:
        w(f"## ⚠ STALE — open ≥{STALE_DAYS}d, not revisited (misconception risk)")
        for o in sorted(stale, key=lambda o:-(age_days(o['created'],today) or 0)):
            w(f"- #{o['id']} [{o['operation']}/{dlabel(o['dimension'])}] {age_days(o['created'],today)}d — {(o['narrative'] or '')[:80]}…  → {o['reconsider_at']}")
        w()

    # RECENTLY RESOLVED (sanity check)
    w("## RECENTLY RESOLVED (spot-check for wrong closures)")
    rr=[o for o in obs if o['status']=='resolved']
    rr=sorted(rr, key=lambda o:str(o['created'] or ''), reverse=True)[:10]
    for o in rr:
        w(f"- #{o['id']} [{o['operation']}/{dlabel(o['dimension'])}] {(o['narrative'] or '')[:80]}…")
    w()
    w("---")
    w("_To act: pick the top FAN-OUT PLAN verse → prepare it (`_assess_verse_raw_data.py --ref ...`) → read → capture to `ib_observation`. Re-run this page to see the threads close._")

    out="\n".join(L)
    if a.stdout: print(out)
    else:
        with open(OUT,'w',encoding='utf-8') as fh: fh.write(out)
        print(f"wrote {OUT} — {len(obs)} obs, {len(openobs)} open, {len(stale)} stale, {len(ranked)} fan-out targets")
    conn.close()

if __name__=='__main__': main()
