"""_export_m15_clean_slate_v1_20260511.py — read-only.

Emit a deliberately slim per-verse JSON for AI cleanup work:

  vr_id · reference · verse_text · strongs · translit · gloss · meaning

No current/new VCG, no sub-group context, no AI annotations from prior
passes. The goal is to give AI a fresh canvas anchored on the verse text
+ span, not on existing groupings — so its new VCG derivations are driven
by the verse content rather than by inherited structure.

Source: m15-baseline-verses-v5-20260511.json (latest)
Output: m15-clean-slate-v1-20260511.json
"""
from __future__ import annotations

import json
import os
import sys
from datetime import datetime, timezone

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
M15_DIR = os.path.join(ROOT, "Sessions", "Session_Clusters", "M15")
SOURCE = os.path.join(M15_DIR, "m15-baseline-verses-v5-20260511.json")
OUT = os.path.join(M15_DIR, "m15-clean-slate-v1-20260511.json")


def now_iso() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def main() -> int:
    try:
        sys.stdout.reconfigure(encoding="utf-8")
    except Exception:
        pass

    with open(SOURCE, "r", encoding="utf-8") as f:
        data = json.load(f)
    rows_in = data["verses"]

    slim = []
    n_with_meaning = 0
    for v in rows_in:
        t = v["term"]
        m = (v.get("meaning") or {}).get("text")
        if m:
            n_with_meaning += 1
        slim.append({
            "vr_id": v["vr_id"],
            "reference": v["reference"],
            "verse_text": (v.get("verse_text") or "").strip(),
            "strongs": t["strongs"],
            "translit": t["translit"],
            "gloss": t.get("gloss"),
            "meaning": m,
        })

    out = {
        "metadata": {
            "cluster_code": "M15",
            "purpose": (
                "Clean-slate per-verse input for AI re-derivation of VCG "
                "groupings. Deliberately omits any current or proposed VCG "
                "code, sub-group code, or sub-group description so AI is "
                "anchored on the verse text + term span + verse-level "
                "meaning only."
            ),
            "generated_at": now_iso(),
            "source": os.path.relpath(SOURCE, ROOT).replace("\\", "/"),
            "row_count": len(slim),
            "rows_with_meaning": n_with_meaning,
            "rows_without_meaning": len(slim) - n_with_meaning,
            "natural_key": "vr_id (one row per term-occurrence at a verse location)",
            "field_definitions": {
                "vr_id": "wa_verse_records.id — the canonical surrogate key",
                "reference": "human-readable verse reference (e.g. 'Gen 41:8')",
                "verse_text": "the full verse text as held in wa_verse_records",
                "strongs": "Strong's number of the M15 term occurring in this verse",
                "translit": "transliteration of the Strong's term",
                "gloss": "canonical English gloss for the term",
                "meaning": ("verse-level meaning generated by AI in the v1 "
                            "meaning-table pass; null where AI did not "
                            "produce one"),
            },
        },
        "verses": slim,
    }

    with open(OUT, "w", encoding="utf-8") as f:
        json.dump(out, f, ensure_ascii=False, indent=2)
    print(f"  rows: {len(slim)}  with meaning: {n_with_meaning}  without: {len(slim) - n_with_meaning}")
    print(f"  written: {OUT}")
    print(f"  size: {os.path.getsize(OUT):,} bytes")
    return 0


if __name__ == "__main__":
    sys.exit(main())
