"""_exploratory_verse_term_registry_profile_v1_20260503.py — read-only.

Produces three distributions to characterise overlap across the registry
network:

  Q1  Verse → N registries     (canonical book/chap/verse in N OWNER registries)
  Q2  Verse → N terms          (canonical verse under N distinct Strong's)
  Q3  Term  → N registries     (Strong's number across N registries; OWNER + XREF)

Plus top examples for each, and scope variants:
  - "all OWNER verses" (wa_verse_records, OWNER term_inv, not delete_flagged)
  - "analytically retained" (verse_context.is_relevant=1)
  - "anchors only"           (verse_context.is_anchor=1)

Output: markdown to stdout. Redirect to outputs/markdown/.
"""
from __future__ import annotations

import os
import sqlite3
import sys

DB_PATH = os.path.join("database", "bible_research.db")


def open_db() -> sqlite3.Connection:
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    return conn


def hist(rows, key_label: str) -> list[str]:
    """Render a histogram from rows of (n, count) ordered by n.
    Adds a >=2 cumulative tally and a percentage column."""
    L = []
    total = sum(r[1] for r in rows)
    multi = sum(r[1] for r in rows if r[0] >= 2)
    L.append(f"| {key_label} | count | % of total |")
    L.append("|---:|---:|---:|")
    for r in rows:
        pct = (r[1] / total * 100) if total else 0
        L.append(f"| {r[0]} | {r[1]:,} | {pct:.1f}% |")
    L.append(f"| **all (≥1)** | **{total:,}** | 100.0% |")
    L.append(f"| **multi (≥2)** | **{multi:,}** | "
             f"**{(multi/total*100 if total else 0):.1f}%** |")
    return L


def get_distribution(conn, sql: str) -> list[tuple]:
    return [(r[0], r[1]) for r in conn.execute(sql).fetchall()]


def main() -> int:
    conn = open_db()
    L: list[str] = []

    # ── Programme totals ───────────────────────────────────────────────────
    totals = conn.execute("""
        SELECT
          (SELECT COUNT(*) FROM word_registry) AS registries,
          (SELECT COUNT(*) FROM mti_terms WHERE delete_flagged = 0) AS mti_active,
          (SELECT COUNT(*) FROM wa_term_inventory
            WHERE delete_flagged = 0) AS ti_active,
          (SELECT COUNT(*) FROM wa_term_inventory
            WHERE delete_flagged = 0 AND term_owner_type='OWNER') AS owner_terms,
          (SELECT COUNT(*) FROM wa_term_inventory
            WHERE delete_flagged = 0 AND term_owner_type='XREF') AS xref_terms,
          (SELECT COUNT(*) FROM wa_verse_records vr
             JOIN wa_term_inventory ti ON ti.id = vr.term_inv_id
            WHERE vr.delete_flagged = 0 AND ti.delete_flagged = 0
              AND ti.term_owner_type = 'OWNER') AS owner_verse_records,
          (SELECT COUNT(*) FROM verse_context
            WHERE delete_flagged = 0 AND is_relevant = 1) AS vc_relevant,
          (SELECT COUNT(*) FROM verse_context
            WHERE delete_flagged = 0 AND is_anchor = 1) AS vc_anchors
    """).fetchone()

    L.append("# Verse / Term / Registry Distribution Profile")
    L.append("")
    L.append("_Generated by `scripts/_exploratory_verse_term_registry_profile_v1_20260503.py`. "
             "Read-only. Run again any time DB changes._")
    L.append("")
    L.append("## Programme totals")
    L.append("")
    L.append(f"- **Registries:** {totals['registries']:,}")
    L.append(f"- **Active `mti_terms` (Strong's, programme-wide):** {totals['mti_active']:,}")
    L.append(f"- **Active `wa_term_inventory` rows:** {totals['ti_active']:,}  ·  "
             f"**OWNER:** {totals['owner_terms']:,}  ·  **XREF:** {totals['xref_terms']:,}")
    L.append(f"- **OWNER `wa_verse_records` (per-term-occurrence):** "
             f"{totals['owner_verse_records']:,}")
    L.append(f"- **`verse_context` rows is_relevant=1:** {totals['vc_relevant']:,}  ·  "
             f"**is_anchor=1:** {totals['vc_anchors']:,}")
    L.append("")

    distinct_canonical = conn.execute("""
        SELECT COUNT(*) FROM (
          SELECT DISTINCT vr.book_id, vr.chapter, vr.verse_num
            FROM wa_verse_records vr
            JOIN wa_term_inventory ti ON ti.id = vr.term_inv_id
           WHERE vr.delete_flagged = 0 AND ti.delete_flagged = 0
             AND ti.term_owner_type = 'OWNER'
        )
    """).fetchone()[0]
    L.append(f"- **Distinct canonical verses (book/chapter/verse) in OWNER scope:** "
             f"{distinct_canonical:,}")
    L.append("")

    # ── Q1: Verse → N registries ─────────────────────────────────────────────
    L.append("---")
    L.append("")
    L.append("## Q1 — Verses in N registries")
    L.append("")
    L.append("How many distinct canonical verses (book/chapter/verse) appear in 1, 2, 3, … "
             "OWNER registries? Three scope variants. A verse is counted once per registry "
             "regardless of how many terms it carries.")
    L.append("")

    for label, where_extra in [
        ("All OWNER `wa_verse_records`", ""),
        ("Analytically retained (`verse_context.is_relevant=1`)",
         """JOIN verse_context vc ON vc.verse_record_id = vr.id
                                 AND vc.delete_flagged = 0
                                 AND vc.is_relevant = 1"""),
        ("Anchors only (`verse_context.is_anchor=1`)",
         """JOIN verse_context vc ON vc.verse_record_id = vr.id
                                 AND vc.delete_flagged = 0
                                 AND vc.is_anchor = 1"""),
    ]:
        sql = f"""
            WITH ov AS (
              SELECT DISTINCT vr.book_id, vr.chapter, vr.verse_num,
                     wr.id AS reg_id
                FROM wa_verse_records vr
                JOIN wa_term_inventory ti ON ti.id = vr.term_inv_id
                JOIN wa_file_index fi ON fi.id = ti.file_id
                JOIN word_registry wr ON wr.id = fi.word_registry_fk
                {where_extra}
               WHERE vr.delete_flagged = 0
                 AND ti.delete_flagged = 0
                 AND ti.term_owner_type = 'OWNER'
            )
            SELECT n_reg, COUNT(*) AS n_verses FROM (
              SELECT book_id, chapter, verse_num, COUNT(DISTINCT reg_id) AS n_reg
                FROM ov
               GROUP BY book_id, chapter, verse_num
            )
            GROUP BY n_reg ORDER BY n_reg
        """
        rows = get_distribution(conn, sql)
        L.append(f"### {label}")
        L.append("")
        L += hist(rows, "registries per verse")
        L.append("")

    # Top 25 verses by registry count
    top_v_reg = conn.execute("""
        WITH ov AS (
          SELECT DISTINCT vr.book_id, vr.chapter, vr.verse_num, vr.reference,
                 wr.no AS reg_no, wr.word AS reg_word
            FROM wa_verse_records vr
            JOIN wa_term_inventory ti ON ti.id = vr.term_inv_id
            JOIN wa_file_index fi ON fi.id = ti.file_id
            JOIN word_registry wr ON wr.id = fi.word_registry_fk
           WHERE vr.delete_flagged = 0 AND ti.delete_flagged = 0
             AND ti.term_owner_type = 'OWNER'
        )
        SELECT reference,
               COUNT(DISTINCT reg_no) AS n_reg,
               GROUP_CONCAT(DISTINCT reg_no || ':' || reg_word) AS regs
          FROM ov
         GROUP BY book_id, chapter, verse_num, reference
         ORDER BY n_reg DESC, reference
         LIMIT 25
    """).fetchall()
    L.append("### Top 25 verses by registry count (all OWNER scope)")
    L.append("")
    L.append("| reference | n registries | registries |")
    L.append("|---|---:|---|")
    for r in top_v_reg:
        regs = r['regs'][:200] + ("…" if len(r['regs']) > 200 else "")
        L.append(f"| {r['reference']} | {r['n_reg']} | {regs} |")
    L.append("")

    # ── Q2: Verse → N distinct strongs (regardless of registry) ─────────────
    L.append("---")
    L.append("")
    L.append("## Q2 — Verses under N distinct terms")
    L.append("")
    L.append("How many distinct canonical verses carry 1, 2, 3, … distinct Strong's numbers "
             "(across all OWNER term occurrences in the verse). Same scope variants as Q1.")
    L.append("")

    for label, where_extra in [
        ("All OWNER `wa_verse_records`", ""),
        ("Analytically retained (`verse_context.is_relevant=1`)",
         """JOIN verse_context vc ON vc.verse_record_id = vr.id
                                 AND vc.delete_flagged = 0
                                 AND vc.is_relevant = 1"""),
        ("Anchors only (`verse_context.is_anchor=1`)",
         """JOIN verse_context vc ON vc.verse_record_id = vr.id
                                 AND vc.delete_flagged = 0
                                 AND vc.is_anchor = 1"""),
    ]:
        sql = f"""
            WITH vt AS (
              SELECT DISTINCT vr.book_id, vr.chapter, vr.verse_num,
                     ti.strongs_number
                FROM wa_verse_records vr
                JOIN wa_term_inventory ti ON ti.id = vr.term_inv_id
                {where_extra}
               WHERE vr.delete_flagged = 0
                 AND ti.delete_flagged = 0
                 AND ti.term_owner_type = 'OWNER'
            )
            SELECT n_terms, COUNT(*) AS n_verses FROM (
              SELECT book_id, chapter, verse_num,
                     COUNT(DISTINCT strongs_number) AS n_terms
                FROM vt
               GROUP BY book_id, chapter, verse_num
            )
            GROUP BY n_terms ORDER BY n_terms
        """
        rows = get_distribution(conn, sql)
        L.append(f"### {label}")
        L.append("")
        L += hist(rows, "distinct Strong's per verse")
        L.append("")

    # Top 25 verses by term count
    top_v_term = conn.execute("""
        WITH vt AS (
          SELECT DISTINCT vr.book_id, vr.chapter, vr.verse_num, vr.reference,
                 ti.strongs_number
            FROM wa_verse_records vr
            JOIN wa_term_inventory ti ON ti.id = vr.term_inv_id
           WHERE vr.delete_flagged = 0 AND ti.delete_flagged = 0
             AND ti.term_owner_type = 'OWNER'
        )
        SELECT reference,
               COUNT(DISTINCT strongs_number) AS n_terms,
               GROUP_CONCAT(DISTINCT strongs_number) AS strongs_list
          FROM vt
         GROUP BY book_id, chapter, verse_num, reference
         ORDER BY n_terms DESC, reference
         LIMIT 25
    """).fetchall()
    L.append("### Top 25 verses by distinct-Strong's count (all OWNER scope)")
    L.append("")
    L.append("| reference | n terms | strongs |")
    L.append("|---|---:|---|")
    for r in top_v_term:
        sl = r['strongs_list'][:200] + ("…" if len(r['strongs_list']) > 200 else "")
        L.append(f"| {r['reference']} | {r['n_terms']} | `{sl}` |")
    L.append("")

    # ── Q3: Strong's → N registries ─────────────────────────────────────────
    L.append("---")
    L.append("")
    L.append("## Q3 — Strong's numbers across N registries")
    L.append("")
    L.append("How many `mti_terms` rows (Strong's, programme-wide) appear in 1, 2, 3, … "
             "registries. Counts across both OWNER and XREF copies in `wa_term_inventory`. "
             "A Strong's appears in N registries when its OWNER home is one registry and it "
             "has XREF copies in N − 1 others (or other configurations).")
    L.append("")

    sql_q3 = """
        SELECT n_reg, COUNT(*) AS n_strongs FROM (
          SELECT ti.strongs_number, COUNT(DISTINCT wr.id) AS n_reg
            FROM wa_term_inventory ti
            JOIN wa_file_index fi ON fi.id = ti.file_id
            JOIN word_registry wr ON wr.id = fi.word_registry_fk
           WHERE ti.delete_flagged = 0
           GROUP BY ti.strongs_number
        )
        GROUP BY n_reg ORDER BY n_reg
    """
    rows_q3 = get_distribution(conn, sql_q3)
    L.append("### All active term inventory rows (OWNER + XREF combined)")
    L.append("")
    L += hist(rows_q3, "registries per Strong's")
    L.append("")

    # OWNER-only — every Strong's has exactly one OWNER row, so this is a sanity check
    rows_q3_owner = get_distribution(conn, """
        SELECT n_reg, COUNT(*) AS n_strongs FROM (
          SELECT ti.strongs_number, COUNT(DISTINCT wr.id) AS n_reg
            FROM wa_term_inventory ti
            JOIN wa_file_index fi ON fi.id = ti.file_id
            JOIN word_registry wr ON wr.id = fi.word_registry_fk
           WHERE ti.delete_flagged = 0 AND ti.term_owner_type = 'OWNER'
           GROUP BY ti.strongs_number
        )
        GROUP BY n_reg ORDER BY n_reg
    """)
    L.append("### OWNER-only sanity check (each Strong's has exactly one OWNER home)")
    L.append("")
    L += hist(rows_q3_owner, "OWNER registries per Strong's")
    L.append("")

    # Top 25 Strong's by registry count
    top_s_reg = conn.execute("""
        SELECT mt.strongs_number, mt.transliteration, mt.gloss, mt.language,
               COUNT(DISTINCT wr.id) AS n_reg,
               SUM(CASE WHEN ti.term_owner_type='OWNER' THEN 1 ELSE 0 END) AS n_owner,
               SUM(CASE WHEN ti.term_owner_type='XREF'  THEN 1 ELSE 0 END) AS n_xref,
               (SELECT wr2.no || ':' || wr2.word
                  FROM wa_term_inventory ti2
                  JOIN wa_file_index fi2 ON fi2.id = ti2.file_id
                  JOIN word_registry wr2 ON wr2.id = fi2.word_registry_fk
                 WHERE ti2.strongs_number = mt.strongs_number
                   AND ti2.term_owner_type='OWNER'
                   AND ti2.delete_flagged = 0
                 LIMIT 1) AS owner_home,
               GROUP_CONCAT(DISTINCT wr.no || ':' || wr.word) AS regs
          FROM mti_terms mt
          JOIN wa_term_inventory ti ON ti.strongs_number = mt.strongs_number
                                   AND ti.delete_flagged = 0
          JOIN wa_file_index fi ON fi.id = ti.file_id
          JOIN word_registry wr ON wr.id = fi.word_registry_fk
         WHERE mt.delete_flagged = 0
         GROUP BY mt.strongs_number
         ORDER BY n_reg DESC, mt.strongs_number
         LIMIT 25
    """).fetchall()
    L.append("### Top 25 Strong's by registry count")
    L.append("")
    L.append("| strongs | translit | gloss | lang | n_reg | OWNER home | OWNER + XREF rows |")
    L.append("|---|---|---|---|---:|---|---|")
    for r in top_s_reg:
        regs = r['regs'][:200] + ("…" if len(r['regs']) > 200 else "")
        L.append(f"| `{r['strongs_number']}` | {r['transliteration'] or ''} | "
                 f"{(r['gloss'] or '')[:30]} | {r['language'][:1]} | {r['n_reg']} | "
                 f"{r['owner_home'] or '?'} | O={r['n_owner']} X={r['n_xref']}; {regs} |")
    L.append("")

    # ── Bonus: how many registries are reached, on average, per Strong's ──
    avg_stat = conn.execute("""
        SELECT AVG(n_reg) AS avg_n_reg, MAX(n_reg) AS max_n_reg
          FROM (
            SELECT ti.strongs_number, COUNT(DISTINCT wr.id) AS n_reg
              FROM wa_term_inventory ti
              JOIN wa_file_index fi ON fi.id = ti.file_id
              JOIN word_registry wr ON wr.id = fi.word_registry_fk
             WHERE ti.delete_flagged = 0
             GROUP BY ti.strongs_number
          )
    """).fetchone()
    L.append(f"_Average registries per Strong's: **{avg_stat['avg_n_reg']:.2f}** · "
             f"max: **{avg_stat['max_n_reg']}**._")
    L.append("")

    # ── Closing summary block ────────────────────────────────────────────
    L.append("---")
    L.append("")
    L.append("## Quick read")
    L.append("")
    L.append("- **Q1** measures verse-level cross-registry overlap — high counts in N≥2 indicate "
             "verses that touch multiple inner-being characteristics simultaneously (e.g. complex "
             "psalms or prophet passages).")
    L.append("- **Q2** measures intra-verse term richness — verses with multiple Strong's may "
             "still belong to a single registry; this is independent of Q1.")
    L.append("- **Q3** measures programme-wide vocabulary sharing — the count of Strong's that "
             "have one OWNER home and ≥1 XREF copies elsewhere.")
    L.append("")
    print("\n".join(L))
    conn.close()
    return 0


if __name__ == "__main__":
    sys.exit(main())
