import sys; sys.path.insert(0,'scripts')
from _reread_ledger_lib import Reading, IB, GOD, PER
r=Reading("Psa",19,86,
  note="Ps86 David's personal prayer (17v). Passages: plea of the poor+godly v1-7; praise of the incomparable God v8-10; the request to be taught + united heart v11-13; deliverance from the insolent + closing plea v14-17. Human IB (rich): the POOR/NEEDY, GODLY self who TRUSTS; the CRYing + lifting of the SOUL; those who CALL; WORSHIP + GLORIFY; WALK in truth, the united HEART that FEARS; GIVE-THANKS with whole HEART; the INSOLENT/RUTHLESS who SEEK the life; the HATERS put to SHAME; being COMFORTED. God's incline/answer/gracious/merciful/steadfast-love/deliver = qualifiers; Sheol/depths/sign imagery = standalone.")
for a in [
 (306975,"poor (ani)","status","the psalmist","be poor / afflicted","before God","paired with being needy",IB,"v1: 'answer me, for I am POOR (ani) and needy' - the lowly estate David pleads as his claim on God, humility the ground of the appeal."),
 (306976,"needy (ebyon)","status","the psalmist","be needy","before God","paired with being poor",IB,"v1: 'for I am poor and NEEDY (ebyon)' - the destitution that casts him wholly on God."),
 (284326,"life / soul (nephesh)","faculty","the psalmist","be preserved","by God","paired with being godly",IB,"v2: 'PRESERVE my life (nephesh), for I am godly' - the self committed to God for keeping."),
 (284329,"godly (chasid)","status","the psalmist","be godly / devoted","to God","paired with trusting God",IB,"v2: 'preserve my life, for I am GODLY (chasid)' - the covenant-devotion David claims, not merit but belonging to God."),
 (284332,"trust (batach)","disposition","the psalmist","trust","in God","paired with being godly",GOD,"v2: 'save your servant who TRUSTS (batach) in you' - the reliance on God that undergirds every petition."),
 (284340,"cry (qara)","action","the psalmist","cry out","to God all day","paired with the plea for grace",GOD,"v3: 'for to you do I CRY (qara) all the day' - the ceaseless calling, prayer sustained through the whole day."),
 (284344,"soul (nephesh)","faculty","the psalmist","be gladdened","by God","paired with lifting up the soul",IB,"v4: 'Gladden the SOUL (nephesh) of your servant' - the self longing for joy from God."),
 (284349,"lift up (nasa)","action","the psalmist","lift up the soul","to God","paired with the soul gladdened",GOD,"v4: 'for to you, O Lord, do I LIFT UP (nasa) my soul' - the aspiration of the whole self toward God, devotion as upward reach."),
 (284350,"soul (nephesh)","faculty","the psalmist","be lifted to God","in longing","paired with the lifting",IB,"v4: 'do I lift up my SOUL (nephesh)' - the self raised toward God, the object of the aspiration."),
 (284359,"call (qara)","action","those who call on God","call upon","God","paired with God's abounding love",GOD,"v5: 'abounding in steadfast love to all who CALL (qara) upon you' - the invoking of God that his love answers."),
 (284363,"prayer (tephillah)","action","the psalmist","pray","to God","paired with the plea for grace",GOD,"v6: 'Give ear, O LORD, to my PRAYER (tephillah)' - the petition David lifts, asking to be heard."),
 (284370,"call (qara)","action","the psalmist","call upon","God in trouble","paired with God's answering",GOD,"v7: 'In the day of my trouble I CALL (qara) upon you' - the appeal in distress, confident of an answer."),
 (284378,"worship (shachah)","action","all the nations","worship","before God","paired with glorifying his name",GOD,"v9: 'All the nations... shall come and WORSHIP (shachah) before you' - the homage of the peoples, worship as the destiny of the nations."),
 (284381,"glorify (kabad)","action","all the nations","glorify","God's name","paired with the worship",GOD,"v9: 'and shall GLORIFY (kabad) your name' - the nations honouring God's name."),
 (284256,"walk (halak)","action","the psalmist","walk","in God's truth","paired with the united heart",GOD,"v11: 'that I may WALK (halak) in your truth' - the request to live in God's truth, obedience as the fruit of teaching."),
 (284259,"heart (lebab)","faculty","the psalmist","be united","to fear God","paired with the fear of God's name",IB,"v11: 'UNITE my HEART (lebab) to fear your name' - the plea for an undivided heart, the inner self gathered to one devotion."),
 (284260,"fear (yare)","disposition","the psalmist","fear / revere","God's name","paired with the united heart",GOD,"v11: 'unite my heart to FEAR (yare) your name' - the reverence that the united heart exists for, worship's single aim."),
 (284263,"give thanks (yadah)","action","the psalmist","give thanks","to God wholeheartedly","paired with the whole heart and glorifying",GOD,"v12: 'I GIVE THANKS (yadah) to you, O Lord my God, with my whole heart' - the gratitude of the whole self, thanksgiving vowed forever."),
 (284267,"heart (lebab)","faculty","the psalmist","give thanks","with the whole heart","paired with the thanks and glorifying",IB,"v12: 'with my whole HEART (lebab)' - the entire inner self engaged in thanks, no reserve held back."),
 (284268,"glorify (kabad)","action","the psalmist","glorify","God's name forever","paired with the thanks",GOD,"v12: 'and I will GLORIFY (kabad) your name forever' - the honouring of God vowed without end."),
 (284276,"soul (nephesh)","faculty","the psalmist","be delivered","from Sheol","paired with God's steadfast love",IB,"v13: 'you have delivered my SOUL (nephesh) from the depths of Sheol' - the self rescued from death, ground of the thanks."),
 (284281,"insolent (zed)","status","insolent men","rise up","against the psalmist","paired with the ruthless band",IB,"v14: 'INSOLENT (zed) men have risen up against me' - the arrogant foes, pride turned to violence."),
 (284285,"ruthless men (arits)","status","a band of ruthless men","seek the psalmist's life","without regard for God","paired with the insolent",IB,"v14: 'a band of RUTHLESS MEN (arits) seeks my life' - the merciless enemies, violence without conscience."),
 (284286,"seek (baqash)","action","the ruthless men","seek","the psalmist's life","paired with their disregard of God",IB,"v14: 'seeks my life, and they do not set you before them' - the murderous intent of the godless, malice that ignores God."),
 (284316,"hate (sane)","disposition","those who hate the psalmist","hate","the psalmist","paired with being put to shame",IB,"v17: 'that those who HATE (sane) me may see and be put to shame' - the enemies' enmity, which God's help exposes."),
 (284318,"be put to shame (bosh)","state","the haters","be put to shame","by God's help to the psalmist","paired with the hatred",IB,"v17: 'may see and be PUT TO SHAME (bosh)' - the confounding of the foes when God vindicates his servant."),
 (284323,"be comforted (nacham)","state","the psalmist","be comforted","by God","paired with being helped",IB,"v17: 'because you, LORD, have helped me and COMFORTED (nacham) me' - the consolation God gives, the answered lament turned to comfort."),
]: r.ch(*a)
for sid,sense,src,d in [
 (306969,"incline (natah)",306975,"v1: 'INCLINE (natah) your ear, O LORD' - God's attentive bending petitioned. Qualifier."),
 (306972,"answer (anah)",306975,"v1: 'and ANSWER (anah) me' - God's response petitioned. Qualifier."),
 (284325,"preserve (shamar)",284326,"v2: 'PRESERVE (shamar) my life' - God's keeping petitioned. Qualifier."),
 (284330,"save (yasha)",284332,"v2: 'SAVE (yasha) your servant who trusts in you' - God's saving. Qualifier."),
 (284336,"be gracious (chanan)",284340,"v3: 'Be GRACIOUS (chanan) to me, O Lord' - God's grace petitioned. Qualifier."),
 (284343,"gladden (samach)",284344,"v4: 'GLADDEN (samach) the soul of your servant' - God's giving of joy petitioned. Qualifier."),
 (284354,"good (tob)",284359,"v5: 'For you, O Lord, are GOOD (tob) and forgiving' - God's goodness. Qualifier."),
 (284355,"forgiving (sallach)",284359,"v5: 'good and FORGIVING (sallach)' - God's readiness to pardon. Qualifier."),
 (284357,"steadfast love (chesed)",284359,"v5: 'abounding in STEADFAST LOVE (chesed)' - God's covenant love. Qualifier."),
 (284361,"give ear (azan)",284363,"v6: 'GIVE EAR (azan), O LORD, to my prayer' - God's attention petitioned. Qualifier."),
 (284364,"listen (qashab)",284363,"v6: 'LISTEN (qashab) to my plea for grace' - God's listening petitioned. Qualifier."),
 (284372,"answer (anah)",284370,"v7: 'for you ANSWER (anah) me' - God's answering. Qualifier."),
 (306981,"works (maaseh)",284378,"v8: 'nor are there any WORKS (maaseh) like yours' - God's incomparable deeds. Qualifier."),
 (284383,"name (shem)",284381,"v9: 'and shall glorify your NAME (shem)' - God's name. Qualifier."),
 (284250,"wondrous things (pala)",284378,"v10: 'you are great and do WONDROUS THINGS (pala)' - God's marvels. Qualifier."),
 (284253,"teach (yarah)",284256,"v11: 'TEACH (yarah) me your way, O LORD' - God's instruction petitioned. Qualifier."),
 (284257,"truth (emeth)",284256,"v11: 'that I may walk in your TRUTH (emeth)' - God's truth. Qualifier."),
 (284258,"unite (yachad)",284259,"v11: 'UNITE (yachad) my heart to fear your name' - God's uniting of the heart petitioned. Qualifier."),
 (284262,"name (shem)",284260,"v11: 'to fear your NAME (shem)' - God's name. Qualifier."),
 (284269,"name (shem)",284268,"v12: 'I will glorify your NAME (shem) forever' - God's name. Qualifier."),
 (284273,"steadfast love (chesed)",284276,"v13: 'For great is your STEADFAST LOVE (chesed) toward me' - God's covenant love. Qualifier."),
 (284275,"deliver (natsal)",284276,"v13: 'you have DELIVERED (natsal) my soul from the depths of Sheol' - God's rescue. Qualifier."),
 (284295,"merciful (rachum)",284323,"v15: 'you, O Lord, are a God MERCIFUL (rachum) and gracious' - God's mercy. Qualifier."),
 (284296,"gracious (chanun)",284323,"v15: 'merciful and GRACIOUS (chanun)' - God's grace. Qualifier."),
 (284297,"slow to anger (erek)",284323,"v15: 'SLOW (erek) to anger' - God's patience. Qualifier."),
 (284298,"anger (aph)",284323,"v15: 'slow to ANGER (aph)' - God's forbearance regarding anger. Qualifier."),
 (284300,"steadfast love (chesed)",284323,"v15: 'abounding in STEADFAST LOVE (chesed)' - God's covenant love. Qualifier."),
 (284301,"faithfulness (emeth)",284323,"v15: 'and FAITHFULNESS (emeth)' - God's faithfulness. Qualifier."),
 (284302,"turn (panah)",284323,"v16: 'TURN (panah) to me and be gracious to me' - God's turning petitioned. Qualifier."),
 (284304,"be gracious (chanan)",284323,"v16: 'and be GRACIOUS (chanan) to me' - God's grace petitioned. Qualifier."),
 (284306,"strength (oz)",284323,"v16: 'give your STRENGTH (oz) to your servant' - God's strength given. Qualifier."),
 (284309,"save (yasha)",284323,"v16: 'and SAVE (yasha) the son of your maidservant' - God's saving petitioned. Qualifier."),
 (284314,"sign (oth)",284323,"v17: 'Show me a SIGN (oth) of your favour' - God's token of favour petitioned. Qualifier."),
 (284315,"favor (tob)",284323,"v17: 'a sign of your FAVOUR (tobah)' - God's goodness/favour. Qualifier."),
 (284317,"see (raah)",284316,"v17: 'that those who hate me may SEE (raah)' - the foes' seeing of God's help. Qualifier."),
 (284322,"help (azar)",284323,"v17: 'because you, LORD, have HELPED (azar) me' - God's help. Qualifier."),
]: r.qu(sid,sense,src,d)
for sid,sense,d in [
 (306967,"Prayer (tephillah)","v0 superscription: 'A PRAYER (tephillah) of David' - the psalm-heading/type. Standalone."),
 (284365,"plea (techinnah)","v6: 'listen to my PLEA (techinnah) for grace' - the supplication, object of God's listening. Standalone."),
 (284366,"grace / supplication (tachanun)","v6: 'my plea for GRACE (tachanun)' - the entreaty for favour, content of the prayer. Standalone."),
 (284369,"trouble (tsarah)","v7: 'In the day of my TROUBLE (tsarah) I call' - the distress occasioning the call; circumstance. Standalone."),
 (284254,"way (derek)","v11: 'Teach me your WAY (derek)' - God's way, the object of the teaching. Standalone."),
 (284270,"forever (olam)","v12: 'I will glorify your name FOREVER (olam)' - the perpetuity of the vowed praise; temporal. Standalone."),
 (284278,"depths (tachti)","v13: 'from the DEPTHS (tachti) of Sheol' - the lowest grave, image of the death escaped. Standalone."),
 (284279,"Sheol (sheol)","v13: 'from the depths of SHEOL (sheol)' - the realm of death, image. Standalone."),
 (284284,"band (edah)","v14: 'a BAND (edah) of ruthless men' - the company of foes. Standalone."),
 (284287,"life (nephesh)","v14: 'seeks my LIFE (nephesh)' - the life the enemies seek, object of their malice. Standalone."),
 (284289,"set (sim)","v14: 'they do not SET (sim) you before them' - the enemies' disregard of God, the mark of their godlessness. Standalone."),
]: r.st(sid,sense,d)
r.write()
