import sys; sys.path.insert(0,'scripts')
from _reread_ledger_lib import Reading, IB, GOD, PER
r=Reading("Psa",19,106,
  note="Ps106 confession-recital (48v, 186 spans). Read by CHAR-ARC. Arcs: A praise+plea v1-5; B confession thesis 'we have SINNED' v6; C Red Sea (didn't CONSIDER/REMEMBER, REBELLED->BELIEVED/SANG) v7-12; D wilderness (FORGOT, wouldn't WAIT, WANTON CRAVING, TESTED, ASKED) v13-15; E ENVY of Moses v16; F golden calf (WORSHIPED, EXCHANGED glory, FORGOT) v19-21; G despised land (DESPISED, no FAITH, MURMURED, disobeyed) v24-25; H Baal-Peor+Phinehas (YOKED, PROVOKED->INTERVENED, RIGHTEOUSNESS) v28-31; I Meribah (ANGERED, bitter SPIRIT, SPOKE-RASHLY) v32-33; J Canaanite idolatry (didn't DESTROY, MIXED, LEARNED, SERVED idols, SACRIFICED sons, POURED innocent blood, POLLUTED, UNCLEAN, WHORE) v34-39; K judgment cycle (HATED, OPPRESSED, SUBJECTION, REBELLIOUS, PURPOSES, INIQUITY) v41-43; L mercy+plea (CRY, GIVE-THANKS, GLORY, BLESSED, PRAISE) v44-48. Between = God's acts (qualifiers) + imagery (standalone).")
A=269572; B=269835; C=269848; D=269610; E=269622; F=269630; G=269673; H=269694; I=269716; J=269722; K=269772; L=269782
CH=[
 # Arc A
 (269572,"praise (halal)","action","the worshippers","praise","the LORD",GOD,"paired with giving thanks","v1: 'PRAISE (halal) the LORD! Oh give thanks to the LORD, for he is good' - the opening Hallelujah of the confession-hymn."),
 (269574,"give thanks (yadah)","action","the worshippers","give thanks","to the LORD",GOD,"paired with praising","v1: 'Oh GIVE THANKS (yadah) to the LORD, for he is good' - gratitude for God's enduring love, the frame around the confession."),
 (269636,"declare (shama)","action","the worshippers","declare / proclaim","all God's praise",GOD,"paired with praising","v2: 'or DECLARE (shama) all his praise?' - the rhetorical reach of proclaiming God's mighty deeds, more than any can utter."),
 (269698,"blessed (esher)","state","those who keep justice","be blessed","in keeping justice",IB,"paired with observing justice and doing righteousness","v3: 'BLESSED (esher) are they who observe justice' - the happiness of the just, set before the confession as the standard the fathers failed."),
 (269699,"observe (shamar)","action","the just","observe / keep","justice",IB,"paired with the blessedness and righteousness","v3: 'they who OBSERVE (shamar) justice' - the keeping of justice, righteous conduct."),
 (269700,"justice (mishpat)","disposition","the just","keep justice","at all times",IB,"paired with righteousness","v3: 'they who observe JUSTICE (mishpat)' - the justice the blessed keep, righteous dealing."),
 (269702,"righteousness (tsedaqah)","disposition","the just","do righteousness","at all times",IB,"paired with justice","v3: 'who do RIGHTEOUSNESS (tsedaqah) at all times!' - the constant right conduct of the blessed, the ideal against which Israel's history is confessed."),
 (269826,"rejoice (samach)","state","the psalmist","rejoice","in the gladness of God's nation",IB,"paired with gladness and glorying","v5: 'that I may REJOICE (samach) in the gladness of your nation' - the psalmist's longing to share his people's joy in God's favour."),
 (269827,"gladness (simchah)","state","God's nation","have gladness","in God","paired with rejoicing",IB,"v5: 'in the GLADNESS (simchah) of your nation' - the joy of the redeemed people the psalmist longs to share."),
 (269830,"glory (halal)","action","the psalmist","glory","with God's inheritance",GOD,"paired with rejoicing","v5: 'that I may GLORY (halal) with your inheritance' - the psalmist's desire to exult with God's people, boasting in him."),
 # Arc B confession
 (269835,"sin (chata)","action","we and our fathers","sin","against God",GOD,"paired with iniquity and wickedness","v6: 'Both we and our fathers have SINNED (chata)' - the confession's thesis, the whole nation owning its guilt across the generations."),
 (269837,"commit iniquity (avah)","action","we and our fathers","commit iniquity","against God",GOD,"paired with sinning","v6: 'we have COMMITTED INIQUITY (avah)' - the twisting of the right, the second term of the threefold confession."),
 (269838,"do wickedness (rasha)","action","we and our fathers","do wickedness","against God",GOD,"paired with sinning","v6: 'we have DONE WICKEDNESS (rasha)' - the active wrong, the confession's full admission of guilt."),
 # Arc C Red Sea
 (269842,"consider (sakal, negated)","action","the fathers","fail to consider","God's wondrous works",IB,"paired with not remembering his love","v7: 'Our fathers... did not CONSIDER (sakal) your wondrous works' - the failure to weigh God's deeds, unbelief born of inattention."),
 (269845,"remember (zakar, negated)","action","the fathers","fail to remember","God's steadfast love",IB,"paired with not considering, and with rebelling","v7: 'they did not REMEMBER (zakar) the abundance of your steadfast love' - the forgetting of God's love that bred rebellion."),
 (269848,"rebel (marah)","action","the fathers","rebel","against God at the sea",GOD,"paired with the failure to remember","v7: 'but REBELLED (marah) by the sea, at the Red Sea' - the first act of the catalogue, defiance at the very edge of deliverance."),
 (269595,"believe (aman)","disposition","the fathers","believe","God's words",GOD,"paired with singing his praise","v12: 'Then they BELIEVED (aman) his words' - the flash of faith after the sea's deliverance, belief that would not last."),
 (269598,"sing (shir)","action","the fathers","sing","God's praise",GOD,"paired with believing","v12: 'they SANG (shir) his praise' - the song of the redeemed at the sea, worship soon forgotten (v13)."),
 # Arc D wilderness craving
 (269602,"forget (shakach)","action","the fathers","forget","God's works",IB,"paired with not waiting for his counsel","v13: 'But they soon FORGOT (shakach) his works' - the swift forgetting, the song of v12 dying within days."),
 (269606,"wait (chakah, negated)","disposition","the fathers","fail to wait","for God's counsel",GOD,"paired with forgetting","v13: 'they did not WAIT (chakah) for his counsel' - the impatience that would not trust God's timing."),
 (269609,"wanton (taavah)","disposition","the fathers","have a wanton craving","in the wilderness",IB,"paired with the craving and the testing","v14: 'But they had a WANTON (taavah) craving in the wilderness' - the fierce appetite that ruled them, desire become idolatry."),
 (269610,"craving (avah)","disposition","the fathers","crave","food in the desert",IB,"paired with the wanton desire","v14: 'they had a wanton CRAVING (avah) in the wilderness' - the lusting after food, the greed that tested God."),
 (269613,"test (nasah)","action","the fathers","test / put to proof","God in the desert",GOD,"paired with the craving","v14: 'and put God to the TEST (nasah) in the desert' - the presumptuous trying of God born of appetite."),
 (269616,"ask (sheelah)","action","the fathers","ask / demand","what they craved",GOD,"paired with the craving God granted","v15: 'He gave them what they ASKED (sheelah)' - the demand God met, granting their request but sending leanness."),
 # Arc E envy
 (269622,"jealous / envy (qana)","disposition","men in the camp","be jealous","of Moses and Aaron",IB,"paired with the earth swallowing the rebels","v16: 'When men in the camp were JEALOUS (qana) of Moses' - the envy of Korah's company against God's chosen leaders."),
 # Arc F golden calf
 (269630,"worship (shachah)","action","the fathers","worship","a metal image",IB,"paired with exchanging the glory","v19: 'and WORSHIPED (shachah) a metal image' - the calf-worship at Horeb, the exchange of the living God for an idol."),
 (269640,"exchange (mur)","action","the fathers","exchange","the glory of God for an ox-image",IB,"paired with worshiping the calf","v20: 'They EXCHANGED (mur) the glory of God for the image of an ox' - the fatal swap, the Creator traded for a grass-eating beast."),
 (307456,"forget (shakach)","action","the fathers","forget","God their Saviour",IB,"paired with worshiping the calf","v21: 'They FORGOT (shakach) God, their Saviour, who had done great things in Egypt' - the forgetting of the very God who redeemed them."),
 # Arc G despising the land
 (269666,"despise (maas)","action","the fathers","despise","the pleasant land",IB,"paired with having no faith","v24: 'Then they DESPISED (maas) the pleasant land' - the scorn of Canaan at Kadesh, rejecting God's gift."),
 (269670,"faith (aman, negated)","disposition","the fathers","have no faith","in God's promise",GOD,"paired with despising the land","v24: 'having no FAITH (aman) in his promise' - the unbelief that could not trust God to give the land."),
 (269673,"murmur (ragan)","action","the fathers","murmur / grumble","in their tents",GOD,"paired with not obeying","v25: 'They MURMURED (ragan) in their tents' - the grumbling of the people, discontent turned to complaint against God."),
 (269676,"obey (shama, negated)","action","the fathers","fail to obey","the voice of the LORD",GOD,"paired with murmuring","v25: 'and did not OBEY (shama) the voice of the LORD' - the disobedience behind the murmuring."),
 # Arc H Baal-Peor + Phinehas
 (269689,"yoke (tsamad)","action","the fathers","yoke themselves","to the Baal of Peor",IB,"paired with provoking God","v28: 'Then they YOKED (tsamad) themselves to the Baal of Peor' - the harnessing to a false god, apostasy joined to immorality."),
 (269694,"provoke (kaas)","action","the fathers","provoke to anger","the LORD by their deeds",GOD,"paired with the plague and Phinehas' intervention","v29: 'they PROVOKED (kaas) the LORD to anger with their deeds' - the rousing of God's wrath, met by plague."),
 (269707,"intervene (palal)","action","Phinehas","intervene / execute judgment","and the plague was stayed",GOD,"paired with the righteousness counted him","v30: 'Then Phinehas stood up and INTERVENED (palal), and the plague was stayed' - the zeal of Phinehas, decisive action that turned back the wrath."),
 (269711,"righteousness (tsedaqah)","state","Phinehas","be counted righteous","for his zeal",IB,"paired with his intervention","v31: 'And that was counted to him as RIGHTEOUSNESS (tsedaqah)' - the reckoning of Phinehas' zeal to his everlasting credit."),
 # Arc I Meribah
 (269716,"anger (qatsaph)","action","the fathers","anger / provoke","God at Meribah",GOD,"paired with Moses' embittered spirit","v32: 'They ANGERED (qatsaph) him at the waters of Meribah' - the provoking at Meribah, whose fallout reached even Moses."),
 (307463,"spirit (ruach)","faculty","Moses","have the spirit embittered","by the people",IB,"paired with the bitterness and rash speech","v33: 'for they made his SPIRIT (ruach) bitter' - Moses' inner self soured by the people's strife, the meekest man goaded."),
 (307464,"bitter (marah)","state","Moses","be embittered","in spirit",IB,"paired with the spirit and rash words","v33: 'they made his spirit BITTER (marah)' - the embittering of Moses, provocation working inward."),
 (307465,"speak rashly (bata)","action","Moses","speak rashly","with his lips",IB,"paired with the embittered spirit","v33: 'and he SPOKE RASHLY (bata) with his lips' - Moses' hasty words at Meribah, the one lapse that cost him the land."),
 # Arc J Canaanite idolatry
 (307469,"destroy (shamad, negated)","action","the fathers","fail to destroy","the peoples as commanded",GOD,"paired with mixing with the nations","v34: 'They did not DESTROY (shamad) the peoples, as the LORD commanded them' - the disobedient sparing that led to idolatry."),
 (307474,"mix (arab)","action","the fathers","mix / mingle","with the nations",IB,"paired with learning their ways","v35: 'but they MIXED (arab) with the nations' - the intermingling with the peoples, compromise that bred corruption."),
 (307476,"learn (lamad)","action","the fathers","learn","to do as the nations did",IB,"paired with mixing","v35: 'and LEARNED (lamad) to do as they did' - the adoption of pagan ways, sin caught by association."),
 (269722,"serve (abad)","action","the fathers","serve","their idols",IB,"paired with the idols that snared them","v36: 'They SERVED (abad) their idols, which became a snare to them' - the idolatry that trapped the people."),
 (307478,"sacrifice (zabach)","action","the fathers","sacrifice","their sons and daughters to demons",IB,"paired with pouring out innocent blood","v37: 'They SACRIFICED (zabach) their sons and their daughters to the demons' - the child-sacrifice, idolatry at its most horrific."),
 (269726,"pour out (shaphak)","action","the fathers","pour out","innocent blood",IB,"paired with sacrificing their children","v38: 'they POURED OUT (shaphak) innocent blood, the blood of their sons and daughters' - the shedding of innocent blood, murder as worship."),
 (269737,"pollute (chaneph)","action","the fathers","pollute","the land with blood",IB,"paired with becoming unclean","v38: 'and the land was POLLUTED (chaneph) with blood' - the defilement of the land by their bloodshed."),
 (269739,"become unclean (tame)","state","the fathers","become unclean","by their acts",IB,"paired with playing the whore","v39: 'Thus they became UNCLEAN (tame) by their acts' - the defilement of the people themselves, sin as pollution."),
 (269741,"play the whore (zanah)","action","the fathers","play the whore","in their deeds",IB,"paired with becoming unclean","v39: 'and played the WHORE (zanah) in their deeds' - the spiritual adultery of idolatry, unfaithfulness to God imaged as harlotry."),
 # Arc K judgment cycle
 (269759,"hate (sane)","disposition","the enemies","hate","God's people",IB,"paired with ruling over them","v41: 'those who HATED (sane) them ruled over them' - the enmity of the nations to whom God gave his people over."),
 (269763,"oppress (lachats)","action","the enemies","oppress","God's people",IB,"paired with bringing them into subjection","v42: 'Their enemies OPPRESSED (lachats) them' - the affliction of Israel under the nations, the fruit of their sin."),
 (269764,"subjection (kana)","state","the fathers","be brought into subjection","under the enemies' power",IB,"paired with the oppression","v42: 'and they were brought into SUBJECTION (kana) under their power' - the humbling of Israel, abased beneath their foes."),
 (269772,"rebellious (marah)","disposition","the fathers","be rebellious","in their purposes",GOD,"paired with their self-willed counsel","v43: 'but they were REBELLIOUS (marah) in their purposes' - the persistent defiance, deliverance met again with rebellion."),
 (269773,"purposes (etsah)","faculty","the fathers","follow their own counsel","against God",IB,"paired with rebelliousness","v43: 'rebellious in their PURPOSES (etsah)' - the self-devised counsels the people preferred to God's will."),
 (269776,"iniquity (avon)","state","the fathers","be brought low","through their iniquity",IB,"paired with being brought low","v43: 'and were brought low through their INIQUITY (avon)' - the guilt that sank them, sin bearing its own judgment."),
 # Arc L mercy + plea
 (269782,"cry (rinnah)","action","the fathers","cry","to God in distress",GOD,"paired with God hearing and remembering","v44: 'when he heard their CRY (rinnah)' - the cry of the afflicted that moved God to remember his covenant."),
 (269801,"give thanks (yadah)","action","the redeemed","give thanks","to God's holy name",GOD,"paired with glorying in his praise","v47: 'that we may GIVE THANKS (yadah) to your holy name' - the vow of the gathered people, the aim of the plea to be saved."),
 (269804,"glory (shabach)","action","the redeemed","glory / triumph","in God's praise",GOD,"paired with giving thanks","v47: 'and GLORY (shabach) in your praise' - the exulting in God the gathered would render."),
 (269807,"blessed be (barak)","action","the worshippers","bless","the LORD, the God of Israel",GOD,"paired with the closing praise","v48: 'BLESSED (barak) be the LORD, the God of Israel, from everlasting to everlasting!' - the doxology closing Book IV."),
 (269819,"praise (halal)","action","the people","praise","the LORD",GOD,"paired with the blessing","v48: 'Let all the people say, Amen! PRAISE (halal) the LORD!' - the closing Hallelujah, the whole people's Amen."),
]
for a in CH: r.ch(*a)
QU=[
 (269633,"utter (malal)",A,"v2: 'Who can UTTER (malal) the mighty deeds of the LORD' - the telling of God's deeds, more than any can voice. Qualifier."),
 (269634,"mighty deeds (geburah)",A,"v2: 'the MIGHTY DEEDS (geburah) of the LORD' - God's mighty acts. Qualifier."),
 (269639,"praise (tehillah)",A,"v2: 'declare all his PRAISE (tehillah)' - God's praiseworthiness. Qualifier."),
 (269577,"good (tob)",A,"v1: 'for he is GOOD (tob)' - God's goodness. Qualifier."),
 (269579,"steadfast love (chesed)",A,"v1: 'for his STEADFAST LOVE (chesed) endures forever!' - God's covenant love. Qualifier."),
 (269580,"endures forever (olam)",A,"v1: 'his steadfast love ENDURES FOREVER (olam)' - the perpetuity of God's love. Qualifier."),
 (269701,"do (asah)",269698,"v3: 'who DO (asah) righteousness at all times!' - the doing of righteousness (with the char, 269702). Qualifier."),
 (269744,"remember (zakar)",A,"v4: 'REMEMBER (zakar) me, O LORD, when you show favour' - God's remembering petitioned. Qualifier."),
 (269746,"favor (ratson)",A,"v4: 'when you show FAVOUR (ratson) to your people' - God's favour. Qualifier."),
 (269748,"help (paqad)",A,"v4: 'HELP (paqad) me when you save them' - God's visitation/help petitioned. Qualifier."),
 (269749,"save (yeshuah)",A,"v4: 'when you SAVE (yeshuah) them' - God's salvation. Qualifier."),
 (269832,"inheritance (nachalah)",A,"v5: 'that I may glory with your INHERITANCE (nachalah)' - God's inheritance, his people. Qualifier."),
 (269843,"wondrous works (pala)",C,"v7: 'did not consider your WONDROUS WORKS (pala)' - God's marvels. Qualifier."),
 (269846,"abundance (rob)",C,"v7: 'the ABUNDANCE (rob) of your steadfast love' - the fullness of God's love. Qualifier."),
 (269847,"steadfast love (chesed)",C,"v7: 'the abundance of your STEADFAST LOVE (chesed)' - God's covenant love. Qualifier."),
 (269853,"saved (yasha)",C,"v8: 'Yet he SAVED (yasha) them for his name's sake' - God's deliverance. Qualifier."),
 (269855,"name (shem)",C,"v8: 'for his NAME'S (shem) sake' - God's name. Qualifier."),
 (269857,"made known (yada)",C,"v8: 'that he might make KNOWN (yada) his mighty power' - God's self-revelation. Qualifier."),
 (269859,"mighty power (geburah)",C,"v8: 'his MIGHTY POWER (geburah)' - God's power. Qualifier."),
 (307442,"rebuked (gaar)",C,"v9: 'He REBUKED (gaar) the Red Sea, and it became dry' - God's command over the sea. Qualifier."),
 (307445,"became dry (chareb)",C,"v9: 'and it BECAME DRY (chareb)' - God's drying of the sea. Qualifier."),
 (269581,"saved (yasha)",C,"v10: 'So he SAVED (yasha) them from the hand of the foe' - God's rescue. Qualifier."),
 (269585,"redeemed (gaal)",C,"v10: 'and REDEEMED (gaal) them from the power of the enemy' - God's redemption. Qualifier."),
 (269590,"covered (kasah)",C,"v11: 'the waters COVERED (kasah) their adversaries' - God's judgment on the foe. Qualifier."),
 (269594,"left (yathar)",C,"v11: 'not one of them was LEFT (yathar)' - the total destruction of the foe. Qualifier."),
 (269596,"words (dabar)",269595,"v12: 'Then they believed his WORDS (dabar)' - God's words. Qualifier."),
 (269600,"praise (tehillah)",269598,"v12: 'they sang his PRAISE (tehillah)' - God's praiseworthiness. Qualifier."),
 (269608,"counsel (etsah)",D,"v13: 'they did not wait for his COUNSEL (etsah)' - God's counsel. Qualifier."),
 (269615,"gave (nathan)",D,"v15: 'He GAVE (nathan) them what they asked' - God's granting of the craving. Qualifier."),
 (269617,"sent (shalach)",D,"v15: 'but SENT (shalach) a wasting disease among them' - God's judgment. Qualifier."),
 (269627,"made (asah)",F,"v19: 'They MADE (asah) a calf in Horeb' - the making of the calf (with the char worshiped, 269630). Qualifier."),
 (269641,"glory (kabod)",F,"v20: 'They exchanged the GLORY (kabod) of God' - God's glory, exchanged for an idol. Qualifier."),
 (307459,"done (asah)",F,"v21: 'who had DONE (asah) great things in Egypt' - God's mighty acts. Qualifier."),
 (269647,"wondrous works (pala)",F,"v22: 'WONDROUS WORKS (pala) in the land of Ham' - God's marvels. Qualifier."),
 (269650,"awesome deeds (yare)",F,"v22: 'and AWESOME DEEDS (yare) by the Red Sea' - God's awesome acts. Qualifier."),
 (269654,"destroy (shamad)",F,"v23: 'he said he would DESTROY (shamad) them' - God's threatened judgment. Qualifier."),
 (269658,"stood (amad)",F,"v23: 'had not Moses... STOOD (amad) in the breach before him' - Moses standing in the breach (God's-side mediation). Qualifier."),
 (269662,"turn away (shuv)",F,"v23: 'to TURN AWAY (shuv) his wrath from destroying them' - the turning of God's wrath. Qualifier."),
 (269663,"wrath (chemah)",F,"v23: 'to turn away his WRATH (chemah)' - God's wrath. Qualifier."),
 (269665,"destroying (shachath)",F,"v23: 'his wrath from DESTROYING (shachath) them' - God's destruction averted. Qualifier."),
 (269672,"promise (dabar)",G,"v24: 'having no faith in his PROMISE (dabar)' - God's promise. Qualifier."),
 (269677,"voice (qol)",G,"v25: 'did not obey the VOICE (qol) of the LORD' - God's voice. Qualifier."),
 (269679,"raised his hand (nasa)",G,"v26: 'Therefore he RAISED (nasa) his hand and swore to them' - God's oath of judgment. Qualifier."),
 (269682,"fall (naphal)",G,"v26: 'to make them FALL (naphal) in the wilderness' - God's sentence of death. Qualifier."),
 (269685,"fall (naphal)",G,"v27: 'and would make their offspring FALL (naphal) among the nations' - God's judgment. Qualifier."),
 (269687,"scattering (zarah)",G,"v27: 'SCATTERING (zarah) them among the lands' - God's dispersal. Qualifier."),
 (269695,"deeds (maalal)",H,"v29: 'provoked the LORD to anger with their DEEDS (maalal)' - the deeds that provoked (the char provoked, 269694). Qualifier."),
 (269709,"stayed (atsar)",H,"v30: 'and the plague was STAYED (atsar)' - God's staying of the plague. Qualifier."),
 (269710,"counted (chashab)",H,"v31: 'And that was COUNTED (chashab) to him as righteousness' - God's reckoning of Phinehas' zeal. Qualifier."),
 (269719,"went ill (yara)",I,"v32: 'and it WENT ILL (yara) with Moses on their account' - the harm that came to Moses through the people. Qualifier."),
 (307467,"lips (saphah)",I,"v33: 'he spoke rashly with his LIPS (saphah)' - the lips of Moses' rash speech (char, 307465). Qualifier."),
 (269723,"idols (atsab)",J,"v36: 'They served their IDOLS (atsab)' - the idols served (char served, 269722). Qualifier."),
 (269725,"snare (moqesh)",J,"v36: 'which became a SNARE (moqesh) to them' - the trap of idolatry. Qualifier."),
 (269733,"sacrificed (zabach)",J,"v38: 'whom they SACRIFICED (zabach) to the idols of Canaan' - the child-sacrifice (with char, 307478). Qualifier."),
 (269743,"deeds (maaseh)",J,"v39: 'unclean by their DEEDS (maaseh)' - the defiling deeds (char unclean, 269739). Qualifier."),
 (269750,"anger (aph)",I,"v40: 'Then the ANGER (aph) of the LORD was kindled against his people' - God's anger. Qualifier."),
 (269752,"kindled (charah)",I,"v40: 'the anger of the LORD was KINDLED (charah)' - God's kindled wrath. Qualifier."),
 (269754,"abhorred (taab)",I,"v40: 'and he ABHORRED (taab) his heritage' - God's abhorrence of the sinful people. Qualifier."),
 (269755,"heritage (nachalah)",I,"v40: 'he abhorred his HERITAGE (nachalah)' - God's inheritance, his people. Qualifier."),
 (269756,"gave (nathan)",K,"v41: 'He GAVE (nathan) them into the hand of the nations' - God's handing-over. Qualifier."),
 (269760,"ruled (mashal)",K,"v41: 'those who hated them RULED (mashal) over them' - the enemies' dominion (God-permitted). Qualifier."),
 (269774,"brought low (makak)",K,"v43: 'and were BROUGHT LOW (makak) through their iniquity' - God's humbling of the people. Qualifier."),
 (269770,"delivered (natsal)",K,"v43: 'Many times he DELIVERED (natsal) them' - God's repeated deliverance despite their rebellion. Qualifier."),
 (269777,"looked (raah)",L,"v44: 'Nevertheless, he LOOKED (raah) upon their distress' - God's regard for their affliction. Qualifier."),
 (269780,"heard (shama)",L,"v44: 'when he HEARD (shama) their cry' - God's hearing. Qualifier."),
 (269783,"remembered (zakar)",L,"v45: 'he REMEMBERED (zakar) his covenant' - God's faithful remembrance. Qualifier."),
 (269784,"covenant (berith)",L,"v45: 'he remembered his COVENANT (berith)' - God's covenant. Qualifier."),
 (269785,"relented (nacham)",L,"v45: 'and RELENTED (nacham) according to the abundance of his steadfast love' - God's compassion. Qualifier."),
 (269786,"abundance (rob)",L,"v45: 'according to the ABUNDANCE (rob) of his steadfast love' - the fullness of God's love. Qualifier."),
 (269788,"steadfast love (chesed)",L,"v45: 'the abundance of his STEADFAST LOVE (chesed)' - God's covenant love. Qualifier."),
 (269789,"caused to be pitied (nathan)",L,"v46: 'He CAUSED (nathan) them to be pitied by all those who held them captive' - God's granting them mercy. Qualifier."),
 (269794,"save (yasha)",L,"v47: 'SAVE (yasha) us, O LORD our God' - God's salvation petitioned. Qualifier."),
 (269797,"gather (qabats)",L,"v47: 'and GATHER (qabats) us from among the nations' - God's regathering petitioned. Qualifier."),
 (269802,"holy (qodesh)",L,"v47: 'give thanks to your HOLY (qodesh) name' - God's holiness. Qualifier."),
 (269803,"name (shem)",L,"v47: 'to your holy NAME (shem)' - God's name. Qualifier."),
 (269806,"praise (tehillah)",L,"v47: 'and glory in your PRAISE (tehillah)' - God's praiseworthiness. Qualifier."),
]
for sid,sense,src,d in QU: r.qu(sid,sense,src,d)
ST=[
 (269851,"Red Sea (suph)","v7: 'rebelled by the sea, at the RED (suph) Sea' - the Sea of Reeds, place of the rebellion. Standalone."),
 (307443,"Red Sea (suph)","v9: 'He rebuked the RED (suph) Sea' - the sea God dried, place. Standalone."),
 (307447,"deep (tehom)","v9: 'he led them through the DEEP (tehom) as through a desert' - the sea-depths, image. Standalone."),
 (269584,"foe (sane)","v10: 'he saved them from the hand of the FOE (sane)' - the enemy at the sea, object. Standalone."),
 (269591,"adversaries (tsar)","v11: 'the waters covered their ADVERSARIES (tsar)' - the drowned foes, image. Standalone."),
 (269601,"soon (maher)","v13: 'But they SOON (maher) forgot his works' - the swiftness of the forgetting; temporal. Standalone."),
 (269618,"wasting disease (razon)","v15: 'but sent a WASTING DISEASE (razon) among them' - the leanness sent as judgment, image. Standalone."),
 (269619,"among them (nephesh)","v15: 'a wasting disease AMONG THEM (nephesh, into their soul)' - the judgment into their very life, image. Standalone."),
 (269621,"camp (machaneh)","v16: 'When men in the CAMP (machaneh) were jealous' - the Israelite camp, setting. Standalone."),
 (269625,"holy one (qadosh)","v16: 'Aaron, the HOLY ONE (qadosh) of the LORD' - Aaron as God's consecrated priest, object of the envy. Standalone."),
 (307450,"opened (pathach)","v17: 'The earth OPENED (pathach) and swallowed up Dathan' - the earth's opening in judgment, image. Standalone."),
 (307451,"swallowed up (bala)","v17: 'and SWALLOWED UP (bala) Dathan' - the earth engulfing the rebels, image. Standalone."),
 (307453,"covered (kasah)","v17: 'and COVERED (kasah) the company of Abiram' - the buried rebels, image. Standalone."),
 (307454,"company (edah)","v17: 'the COMPANY (edah) of Abiram' - Abiram's band, the rebels. Standalone."),
 (302403,"broke out (baar)","v18: 'Fire also BROKE OUT (baar) in their company' - the fire of judgment, image. Standalone."),
 (302404,"company (edah)","v18: 'broke out in their COMPANY (edah)' - the rebel band, image. Standalone."),
 (302405,"flame (lehabah)","v18: 'the FLAME (lehabah) burned up the wicked' - the fire of judgment, image. Standalone."),
 (302406,"burned up (lahat)","v18: 'the flame BURNED UP (lahat) the wicked' - the consuming fire, image. Standalone."),
 (302407,"wicked (rasha)","v18: 'the flame burned up the WICKED (rasha)' - the rebels consumed, object of the judgment. Standalone."),
 (269628,"calf (egel)","v19: 'They made a CALF (egel) in Horeb' - the golden calf, image of the idolatry (char worshiped, 269630). Standalone."),
 (269631,"metal image (massekah)","v19: 'and worshiped a METAL IMAGE (massekah)' - the cast idol, image. Standalone."),
 (269643,"image (tabnith)","v20: 'for the IMAGE (tabnith) of an ox' - the ox-form idol, image. Standalone."),
 (269644,"ox (shor)","v20: 'the image of an OX (shor)' - the bull-idol, image. Standalone."),
 (269645,"eats (akal)","v20: 'an ox that EATS (akal) grass' - the grass-eating beast, image of the idol's worthlessness. Standalone."),
 (269646,"grass (eseb)","v20: 'an ox that eats GRASS (eseb)' - the fodder, image. Standalone."),
 (307458,"Savior (yasha)","v21: 'They forgot God, their SAVIOUR (yasha)' - God as saviour, forgotten (char forgot, 307456). Standalone."),
 (269651,"Red Sea (suph)","v22: 'awesome deeds by the RED (suph) Sea' - the sea of the wonders, place. Standalone."),
 (269659,"breach (perets)","v23: 'had not Moses... stood in the BREACH (perets)' - the gap in the wall, image of Moses' mediation. Standalone."),
 (269667,"pleasant (chemdah)","v24: 'Then they despised the PLEASANT (chemdah) land' - the desirable land despised (char despised, 269666). Standalone."),
 (269689,"yoked (tsamad)","v28: 'they yoked themselves to the Baal of PEOR (peor)' - see char yoked; the Baal-place. Standalone."),
 (269691,"ate (akal)","v28: 'and ATE (akal) sacrifices offered to the dead' - the sacrificial meals of idolatry, image. Standalone."),
 (269692,"sacrifices (zebach)","v28: 'ate SACRIFICES (zebach) offered to the dead' - the pagan offerings, image. Standalone."),
 (269693,"dead (muth)","v28: 'sacrifices offered to the DEAD (muth)' - the lifeless idols/dead gods, image. Standalone."),
 (269696,"plague (maggephah)","v29: 'and a PLAGUE (maggephah) broke out among them' - the plague of judgment, image. Standalone."),
 (269697,"broke out (parats)","v29: 'a plague BROKE OUT (parats) among them' - the outbreak of judgment, image. Standalone."),
 (269705,"Phinehas (pinechas)","v30: 'Then PHINEHAS (pinechas) stood up and intervened' - Phinehas, the zealous priest (char intervened, 269707). Standalone."),
 (269706,"stood up (amad)","v30: 'Phinehas STOOD UP (amad)' - Phinehas rising to act, image of his zeal. Standalone."),
 (269708,"plague (maggephah)","v30: 'and the PLAGUE (maggephah) was stayed' - the plague halted, image. Standalone."),
 (307469,"peoples (am)","v34: 'They did not destroy the PEOPLES (am)' - the Canaanite nations spared (char destroy, 307469 handled). Standalone."),
 (269727,"innocent (naqi)","v38: 'they poured out INNOCENT (naqi) blood' - the guiltless children slain, object. Standalone."),
 (269728,"blood (dam)","v38: 'poured out innocent BLOOD (dam)' - the shed blood, image. Standalone."),
 (269729,"blood (dam)","v38: 'the BLOOD (dam) of their sons and daughters' - the children's blood, image. Standalone."),
 (269734,"idols (atsab)","v38: 'whom they sacrificed to the IDOLS (atsab) of Canaan' - the Canaanite idols, image. Standalone."),
 (269738,"blood (dam)","v38: 'and the land was polluted with BLOOD (dam)' - the defiling blood, image. Standalone."),
 (307481,"demons (shed)","v37: 'their sons and daughters to the DEMONS (shed)' - the demonic gods, image. Standalone."),
 (269765 if False else 269793,"captive (shabah)","v46: 'all those who held them CAPTIVE (shabah)' - the captors, image. Standalone."),
 (269790,"pitied (racham)","v46: 'He caused them to be PITIED (racham) by all those who held them captive' - the compassion the captors were made to show, image. Standalone."),
 (269822,"look upon (raah)","v5: 'that I may LOOK UPON (raah) the prosperity of your chosen ones' - the psalmist's longing to behold his people's good, image. Standalone."),
 (269823,"prosperity (tob)","v5: 'the PROSPERITY (tob) of your chosen ones' - the good/welfare of God's elect, object of the longing. Standalone."),
 (269778,"distress (tsar)","v44: 'he looked upon their DISTRESS (tsar)' - the affliction God regarded, image. Standalone."),
 (269812,"everlasting (olam)","v48: 'from EVERLASTING (olam)' - God's eternity; temporal. Standalone."),
 (269814,"everlasting (olam)","v48: 'to EVERLASTING (olam)' - God's eternity; temporal. Standalone."),
]
for sid,sense,d in ST: r.st(sid,sense,d)
r.write()
