import sys; sys.path.insert(0,'scripts')
from _reread_ledger_lib import Reading, IB, GOD, PER
r=Reading("Psa",19,85,
  note="Ps85 restoration prayer (Korah, 13v). Passages: past favour recalled v1-3; the plea to restore v4-7; the oracle of peace + the meeting of God's virtues v8-13. Human IB is thin against God's attributes/acts: the forgiven INIQUITY/SIN; the people who REJOICE; the psalmist who would HEAR God's word; the SAINTS; the plea not to TURN-BACK to FOLLY; those who FEAR him. God's favour/forgive/restore/steadfast-love/righteousness/peace = qualifiers; fortunes/increase/footsteps imagery = standalone.")
for a in [
 (284184,"iniquity (avon)","state","your people","bear iniquity, now forgiven","before God","paired with the sin covered",IB,"v2: 'You forgave the INIQUITY (avon) of your people' - the people's guilt, remembered as what God's grace lifted."),
 (284189,"sin (chattath)","state","your people","bear sin, now covered","before God","paired with the iniquity forgiven",IB,"v2: 'you COVERED all their SIN (chattath)' - the people's sin, owned in the memory of God's pardon."),
 (284216,"rejoice (samach)","action","your people","rejoice","in God","paired with the plea to revive them",GOD,"v6: 'that your people may REJOICE (samach) in you' - the joy revival would bring, gladness as the aim of restoration."),
 (284224,"hear (shama)","action","the psalmist","hear / listen","to what God will speak","paired with the peace God speaks",GOD,"v8: 'Let me HEAR (shama) what God the LORD will speak' - the posture of attentive faith, waiting on God's word of peace."),
 (284235,"saints / godly (chasid)","status","his saints","be God's faithful","who hear his peace","paired with not turning to folly",IB,"v8: 'he will speak peace to his people, to his SAINTS (chasid)' - the covenant-faithful to whom God speaks peace, the godly community."),
 (284237,"turn back (shuv)","disposition","the saints","not turn back","to folly","paired with the folly warned against",IB,"v8: 'but let them not TURN BACK (shuv) to folly' - the relapse guarded against, the danger that the restored might revert."),
 (284238,"folly (kislah)","disposition","the people","fall into folly","away from God","paired with the turning-back",IB,"v8: 'let them not turn back to FOLLY (kislah)' - the senseless self-confidence the people must not resume, sin as folly."),
 (284242,"fear (yare)","disposition","those who fear God","fear / revere","God","paired with the nearness of his salvation",GOD,"v9: 'Surely his salvation is near to those who FEAR (yare) him' - the reverent, to whom deliverance draws near; the fear that receives grace."),
]: r.ch(*a)
for sid,sense,src,d in [
 (284149,"be favorable (ratsah)",284216,"v1: 'LORD, you were FAVOURABLE (ratsah) to your land' - God's past favour. Qualifier."),
 (284152,"restore (shuv)",284216,"v1: 'you RESTORED (shuv) the fortunes of Jacob' - God's past restoration. Qualifier."),
 (284183,"forgive (nasa)",284184,"v2: 'You FORGAVE (nasa) the iniquity of your people' - God's pardon. Qualifier."),
 (284187,"cover (kasah)",284189,"v2: 'you COVERED (kasah) all their sin' - God's covering of sin. Qualifier."),
 (284191,"withdraw (asaph)",284216,"v3: 'You WITHDREW (asaph) all your wrath' - God's set-aside anger. Qualifier."),
 (284193,"wrath (ebrah)",284216,"v3: 'you withdrew all your WRATH (ebrah)' - God's anger. Qualifier."),
 (284195,"turn (shuv)",284216,"v3: 'you TURNED (shuv) from your hot anger' - God's turning from wrath. Qualifier."),
 (284197,"hot (charon)",284216,"v3: 'from your HOT (charon) anger' - God's fierce anger. Qualifier."),
 (284198,"anger (aph)",284216,"v3: 'from your hot ANGER (aph)' - God's anger. Qualifier."),
 (284201,"salvation (yesha)",284216,"v4: 'Restore us again, O God of our SALVATION (yesha)' - God's saving. Qualifier."),
 (284202,"put away (parar)",284216,"v4: 'PUT AWAY (parar) your indignation toward us' - God's laying aside of anger petitioned. Qualifier."),
 (284203,"indignation (kaas)",284216,"v4: 'put away your INDIGNATION (kaas)' - God's displeasure. Qualifier."),
 (284206,"be angry (anaph)",284216,"v5: 'Will you be ANGRY (anaph) with us forever?' - God's anger. Qualifier."),
 (284208,"prolong (mashak)",284216,"v5: 'Will you PROLONG (mashak) your anger to all generations?' - God's continued anger questioned. Qualifier."),
 (284209,"anger (aph)",284216,"v5: 'will you prolong your ANGER (aph)' - God's anger. Qualifier."),
 (284213,"revive (chayah)",284216,"v6: 'Will you not REVIVE (chayah) us again?' - God's reviving petitioned. Qualifier."),
 (284218,"show (raah)",284224,"v7: 'SHOW (raah) us your steadfast love, O LORD' - God's showing of love petitioned. Qualifier."),
 (284219,"steadfast love (chesed)",284224,"v7: 'show us your STEADFAST LOVE (chesed)' - God's covenant love. Qualifier."),
 (284221,"grant (nathan)",284224,"v7: 'and GRANT (nathan) us your salvation' - God's giving. Qualifier."),
 (284223,"salvation (yesha)",284224,"v7: 'grant us your SALVATION (yesha)' - God's deliverance. Qualifier."),
 (284228,"speak (dabar)",284224,"v8: 'what God the LORD will SPEAK (dabar)' - God's word. Qualifier."),
 (284230,"speak (dabar)",284224,"v8: 'he will SPEAK (dabar) peace to his people' - God's speaking peace. Qualifier."),
 (284231,"peace (shalom)",284235,"v8: 'he will speak PEACE (shalom) to his people' - the shalom God grants. Qualifier."),
 (284240,"salvation (yesha)",284242,"v9: 'his SALVATION (yesha) is near to those who fear him' - God's deliverance. Qualifier."),
 (284241,"near (qarob)",284242,"v9: 'his salvation is NEAR (qarob)' - God's nearness in salvation. Qualifier."),
 (284243,"glory (kabod)",284242,"v9: 'that GLORY (kabod) may dwell in our land' - God's glory. Qualifier."),
 (284244,"dwell (shakan)",284242,"v9: 'that glory may DWELL (shakan) in our land' - God's presence dwelling. Qualifier."),
 (284155,"steadfast love (chesed)",284231,"v10: 'STEADFAST LOVE (chesed) and faithfulness meet' - God's love, personified. Qualifier."),
 (284156,"faithfulness (emeth)",284231,"v10: 'steadfast love and FAITHFULNESS (emeth) meet' - God's faithfulness. Qualifier."),
 (284157,"meet (pagash)",284231,"v10: 'steadfast love and faithfulness MEET (pagash)' - God's virtues reconciled. Qualifier."),
 (284158,"righteousness (tsedeq)",284231,"v10: 'RIGHTEOUSNESS (tsedeq) and peace kiss each other' - God's righteousness. Qualifier."),
 (284159,"peace (shalom)",284231,"v10: 'righteousness and PEACE (shalom) kiss' - the shalom of God's order. Qualifier."),
 (284160,"kiss (nashaq)",284231,"v10: 'righteousness and peace KISS (nashaq)' - God's virtues embracing. Qualifier."),
 (284161,"faithfulness (emeth)",284231,"v11: 'FAITHFULNESS (emeth) springs up from the ground' - God's faithfulness. Qualifier."),
 (284162,"spring up (tsamach)",284231,"v11: 'faithfulness SPRINGS UP (tsamach) from the ground' - God's faithfulness rising. Qualifier."),
 (284165,"righteousness (tsedeq)",284231,"v11: 'and RIGHTEOUSNESS (tsedeq) looks down from the sky' - God's righteousness. Qualifier."),
 (284166,"look down (shaqaph)",284231,"v11: 'righteousness LOOKS DOWN (shaqaph) from the sky' - God's righteousness surveying. Qualifier."),
 (284171,"give (nathan)",284231,"v12: 'the LORD will GIVE (nathan) what is good' - God's giving. Qualifier."),
 (284172,"good (tob)",284231,"v12: 'the LORD will give what is GOOD (tob)' - God's good gift. Qualifier."),
 (284174,"yield (nathan)",284231,"v12: 'and our land will YIELD (nathan) its increase' - the land's God-given fruit. Qualifier."),
 (284176,"righteousness (tsedeq)",284231,"v13: 'RIGHTEOUSNESS (tsedeq) will go before him' - God's righteousness. Qualifier."),
 (284179,"make (sim)",284231,"v13: 'and MAKE (sim) his footsteps a way' - God's preparing his path. Qualifier."),
]: r.qu(sid,sense,src,d)
for sid,sense,d in [
 (284153,"fortunes (shebuth)","v1: 'you restored the FORTUNES (shebuth) of Jacob' - the reversed captivity, the object of God's restoring. Standalone."),
 (284199,"again (shuv)","v4: 'Restore us AGAIN (shuv), O God' - the renewal sought; temporal. Standalone."),
 (284207,"forever (olam)","v5: 'Will you be angry with us FOREVER (olam)?' - the feared perpetuity; temporal. Standalone."),
 (284214,"again (shuv)","v6: 'Will you not revive us AGAIN (shuv)?' - the renewal sought; temporal. Standalone."),
 (284175,"increase (yebul)","v12: 'our land will yield its INCREASE (yebul)' - the harvest, image of blessing. Standalone."),
 (284181,"footsteps (paam)","v13: 'and make his FOOTSTEPS (paam) a way' - God's tread, image of his advancing righteousness. Standalone."),
 (284182,"way (derek)","v13: 'make his footsteps a WAY (derek)' - the path prepared, image. Standalone."),
]: r.st(sid,sense,d)
r.write()
