import sys; sys.path.insert(0,'scripts')
from _reread_ledger_lib import Reading, IB, GOD, PER
r=Reading("Psa",19,137,
  note="Ps137 'By the rivers of Babylon' (9v). Operations: the grief-WEEPING in exile at the memory (REMEMBERED) of Zion; the refusal/inability to SING the LORD's song in a foreign land; the fierce self-binding vow of memory (FORGET x2 - let hand/tongue fail if I FORGET; REMEMBER; Jerusalem above my highest JOY); the imprecatory BLESSING x2 on Babylon's destroyer. God's remember-against-Edom = qualifier; willows/lyres/rock imagery = standalone.")
CH=[
 (273270,"weep (bakah)","state","the exiles","weep","at the memory of Zion",IB,"paired with remembering Zion",
  "v1: 'there we WEPT (bakah), when we remembered Zion' - the operation of grief triggered by memory: the sight of Babylon's rivers loosing tears for the lost city."),
 (273272,"remember (zakar)","action","the exiles","remember","Zion",IB,"paired with the weeping",
  "v1: 'when we REMEMBERED (zakar) Zion' - the memory that opens the grief, the lost home called to mind."),
 (308025,"sing (shir, refused)","action","the exiles","be unable to sing","the LORD's song in exile",GOD,"paired with the captors' demand",
  "v4: 'How shall we SING (shir) the LORD's song in a foreign land?' - the operation of grief silencing joy: the captors demand a Zion-song, but praise cannot be performed on command in a strange land."),
 (308031,"forget (shakach, negated)","disposition","the psalmist","not forget","Jerusalem",IB,"paired with the hand failing if he forgets",
  "v5: 'If I FORGET (shakach) you, O Jerusalem, let my right hand forget its skill!' - the operation of self-binding memory: the vow to hold Jerusalem so fast that forgetting would be self-mutilation."),
 (308035,"forget (shakach)","action","the psalmist's hand","forget its skill","if he forgets Jerusalem",IB,"paired with the vow not to forget",
  "v5: 'let my right HAND forget (shakach) its skill!' - the self-curse that seals the vow: may the very hand lose its cunning if the memory of Zion lapses."),
 (273290,"remember (zakar)","action","the psalmist","remember","Jerusalem above all joy",IB,"paired with setting Jerusalem above his highest joy",
  "v6: 'if I do not REMEMBER you, if I do not set Jerusalem above my highest joy!' - the operation of ordered love: the city bound to the top of all the psalmist's joys."),
 (273297,"joy (simchah)","state","the psalmist","rank Jerusalem above his highest joy","in exile",IB,"paired with remembering the city",
  "v6: 'above my highest JOY (simchah)!' - the highest gladness itself made subordinate to the memory of Jerusalem, love that orders every joy beneath the city."),
 (308039,"blessed (esher)","state","the avenger","be blessed","for repaying Babylon",IB,"paired with the repayment invoked",
  "v8: 'BLESSED (esher) shall he be who repays you with what you have done to us!' - the imprecatory beatitude: the fierce blessing pronounced on the agent of Babylon's just recompense."),
 (308043,"blessed (esher)","state","the avenger","be blessed","for the dreadful requital",IB,"paired with the dashing of the little ones",
  "v9: 'BLESSED (esher) shall he be who takes your little ones and dashes them against the rock!' - the harshest imprecation of the Psalter, exile's rage pronounced as a blessing on the executioner of talion justice."),
]
for a in CH: r.ch(*a)
r.qu(273298,"remember (zakar)",273290,"v7: 'REMEMBER (zakar), O LORD, against the Edomites the day of Jerusalem' - God's remembrance invoked against the foe. Qualifier.")
for sid,sense,d in [
 (273265,"waters (nahar)","v1: 'By the WATERS (nahar) of Babylon' - the rivers of exile, image. Standalone."),
 (273268,"sat down (yashab)","v1: 'there we SAT DOWN (yashab) and wept' - the posture of mourning, image. Standalone."),
 (308019,"willows (arab)","v2: 'On the WILLOWS (arab) there we hung up our lyres' - the trees of the exile-land, image. Standalone."),
 (308021,"hung up (talah)","v2: 'we HUNG UP (talah) our lyres' - the silenced instruments, image of grief. Standalone."),
 (308023,"lyres (kinnor)","v2: 'our LYRES (kinnor)' - the harps laid aside, image. Standalone."),
 (273276,"captors (shabah)","v3: 'our CAPTORS (shabah) required of us songs' - the Babylonian jailers, image. Standalone."),
 (273277,"required (shaal)","v3: 'REQUIRED (shaal) of us songs' - the demand for entertainment, image. Standalone."),
 (273278,"songs (dabar)","v3: 'required of us SONGS (dabar)' - the songs demanded, image. Standalone."),
 (273279,"tormentors (talal)","v3: 'and our TORMENTORS (talal), mirth' - the mockers, image. Standalone."),
 (273280,"mirth (simchah)","v3: 'our tormentors, MIRTH (simchah)' - the forced gaiety demanded, image. Standalone."),
 (273281,"sing (shir)","v3: 'SING (shir) us one of the songs of Zion!' - the captors' taunting demand, image. Standalone."),
 (273283,"songs (shir)","v3: 'one of the SONGS (shir) of Zion!' - the Zion-songs demanded, image. Standalone."),
 (308027,"song (shir)","v4: 'How shall we sing the LORD's SONG (shir)' - the sacred song (char sing, 308025), image. Standalone."),
 (308028,"foreign (nekar)","v4: 'in a FOREIGN (nekar) land?' - the alien soil, image. Standalone."),
 (308034,"right hand (yamin)","v5: 'let my RIGHT HAND (yamin) forget its skill!' - the hand of the char forget (308035), image. Standalone."),
 (273285,"tongue (lashon)","v6: 'Let my TONGUE (lashon) stick to the roof of my mouth' - the self-curse of muteness, image. Standalone."),
 (273286,"stick (dabaq)","v6: 'Let my tongue STICK (dabaq)' - the tongue cleaving, image of the vow. Standalone."),
 (273287,"mouth (chek)","v6: 'to the roof of my MOUTH (chek)' - the palate, image. Standalone."),
 (273293,"set (alah)","v6: 'if I do not SET (alah) Jerusalem' - the ranking of the city (char remember, 273290), image. Standalone."),
 (273296,"highest (rosh)","v6: 'above my HIGHEST (rosh) joy!' - the top of all joys (char joy, 273297), image. Standalone."),
 (273300,"Edomites (ben)","v7: 'against the EDOMITES (ben Edom)' - the foes who cheered Jerusalem's fall, image. Standalone."),
 (273304,"lay bare (arah)","v7: 'LAY IT BARE (arah), lay it bare' - the Edomites' cry to raze the city, image. Standalone."),
 (273305,"lay bare (arah)","v7: 'lay it BARE (arah), down to its foundations!' - the cry repeated, image. Standalone."),
 (273308,"foundations (yesod)","v7: 'down to its FOUNDATIONS (yesod)!' - the city's base to be razed, image. Standalone."),
 (308036,"daughter (bath)","v8: 'O DAUGHTER (bath) of Babylon, doomed to be destroyed' - Babylon personified, image. Standalone."),
 (308038,"destroyed (shadad)","v8: 'doomed to be DESTROYED (shadad)' - Babylon's decreed ruin, image. Standalone."),
 (308040,"repays (shalam)","v8: 'who REPAYS (shalam) you with what you have done to us!' - the talion requital (char blessed, 308039), image. Standalone."),
 (308042,"done to us (gamal)","v8: 'what you have DONE to us (gamal)' - Babylon's deeds recoiling, image. Standalone."),
 (308044,"takes (achaz)","v9: 'who TAKES (achaz) your little ones' - the seizing, image of the imprecation (char Blessed, 308043). Standalone."),
 (308045,"little ones (olel)","v9: 'your LITTLE ONES (olel)' - Babylon's infants, image. Standalone."),
 (308046,"dashes (naphats)","v9: 'and DASHES (naphats) them against the rock!' - the talion violence, image. Standalone."),
 (308048,"rock (sela)","v9: 'against the ROCK (sela)!' - the rock of execution, image. Standalone."),
]: r.st(sid,sense,d)
r.write()
