import sys; sys.path.insert(0,'scripts')
from _reread_ledger_lib import Reading, IB, GOD, PER
r=Reading("Psa",19,84,
  note="Ps84 pilgrimage-longing for God's house (Korah, 12v). Passages: the longing soul v1-4; the blessed pilgrim's ascent v5-7; the prayer + the worth of a day in the courts v8-12. Human IB: SOUL LONGS/FAINTS, HEART+FLESH SING-FOR-JOY; the BLESSED who dwell and PRAISE; those whose STRENGTH is in God, HEART set on the highways; the pilgrim from STRENGTH to strength; the PRAYER; a day BETTER, RATHER a doorkeeper; those who WALK UPRIGHTLY; BLESSED is the one who TRUSTS. God's hear/behold/shield/bestow-favor-honor-good = qualifiers; sparrow/valley/springs/courts imagery = standalone.")
for a in [
 (284072,"soul (nephesh)","faculty","the pilgrim","long and faint","for God's courts","paired with the longing and fainting",IB,"v2: 'My SOUL (nephesh) longs, yes, faints for the courts of the LORD' - the whole self yearning for God's presence, homesickness for the sanctuary."),
 (284073,"long (kasaph)","disposition","the pilgrim","long / yearn","for God's courts","paired with the fainting soul",IB,"v2: 'My soul LONGS (kasaph)' - the ache of desire for God's dwelling, longing so strong it exhausts."),
 (284075,"faint (kalah)","state","the pilgrim","faint / be spent","with longing","paired with the longing soul",IB,"v2: 'yes, FAINTS (kalah) for the courts of the LORD' - the swooning of desire, the self spent in yearning for God."),
 (284079,"heart (leb)","faculty","the pilgrim","sing for joy","to the living God","paired with the flesh and the joyful cry",IB,"v2: 'my HEART (leb) and flesh sing for joy to the living God' - the inmost self, joined with the body, crying out to God."),
 (284080,"flesh (basar)","faculty","the pilgrim","sing for joy","to the living God","paired with the heart",IB,"v2: 'my heart and FLESH (basar) sing for joy' - the whole embodied person, not soul alone, drawn to God."),
 (284081,"sing for joy (ranan)","action","the pilgrim","sing for joy","to the living God","paired with heart and flesh",GOD,"v2: 'my heart and flesh SING FOR JOY (ranan) to the living God' - the exultant cry of the whole self toward the living God."),
 (284099,"blessed (esher)","state","those who dwell in God's house","be blessed","in God's presence","paired with their ceaseless praise",IB,"v4: 'BLESSED (esher) are those who dwell in your house' - the happiness of those who abide with God, blessedness as nearness."),
 (284103,"praise (halal)","action","those who dwell in God's house","ever praise","God","paired with their blessedness",GOD,"v4: 'ever singing your PRAISE (halal)' - the unbroken worship of those who dwell with God, praise as the air of the house."),
 (284105,"blessed (esher)","state","those whose strength is in God","be blessed","in reliance on God","paired with the highways in the heart",IB,"v5: 'BLESSED (esher) are those whose strength is in you' - the happiness of the God-reliant, the pilgrim whose power is not his own."),
 (284107,"strength (oz)","disposition","the pilgrim","find strength","in God","paired with the heart set on Zion","external:god","v5: 'those whose STRENGTH (oz) is in you' - reliance on God as one's power, the inner leaning that sustains the journey."),
 (284109,"heart (lebab)","faculty","the pilgrim","set the heart","on the highways to Zion","paired with the strength in God",IB,"v5: 'in whose HEART (lebab) are the highways to Zion' - the inner road, the pilgrimage begun in the heart before the feet."),
 (284122,"strength (chayil)","state","the pilgrims","go from strength to strength","toward God","paired with appearing before God",IB,"v7: 'They go from STRENGTH (chayil) to strength' - the mounting vigour of the pilgrim, renewed not drained as Zion nears."),
 (284132,"prayer (tephillah)","action","the pilgrim","pray","to God","paired with the plea to hear and give ear","external:god","v8: 'O LORD God of hosts, hear my PRAYER (tephillah)' - the petition lifted from the road, the pilgrim's cry to be heard."),
 (284040,"better (tob)","disposition","the psalmist","value / prefer","a day in God's courts","paired with choosing the threshold",IB,"v10: 'a day in your courts is BETTER (tob) than a thousand elsewhere' - the reckoning of devotion, God's presence weighed against every alternative and found worth more."),
 (284043,"would rather (bachar)","disposition","the psalmist","choose / prefer","the threshold of God's house","paired with rejecting the tents of wickedness",IB,"v10: 'I would RATHER (bachar) be a doorkeeper in the house of my God' - the deliberate choice, the least place with God preferred to ease among the wicked."),
 (284064,"walk (halak)","action","the upright","walk","before God","paired with uprightness",GOD,"v11: 'No good thing does he withhold from those who WALK (halak) uprightly' - the God-ward conduct that receives his good, a way of life set toward him."),
 (284065,"uprightly (tamim)","disposition","the upright","be blameless","in walk","paired with the walking",IB,"v11: 'from those who walk UPRIGHTLY (tamim)' - the integrity of the God-ward life, blamelessness as the pilgrim's character."),
 (284068,"blessed (esher)","state","the one who trusts God","be blessed","in trusting God","paired with the trust",IB,"v12: 'BLESSED (esher) is the one who trusts in you' - the closing beatitude, happiness resting wholly on trust."),
 (284070,"trust (batach)","disposition","the one who trusts","trust","in God of hosts","paired with the blessedness",GOD,"v12: 'blessed is the one who TRUSTS (batach) in you' - the confidence in God that is the whole psalm's ground, longing resolved into trust."),
]: r.ch(*a)
for sid,sense,src,d in [
 (284125,"appear (raah)",284122,"v7: 'each one APPEARS (raah) before God in Zion' - the pilgrim's coming into God's presence. Qualifier."),
 (284131,"hear (shama)",284132,"v8: 'HEAR (shama) my prayer' - God's hearing petitioned. Qualifier."),
 (284133,"give ear (azan)",284132,"v8: 'GIVE EAR (azan), O God of Jacob' - God's attention petitioned. Qualifier."),
 (284137,"behold (raah)",284132,"v9: 'BEHOLD (raah) our shield, O God' - God's regard petitioned. Qualifier."),
 (284138,"shield (magen)",284132,"v9: 'behold our SHIELD (magen)' - God (or the king) as shield; God-content. Qualifier."),
 (284140,"look (nabat)",284132,"v9: 'LOOK (nabat) on the face of your anointed' - God's favourable looking petitioned. Qualifier."),
 (284055,"shield (magen)",284068,"v11: 'For the LORD God is a sun and SHIELD (magen)' - God as sun and shield. Qualifier."),
 (284057,"bestow (nathan)",284068,"v11: 'the LORD BESTOWS (nathan) favour and honour' - God's giving. Qualifier."),
 (284058,"favor (chen)",284068,"v11: 'bestows FAVOUR (chen)' - God's grace given. Qualifier."),
 (284059,"honor (kabod)",284068,"v11: 'favour and HONOUR (kabod)' - God's honour bestowed. Qualifier."),
 (284061,"good (tob)",284068,"v11: 'No GOOD (tob) thing does he withhold' - God's goodness. Qualifier."),
 (284062,"withhold (mana, negated)",284068,"v11: 'No good thing does he WITHHOLD (mana)' - God's unstinting giving. Qualifier."),
]: r.qu(sid,sense,src,d)
for sid,sense,d in [
 (284077,"courts (chatser)","v2: 'faints for the COURTS (chatser) of the LORD' - the temple courts, object of longing. Standalone."),
 (284085,"sparrow (tsippor)","v3: 'Even the SPARROW (tsippor) finds a home' - the nesting bird, image of belonging at God's altars. Standalone."),
 (284086,"finds (matsa)","v3: 'the sparrow FINDS (matsa) a home' - the bird's finding a place, image. Standalone."),
 (284088,"swallow (deror)","v3: 'and the SWALLOW (deror) a nest for herself' - the nesting bird, image. Standalone."),
 (284089,"nest (qen)","v3: 'a NEST (qen) for herself, where she may lay her young' - the bird's home at the altars, image. Standalone."),
 (284091,"lay (shith)","v3: 'where she may LAY (shith) her young' - the nesting, image. Standalone."),
 (284092,"young (ephroach)","v3: 'lay her YOUNG (ephroach)' - the fledglings, image of home at God's altars. Standalone."),
 (284093,"altars (mizbeach)","v3: 'at your ALTARS (mizbeach), O LORD of hosts' - the temple altars, the longed-for home. Standalone."),
 (284110,"highways (mesillah)","v5: 'in whose heart are the HIGHWAYS (mesillah) to Zion' - the pilgrim roads, image of the inward journey. Standalone."),
 (284111,"go (abar)","v6: 'As they GO (abar) through the Valley of Baca' - the passage of the pilgrims, image. Standalone."),
 (284112,"Valley of Baca (baka)","v6: 'through the VALLEY OF BACA (baka, weeping)' - the arid valley of tears, image of hardship turned to blessing. Standalone."),
 (284114,"make (shith)","v6: 'they MAKE (shith) it a place of springs' - the transformation of the dry valley, image. Standalone."),
 (284115,"springs (mayan)","v6: 'a place of SPRINGS (mayan)' - the water in the desert, image of refreshment. Standalone."),
 (284116,"early rain (moreh)","v6: 'the EARLY RAIN (moreh) also covers it with pools' - the autumn rain, image of blessing on the way. Standalone."),
 (284118,"covers (atah)","v6: 'the early rain COVERS (atah) it' - the rain clothing the valley, image. Standalone."),
 (284119,"pools (berakah)","v6: 'covers it with POOLS (berakah)' - the gathered rain, image of blessing. Standalone."),
 (284120,"go (halak)","v7: 'They GO (halak) from strength to strength' - the pilgrims' progress, image. Standalone."),
 (284124,"strength (chayil)","v7: 'from strength to STRENGTH (chayil)' - the second term of the idiom, the goal of the mounting vigour (the char, 284122). Standalone."),
 (284143,"anointed (mashiach)","v9: 'look on the face of your ANOINTED (mashiach)' - the king, the Lord's anointed, for whom the prayer is made. Standalone."),
 (284039,"courts (chatser)","v10: 'a day in your COURTS (chatser)' - the temple courts, the treasured place. Standalone."),
 (284044,"doorkeeper (saphaph)","v10: 'I would rather be a DOORKEEPER (saphaph) in the house of my God' - the humblest station at the threshold, image of chosen lowliness. Standalone."),
 (284048,"dwell (dur)","v10: 'than DWELL (dur) in the tents of wickedness' - the rejected alternative, image. Standalone."),
 (284050,"wickedness (resha)","v10: 'the tents of WICKEDNESS (resha)' - the dwelling of the wicked, spurned for the threshold of God's house. Standalone."),
]: r.st(sid,sense,d)
r.write()
