import sys; sys.path.insert(0,'scripts')
from _reread_ledger_lib import Reading, IB, GOD, PER
r=Reading("Psa",19,104,
  note="Ps104 creation hymn (35v, 166 spans). Read by CHAR-ARC (not verse-blocks): the human IB lives in 3 arcs amid a vast creation-catalogue. ARC-A doxology frame: v1 'Bless the LORD O my soul... you are very great' <-> v35b 'Bless the LORD O my soul! Praise the LORD!' (bookends). ARC-B heart-provision v14-15: wine to GLADDEN the HEART, oil to make the face SHINE, bread to strengthen man's HEART. ARC-C closing response v33-35a: I will SING + SING-PRAISE, may my MEDITATION be PLEASING, I REJOICE in the LORD, let SINNERS/WICKED be consumed. Between (v2-13,16-32) = God's creative ACTS (qualifiers, source-linked to the doxology) + created THINGS (standalone) - substrate, not a char passage.")
# ---- ARC A: doxology frame (v1 <-> v35) ----
r.ch(269203,"bless (barak)","action","the psalmist","bless","the LORD",GOD,"paired with the soul, bookended at v35",
  "v1: 'BLESS (barak) the LORD, O my soul! O LORD my God, you are very great!' - the self-summons that opens the hymn; the whole creation-catalogue that follows is the ground of this blessing. (Frame with v35.)")
r.ch(269205,"soul (nephesh)","faculty","the psalmist","bless the LORD","from within",IB,"paired with the blessing",
  "v1: 'Bless the LORD, O my SOUL (nephesh)!' - the innermost self roused to bless God for his works, the vantage from which the whole psalm is sung.")
r.ch(269343,"bless (barak)","action","the psalmist","bless","the LORD",GOD,"bookend to the opening blessing (v1)",
  "v35: 'BLESS (barak) the LORD, O my soul!' - the closing return of the frame; having surveyed all God's works, the soul comes back to bless. (Directly interrelated with v1, 269203.)")
r.ch(269345,"soul (nephesh)","faculty","the psalmist","bless the LORD","to the last",IB,"paired with the closing blessing",
  "v35: 'Bless the LORD, O my SOUL (nephesh)!' - the innermost self, first and last called to bless the Creator.")
r.ch(269346,"praise (halal)","action","the psalmist","praise","the LORD (Hallelujah)",GOD,"paired with the closing blessing",
  "v35: 'PRAISE (halal) the LORD!' - the first Hallelujah of the Psalter, sealing the creation-hymn with praise.")
# ---- ARC B: heart-provision cluster (v14-15) ----
r.ch(269240,"gladden (samach)","state","man","have the heart gladdened","by wine (God's provision)",IB,"paired with the heart, and with the face that shines",
  "v14-15: 'wine to GLADDEN (samach) the heart of man' - the inner lift God's provision gives, gladness as one of the ends of the harvest; the arc's centre.")
r.ch(269241,"heart (lebab)","faculty","man","be gladdened","by wine",IB,"paired with the gladdening, and with the strengthened heart (269249)",
  "v15: 'wine to gladden the HEART (lebab) of man' - the inner seat God's gift reaches, the heart that wine cheers.")
r.ch(269245,"shine (tsahal)","state","man","have the face shine","with oil",IB,"paired with the gladdened heart",
  "v15: 'oil to make his face SHINE (tsahal)' - the brightened countenance, the outward glow of the inner gladness God's provision brings.")
r.ch(269249,"heart (lebab)","faculty","man","be strengthened","by bread",IB,"paired with the gladdened heart (269241)",
  "v15: 'and bread to strengthen man's HEART (lebab)' - the heart sustained by food, the inner self upheld; parallel to the heart gladdened by wine.")
# ---- ARC C: closing personal response (v33-35a) ----
r.ch(269324,"sing (shir)","action","the psalmist","sing","to the LORD as long as he lives",GOD,"paired with singing praise",
  "v33: 'I will SING (shir) to the LORD as long as I live' - the lifelong vow of praise, the personal response to all God's works.")
r.ch(269328,"sing praise (zamar)","action","the psalmist","sing praise","to God while he has being",GOD,"paired with the singing",
  "v33: 'I will SING PRAISE (zamar) to my God while I have being' - the pledge of praise for as long as life lasts.")
r.ch(269331,"meditation (siach)","faculty","the psalmist","meditate","on God",GOD,"paired with rejoicing, and with its being pleasing",
  "v34: 'May my MEDITATION (siach) be pleasing to him' - the inward musing on God the psalmist hopes God will accept, worship of the mind.")
r.ch(269332,"pleasing (arab)","state","the psalmist's meditation","be pleasing / acceptable","to God",GOD,"paired with the meditation",
  "v34: 'may my meditation be PLEASING (arab) to him' - the acceptability sought for the inner worship, that the musing may delight God.")
r.ch(269334,"rejoice (samach)","action","the psalmist","rejoice","in the LORD",GOD,"paired with the singing",
  "v34: 'for I REJOICE (samach) in the LORD' - the joy in God that fuels the song, gladness that is worship's spring.")
r.ch(269336,"sinners (chatta)","status","sinners","be sinners","consumed from the earth",IB,"paired with the wicked",
  "v35: 'Let SINNERS (chatta) be consumed from the earth' - the one discordant note in the creation-praise, the wish that evil be cleared from God's good world.")
r.ch(269340,"wicked (rasha)","status","the wicked","be wicked","and be no more",IB,"paired with the sinners",
  "v35: 'and let the WICKED (rasha) be no more!' - the wicked whose end the psalmist longs for, so creation's praise may be unmarred.")
# ---- QUALIFIERS: God's creative acts (source -> the doxology / provision they evoke) ----
CRE=269203  # creation acts blessed by the soul
PRO=269240  # v14-15 provision acts -> the heart-gladdening
QU=[
 (269209,"great (gadal)",CRE,"v1: 'you are very GREAT (gadal)!' - God's greatness, the ground of the blessing. Qualifier."),
 (269210,"clothed (labesh)",CRE,"v1: 'You are CLOTHED (labesh) with splendour and majesty' - God robed in glory. Qualifier."),
 (269211,"splendor (hod)",CRE,"v1: 'clothed with SPLENDOUR (hod)' - God's splendour. Qualifier."),
 (269212,"majesty (hadar)",CRE,"v1: 'splendour and MAJESTY (hadar)' - God's majesty. Qualifier."),
 (307249,"covering (atah)",CRE,"v2: 'COVERING (atah) yourself with light as with a garment' - God clothed in light. Qualifier."),
 (307252,"stretching out (natah)",CRE,"v2: 'STRETCHING OUT (natah) the heavens like a tent' - God spreading the sky. Qualifier."),
 (307256,"lays the beams (qarah)",CRE,"v3: 'He LAYS THE BEAMS (qarah) of his chambers on the waters' - God building his upper chambers. Qualifier."),
 (307260,"makes (sim)",CRE,"v3: 'he MAKES (sim) the clouds his chariot' - God's use of the clouds. Qualifier."),
 (307264,"rides (halak)",CRE,"v3: 'he RIDES (halak) on the wings of the wind' - God riding the storm. Qualifier."),
 (307268,"makes (asah)",CRE,"v4: 'he MAKES (asah) his messengers winds' - God's commissioning of winds and fire. Qualifier."),
 (307274,"set (yasad)",CRE,"v5: 'He SET (yasad) the earth on its foundations' - God's founding of the earth. Qualifier."),
 (307280,"moved (mot)",CRE,"v5: 'so that it should never be MOVED (mot)' - God's establishing the earth unshakeable. Qualifier."),
 (307281,"covered (kasah)",CRE,"v6: 'You COVERED (kasah) it with the deep as with a garment' - God's covering of the earth with waters. Qualifier."),
 (269349,"rebuke (gaarah)",CRE,"v7: 'At your REBUKE (gaarah) they fled' - God's rebuke driving back the waters. Qualifier."),
 (269362,"appointed (yasad)",CRE,"v8: 'to the place that you APPOINTED (yasad) for them' - God's assigning of the waters' place. Qualifier."),
 (307288,"set a boundary (sim)",CRE,"v9: 'You SET (sim) a boundary that they may not pass' - God's bounding of the seas. Qualifier."),
 (307297,"gush forth (shalach)",CRE,"v10: 'You make springs GUSH FORTH (shalach) in the valleys' - God's sending of the springs. Qualifier."),
 (269213,"give drink (shaqah)",CRE,"v11: 'they GIVE DRINK (shaqah) to every beast of the field' - God's watering of the beasts. Qualifier."),
 (307304,"water (shaqah)",CRE,"v13: 'From your lofty abode you WATER (shaqah) the mountains' - God's watering. Qualifier."),
 (307309,"work (maaseh)",CRE,"v13: 'the earth is satisfied with the fruit of your WORK (maaseh)' - God's work. Qualifier."),
 (269229,"grow (tsamach)",PRO,"v14: 'You cause the grass to GROW (tsamach) for the livestock' - God's provision of growth. Qualifier."),
 (269235,"bring forth (yatsa)",PRO,"v14: 'to BRING FORTH (yatsa) food from the earth' - God's yielding of food. Qualifier."),
 (269247,"strengthen (saad)",PRO,"v15: 'bread to STRENGTHEN (saad) man's heart' - God's sustaining of man by bread. Qualifier."),
 (307312,"watered abundantly (saba)",CRE,"v16: 'The trees of the LORD are WATERED ABUNDANTLY (saba)' - God's watering of the trees. Qualifier."),
 (307316,"planted (nata)",CRE,"v16: 'the cedars of Lebanon that he PLANTED (nata)' - God's planting. Qualifier."),
 (307324,"made (asah)",CRE,"v19: 'He MADE (asah) the moon to mark the seasons' - God's making of moon and sun. Qualifier."),
 (269256,"make (shith)",CRE,"v20: 'You MAKE (shith) darkness, and it is night' - God's ordering of night. Qualifier."),
 (307341,"made (asah)",CRE,"v24: 'in wisdom have you MADE (asah) them all' - God's making of all creatures. Qualifier."),
 (307340,"wisdom (chokmah)",CRE,"v24: 'In WISDOM (chokmah) have you made them all' - God's wisdom in creation. Qualifier."),
 (269293,"formed (yatsar)",CRE,"v26: 'Leviathan, which you FORMED (yatsar) to play in it' - God's forming of the sea-creature. Qualifier."),
 (269299,"give (nathan)",CRE,"v27: 'to GIVE (nathan) them their food in due season' - God's feeding of all creatures. Qualifier."),
 (305851,"give (nathan)",CRE,"v28: 'When you GIVE (nathan) it to them, they gather it up' - God's giving. Qualifier."),
 (305853,"open (pathach)",CRE,"v28: 'when you OPEN (pathach) your hand, they are filled with good things' - God's open-handed provision. Qualifier."),
 (269302,"hide (sathar)",CRE,"v29: 'When you HIDE (sathar) your face, they are dismayed' - God's withdrawing of his presence. Qualifier."),
 (269305,"take away (asaph)",CRE,"v29: 'when you TAKE AWAY (asaph) their breath, they die' - God's recall of the breath of life. Qualifier."),
 (307347,"send forth (shalach)",CRE,"v30: 'When you SEND FORTH (shalach) your Spirit, they are created' - God's life-giving. Qualifier."),
 (307348,"Spirit (ruach)",CRE,"v30: 'When you send forth your SPIRIT (ruach)' - God's Spirit that creates and renews. Qualifier."),
 (307349,"created (bara)",CRE,"v30: 'they are CREATED (bara)' - God's creating. Qualifier."),
 (307350,"renew (chadash)",CRE,"v30: 'and you RENEW (chadash) the face of the ground' - God's renewal of creation. Qualifier."),
 (269311,"glory (kabod)",CRE,"v31: 'May the GLORY (kabod) of the LORD endure forever' - God's glory. Qualifier."),
 (269315,"rejoice (samach)",CRE,"v31: 'may the LORD REJOICE (samach) in his works' - God's own delight in creation. Qualifier."),
 (269317,"works (maaseh)",CRE,"v31: 'may the LORD rejoice in his WORKS (maaseh)' - God's works. Qualifier."),
 (269318,"looks (nabat)",CRE,"v32: 'who LOOKS (nabat) on the earth and it trembles' - God's glance that shakes the earth. Qualifier."),
 (269321,"touches (naga)",CRE,"v32: 'who TOUCHES (naga) the mountains and they smoke' - God's touch that makes mountains smoke. Qualifier."),
 (269337,"consumed (tamam)",269336,"v35: 'Let sinners be CONSUMED (tamam) from the earth' - God's removal of sinners petitioned. Qualifier."),
]
for sid,sense,src,d in QU: r.qu(sid,sense,src,d)
# ---- STANDALONE: created things / creatures / cosmic features / places / temporal ----
ST=[
 (307250,"light (or)","v2: 'covering yourself with LIGHT (or) as with a garment' - the robe of light, image of God's splendour. Standalone."),
 (307251,"garment (salmah)","v2: 'as with a GARMENT (salmah)' - the light-robe, image. Standalone."),
 (307255,"tent (yeriah)","v2: 'stretching out the heavens like a TENT (yeriah)' - the sky as tent-curtain, image. Standalone."),
 (307257,"chambers (aliyah)","v3: 'the beams of his CHAMBERS (aliyah)' - God's upper rooms on the waters, image. Standalone."),
 (307261,"clouds (ab)","v3: 'he makes the CLOUDS (ab) his chariot' - the storm-clouds, image. Standalone."),
 (307262,"chariot (rekub)","v3: 'the clouds his CHARIOT (rekub)' - God's cloud-chariot, image. Standalone."),
 (307266,"wings (kanaph)","v3: 'on the WINGS (kanaph) of the wind' - the wind's wings, image. Standalone."),
 (307267,"wind (ruach)","v3: 'on the wings of the WIND (ruach)' - the storm-wind God rides, image. Standalone."),
 (307269,"messengers (malak)","v4: 'he makes his MESSENGERS (malak) winds' - the wind-messengers, image. Standalone."),
 (307270,"winds (ruach)","v4: 'his messengers WINDS (ruach)' - the winds as God's agents, image. Standalone."),
 (307271,"ministers (sharath)","v4: 'his MINISTERS (sharath) a flaming fire' - the fire-ministers, image. Standalone."),
 (307272,"flaming (lahat)","v4: 'a FLAMING (lahat) fire' - the fire of God's service, image. Standalone."),
 (307279,"never (olam)","v5: 'so that it should NEVER (olam) be moved' - the perpetuity of the earth's stability; temporal. Standalone."),
 (307282,"deep (tehom)","v6: 'You covered it with the DEEP (tehom)' - the primeval waters, image. Standalone."),
 (307283,"garment (lebush)","v6: 'as with a GARMENT (lebush)' - the deep as a robe, image. Standalone."),
 (307285,"stood (amad)","v6: 'the waters STOOD (amad) above the mountains' - the primeval flood, image. Standalone."),
 (307287,"mountains (har)","v6: 'above the MOUNTAINS (har)' - the mountains under the flood, image. Standalone."),
 (269350,"fled (nus)","v7: 'At your rebuke they FLED (nus)' - the waters fleeing, image. Standalone."),
 (269352,"sound (qol)","v7: 'at the SOUND (qol) of your thunder' - the thunder-voice, image. Standalone."),
 (269353,"thunder (raam)","v7: 'the sound of your THUNDER (raam)' - God's thunder, image. Standalone."),
 (269354,"flight (chaphaz)","v7: 'they took to FLIGHT (chaphaz)' - the waters' hasty retreat, image. Standalone."),
 (269355,"mountains (har)","v8: 'The MOUNTAINS (har) rose, the valleys sank down' - the shaping of the land, image. Standalone."),
 (269356,"rose (alah)","v8: 'the mountains ROSE (alah)' - the mountains lifting, image. Standalone."),
 (269357,"valleys (biqah)","v8: 'the VALLEYS (biqah) sank down' - the valleys settling, image. Standalone."),
 (307291,"pass (abar)","v9: 'a boundary that they may not PASS (abar)' - the limit the waters cannot cross, image. Standalone."),
 (307293,"again (shuv)","v9: 'so that they might not AGAIN (shuv) cover the earth' - the flood not to return, image. Standalone."),
 (307294,"cover (kasah)","v9: 'not again COVER (kasah) the earth' - the waters restrained, image. Standalone."),
 (307296,"springs (mayan)","v10: 'You make SPRINGS (mayan) gush forth' - the springs, image of provision. Standalone."),
 (307298,"valleys (nachal)","v10: 'gush forth in the VALLEYS (nachal)' - the watercourses, image. Standalone."),
 (307299,"flow (halak)","v10: 'they FLOW (halak) between the hills' - the streams, image. Standalone."),
 (307301,"hills (har)","v10: 'between the HILLS (har)' - the hills, image. Standalone."),
 (269216,"field (sadeh)","v11: 'every beast of the FIELD (sadeh)' - the wild beasts' range, image. Standalone."),
 (269217,"wild donkeys (pere)","v11: 'the WILD DONKEYS (pere) quench their thirst' - the wild asses, image of provisioned creatures. Standalone."),
 (269218,"quench (shabar)","v11: 'the wild donkeys QUENCH (shabar) their thirst' - the beasts drinking, image. Standalone."),
 (269220,"thirst (tsama)","v11: 'quench their THIRST (tsama)' - the creatures' thirst met, image. Standalone."),
 (269222,"birds (oph)","v12: 'the BIRDS (oph) of the heavens dwell' - the nesting birds, image. Standalone."),
 (269224,"dwell (shakan)","v12: 'the birds DWELL (shakan) by them' - the birds nesting by the streams, image. Standalone."),
 (269225,"sing (nathan)","v12: 'they SING (nathan) among the branches' - the birdsong, image. Standalone."),
 (269227,"branches (ophi)","v12: 'among the BRANCHES (ophi)' - the boughs, image. Standalone."),
 (307303,"lofty abode (aliyah)","v13: 'From your LOFTY ABODE (aliyah)' - God's upper chambers, image. Standalone."),
 (307305,"mountains (har)","v13: 'you water the MOUNTAINS (har)' - the watered hills, image. Standalone."),
 (307307,"satisfied (saba)","v13: 'the earth is SATISFIED (saba)' - the earth filled by God's provision, image. Standalone."),
 (307308,"fruit (peri)","v13: 'the FRUIT (peri) of your work' - the produce of God's work, image. Standalone."),
 (269228,"grass (chatsir)","v14: 'You cause the GRASS (chatsir) to grow' - the grass for the livestock, image. Standalone."),
 (269231,"plants (eseb)","v14: 'and PLANTS (eseb) for man to cultivate' - the crops, image. Standalone."),
 (269233,"cultivate (abodah)","v14: 'plants for man to CULTIVATE (abodah)' - the tillage, image of man's ordered work. Standalone."),
 (269236,"food (lechem)","v14: 'to bring forth FOOD (lechem) from the earth' - the food, image of provision. Standalone."),
 (269239,"wine (yayin)","v15: 'WINE (yayin) to gladden the heart of man' - the wine, God's gift that gladdens (char, 269240). Standalone."),
 (269243,"oil (shemen)","v15: 'OIL (shemen) to make his face shine' - the oil, gift that brightens the face (char, 269245). Standalone."),
 (269246,"bread (lechem)","v15: 'and BREAD (lechem) to strengthen man's heart' - the bread, gift that sustains the heart (char, 269249). Standalone."),
 (307310,"trees (ets)","v16: 'The TREES (ets) of the LORD are watered abundantly' - the great trees, image. Standalone."),
 (307313,"cedars (erez)","v16: 'the CEDARS (erez) of Lebanon' - the cedars, image. Standalone."),
 (307314,"Lebanon (lebanon)","v16: 'the cedars of LEBANON (lebanon)' - the mountain forest, place. Standalone."),
 (307318,"birds (tsippor)","v17: 'the BIRDS (tsippor) build their nests' - the nesting birds, image. Standalone."),
 (307319,"nests (qanan)","v17: 'the birds build their NESTS (qanan)' - the birds' homes, image. Standalone."),
 (307320,"stork (chasidah)","v17: 'the STORK (chasidah) has her home in the fir trees' - the stork, image. Standalone."),
 (307323,"fir trees (berosh)","v17: 'in the FIR TREES (berosh)' - the firs, image. Standalone."),
 (269251,"mountains (har)","v18: 'The high MOUNTAINS (har) are for the wild goats' - the crags, image. Standalone."),
 (269252,"wild goats (yael)","v18: 'for the WILD GOATS (yael)' - the mountain goats, image. Standalone."),
 (269253,"rocks (sela)","v18: 'the ROCKS (sela) are a refuge for the rock badgers' - the crags, image. Standalone."),
 (269254,"refuge (machseh)","v18: 'the rocks are a REFUGE (machseh) for the rock badgers' - the creatures' shelter, image. Standalone."),
 (269255,"rock badgers (shaphan)","v18: 'for the ROCK BADGERS (shaphan)' - the coneys, image. Standalone."),
 (307325,"moon (yareach)","v19: 'He made the MOON (yareach) to mark the seasons' - the moon, image. Standalone."),
 (307326,"seasons (moed)","v19: 'to mark the SEASONS (moed)' - the appointed times, image. Standalone."),
 (307327,"sun (shemesh)","v19: 'the SUN (shemesh) knows its time for setting' - the sun, image. Standalone."),
 (307328,"knows (yada)","v19: 'the sun KNOWS (yada) its time for setting' - the sun's ordered course, cosmic personification. Standalone."),
 (269257,"darkness (choshek)","v20: 'You make DARKNESS (choshek), and it is night' - the night, image. Standalone."),
 (269262,"forest (yaar)","v20: 'when all the beasts of the FOREST (yaar) creep about' - the woods, image. Standalone."),
 (269263,"creep (ramas)","v20: 'the beasts of the forest CREEP (ramas) about' - the prowling beasts, image. Standalone."),
 (269264,"young lions (kephir)","v21: 'The YOUNG LIONS (kephir) roar for their prey' - the lions, image of provisioned creatures. Standalone."),
 (269265,"roar (shaag)","v21: 'the young lions ROAR (shaag) for their prey' - the lions' cry, image. Standalone."),
 (269266,"prey (tereph)","v21: 'roar for their PREY (tereph)' - the lions' food, image. Standalone."),
 (269267,"seeking (baqash)","v21: 'SEEKING (baqash) their food from God' - the lions seeking, image (creature, not human IB). Standalone."),
 (269269,"food (okel)","v21: 'seeking their FOOD (okel) from God' - the lions' meat, image. Standalone."),
 (307330,"sun (shemesh)","v22: 'When the SUN (shemesh) rises, they steal away' - the dawn, image. Standalone."),
 (307331,"rises (zarach)","v22: 'when the sun RISES (zarach)' - the sunrise, image. Standalone."),
 (307332,"steal away (asaph)","v22: 'they STEAL AWAY (asaph)' - the beasts retreating at dawn, image. Standalone."),
 (307333,"lie down (rabats)","v22: 'and LIE DOWN (rabats) in their dens' - the beasts resting, image. Standalone."),
 (307334,"dens (maon)","v22: 'in their DENS (maon)' - the lairs, image. Standalone."),
 (269273,"goes out (yatsa)","v23: 'Man GOES OUT (yatsa) to his work' - man's daylabour, his ordered place in the diurnal round (parallel to the beasts; an activity, not an inner state). Standalone."),
 (269275,"labor (abodah)","v23: 'to his work and to his LABOUR (abodah) until the evening' - man's toil, his appointed day-work. Standalone."),
 (307337,"manifold (rabab)","v24: 'how MANIFOLD (rabab) are your works!' - the multitude of God's works, image. Standalone."),
 (307338,"works (maaseh)","v24: 'O LORD, how manifold are your WORKS (maaseh)!' - God's works surveyed, image. Standalone."),
 (307344,"full (male)","v24: 'the earth is FULL (male) of your creatures' - the teeming earth, image. Standalone."),
 (307346,"creatures (qinyan)","v24: 'full of your CREATURES (qinyan)' - God's creatures, image. Standalone."),
 (269283,"creatures (remes)","v25: 'living CREATURES (remes) both small and great' - the sea-swarms, image. Standalone."),
 (269284,"innumerable (mispar)","v25: 'creatures INNUMERABLE (mispar)' - the countless sea-life, image. Standalone."),
 (269289,"go (halak)","v26: 'There GO (halak) the ships' - the ships on the sea, image. Standalone."),
 (269290,"ships (oniyah)","v26: 'there go the SHIPS (oniyah)' - the sea-going vessels, image. Standalone."),
 (269291,"Leviathan (livyathan)","v26: 'and LEVIATHAN (livyathan), which you formed to play' - the sea-monster, image. Standalone."),
 (269294,"play (sachaq)","v26: 'which you formed to PLAY (sachaq) in it' - Leviathan's sporting, image (creature, not human IB). Standalone."),
 (269297,"look (sabar)","v27: 'These all LOOK (sabar) to you' - the creatures waiting on God, image. Standalone."),
 (269300,"food (okel)","v27: 'to give them their FOOD (okel) in due season' - the creatures' food, image. Standalone."),
 (305852,"gather up (laqat)","v28: 'they GATHER IT UP (laqat)' - the creatures taking their food, image. Standalone."),
 (305855,"filled (saba)","v28: 'they are FILLED (saba) with good things' - the creatures satisfied, image. Standalone."),
 (305856,"good things (tob)","v28: 'filled with GOOD THINGS (tob)' - the good God provides, image. Standalone."),
 (269304,"dismayed (bahal)","v29: 'you hide your face, they are DISMAYED (bahal)' - the creatures' terror at God's withdrawal, image (creature-reaction). Standalone."),
 (269306,"breath (ruach)","v29: 'when you take away their BREATH (ruach), they die' - the breath of life, image. Standalone."),
 (269307,"die (gava)","v29: 'they DIE (gava) and return to their dust' - the creatures' death, image. Standalone."),
 (269308,"return (shuv)","v29: 'and RETURN (shuv) to their dust' - the return to dust, image. Standalone."),
 (269310,"dust (aphar)","v29: 'return to their DUST (aphar)' - the dust of death, image. Standalone."),
 (269313,"forever (olam)","v31: 'May the glory of the LORD endure FOREVER (olam)' - the perpetuity of God's glory; temporal. Standalone."),
 (269320,"trembles (raad)","v32: 'who looks on the earth and it TREMBLES (raad)' - the earth quaking at God's glance, cosmic reaction. Standalone."),
 (269322,"mountains (har)","v32: 'who touches the MOUNTAINS (har) and they smoke' - the mountains, image. Standalone."),
 (269323,"smoke (ashan)","v32: 'the mountains and they SMOKE (ashan)' - the smoking peaks, image of theophany. Standalone."),
]
for sid,sense,d in ST: r.st(sid,sense,d)
r.write()
