import sys; sys.path.insert(0,'scripts')
from _reread_ledger_lib import Reading, IB, GOD, PER
r=Reading("Psa",19,80,
  note="Ps80 'Restore us, let your face shine, that we may be saved' (Asaph; refrain v3/7/19). Passages: appeal to the Shepherd v1-7; the vine-of-Egypt allegory v8-16; final plea v17-19. Human IB is thin against the God-petitions + vine imagery: the people's PRAYERS God is angry with; the TEARS they eat and drink; being an object of CONTENTION; and the vow not to TURN BACK but to CALL on God's name. God's shepherd/shine/restore/save/stir-might/plant-the-vine acts = qualifiers; vine/branches/boar/walls imagery = standalone.")
r.ch(283766,"prayers (tephillah)","action","your people","pray","to God","paired with the tears they are fed",GOD,
  "v4: 'How long will you be angry with your people's PRAYERS (tephillah)?' - the people's praying, met (they fear) with divine anger; petition itself becomes the ground of the lament.")
r.ch(283769,"tears (dimah)","state","the people","weep","in grief","paired with the tears given as drink",IB,
  "v5: 'You have fed them with the bread of TEARS (dimah)' - the people's weeping become their very sustenance; grief so constant it is eaten as bread.")
r.ch(283774,"object of contention (madon)","state","us (the people)","become a thing fought over","by the neighbours","paired with the enemies' laughter",IB,
  "v6: 'You make us an object of CONTENTION (madon) for our neighbours' - the shame of a people wrangled over and mocked, humiliation felt as an inner wound.")
r.ch(283738,"turn back (sug, negated)","disposition","we (the people)","not turn away","from God","paired with calling on his name",GOD,
  "v18: 'Then we shall not TURN BACK (sug) from you' - the vowed fidelity, the promise not to apostatize if God will but restore.")
r.ch(283741,"call upon (qara)","action","we (the people)","call upon","God's name","paired with the vow not to turn back",GOD,
  "v18: 'give us life, and we will CALL (qara) upon your name' - the promised worship, invocation vowed in exchange for revival.")
# qualifiers
for sid,sense,src,d in [
 (283702,"give ear (azan)",283766,"v1: 'GIVE EAR (azan), O Shepherd of Israel' - God's hearing petitioned. Qualifier."),
 (283703,"Shepherd (raah)",283766,"v1: 'O SHEPHERD (raah) of Israel, you who lead Joseph like a flock' - God as shepherd. Qualifier."),
 (283705,"lead (nahag)",283766,"v1: 'you who LEAD (nahag) Joseph like a flock' - God's leading. Qualifier."),
 (283710,"shine forth (yapha)",283766,"v1: 'you who are enthroned upon the cherubim, SHINE FORTH (yapha)' - God's radiant appearing petitioned. Qualifier."),
 (283754,"stir up (ur)",283757,"v2: 'STIR UP (ur) your might' - God's rousing of his power petitioned. Qualifier."),
 (283755,"might (geburah)",283757,"v2: 'stir up your MIGHT (geburah)' - God's strength. Qualifier."),
 (283757,"save (yeshuah)",283766,"v2: 'and come to SAVE (yeshuah) us' - God's salvation petitioned. Qualifier."),
 (306848,"restore (shuv)",283738,"v3: 'RESTORE (shuv) us, O God' - the refrain's plea for God to turn/restore. Qualifier."),
 (306851,"shine (or)",283738,"v3: 'let your face SHINE (or)' - God's favour petitioned. Qualifier."),
 (306852,"be saved (yasha)",283738,"v3: 'that we may be SAVED (yasha)' - God's deliverance. Qualifier."),
 (283763,"be angry (ashan)",283766,"v4: 'How long will you be ANGRY (ashan) with your people's prayers?' - God's smouldering anger. Qualifier."),
 (283767,"fed (akal)",283769,"v5: 'You have FED (akal) them with the bread of tears' - God's chastening provision. Qualifier."),
 (283771,"give to drink (shaqah)",283769,"v5: 'and given them tears to DRINK (shaqah) in full measure' - God's cup of grief. Qualifier."),
 (283773,"make / set (sim)",283774,"v6: 'You MAKE (sim) us an object of contention' - God's act behind the humiliation. Qualifier."),
 (283779,"restore (shuv)",283738,"v7: 'RESTORE (shuv) us, O God of hosts' - the refrain. Qualifier."),
 (283783,"shine (or)",283738,"v7: 'let your face SHINE (or)' - God's favour. Qualifier."),
 (283784,"be saved (yasha)",283738,"v7: 'that we may be SAVED (yasha)' - God's deliverance. Qualifier."),
 (306853,"brought (nasa)",283774,"v8: 'You BROUGHT (nasa) a vine out of Egypt' - God's planting of Israel. Qualifier."),
 (306856,"drove out (garash)",283774,"v8: 'you DROVE OUT (garash) the nations and planted it' - God's clearing the land. Qualifier."),
 (306858,"planted (nata)",283774,"v8: 'and PLANTED (nata) it' - God's establishing of the vine. Qualifier."),
 (306860,"cleared (panah)",283774,"v9: 'You CLEARED (panah) the ground for it' - God's preparing the land. Qualifier."),
 (306867,"covered (kasah)",283774,"v10: 'The mountains were COVERED (kasah) with its shade' - the vine's God-given flourishing. Qualifier."),
 (283714,"look down (nabat)",283774,"v14: 'LOOK DOWN (nabat) from heaven, and see' - God's regard petitioned. Qualifier."),
 (283717,"have regard (paqad)",283774,"v14: 'have REGARD (paqad) for this vine' - God's attention to his vine petitioned. Qualifier."),
 (283723,"planted (nata)",283774,"v15: 'the stock that your right hand PLANTED (nata)' - God's planting. Qualifier."),
 (283726,"made strong (amets)",283774,"v15: 'the son whom you MADE STRONG (amets) for yourself' - God's strengthening. Qualifier."),
 (306895,"perish (abad)",283774,"v16: 'may they PERISH (abad) at the rebuke of your face' - God's judgment on the ravagers. Qualifier."),
 (306896,"rebuke (gaarah)",283774,"v16: 'at the REBUKE (gaarah) of your face' - God's rebuke. Qualifier."),
 (283735,"made strong (amets)",283738,"v17: 'the son of man whom you have MADE STRONG (amets) for yourself' - God's strengthening of the king. Qualifier."),
 (283740,"give life (chayah)",283741,"v18: 'GIVE US LIFE (chayah)' - God's reviving petitioned. Qualifier."),
 (283742,"name (shem)",283741,"v18: 'we will call upon your NAME (shem)' - God's name. Qualifier."),
 (283743,"restore (shuv)",283738,"v19: 'RESTORE (shuv) us, O LORD God of hosts' - the closing refrain. Qualifier."),
 (283748,"shine (or)",283738,"v19: 'let your face SHINE (or)' - God's favour. Qualifier."),
 (283749,"be saved (yasha)",283738,"v19: 'that we may be SAVED (yasha)' - God's deliverance. Qualifier."),
]: r.qu(sid,sense,src,d)
# standalone
for sid,sense,d in [
 (283698,"Lilies (shoshan)","v1 superscription: 'according to LILIES (shoshan), a Testimony' - the tune/heading. Standalone."),
 (283699,"Testimony (eduth)","v1 superscription: 'a TESTIMONY (eduth) of Asaph' - the heading term. Standalone."),
 (283709,"cherubim (kerub)","v1: 'enthroned upon the CHERUBIM (kerub)' - the throne-place image. Standalone."),
 (283770,"tears (dimah)","v5: 'given them TEARS (dimah) to drink' - the measure of tears as drink, image of the char-grief (283769). Standalone."),
 (283772,"full measure (shalish)","v5: 'tears to drink in FULL MEASURE (shalish)' - the brimming cup, image. Standalone."),
 (283777,"laugh (laag)","v6: 'our enemies LAUGH (laag) among themselves' - the foes' derision, image. Standalone."),
 (306854,"vine (gephen)","v8: 'You brought a VINE (gephen) out of Egypt' - the allegory of Israel as vine. Standalone."),
 (306862,"took deep root (sharash)","v9: 'it TOOK DEEP ROOT (sharash)' - the vine's rooting, image. Standalone."),
 (306863,"root (sheresh)","v9: 'it took deep ROOT (sheresh)' - the vine's root, image. Standalone."),
 (306864,"filled the land (male)","v9: 'and FILLED (male) the land' - the vine's spread, image. Standalone."),
 (306868,"shade (tsel)","v10: 'the mountains were covered with its SHADE (tsel)' - the vine's canopy, image. Standalone."),
 (306871,"branches (anaph)","v10: 'the mighty cedars with its BRANCHES (anaph)' - the vine's boughs, image. Standalone."),
 (306873,"branches (qatsir)","v11: 'It sent out its BRANCHES (qatsir) to the sea' - the vine's reach, image. Standalone."),
 (306875,"shoots (yoneqeth)","v11: 'and its SHOOTS (yoneqeth) to the River' - the vine's tendrils, image. Standalone."),
 (306879,"broken down (parats)","v12: 'Why then have you BROKEN DOWN (parats) its walls' - the vine's ruin, image. Standalone."),
 (306880,"walls (gader)","v12: 'broken down its WALLS (gader)' - the vine's hedge, image. Standalone."),
 (306882,"pass by (abar)","v12: 'so that all who PASS (abar) along the way pluck its fruit' - the exposed vine, image. Standalone."),
 (306884,"pluck (arah)","v12: 'all who pass PLUCK (arah) its fruit' - the plundered vine, image. Standalone."),
 (306885,"boar (chazir)","v13: 'The BOAR (chazir) from the forest ravages it' - the ravaging beast, image of the enemy. Standalone."),
 (306887,"ravages (kirsem)","v13: 'the boar RAVAGES (kirsem) it' - the devastation, image. Standalone."),
 (306888,"move / creatures (ziz)","v13: 'and all that MOVE (ziz) in the field feed on it' - the field-creatures, image. Standalone."),
 (306890,"feed on (raah)","v13: 'feed on (raah) it' - the beasts devouring the vine, image. Standalone."),
 (283711,"again (shuv)","v14: 'Turn AGAIN (shuv), O God of hosts' - the plea to return; temporal/gesture. Standalone."),
 (283719,"vine (gephen)","v14: 'have regard for this VINE (gephen)' - the vine-image, object of God's regard (the qual, 283717). Standalone."),
 (283720,"stock (kannah)","v15: 'the STOCK (kannah) that your right hand planted' - the vine-stem, image. Standalone."),
 (306892,"burned (saraph)","v16: 'They have BURNED (saraph) it with fire' - the vine set aflame by enemies, image. Standalone."),
 (306894,"cut down (kasach)","v16: 'they have cut it DOWN (kasach)' - the felled vine, image. Standalone."),
]: r.st(sid,sense,d)
r.write()
