import sys; sys.path.insert(0,'scripts')
from _reread_ledger_lib import Reading, IB, GOD, PER
r=Reading("Psa",19,92,
  note="Ps92 Sabbath song (15v). Passages: it is good to give thanks + sing v1-4; God's great works/deep thoughts, the stupid don't know, the wicked sprout then perish v5-9; the righteous flourish like a palm, declaring God's uprightness v10-15. IB: GIVE-THANKS + SING-PRAISES + DECLARE God's love; GLAD + SING-FOR-JOY at his works; the STUPID/FOOL who cannot KNOW/UNDERSTAND; the WICKED; the eyes that have SEEN + ears HEARD the enemies' fall; the RIGHTEOUS who flourish; the DECLARing that God is upright. God's steadfast-love/works/thoughts/exalt/scatter-foes/uprightness = qualifiers; grass/palm/oil/old-age imagery = standalone.")
for a in [
 (285157,"give thanks (yadah)","action","the worshipper","give thanks","to the LORD",GOD,"paired with singing praises","v1: 'It is good to GIVE THANKS (yadah) to the LORD' - the fitting worship that opens the Sabbath song, gratitude as the good work of the day."),
 (285160,"sing praises (zamar)","action","the worshipper","sing praises","to God's name",GOD,"paired with giving thanks","v1: 'to SING PRAISES (zamar) to your name, O Most High' - the sung worship of God's name, praise as the day's fit occupation."),
 (285199,"declare (nagad)","action","the worshipper","declare / proclaim","God's steadfast love in the morning",GOD,"paired with declaring his faithfulness","v2: 'to DECLARE (nagad) your steadfast love in the morning' - the proclaiming of God's love, testimony morning and night."),
 (285212,"be glad (samach)","state","the psalmist","be made glad","by God's work",GOD,"paired with singing for joy","v4: 'For you make me GLAD (samach) by your work' - the gladness God's deeds produce, joy at what his hands have done."),
 (285217,"sing for joy (ranan)","action","the psalmist","sing for joy","at the works of God's hands",GOD,"paired with the gladness","v4: 'at the works of your hands I SING FOR JOY (ranan)' - the exultant response to God's works, gladness overflowing into song."),
 (285226,"stupid (baar)","status","the stupid man","be brutish / senseless","unable to know God's works",IB,"paired with the fool's failure to understand","v6: 'The STUPID (baar) man cannot know' - the brutish insensibility that misses God's deep purposes, dullness of heart."),
 (285229,"know (yada, negated)","faculty","the stupid man","fail to know","God's works and thoughts",IB,"paired with the failure to understand","v6: 'The stupid man cannot KNOW (yada); the fool cannot understand this' - the ignorance that cannot read God's dealings."),
 (285230,"fool (kesil)","status","the fool","be a fool","unable to understand God's ways",IB,"paired with the stupid man's ignorance","v6: 'the FOOL (kesil) cannot understand this' - the senseless one blind to God's justice in history."),
 (285232,"understand (bin, negated)","faculty","the fool","fail to understand","God's ways",IB,"paired with the failure to know","v6: 'the fool cannot UNDERSTAND (bin) this' - the want of discernment that misreads the flourishing of the wicked."),
 (285234,"wicked (rasha)","status","the wicked","sprout like grass","doomed to destruction",IB,"paired with the evildoers' brief flourishing","v7: 'that though the WICKED (rasha) sprout like grass' - the godless whose quick flourishing only hastens their ruin, the fool's misreading corrected."),
 (285170,"see (nabat)","action","the psalmist","see / behold","the downfall of his enemies",IB,"paired with hearing their doom","v11: 'My eyes have SEEN (nabat) the downfall of my enemies' - the witnessing of God's vindication, the beholding of justice done."),
 (285174,"hear (shama)","action","the psalmist","hear","the doom of his evil assailants",IB,"paired with seeing their downfall","v11: 'my ears have HEARD (shama) the doom of my evil assailants' - the hearing of the wicked's judgment, vindication confirmed to the senses."),
 (285177,"righteous (tsaddiq)","status","the righteous","flourish like a palm","planted in God's house",IB,"paired with growing like a cedar","v12: 'The RIGHTEOUS (tsaddiq) flourish like the palm tree' - the upright whose God-rooted life bears lasting fruit, set against the grass-like wicked."),
 (285190,"declare (nagad)","action","the aged righteous","declare / proclaim","that the LORD is upright",GOD,"paired with proclaiming God as rock","v15: 'to DECLARE (nagad) that the LORD is upright' - the testimony of the flourishing righteous, their fruitful old age itself proclaiming God's justice."),
]: r.ch(*a)
for sid,sense,src,d in [
 (285161,"name (shem)",285160,"v1: 'to sing praises to your NAME (shem), O Most High' - God's name. Qualifier."),
 (285200,"steadfast love (chesed)",285199,"v2: 'to declare your STEADFAST LOVE (chesed) in the morning' - God's covenant love. Qualifier."),
 (285202,"faithfulness (emunah)",285199,"v2: 'and your FAITHFULNESS (emunah) by night' - God's faithfulness. Qualifier."),
 (285213,"work (poal)",285212,"v4: 'you make me glad by your WORK (poal)' - God's deed. Qualifier."),
 (285215,"works (maaseh)",285217,"v4: 'at the WORKS (maaseh) of your hands' - God's works. Qualifier."),
 (285219,"great (gadal)",285217,"v5: 'How GREAT (gadal) are your works, O LORD!' - God's great deeds. Qualifier."),
 (285220,"works (maaseh)",285217,"v5: 'How great are your WORKS (maaseh)' - God's works. Qualifier."),
 (285223,"thoughts (machashabah)",285217,"v5: 'Your THOUGHTS (machashabah) are very deep!' - God's deep purposes. Qualifier."),
 (285225,"deep (amaq)",285217,"v5: 'Your thoughts are very DEEP (amaq)' - the depth of God's counsel. Qualifier."),
 (285252,"perish (abad)",285234,"v9: 'For behold, your enemies shall PERISH (abad)' - God's judgment on the wicked. Qualifier."),
 (285255,"be scattered (parad)",285234,"v9: 'all evildoers shall be SCATTERED (parad)' - God's scattering of the wicked. Qualifier."),
 (285163,"exalt (rum)",285177,"v10: 'But you have EXALTED (rum) my horn like that of the wild ox' - God's exalting of the righteous. Qualifier."),
 (285166,"pour (balal)",285177,"v10: 'you have POURED (balal) over me fresh oil' - God's anointing/refreshing. Qualifier."),
 (307111,"planted (shathal)",285177,"v13: 'They are PLANTED (shathal) in the house of the LORD' - God's planting of the righteous. Qualifier."),
 (285193,"upright (yashar)",285190,"v15: 'to declare that the LORD is UPRIGHT (yashar)' - God's uprightness. Qualifier."),
 (285194,"rock (tsur)",285190,"v15: 'he is my ROCK (tsur)' - God as rock. Qualifier."),
 (285196,"unrighteousness (avlatah, negated)",285190,"v15: 'and there is no UNRIGHTEOUSNESS (avlatah) in him' - God's perfect justice. Qualifier."),
]: r.qu(sid,sense,src,d)
for sid,sense,d in [
 (285156,"good (tob)","v1: 'It is GOOD (tob) to give thanks to the LORD' - the fittingness of worship, the value-predicate of the thanks (char, 285157). Standalone."),
 (285208,"melody (higgayon)","v3: 'to the MELODY (higgayon) of the lyre' - the instrumental music, worship-medium. Standalone."),
 (285235,"sprout (parach)","v7: 'though the wicked SPROUT (parach) like grass' - the quick growth of the wicked, image. Standalone."),
 (285236,"grass (eseb)","v7: 'sprout like GRASS (eseb)' - the short-lived grass, image of the wicked. Standalone."),
 (285238,"evildoers (paal aven)","v7: 'and all EVILDOERS (paal aven) flourish' - the workers of iniquity, parallel to the wicked (char, 285234). Standalone."),
 (285239,"flourish (tsuts)","v7: 'and all evildoers FLOURISH (tsuts)' - the transient blooming of the wicked, image. Standalone."),
 (285240,"destruction (shamad)","v7: 'they are doomed to DESTRUCTION (shamad) forever' - the ruin appointed the wicked, image. Standalone."),
 (285244,"forever (olam)","v8: 'you, O LORD, are on high FOREVER (olam)' - God's eternal exaltation; temporal descriptor. Standalone."),
 (285254,"evildoers (paal aven)","v9: 'all EVILDOERS (paal aven) shall be scattered' - the workers of iniquity, scattered by God. Standalone."),
 (285164,"horn (qeren)","v10: 'you have exalted my HORN (qeren) like that of the wild ox' - the horn of strength, image of the exalted righteous. Standalone."),
 (285165,"wild ox (reem)","v10: 'like that of the WILD OX (reem)' - the powerful beast, image of strength. Standalone."),
 (285167,"fresh (raanan)","v10: 'you have poured over me FRESH (raanan) oil' - the new oil, image of renewal. Standalone."),
 (285168,"oil (shemen)","v10: 'poured over me fresh OIL (shemen)' - the anointing oil, image of blessing. Standalone."),
 (285171,"enemies (shur)","v11: 'the downfall of my ENEMIES (shur)' - the foes whose fall is seen. Standalone."),
 (285175,"evil (raa)","v11: 'my EVIL (raa) assailants' - the wicked attackers. Standalone."),
 (285176,"assailants (qum)","v11: 'my evil ASSAILANTS (qum, those who rise against)' - the risen foes, the object of the vindication. Standalone."),
 (285178,"flourish (parach)","v12: 'The righteous FLOURISH (parach) like the palm tree' - the flourishing of the righteous, image. Standalone."),
 (285179,"palm tree (tamar)","v12: 'flourish like the PALM TREE (tamar)' - the fruitful palm, image of the righteous. Standalone."),
 (285180,"grow (sagah)","v12: 'and GROW (sagah) like a cedar in Lebanon' - the growth of the righteous, image. Standalone."),
 (307114,"flourish (parach)","v13: 'they FLOURISH (parach) in the courts of our God' - the thriving of the God-planted righteous, image. Standalone."),
 (285184,"bear fruit (nub)","v14: 'They still BEAR FRUIT (nub) in old age' - the fruitful age of the righteous, image. Standalone."),
 (285185,"old age (sebah)","v14: 'they still bear fruit in OLD AGE (sebah)' - the aged righteous, image of enduring life. Standalone."),
 (285187,"sap / full of sap (dashen)","v14: 'they are ever full of SAP (dashen)' - the vigour of the righteous, image. Standalone."),
 (285188,"green (raanan)","v14: 'and GREEN (raanan)' - the verdant life of the righteous, image. Standalone."),
]: r.st(sid,sense,d)
r.write()
