import sys; sys.path.insert(0,'scripts')
from _reread_ledger_lib import Reading, IB, GOD, PER
r=Reading("Psa",19,83,
  note="Ps83 plea against a confederacy of nations (Asaph, 18v). Passages: the plea + the enemies' conspiracy v1-8; the invoked judgment (as Midian, as chaff/fire/tempest) v9-15; the aim - shame that they may seek and KNOW God v16-18. Human IB = the enemies' malice: those who HATE God; the CRAFTY PLANS, the CONSULTing and CONSPIRing with one ACCORD; and (the hoped-for turn) the shame by which they may SEEK, be DISMAYED / in DISGRACE, and KNOW that God alone is Most High. God's be-not-silent / do-to-them-as-Midian / pursue-with-tempest / fill-with-shame = qualifiers; the nation-list, chaff/fire/whirlwind imagery = standalone.")
for a in [
 (283991,"hate (sane)","disposition","those who hate God","hate","God","paired with lifting up their heads",GOD,
  "v2: 'those who HATE (sane) you have raised their heads' - the enemies' enmity toward God himself, hostility grown bold."),
 (283994,"crafty (aram)","disposition","the enemies","scheme cunningly","against God's people","paired with their plans",IB,
  "v3: 'They lay CRAFTY (aram) plans against your people' - the cunning malice of the confederates, calculated hostility."),
 (283995,"plans (sod)","action","the enemies","devise secret plans","against the people","paired with the craft",IB,
  "v3: 'They lay crafty PLANS (sod) against your people' - the secret plotting, malice organized into design."),
 (283998,"consult together (yaats)","action","the enemies","take counsel together","against God's hidden ones","paired with conspiring",IB,
  "v3: 'they CONSULT (yaats) together against your treasured ones' - the collusion of the foes, heads laid together against God's own."),
 (284011,"conspire (yaats)","action","the enemies","conspire","against God","paired with their single accord",IB,
  "v5: 'For they CONSPIRE (yaats) with one accord' - the united scheming, many peoples fused into one hostile will."),
 (284013,"one accord / heart (leb)","disposition","the enemies","be of one heart","against God","paired with the conspiracy",IB,
  "v5: 'they conspire with one ACCORD (leb, heart)' - the single-minded unity of the alliance, hearts joined in enmity."),
 (283971,"seek (baqash)","action","the enemies","seek","God's name","paired with the shame that drives them",GOD,
  "v16: 'Fill their faces with shame, that they may SEEK (baqash) your name, O LORD' - the hoped-for turn, that even the foes' humbling might bend them to seek God."),
 (283974,"be put to shame (bosh)","state","the enemies","be put to shame","before God","paired with being dismayed",IB,
  "v17: 'Let them be PUT TO SHAME (bosh) and dismayed forever' - the enemies' humiliation invoked, disgrace as the outcome of their enmity."),
 (283975,"be dismayed (bahal)","state","the enemies","be dismayed / terrified","under judgment","paired with the shame",IB,
  "v17: 'Let them be put to shame and DISMAYED (bahal) forever' - the panic of the judged foe, terror answering their arrogance."),
 (283978,"perish in disgrace (chapher)","state","the enemies","be disgraced","and perish","paired with the shame and dismay",IB,
  "v17: 'let them perish in DISGRACE (chapher)' - the confounded end of the confederates, honour stripped away."),
 (283979,"know (yada)","action","the enemies","come to know","that God alone is Most High","paired with the shame that teaches it",GOD,
  "v18: 'that they may KNOW (yada) that you alone... are the Most High' - the ultimate aim, that judgment itself would teach the nations who God is."),
]: r.ch(*a)
for sid,sense,src,d in [
 (283947,"keep silence (domi, negated)",283991,"v1: 'O God, do not KEEP SILENCE (domi)' - God's silence, asked to be broken. Qualifier."),
 (283949,"hold peace (charash, negated)",283991,"v1: 'do not hold your PEACE (charash)' - God's inaction petitioned against. Qualifier."),
 (283950,"be still (shaqat, negated)",283991,"v1: 'be not STILL (shaqat), O God' - God asked to act. Qualifier."),
 (306935,"do to them (asah)",283994,"v9: 'DO (asah) to them as you did to Midian' - God's judgment invoked. Qualifier."),
 (306942,"destroyed (shamad)",283994,"v10: 'who were DESTROYED (shamad) at En-dor' - God's past judgment recalled. Qualifier."),
 (283952,"make (shith)",283994,"v11: 'MAKE (shith) their nobles like Oreb and Zeeb' - God's judgment on the leaders invoked. Qualifier."),
 (306953,"make (shith)",283994,"v13: 'MAKE (shith) them like whirling dust' - God's scattering judgment invoked. Qualifier."),
 (283962,"pursue (radaph)",283974,"v15: 'so PURSUE (radaph) them with your tempest' - God's driving judgment. Qualifier."),
 (283965,"terrify (bahal)",283974,"v15: 'and TERRIFY (bahal) them with your hurricane' - God's terror on the foe. Qualifier."),
 (283968,"fill (male)",283971,"v16: 'FILL (male) their faces with shame' - God's act to humble the foe. Qualifier."),
 (283972,"name (shem)",283971,"v16: 'that they may seek your NAME (shem)' - God's name. Qualifier."),
 (283977,"perish (abad)",283979,"v17: 'let them PERISH (abad)' - God's judgment. Qualifier."),
 (283981,"name (shem)",283979,"v18: 'that you alone, whose NAME (shem) is the LORD' - God's name. Qualifier."),
]: r.qu(sid,sense,src,d)
for sid,sense,d in [
 (283990,"uproar (hamah)","v2: 'your enemies make an UPROAR (hamah)' - the tumult of the foes, image. Standalone."),
 (283992,"raised (nasa)","v2: 'have RAISED (nasa) their heads' - the enemies' defiant gesture, image. Standalone."),
 (283993,"heads (rosh)","v2: 'raised their HEADS (rosh)' - the lifted head of arrogance, image. Standalone."),
 (284000,"treasured ones (tsaphan)","v3: 'against your TREASURED ONES (tsaphan)' - God's hidden/protected people, the object of the plot. Standalone."),
 (284003,"wipe out (kachad)","v4: 'Come, let us WIPE THEM OUT (kachad) as a nation' - the enemies' genocidal intent, quoted. Standalone."),
 (284005,"name (shem)","v4: 'that the NAME (shem) of Israel be remembered no more' - Israel's name, object of the plot. Standalone."),
 (284007,"remembered (zakar)","v4: 'be REMEMBERED (zakar) no more' - the erasure the foes intend, quoted. Standalone."),
 (284015,"make (karath)","v5: 'they MAKE (karath) a covenant against you' - the striking of the hostile alliance. Standalone."),
 (284016,"covenant (berith)","v5: 'they make a COVENANT (berith) against you' - the confederacy, the enemy pact. Standalone."),
 (284019,"joined (lavah)","v8: 'Assyria also has JOINED (lavah) them' - the confederate roll, the added ally. Standalone."),
 (284022,"arm (zeroa)","v8: 'they are the ARM (zeroa) of the children of Lot' - the strength lent to the alliance, image. Standalone."),
 (306940,"river / wadi (nachal)","v9: 'as you did... at the RIVER (nachal) Kishon' - the site of Sisera's defeat. Standalone."),
 (306944,"became dung (domen)","v10: 'they BECAME (domen) as dung for the ground' - the fate of the destroyed foe, image. Standalone."),
 (283953,"nobles (nadib)","v11: 'Make their NOBLES (nadib) like Oreb and Zeeb' - the enemy chiefs. Standalone."),
 (283958,"princes (nasik)","v11: 'all their PRINCES (nasik) like Zebah and Zalmunna' - the enemy leaders. Standalone."),
 (306948,"possession (yarash)","v12: 'who said, Let us take POSSESSION (yarash) of the pastures of God' - the foes' land-grab intent, quoted. Standalone."),
 (306954,"whirling dust (galgal)","v13: 'Make them like WHIRLING DUST (galgal)' - the tumbleweed, image of scattering. Standalone."),
 (306956,"chaff (qash)","v13: 'like CHAFF (qash) before the wind' - the driven chaff, image of judgment. Standalone."),
 (306958,"wind (ruach)","v13: 'like chaff before the WIND (ruach)' - the scattering wind, image. Standalone."),
 (306961,"consumes (baar)","v14: 'As fire CONSUMES (baar) the forest' - the devouring fire, image of judgment. Standalone."),
 (306964,"flame (lehabah)","v14: 'as the FLAME (lehabah) sets the mountains ablaze' - the blaze, image. Standalone."),
 (306966,"set ablaze (lahat)","v14: 'sets the mountains ABLAZE (lahat)' - the burning hills, image. Standalone."),
 (283964,"tempest (saar)","v15: 'pursue them with your TEMPEST (saar)' - the storm of judgment, image. Standalone."),
 (283967,"hurricane (suphah)","v15: 'terrify them with your HURRICANE (suphah)' - the whirlwind, image. Standalone."),
 (283970,"shame (qalon)","v16: 'Fill their faces with SHAME (qalon)' - the disgrace God pours on them, the means to the hoped-for seeking (283971). Standalone."),
]: r.st(sid,sense,d)
r.write()
