import sys; sys.path.insert(0,'scripts')
from _reread_ledger_lib import Reading, IB, GOD, PER
r=Reading("Psa",19,89,
  note="Ps89 Davidic-covenant psalm (Ethan, 52v; Book III close). Passages: vow to sing of covenant-love v1-4; hymn to God's incomparable faithfulness + righteous throne + the BLESSED people who walk in his light v5-18; God's oracle establishing David v19-37; the anguished 'but now you have cast off' v38-45; 'how long?... remember' v46-51; doxology v52. Human IB: SING + make KNOWN God's faithfulness; the BLESSED people who KNOW the festal SHOUT, WALK in the light, EXULT in his name; the foes who would OUTWIT/HUMBLE/HATE the king; David's filial CRY 'my Father'; the children who FORSAKE/violate/keep-not the law (their TRANSGRESSION/INIQUITY chastened); the king who BECOMEs a scorn, covered in SHAME, his foes REJOICING; the reflection on human VANITY and mortality (who can LIVE and not see death); the servants MOCKED, the psalmist who BEARs the insults; the enemies who MOCK; the closing BLESSED-be-the-LORD. God's covenant/steadfast-love/faithfulness/establish/exalt/crush-Rahab/rule-the-sea/cast-off/renounce = qualifiers; throne/horn/Rahab/walls/Sheol imagery + names = standalone.")
for a in [
 (284525,"sing (shir)","action","the psalmist","sing","of God's steadfast love forever",GOD,"paired with making known his faithfulness","v1: 'I will SING (shir) of the steadfast love of the LORD forever' - the vow to praise God's covenant love, the psalm's opening resolve."),
 (284531,"make known (yada)","action","the psalmist","make known","God's faithfulness to all generations",PER,"paired with the singing","v1: 'with my mouth I will make KNOWN (yada) your faithfulness to all generations' - the proclaiming of God's covenant faithfulness as testimony."),
 (307038,"blessed (esher)","state","the people","be blessed","who know the festal shout",IB,"paired with knowing the shout and walking in the light","v15: 'BLESSED (esher) are the people who know the festal shout' - the happiness of those who worship God as king."),
 (307040,"know (yada)","disposition","the people","know","the festal shout of God",GOD,"paired with the blessedness and the shout","v15: 'the people who KNOW (yada) the festal shout' - the worship-knowledge of God's people, acquaintance with his acclamation."),
 (307041,"festal shout (teruah)","action","the people","raise the festal shout","to God the king",GOD,"paired with knowing and walking in the light","v15: 'who know the festal SHOUT (teruah)' - the joyful acclamation of God as king, worship as jubilant cry."),
 (307042,"walk (halak)","action","the people","walk","in the light of God's face",GOD,"paired with the festal shout","v15: 'who WALK (halak), O LORD, in the light of your face' - living in God's presence, the blessed life lit by his favour."),
 (284568,"exult (gil)","action","the people","exult / rejoice","in God's name all day",GOD,"paired with being exalted in his righteousness","v16: 'who EXULT (gil) in your name all the day' - the day-long rejoicing of the people in God, joy without ceasing."),
 (284629,"outwit (nasha)","action","the enemy","scheme to outwit","the king","paired with the wicked's attempt to humble him","external:god","v22: 'The enemy shall not OUTWIT (nasha) him' - the foe's cunning against God's anointed, promised to fail."),
 (284632,"humble / afflict (anah)","action","the wicked","seek to humble","the king","paired with the enemy's scheming","external:god","v22: 'the wicked shall not HUMBLE (anah) him' - the wicked's oppression of the anointed, thwarted by God's covenant."),
 (284638,"hate (sane)","disposition","those who hate the king","hate","the king","paired with being struck down",GOD,"v23: 'and strike down those who HATE (sane) him' - the enemies' hostility toward God's anointed."),
 (284645,"cry (qara)","action","David","cry out","to God as Father",GOD,"paired with calling God his Rock","v26: 'He shall CRY (qara) to me, You are my Father, my God' - David's filial appeal, the king's intimate trust in God."),
 (284674,"forsake (azab)","action","David's children","forsake","God's law","paired with not walking in his rules",GOD,"v30: 'If his children FORSAKE (azab) my law' - the apostasy of the sons, abandonment of God's covenant word."),
 (284677,"walk (halak, negated)","action","David's children","fail to walk","in God's rules","paired with forsaking the law",GOD,"v30: 'and do not WALK (halak) according to my rules' - the disobedience of the sons, a life off God's path."),
 (284680,"violate (chalal)","action","David's children","profane / violate","God's statutes","paired with not keeping his commandments",GOD,"v31: 'if they VIOLATE (chalal) my statutes' - the profaning of God's ordinances by the sons."),
 (284683,"keep (shamar, negated)","action","David's children","fail to keep","God's commandments","paired with violating the statutes",GOD,"v31: 'and do not KEEP (shamar) my commandments' - the neglected obedience of the sons."),
 (284686,"transgression (pesha)","state","David's children","bear transgression","chastened by God","paired with their iniquity",IB,"v32: 'then I will punish their TRANSGRESSION (pesha) with the rod' - the sin of the sons, met with fatherly discipline not covenant-rupture."),
 (284688,"iniquity (avon)","state","David's children","bear iniquity","chastened by God","paired with their transgression",IB,"v32: 'and their INIQUITY (avon) with stripes' - the guilt of the sons, chastened but not abandoned."),
 (284759,"become a scorn (cherpah)","state","the king","become","a scorn to his neighbours",IB,"paired with the enemies' rejoicing","v41: 'he has BECOME (cherpah) the scorn of his neighbours' - the king's humiliation, the anointed made a reproach."),
 (284768,"rejoice (samach)","state","the king's enemies","rejoice","over his downfall",IB,"paired with the king's becoming a scorn","v42: 'you have made all his enemies REJOICE (samach)' - the malicious joy of the foes at the king's ruin."),
 (284786,"shame (bushah)","state","the king","be covered with shame","by God","paired with the days of his youth cut short",IB,"v45: 'you have covered him with SHAME (bushah)' - the disgrace laid on the anointed, glory turned to humiliation."),
 (284803,"vanity (shav)","state","all mankind","be created in vanity","transient","paired with the reflection on mortality",IB,"v47: 'For what VANITY (shav) you have created all mankind!' - the frailty and fleetingness of human life, the ground of the plea to remember."),
 (284810,"live (chayah)","state","any man","live","yet not escape death",IB,"paired with the soul unable to escape Sheol","v48: 'What man can LIVE (chayah) and never see death?' - the reflection on mortality, no one delivers his own soul from the grave."),
 (284837,"be mocked (cherpah)","state","God's servants","be mocked / reproached","by the nations",IB,"paired with bearing the insults in the heart","v50: 'Remember, O Lord, how your servants are MOCKED (cherpah)' - the reproach borne by God's people, taunts against the covenant."),
 (284838,"bear (nasa)","action","the psalmist","bear / carry","the insults of the nations in the heart",IB,"paired with the servants' being mocked","v50: 'how I BEAR (nasa) in my heart the insults of all the many nations' - the inward carrying of reproach, humiliation lodged in the heart."),
 (284845,"mock (charaph)","action","the enemies","mock / taunt","God","paired with mocking the anointed's steps",GOD,"v51: 'with which your enemies MOCK (charaph), O LORD' - the foes' scorn directed at God himself."),
 (284848,"mock (charaph)","action","the enemies","mock / taunt","the footsteps of God's anointed","paired with mocking God",GOD,"v51: 'with which they MOCK (charaph) the footsteps of your anointed' - the taunts dogging the king's every step."),
 (284851,"blessed be (barak)","action","the psalmist / all","bless","the LORD forever",GOD,"paired with the everlasting doxology","v52: 'BLESSED (barak) be the LORD forever! Amen and Amen' - the closing doxology, the psalm (and Book III) sealed with praise even out of lament."),
]: r.ch(*a)
QU=[
 (284526,"steadfast love (chesed)",284525,"v1: 'the STEADFAST LOVE (chesed) of the LORD' - God's covenant love, theme of the song."),
 (284532,"faithfulness (emunah)",284531,"v1: 'I will make known your FAITHFULNESS (emunah)' - God's faithfulness."),
 (284604,"steadfast love (chesed)",284525,"v2: 'STEADFAST LOVE (chesed) will be built up forever' - God's enduring love."),
 (284605,"built up (banah)",284525,"v2: 'steadfast love will be BUILT UP (banah) forever' - God's establishing of his love."),
 (284609,"establish (kun)",284525,"v2: 'you will ESTABLISH (kun) your faithfulness in the heavens' - God's fixing of his faithfulness."),
 (284611,"faithfulness (emunah)",284525,"v2: 'establish your FAITHFULNESS (emunah)' - God's faithfulness."),
 (284664,"make (karath)",284645,"v3: 'I have MADE (karath) a covenant with my chosen one' - God's covenant-making."),
 (284665,"covenant (berith)",284645,"v3: 'I have made a COVENANT (berith)' - God's covenant with David."),
 (284668,"sworn (shaba)",284645,"v3: 'I have SWORN (shaba) to David my servant' - God's oath."),
 (284741,"establish (kun)",284645,"v4: 'I will ESTABLISH (kun) your offspring forever' - God's establishing of David's line."),
 (284744,"build (banah)",284645,"v4: 'and BUILD (banah) your throne for all generations' - God's building of the dynasty."),
 (284829,"wonders (pele)",284525,"v5: 'Let the heavens praise your WONDERS (pele)' - God's marvels."),
 (284831,"faithfulness (emunah)",284525,"v5: 'your FAITHFULNESS (emunah) in the assembly of the holy ones' - God's faithfulness."),
 (284859,"be compared (arak)",284525,"v6: 'who in the skies can be COMPARED (arak) to the LORD?' - God's incomparability."),
 (284863,"be like (damah)",284525,"v6: 'who is LIKE (damah) the LORD among the heavenly beings?' - God's uniqueness."),
 (284867,"to be feared (arats)",284525,"v7: 'a God greatly to be FEARED (arats) in the council of the holy ones' - God's awesomeness."),
 (284870,"awesome (yare)",284525,"v7: 'and AWESOME (yare) above all who are around him' - God's awe-inspiring majesty."),
 (284879,"mighty (chasin)",284525,"v8: 'O LORD God of hosts, who is MIGHTY (chasin) as you are?' - God's might."),
 (284881,"faithfulness (emunah)",284525,"v8: 'your FAITHFULNESS (emunah) surrounds you' - God's faithfulness."),
 (284885,"rule (mashal)",284525,"v9: 'You RULE (mashal) the raging of the sea' - God's mastery over chaos."),
 (284891,"still (shabach)",284525,"v9: 'when its waves rise, you STILL (shabach) them' - God's stilling of the sea."),
 (284536,"crush (daka)",284525,"v10: 'You CRUSHED (daka) Rahab like a carcass' - God's defeat of the chaos-monster."),
 (284540,"scatter (pazar)",284525,"v10: 'you SCATTERED (pazar) your enemies with your mighty arm' - God's routing of foes."),
 (284543,"mighty (oz)",284525,"v10: 'with your MIGHTY (oz) arm' - God's strength."),
 (284544,"arm (zeroa)",284525,"v10: 'with your mighty ARM (zeroa)' - God's power."),
 (307036,"founded (yasad)",284525,"v11: 'the world and all that is in it, you have FOUNDED (yasad) them' - God's founding of creation."),
 (284548,"created (bara)",284525,"v12: 'The north and the south, you have CREATED (bara) them' - God's creating."),
 (284552,"name (shem)",284568,"v12: 'Tabor and Hermon joyously praise your NAME (shem)' - God's name."),
 (284553,"mighty (geburah)",284525,"v13: 'You have a MIGHTY (geburah) arm' - God's might."),
 (284554,"arm (zeroa)",284525,"v13: 'you have a mighty ARM (zeroa)' - God's power."),
 (284555,"strong (azaz)",284525,"v13: 'STRONG (azaz) is your hand' - God's strength."),
 (284557,"high (rum)",284525,"v13: 'HIGH (rum) is your right hand' - God's exalted power."),
 (284560,"righteousness (tsedeq)",284568,"v14: 'RIGHTEOUSNESS (tsedeq) and justice are the foundation of your throne' - God's righteousness."),
 (284561,"justice (mishpat)",284568,"v14: 'righteousness and JUSTICE (mishpat)' - God's justice."),
 (284564,"steadfast love (chesed)",284568,"v14: 'STEADFAST LOVE (chesed) and faithfulness go before you' - God's love."),
 (284565,"faithfulness (emeth)",284568,"v14: 'steadfast love and FAITHFULNESS (emeth)' - God's faithfulness."),
 (284566,"go before (qadam)",284568,"v14: 'go BEFORE (qadam) you' - God's attributes attending him."),
 (284569,"name (shem)",284568,"v16: 'who exult in your NAME (shem) all the day' - God's name."),
 (284572,"righteousness (tsedaqah)",284568,"v16: 'and in your RIGHTEOUSNESS (tsedaqah) are exalted' - God's righteousness that lifts the people."),
 (284573,"be exalted (rum)",284568,"v16: 'in your righteousness are EXALTED (rum)' - God's exalting of his people."),
 (284575,"glory (tiphereth)",284568,"v17: 'For you are the GLORY (tiphereth) of their strength' - God as the people's glory."),
 (284576,"strength (oz)",284568,"v17: 'the glory of their STRENGTH (oz)' - God as their strength."),
 (284579,"favor (ratson)",284568,"v17: 'by your FAVOUR (ratson) our horn is exalted' - God's favour."),
 (284581,"be exalted (rum)",284568,"v17: 'our horn is EXALTED (rum)' - God's exalting of the people's horn."),
 (284583,"shield (magen)",284568,"v18: 'For our SHIELD (magen) belongs to the LORD' - God as shield/king. "),
 (284587,"Holy One (qadosh)",284568,"v18: 'our king to the HOLY ONE (qadosh) of Israel' - God's holiness."),
 (284590,"spoke (dabar)",284645,"v19: 'you SPOKE (dabar) in a vision to your godly one' - God's oracle."),
 (284594,"grant (shavah)",284645,"v19: 'I have GRANTED (shavah) help to one who is mighty' - God's giving of help."),
 (284595,"help (ezer)",284645,"v19: 'I have granted HELP (ezer)' - God's help to David."),
 (284597,"mighty (gibbor)",284645,"v19: 'to one who is MIGHTY (gibbor)' - the might God gave David."),
 (284598,"exalt (rum)",284645,"v19: 'I have EXALTED (rum) one chosen from the people' - God's exalting of David."),
 (284599,"chosen (bachar)",284645,"v19: 'one CHOSEN (bachar) from the people' - God's election of David."),
 (284612,"find (matsa)",284645,"v20: 'I have FOUND (matsa) David my servant' - God's finding of David."),
 (284615,"holy (qodesh)",284645,"v20: 'with my HOLY (qodesh) oil I have anointed him' - God's holy oil."),
 (284617,"anoint (mashach)",284645,"v20: 'I have ANOINTED (mashach) him' - God's anointing of David."),
 (284621,"establish (kun)",284645,"v21: 'with whom my hand shall be ESTABLISHED (kun)' - God's steadying hand."),
 (284623,"arm (zeroa)",284645,"v21: 'my ARM (zeroa) also shall strengthen him' - God's strengthening arm."),
 (284625,"strengthen (amets)",284645,"v21: 'my arm shall STRENGTHEN (amets) him' - God's empowering of David."),
 (284634,"crush (kathath)",284638,"v23: 'I will CRUSH (kathath) his foes before him' - God's defeat of David's enemies."),
 (284637,"strike down (nagaph)",284638,"v23: 'and STRIKE DOWN (nagaph) those who hate him' - God's striking of the foes."),
 (284639,"faithfulness (emunah)",284645,"v24: 'My FAITHFULNESS (emunah) and steadfast love shall be with him' - God's faithfulness."),
 (284640,"steadfast love (chesed)",284645,"v24: 'my faithfulness and STEADFAST LOVE (chesed)' - God's covenant love."),
 (284641,"name (shem)",284645,"v24: 'in my NAME (shem) his horn shall be exalted' - God's name."),
 (284643,"be exalted (rum)",284645,"v24: 'his horn shall be EXALTED (rum)' - God's exalting of David's horn."),
 (307046,"set (sim)",284645,"v25: 'I will SET (sim) his hand on the sea' - God's granting David dominion."),
 (284649,"Rock (tsur)",284645,"v26: 'the Rock (tsur) of my salvation' - God as David's rock."),
 (284651,"salvation (yeshuah)",284645,"v26: 'the Rock of my SALVATION (yeshuah)' - God's saving."),
 (284652,"steadfast love (chesed)",284645,"v28: 'My STEADFAST LOVE (chesed) I will keep for him forever' - God's covenant love."),
 (284653,"keep (shamar)",284645,"v28: 'I will KEEP (shamar) for him forever' - God's keeping of his love."),
 (284655,"covenant (berith)",284645,"v28: 'my COVENANT (berith) will stand firm for him' - God's covenant."),
 (284656,"stand firm (aman)",284645,"v28: 'my covenant will STAND FIRM (aman) for him' - God's sure covenant."),
 (284658,"establish (sum)",284645,"v29: 'I will ESTABLISH (sum) his offspring forever' - God's establishing of the line."),
 (284675,"law (torah)",284674,"v30: 'If his children forsake my LAW (torah)' - God's law. "),
 (284678,"rules (mishpat)",284677,"v30: 'do not walk according to my RULES (mishpat)' - God's ordinances."),
 (284681,"statutes (chuqqah)",284680,"v31: 'if they violate my STATUTES (chuqqah)' - God's statutes."),
 (284684,"commandments (mitsvah)",284683,"v31: 'do not keep my COMMANDMENTS (mitsvah)' - God's commands."),
 (284685,"punish (paqad)",284686,"v32: 'then I will PUNISH (paqad) their transgression with the rod' - God's disciplining."),
 (284691,"remove (parar)",284645,"v33: 'but I will not REMOVE (parar) from him my steadfast love' - God's steadfast love not withdrawn."),
 (284694,"steadfast love (chesed)",284645,"v33: 'my STEADFAST LOVE (chesed)' - God's covenant love kept."),
 (284696,"be false (shaqar, negated)",284645,"v33: 'or be FALSE (shaqar) to my faithfulness' - God's unfailing faithfulness."),
 (284698,"faithfulness (emunah)",284645,"v33: 'be false to my FAITHFULNESS (emunah)' - God's faithfulness."),
 (284700,"violate (chalal, negated)",284645,"v34: 'I will not VIOLATE (chalal) my covenant' - God's covenant kept inviolate."),
 (284701,"covenant (berith)",284645,"v34: 'I will not violate my COVENANT (berith)' - God's covenant."),
 (284703,"alter (shanah, negated)",284645,"v34: 'or ALTER (shanah) the word that went forth from my lips' - God's unchanging word."),
 (284707,"sworn (shaba)",284645,"v35: 'Once for all I have SWORN (shaba) by my holiness' - God's oath."),
 (284709,"holiness (qodesh)",284645,"v35: 'I have sworn by my HOLINESS (qodesh)' - God's holiness."),
 (284712,"lie (kazab, negated)",284645,"v35: 'I will not LIE (kazab) to David' - God's truthfulness."),
 (284722,"establish (kun)",284645,"v37: 'Like the moon it shall be ESTABLISHED (kun) forever' - God's establishing of the throne."),
 (284724,"faithful (aman)",284645,"v37: 'a FAITHFUL (aman) witness in the skies' - God's faithful witness."),
 (284729,"cast off (zanach)",284759,"v38: 'But now you have CAST OFF (zanach) and rejected' - God's apparent rejection of the anointed."),
 (284730,"reject (maas)",284759,"v38: 'you have cast off and REJECTED (maas)' - God's rejection."),
 (284731,"be full of wrath (abar)",284759,"v38: 'you are FULL OF WRATH (abar) against your anointed' - God's anger against the king."),
 (284734,"renounce (naar)",284759,"v39: 'You have RENOUNCED (naar) the covenant with your servant' - God's seeming abandonment of the covenant."),
 (284735,"covenant (berith)",284759,"v39: 'you have renounced the COVENANT (berith)' - God's covenant, seemingly spurned."),
 (284738,"defile (chalal)",284759,"v39: 'you have DEFILED (chalal) his crown in the dust' - God's casting down of the crown."),
 (284749,"breach (parats)",284759,"v40: 'You have BREACHED (parats) all his walls' - God's breaking of the king's defences."),
 (284752,"lay in ruins (sim)",284759,"v40: 'you have LAID (sim) his strongholds in ruins' - God's ruining of the strongholds."),
 (284777,"cease (shabath)",284759,"v44: 'You have made his splendour to CEASE (shabath)' - God's ending of the king's glory."),
 (284778,"cast (magar)",284759,"v44: 'and CAST (magar) his throne to the ground' - God's casting down of the throne."),
 (284781,"cut short (qatsar)",284786,"v45: 'You have CUT SHORT (qatsar) the days of his youth' - God's shortening of the king's vigour."),
 (284784,"cover (atah)",284786,"v45: 'you have COVERED (atah) him with shame' - God's clothing the king in disgrace."),
 (284789,"hide (sathar)",284803,"v46: 'How long, O LORD? Will you HIDE (sathar) yourself forever?' - God's hidden face."),
 (284794,"wrath (chemah)",284803,"v46: 'How long will your WRATH (chemah) burn like fire?' - God's anger."),
 (284795,"burn (baar)",284803,"v46: 'will your wrath BURN (baar) like fire?' - God's blazing anger."),
 (284797,"remember (zakar)",284803,"v47: 'REMEMBER (zakar) how short my time is!' - God's mindfulness petitioned."),
 (284804,"create (bara)",284803,"v47: 'for what vanity you have CREATED (bara) all mankind' - God's creating of frail humanity."),
 (284822,"steadfast love (chesed)",284837,"v49: 'Lord, where is your STEADFAST LOVE (chesed) of old' - God's covenant love, seemingly absent."),
 (284824,"faithfulness (emunah)",284837,"v49: 'which by your FAITHFULNESS (emunah) you swore to David?' - God's faithfulness."),
 (284825,"swear (shaba)",284837,"v49: 'which you SWORE (shaba) to David' - God's oath of old."),
 (284834,"remember (zakar)",284837,"v50: 'REMEMBER (zakar), O Lord, how your servants are mocked' - God's remembrance petitioned."),
 (284762,"exalt (rum)",284759,"v42: 'You have EXALTED (rum) the right hand of his foes' - God's lifting of the enemies' hand against the king. Qualifier."),
 (284774,"make stand (qum)",284759,"v43: 'you have not made him STAND (qum) in battle' - God's withholding of victory. Qualifier."),
]
for sid,sense,src,d in QU: r.qu(sid,sense,src,d)
ST=[
 (284528,"forever (olam)","v1: 'the steadfast love of the LORD FOREVER (olam)' - the perpetuity of the theme; temporal. Standalone."),
 (284606,"forever (olam)","v2: 'steadfast love will be built up FOREVER (olam)' - temporal. Standalone."),
 (284671,"servant (ebed)","v3: 'to David my SERVANT (ebed)' - David as God's servant, the covenant partner. Standalone."),
 (284742,"offspring (zera)","v4: 'I will establish your OFFSPRING (zera) forever' - David's line, image of the dynasty. Standalone."),
 (284745,"throne (kisse)","v4: 'and build your THRONE (kisse) for all generations' - the Davidic throne, image. Standalone."),
 (284828,"praise (yadah)","v5: 'Let the HEAVENS praise (yadah) your wonders' - the heavens' praise, cosmic personification. Standalone."),
 (284832,"assembly (qahal)","v5: 'in the ASSEMBLY (qahal) of the holy ones' - the heavenly council, setting. Standalone."),
 (284833,"holy ones (qadosh)","v5: 'the assembly of the HOLY ONES (qadosh)' - the angelic host. Standalone."),
 (284868,"council (sod)","v7: 'in the COUNCIL (sod) of the holy ones' - the divine assembly, setting. Standalone."),
 (284869,"holy ones (qadosh)","v7: 'the council of the HOLY ONES (qadosh)' - the angelic host. Standalone."),
 (284873,"around (sabib)","v7: 'above all who are AROUND (sabib) him' - the heavenly beings surrounding God. Standalone."),
 (284877,"hosts (tsaba)","v8: 'O LORD God of HOSTS (tsaba)' - the heavenly armies; divine title-element. Standalone."),
 (284882,"around (sabib)","v8: 'your faithfulness surrounds (sabib) you' - the encircling faithfulness, image. Standalone."),
 (284886,"raging (geuth)","v9: 'You rule the RAGING (geuth) of the sea' - the tumult of chaos, image. Standalone."),
 (284888,"waves (gal)","v9: 'when its WAVES (gal) rise' - the sea's breakers, image. Standalone."),
 (284889,"rise (sos)","v9: 'when its waves RISE (nasa/sos)' - the surging sea, image. Standalone."),
 (284537,"Rahab (rahab)","v10: 'You crushed RAHAB (rahab) like a carcass' - the chaos-monster, image of God's conquered foe. Standalone."),
 (284538,"carcass (chalal)","v10: 'crushed Rahab like a CARCASS (chalal)' - the slain monster, image. Standalone."),
 (284551,"joyously praise (ranan)","v12: 'Tabor and Hermon JOYOUSLY PRAISE (ranan) your name' - the mountains praising, cosmic personification. Standalone."),
 (284562,"foundation (makon)","v14: 'the FOUNDATION (makon) of your throne' - the base of God's throne, image. Standalone."),
 (284563,"throne (kisse)","v14: 'the foundation of your THRONE (kisse)' - God's throne, image. Standalone."),
 (284580,"horn (qeren)","v17: 'by your favour our HORN (qeren) is exalted' - the horn of strength/dignity, image. Standalone."),
 (284642,"horn (qeren)","v24: 'in my name his HORN (qeren) shall be exalted' - David's horn of strength, image. Standalone."),
 (284586,"king (melek)","v18: 'our KING (melek) to the Holy One of Israel' - the Davidic king. Standalone."),
 (284591,"vision (chazon)","v19: 'you spoke in a VISION (chazon)' - the prophetic vision, medium of the oracle. Standalone."),
 (284592,"godly one (chasid)","v19: 'you spoke in a vision to your GODLY ONE (chasid)' - the prophet/faithful to whom God spoke. Standalone."),
 (284614,"servant (ebed)","v20: 'I have found David my SERVANT (ebed)' - David as God's servant. Standalone."),
 (307050,"rivers (nahar)","v25: 'and his right hand on the RIVERS (nahar)' - the extent of David's dominion, image. Standalone."),
 (307054,"kings (melek)","v27: 'the highest of the KINGS (melek) of the earth' - David's supremacy among kings. Standalone."),
 (284654,"forever (olam)","v28: 'I will keep for him FOREVER (olam)' - the perpetuity of the covenant; temporal. Standalone."),
 (284659,"offspring (zera)","v29: 'I will establish his OFFSPRING (zera) forever' - David's line, image. Standalone."),
 (284661,"throne (kisse)","v29: 'and his THRONE (kisse) as the days of the heavens' - the dynasty, image. Standalone."),
 (284687,"rod (shebet)","v32: 'I will punish their transgression with the ROD (shebet)' - the instrument of discipline, image. Standalone."),
 (284689,"stripes (nega)","v32: 'and their iniquity with STRIPES (nega)' - the blows of chastening, image. Standalone."),
 (284714,"offspring (zera)","v36: 'His OFFSPRING (zera) shall endure forever' - David's line, image. Standalone."),
 (284715,"forever (olam)","v36: 'his offspring shall endure FOREVER (olam)' - temporal. Standalone."),
 (284716,"throne (kisse)","v36: 'his THRONE (kisse) as long as the sun before me' - the dynasty, image. Standalone."),
 (284723,"forever (olam)","v37: 'it shall be established FOREVER (olam)' - temporal. Standalone."),
 (284725,"witness (ed)","v37: 'a faithful WITNESS (ed) in the skies' - the moon as covenant-witness, image. Standalone."),
 (284736,"servant (ebed)","v39: 'the covenant with your SERVANT (ebed)' - David/the king as servant. Standalone."),
 (284739,"crown (nezer)","v39: 'you have defiled his CROWN (nezer) in the dust' - the royal crown, image of the king's dishonour. Standalone."),
 (284751,"walls (gader)","v40: 'You have breached all his WALLS (gader)' - the king's defences, image. Standalone."),
 (284753,"strongholds (mibtsar)","v40: 'you have laid his STRONGHOLDS (mibtsar) in ruins' - the fortresses, image. Standalone."),
 (284754,"ruins (mechittah)","v40: 'laid his strongholds in RUINS (mechittah)' - the rubble, image of ruin. Standalone."),
 (284756,"pass by (abar)","v41: 'All who PASS BY (abar) plunder him' - the passers-by, image of the exposed king. Standalone."),
 (284758,"plunder (shasas)","v41: 'all who pass by PLUNDER (shasas) him' - the pillaging, image. Standalone."),
 (284771,"edge (tsur)","v43: 'you have turned back the EDGE (tsur) of his sword' - the sword's edge, image of lost strength. Standalone."),
 (284772,"sword (chereb)","v43: 'the edge of his SWORD (chereb)' - the king's weapon, image. Standalone."),
 (284775,"battle (milchamah)","v43: 'you have not made him stand in BATTLE (milchamah)' - the war he cannot win, image. Standalone."),
 (284776,"splendor (tohar)","v44: 'You have made his SPLENDOUR (tohar) to cease' - the king's royal glory, image. Standalone."),
 (284779,"throne (kisse)","v44: 'and cast his THRONE (kisse) to the ground' - the dynasty overthrown, image. Standalone."),
 (284799,"short (cheled)","v47: 'Remember how SHORT (cheled) my time is' - the brevity of life; temporal. Standalone."),
 (284812,"see (raah)","v48: 'and never SEE (raah) death' - the dying no one escapes, image. Standalone."),
 (284813,"death (maveth)","v48: 'and never see DEATH (maveth)' - death, image of the human end. Standalone."),
 (284814,"deliver (malat)","v48: 'DELIVER (malat) his soul from the power of Sheol' - the self-rescue no one can achieve, image. Standalone."),
 (284815,"soul (nephesh)","v48: 'deliver his SOUL (nephesh) from the power of Sheol' - the life facing death, the object. Standalone."),
 (284836,"servants (ebed)","v50: 'how your SERVANTS (ebed) are mocked' - God's people, the mocked (the char, 284837). Standalone."),
 (284839,"heart (cheq)","v50: 'how I bear in my HEART (cheq, bosom) the insults' - the bosom where reproach is carried (seat of the char bear, 284838). Standalone."),
 (284849,"footsteps (aqeb)","v51: 'they mock the FOOTSTEPS (aqeb) of your anointed' - the king's every step, image of the pursuing scorn. Standalone."),
 (284853,"forever (olam)","v52: 'Blessed be the LORD FOREVER (olam)!' - the perpetuity of the doxology; temporal. Standalone."),
]
for sid,sense,d in ST: r.st(sid,sense,d)
r.write()
