import sys; sys.path.insert(0,'scripts')
from _reread_ledger_lib import Reading, IB, GOD, PER
r=Reading("Psa",19,111,
  note="Ps111 acrostic praise of God's works (10v). Human IB threads through the God-praise: A whole-HEART thanks-GIVING among the UPRIGHT v1; B the works STUDIED by those who DELIGHT in them v2; C those who FEAR God, provided for v5; D coda - the FEAR of the LORD is the beginning of WISDOM, all who PRACTICE it have good UNDERSTANDING v10. God's works/splendor/righteousness/gracious-merciful/covenant/redemption/holy-awesome = qualifiers; congregation/food/temporal = standalone.")
CH=[
 (270562,"praise (halal)","action","the psalmist","praise","the LORD",GOD,"paired with giving thanks",
  "v1: 'PRAISE (halal) the LORD! I will give thanks to the LORD with my whole heart' - the opening Hallelujah, worship of the whole self."),
 (270564,"give thanks (yadah)","action","the psalmist","give thanks","to the LORD with the whole heart",GOD,"paired with the whole heart and the upright",
  "v1: 'I will GIVE THANKS (yadah) to the LORD with my whole heart' - undivided gratitude, thanks from the entire inner self."),
 (270567,"heart (lebab)","faculty","the psalmist","give thanks","with the whole heart",IB,"paired with the thanksgiving",
  "v1: 'with my whole HEART (lebab)' - the entire inner self engaged in praise, no part withheld."),
 (270570,"upright (yashar)","status","the upright","gather","to praise God",IB,"paired with the thanksgiving in the assembly",
  "v1: 'in the company of the UPRIGHT (yashar), in the congregation' - the righteous among whom the psalmist gives thanks, the fellowship of the godly."),
 (270586,"study (darash)","action","those who delight","study / seek out","the works of the LORD",GOD,"paired with delighting in them",
  "v2: 'Great are the works of the LORD, STUDIED (darash) by all who delight in them' - the searching-out of God's works by those who love them, worship as inquiry."),
 (270588,"delight (chephets)","disposition","those who study","delight","in God's works",GOD,"paired with studying them",
  "v2: 'studied by all who DELIGHT (chephets) in them' - the pleasure in God's works that drives the study, love that seeks to know."),
 (270603,"fear (yare)","disposition","those who fear God","fear / revere","God",GOD,"paired with God's provision and remembered covenant",
  "v5: 'He provides food for those who FEAR (yare) him' - the reverent, for whom God provides and whose covenant he keeps."),
 (270572,"fear (yirah)","disposition","the wise","fear / revere","God",GOD,"paired with wisdom and understanding",
  "v10: 'The FEAR (yirah) of the LORD is the beginning of wisdom' - reverence for God as the foundation of all true wisdom, the psalm's climax."),
 (270575,"wisdom (chokmah)","disposition","the God-fearing","gain wisdom","from fearing God",IB,"paired with the fear of the LORD",
  "v10: 'the beginning of WISDOM (chokmah)' - the wisdom that flows from the fear of God, its root and source."),
 (270577,"practice (asah)","action","the God-fearing","practise","the fear of the LORD",GOD,"paired with good understanding",
  "v10: 'all those who PRACTISE (asah) it have a good understanding' - the doing of God's fear, wisdom proved by a life that lives it."),
 (270579,"understanding (sekel)","disposition","those who practise God's fear","have understanding","of God's ways",IB,"paired with practising",
  "v10: 'have a good UNDERSTANDING (sekel)' - the discernment God gives those who live in his fear, wisdom's fruit."),
]
for a in CH: r.ch(*a)
GA=270588; GB=270603; GC=270572
QU=[
 (270584,"works (maaseh)",GA,"v2: 'Great are the WORKS (maaseh) of the LORD' - God's works. Qualifier."),
 (270589,"splendor (hod)",GA,"v3: 'Full of SPLENDOUR (hod) and majesty is his work' - God's splendour. Qualifier."),
 (270590,"majesty (hadar)",GA,"v3: 'splendour and MAJESTY (hadar)' - God's majesty. Qualifier."),
 (270591,"work (poal)",GA,"v3: 'is his WORK (poal)' - God's work. Qualifier."),
 (270592,"righteousness (tsedaqah)",GA,"v3: 'his RIGHTEOUSNESS (tsedaqah) endures forever' - God's righteousness. Qualifier."),
 (270593,"endures (amad)",GA,"v3: 'his righteousness ENDURES (amad) forever' - the permanence of God's righteousness. Qualifier."),
 (270595,"caused to be remembered (asah)",GA,"v4: 'He has CAUSED (asah) his wondrous works to be remembered' - God's memorializing of his deeds. Qualifier."),
 (270596,"wondrous works (pele)",GA,"v4: 'his WONDROUS WORKS (pele)' - God's marvels. Qualifier."),
 (270597,"remembered (zeker)",GA,"v4: 'to be REMEMBERED (zeker)' - the memorial of God's works. Qualifier."),
 (270599,"gracious (chanun)",GB,"v4: 'the LORD is GRACIOUS (chanun) and merciful' - God's grace. Qualifier."),
 (270600,"merciful (rachum)",GB,"v4: 'gracious and MERCIFUL (rachum)' - God's mercy. Qualifier."),
 (270601,"provides (nathan)",GB,"v5: 'He PROVIDES (nathan) food for those who fear him' - God's provision. Qualifier."),
 (270605,"remembers (zakar)",GB,"v5: 'he REMEMBERS (zakar) his covenant forever' - God's faithful remembrance. Qualifier."),
 (270607,"covenant (berith)",GB,"v5: 'he remembers his COVENANT (berith) forever' - God's covenant. Qualifier."),
 (270610,"shown (nagad)",GB,"v6: 'He has SHOWN (nagad) his people the power of his works' - God's revealing of his power. Qualifier."),
 (270613,"works (maaseh)",GB,"v6: 'the power of his WORKS (maaseh)' - God's works. Qualifier."),
 (270615,"giving (nathan)",GB,"v6: 'in GIVING (nathan) them the inheritance of the nations' - God's gift of the land. Qualifier."),
 (270616,"inheritance (nachalah)",GB,"v6: 'the INHERITANCE (nachalah) of the nations' - God's gift of the nations' land. Qualifier."),
 (270618,"works (maaseh)",GB,"v7: 'The WORKS (maaseh) of his hands are faithful and just' - God's works. Qualifier."),
 (270620,"faithful (emeth)",GB,"v7: 'are FAITHFUL (emeth) and just' - the faithfulness of God's works. Qualifier."),
 (270621,"just (mishpat)",GB,"v7: 'faithful and JUST (mishpat)' - the justice of God's works. Qualifier."),
 (270624,"precepts (piqqud)",GB,"v7: 'all his PRECEPTS (piqqud) are trustworthy' - God's precepts. Qualifier."),
 (270625,"trustworthy (aman)",GB,"v7: 'all his precepts are TRUSTWORTHY (aman)' - the reliability of God's precepts. Qualifier."),
 (270626,"established (samak)",GB,"v8: 'they are ESTABLISHED (samak) forever and ever' - God's establishing of his precepts. Qualifier."),
 (270629,"performed (asah)",GB,"v8: 'to be PERFORMED (asah) with faithfulness and uprightness' - God's precepts done in faithfulness. Qualifier."),
 (270630,"faithfulness (emeth)",GB,"v8: 'with FAITHFULNESS (emeth)' - God's faithfulness. Qualifier."),
 (270631,"uprightness (yashar)",GB,"v8: 'and UPRIGHTNESS (yashar)' - God's uprightness. Qualifier."),
 (270632,"sent (shalach)",GB,"v9: 'He SENT (shalach) redemption to his people' - God's redemption. Qualifier."),
 (270633,"redemption (peduth)",GB,"v9: 'He sent REDEMPTION (peduth)' - God's redemption. Qualifier."),
 (270636,"commanded (tsavah)",GB,"v9: 'he has COMMANDED (tsavah) his covenant forever' - God's covenant established. Qualifier."),
 (270637,"covenant (berith)",GB,"v9: 'his COVENANT (berith) forever' - God's covenant. Qualifier."),
 (270639,"holy (qadosh)",GB,"v9: 'HOLY (qadosh) and awesome is his name!' - God's holiness. Qualifier."),
 (270640,"awesome (yare)",GB,"v9: 'Holy and AWESOME (yare) is his name!' - God's awesomeness. Qualifier."),
 (270642,"name (shem)",GB,"v9: 'is his NAME (shem)!' - God's name. Qualifier."),
 (270580,"praise (tehillah)",GC,"v10: 'His PRAISE (tehillah) endures forever!' - God's praiseworthiness. Qualifier."),
 (270581,"endures (amad)",GC,"v10: 'His praise ENDURES (amad) forever!' - the permanence of God's praise. Qualifier."),
]
for sid,sense,src,d in QU: r.qu(sid,sense,src,d)
ST=[
 (270569,"company (sod)","v1: 'in the COMPANY (sod) of the upright' - the intimate assembly of the godly, setting (char upright, 270570). Standalone."),
 (270571,"congregation (edah)","v1: 'in the CONGREGATION (edah)' - the assembly of worship, setting. Standalone."),
 (270602,"food (tereph)","v5: 'He provides FOOD (tereph) for those who fear him' - the provision for the God-fearing (char fear, 270603), image. Standalone."),
 (270608,"forever (olam)","v5: 'he remembers his covenant FOREVER (olam)' - the perpetuity of the covenant; temporal. Standalone."),
 (270628,"ever (ad)","v8: 'established forever and EVER (ad)' - the endlessness of God's precepts; temporal. Standalone."),
 (270638,"forever (olam)","v9: 'he has commanded his covenant FOREVER (olam)' - the perpetuity of the covenant; temporal. Standalone."),
 (270574,"beginning (reshith)","v10: 'the BEGINNING (reshith) of wisdom' - the starting-point, the fear of God as wisdom's foundation (char wisdom, 270575). Standalone."),
 (270578,"good (tob)","v10: 'have a GOOD (tob) understanding' - the quality of the understanding (char understanding, 270579). Standalone."),
]
for sid,sense,d in ST: r.st(sid,sense,d)
r.write()
