import sys; sys.path.insert(0,'scripts')
from _reread_ledger_lib import Reading, IB, GOD, PER
r=Reading("Psa",19,132,
  note="Ps132 the Davidic covenant / ark to Zion (18v). Human IB: David's ENDURED hardship + his consuming VOW (SWORE/VOWED to find a place for the LORD before resting); the people who HEARD of the ark + WORSHIP at his footstool; the priests' RIGHTEOUSNESS, the SAINTS who SHOUT for JOY (x2); the sons who KEEP the covenant; the POOR God satisfies. God's oath/choose-Zion/bless/clothe-salvation = qualifiers; ark/throne/horn/lamp imagery = standalone.")
CH=[
 (272893,"endure hardship (anah)","state","David","afflict himself / endure","for God's house",IB,"paired with his vow to house the ark",
  "v1: 'Remember... all the hardships he ENDURED (anah)' - the operation of consuming devotion: David's self-affliction, the hardship he bore for the sake of housing God."),
 (272959,"swear (shaba)","action","David","swear a vow","to house the ark",GOD,"paired with the vow to the Mighty One",
  "v2: 'how he SWORE (shaba) to the LORD' - the operation of a binding resolve: David's oath, devotion sworn into an unbreakable vow."),
 (272961,"vow (nadar)","action","David","vow","to the Mighty One of Jacob",GOD,"paired with his oath",
  "v2: 'and VOWED (nadar) to the Mighty One of Jacob' - the vow that would not let him rest or sleep until he found a place for the LORD."),
 (272972,"hear (shama)","action","the people","hear of the ark","and seek it",GOD,"paired with going to worship",
  "v6: 'We HEARD (shama) of it in Ephrathah' - the people's report of the ark, the hearing that moves them to seek and worship."),
 (272979,"worship (shachah)","action","the people","worship","at God's footstool",GOD,"paired with the resting-place of the ark",
  "v7: 'Let us go to his dwelling place; let us WORSHIP (shachah) at his footstool!' - the operation of homage: the people bowing at the place of God's presence."),
 (272989,"righteousness (tsedeq)","disposition","the priests","be clothed with righteousness","in service",IB,"paired with the saints' joy",
  "v9: 'Let your priests be clothed with RIGHTEOUSNESS (tsedeq)' - the priests' rightness, the virtue that fits them to minister."),
 (272990,"saints (chasid)","status","the saints","shout for joy","before God",IB,"paired with the shout of joy",
  "v9: 'and let your SAINTS (chasid) shout for joy' - the godly, whose response to God's presence is jubilant."),
 (272991,"shout for joy (ranan)","action","the saints","shout for joy","at God's dwelling",GOD,"paired with the saints",
  "v9: 'let your saints SHOUT FOR JOY (ranan)' - the operation of jubilation: joy bursting into shout at the ark's coming to rest."),
 (272916,"keep (shamar)","action","David's sons","keep","God's covenant",GOD,"paired with the throne promised",
  "v12: 'If your sons KEEP (shamar) my covenant' - the sons' keeping, the condition on which the enduring throne hangs."),
 (307869,"poor (ebyon)","status","the poor of Zion","be satisfied","with bread by God",IB,"paired with God satisfying them",
  "v15: 'I will satisfy her POOR (ebyon) with bread' - the needy of Zion, whom God fills; the low lifted at the place of his rest."),
 (272943,"saints (chasid)","status","the saints","shout for joy","at God's salvation",IB,"paired with the shout of joy",
  "v16: 'her SAINTS (chasid) will shout for joy' - the godly of Zion, jubilant at the salvation that clothes them."),
 (272944,"shout (ranan)","action","the saints","shout","for joy",GOD,"paired with the joy",
  "v16: 'her saints will SHOUT (ranan) for joy' - the shout of the saints, worship overflowing at God's blessing."),
 (272945,"joy (ranan)","state","the saints","rejoice","in God's salvation",IB,"paired with the shout",
  "v16: 'will shout for JOY (ranan)' - the joy itself, the gladness that voices the shout."),
]
for a in CH: r.ch(*a)
QU=[
 (272889,"remember (zakar)",272893,"v1: 'REMEMBER (zakar), O LORD, in David's favour' - God's remembrance petitioned. Qualifier."),
 (305879,"give (nathan)",272959,"v4: 'I will not GIVE (nathan) sleep to my eyes' - David's vow-content (God's-arena); the sworn abstention. Qualifier."),
 (272974,"found (matsa)",272972,"v6: 'we FOUND (matsa) it in the fields of Jaar' - the finding of the ark. Qualifier."),
 (272981,"arise (qum)",272979,"v8: 'ARISE (qum), O LORD, and go to your resting place' - God's rising to enter his rest. Qualifier."),
 (272988,"clothed (labesh)",272989,"v9: 'Let your priests be CLOTHED (labesh) with righteousness' - God's clothing of the priests. Qualifier."),
 (272898,"turn away (shuv)",272893,"v10: 'do not TURN AWAY (shuv) the face of your anointed' - God's not-rejecting the king. Qualifier."),
 (272903,"swore (shaba)",272916,"v11: 'The LORD SWORE (shaba) to David a sure oath' - God's oath to David. Qualifier."),
 (272905,"sure oath (emeth)",272916,"v11: 'a SURE OATH (emeth) from which he will not turn back' - God's true, firm oath. Qualifier."),
 (272907,"turn back (shuv)",272916,"v11: 'from which he will not TURN BACK (shuv)' - God's unbreakable oath. Qualifier."),
 (272911,"set (shith)",272916,"v11: 'I will SET (shith) on your throne the fruit of your body' - God's establishing of the line. Qualifier."),
 (272917,"covenant (berith)",272916,"v12: 'If your sons keep my COVENANT (berith)' - God's covenant. Qualifier."),
 (272918,"testimonies (edut)",272916,"v12: 'and my TESTIMONIES (edut) that I shall teach them' - God's testimonies. Qualifier."),
 (272920,"teach (lamad)",272916,"v12: 'that I shall TEACH (lamad) them' - God's teaching. Qualifier."),
 (272924,"sit (yashab)",272916,"v12: 'their sons also forever shall SIT (yashab) on your throne' - God's granting of the throne. Qualifier."),
 (272928,"chosen (bachar)",272943,"v13: 'For the LORD has CHOSEN (bachar) Zion' - God's election of Zion. Qualifier."),
 (272930,"desired (avah)",272943,"v13: 'he has DESIRED (avah) it for his dwelling place' - God's desire for Zion. Qualifier."),
 (272937,"dwell (yashab)",272943,"v14: 'here I will DWELL (yashab), for I have desired it' - God's dwelling in Zion. Qualifier."),
 (272938,"desired (avah)",272943,"v14: 'for I have DESIRED (avah) it' - God's desire for Zion. Qualifier."),
 (307865,"abundantly (barak)",307869,"v15: 'I will ABUNDANTLY (barak) bless her provisions' - God's abundant blessing. Qualifier."),
 (307866,"bless (barak)",307869,"v15: 'I will abundantly BLESS (barak) her provisions' - God's blessing of Zion. Qualifier."),
 (307868,"satisfy (saba)",307869,"v15: 'I will SATISFY (saba) her poor with bread' - God's satisfying of the poor. Qualifier."),
 (272941,"clothe (labesh)",272943,"v16: 'Her priests I will CLOTHE (labesh) with salvation' - God's clothing of the priests. Qualifier."),
 (272942,"salvation (yesha)",272943,"v16: 'clothe with SALVATION (yesha)' - God's salvation. Qualifier."),
 (272948,"sprout (tsamach)",272943,"v17: 'There I will make a horn to SPROUT (tsamach) for David' - God's raising of David's horn. Qualifier."),
 (272950,"prepared (arak)",272943,"v17: 'I have PREPARED (arak) a lamp for my anointed' - God's preparing of the lamp. Qualifier."),
 (272955,"clothe (labesh)",272893,"v18: 'His enemies I will CLOTHE (labesh) with shame' - God's shaming of the foes. Qualifier."),
 (272958,"shine (tsuts)",272893,"v18: 'but on him his crown will SHINE (tsuts)' - God's crowning of the king. Qualifier."),
]
for sid,sense,src,d in QU: r.qu(sid,sense,src,d)
for sid,sense,d in [
 (272888,"Ascents (maalah)","v0: heading. Standalone."),
 (307862,"get into (alah)","v3: 'I will not GET INTO (alah) my house' - David's vowed abstention, image. Standalone."),
 (307864,"bed (eres)","v3: 'or get into my BED (eres)' - the rest David denies himself, image. Standalone."),
 (305880,"sleep (shenah)","v4: 'I will not give SLEEP (shenah) to my eyes' - the sleep vowed away, image. Standalone."),
 (305882,"slumber (tenumah)","v4: 'or SLUMBER (tenumah) to my eyelids' - the rest renounced, image. Standalone."),
 (305883,"eyelids (aphaph)","v4: 'or slumber to my EYELIDS (aphaph)' - the tired eyes David denies, image. Standalone."),
 (272965,"find (matsa)","v5: 'until I FIND (matsa) a place for the LORD' - the object of David's vow, image. Standalone."),
 (272975,"fields (sadeh)","v6: 'we found it in the FIELDS (sadeh) of Jaar' - the place the ark was found, image. Standalone."),
 (272980,"footstool (hadom)","v7: 'let us worship at his FOOTSTOOL (hadom)' - the ark/place of worship, image. Standalone."),
 (272983,"resting place (menuchah)","v8: 'go to your RESTING PLACE (menuchah)' - the place of the ark's rest, image. Standalone."),
 (272985,"ark (aron)","v8: 'you and the ARK (aron) of your might' - the ark of the covenant, image. Standalone."),
 (272986,"might (oz)","v8: 'the ark of your MIGHT (oz)' - the ark as sign of God's power, image. Standalone."),
 (272901,"anointed (mashiach)","v10: 'the face of your ANOINTED (mashiach)' - the king, David's line, image. Standalone."),
 (272909,"sons / fruit (peri)","v11: 'the fruit (peri) of your body' - David's offspring, image. Standalone."),
 (272910,"body (beten)","v11: 'the fruit of your BODY (beten)' - David's line, image. Standalone."),
 (272913,"throne (kisse)","v11: 'I will set on your THRONE (kisse)' - the Davidic throne, image. Standalone."),
 (272926,"throne (kisse)","v12: 'shall sit on your THRONE (kisse)' - the dynasty, image. Standalone."),
 (272932,"dwelling place (moshab)","v13: 'he has desired it for his DWELLING PLACE (moshab)' - Zion as God's seat, image. Standalone."),
 (272934,"resting place (menuchah)","v14: 'This is my RESTING PLACE (menuchah) forever' - Zion as God's rest, image. Standalone."),
 (307867,"provisions (tsayid)","v15: 'I will abundantly bless her PROVISIONS (tsayid)' - Zion's food, image of blessing. Standalone."),
 (307870,"bread (lechem)","v15: 'satisfy her poor with BREAD (lechem)' - the food for the poor (char poor, 307869), image. Standalone."),
 (272947,"horn (qeren)","v17: 'I will make a HORN (qeren) to sprout for David' - the horn of Davidic strength, image. Standalone."),
 (272951,"lamp (ner)","v17: 'I have prepared a LAMP (ner) for my anointed' - the lamp of the dynasty, image. Standalone."),
 (272953,"anointed (mashiach)","v17: 'a lamp for my ANOINTED (mashiach)' - the Davidic king, image. Standalone."),
 (272956,"shame (bosheth)","v18: 'His enemies I will clothe with SHAME (bosheth)' - the disgrace on the foes, image. Standalone."),
 (272957,"crown (nezer)","v18: 'but on him his CROWN (nezer) will shine' - the Davidic crown, image. Standalone."),
]: r.st(sid,sense,d)
r.write()
