import sys; sys.path.insert(0,'scripts')
from _reread_ledger_lib import Reading, IB, GOD, PER
r=Reading("Psa",19,102,
  note="Ps102 'A prayer of one afflicted, when faint' (28v). Passages: hear my prayer v1-2; the affliction - days like smoke, heart withered, groaning, taunted, ashes and tears, God's indignation v3-11; but you are enthroned forever, you will have pity on Zion, the nations will fear, the destitute's prayer regarded v12-22; my strength broken, days cut short, but you endure, your servants' children dwell secure v23-28. IB: the AFFLICTED/FAINT one's COMPLAINT/PRAYER/CRY, the CALL; days PASS-AWAY, HEART WITHERED, FORGET to eat, GROANING, TAUNTED/DERIDED, TEARS, WITHER-AWAY; the servants who HOLD Zion dear + PITY her dust; nations FEAR; the DESTITUTE's PRAYER (x2) regarded; the vow to PRAISE/DECLARE/WORSHIP; the prisoners' GROANS. God's hear/incline/pity/favor/build-Zion/regard/endure = qualifiers; smoke/owl/sparrow/ashes/garment imagery = standalone.")
CH=[
 (268890,"afflicted (ani)","status","the psalmist","be afflicted","before God",IB,"paired with being faint","v1: 'A prayer of one AFFLICTED (ani), when he is faint' - the sufferer whose whole prayer rises from affliction."),
 (268892,"faint (ataph)","state","the psalmist","grow faint","under affliction",IB,"paired with being afflicted","v1: 'when he is FAINT (ataph) and pours out his complaint' - the swooning weakness from which the lament pours."),
 (268894,"complaint (siach)","action","the psalmist","pour out complaint","before God",GOD,"paired with the prayer and cry","v1: 'and pours out his COMPLAINT (siach) before the LORD' - the outpoured lament, grief laid before God."),
 (268898,"prayer (tephillah)","action","the psalmist","pray","to God",GOD,"paired with the cry","v1: 'Hear my PRAYER (tephillah), O LORD' - the petition begging God's ear."),
 (268900,"cry (shava)","action","the psalmist","cry for help","to God",GOD,"paired with the prayer","v1: 'let my CRY (shava) come to you!' - the loud plea reaching for God."),
 (268978,"call (qara)","action","the psalmist","call","to God in distress",GOD,"paired with the plea for a speedy answer","v2: 'in the day when I CALL (qara), answer me speedily!' - the urgent calling in the day of distress."),
 (269024,"pass away (kalah)","state","the psalmist","have his days pass away","like smoke",IB,"paired with the burning bones","v3: 'For my days PASS AWAY (kalah) like smoke' - the vanishing of life, days dissolving like smoke in the affliction."),
 (302589,"heart (leb)","faculty","the psalmist","be struck down and withered","like grass",IB,"paired with forgetting to eat","v4: 'My HEART (leb) is struck down like grass and has withered' - the inner self blighted by grief, the heart dried up."),
 (302592,"withered (yabesh)","state","the psalmist","be withered","in heart",IB,"paired with the struck-down heart","v4: 'like grass and has WITHERED (yabesh)' - the drying-up of the heart, vitality gone in the affliction."),
 (302594,"forget (shakach)","state","the psalmist","forget to eat","his bread",IB,"paired with the withered heart","v4: 'I FORGET (shakach) to eat my bread' - the loss of appetite in deep grief, affliction that consumes even hunger."),
 (269033,"groaning (anachah)","action","the psalmist","groan aloud","in affliction",IB,"paired with the wasted flesh","v5: 'Because of my loud GROANING (anachah) my bones cling to my flesh' - the constant groaning of the sufferer, grief worn into the body."),
 (269041,"be taunted (charaph)","state","the psalmist","be taunted","by enemies all day",IB,"paired with being derided","v8: 'All the day my enemies TAUNT (charaph) me' - the ceaseless reproach the sufferer endures from his foes."),
 (269042,"be derided (halal)","state","the psalmist","be mocked","his name a curse",IB,"paired with the taunting","v8: 'those who DERIDE (halal) me use my name for a curse' - the sufferer's name become a byword, mockery at its cruelest."),
 (269049,"tears (beki)","state","the psalmist","weep","mingling tears with drink",IB,"paired with eating ashes","v9: 'and mingle TEARS (beki) with my drink' - the weeping that fills the sufferer's cup, grief drunk with the water."),
 (307200,"wither away (yabesh)","state","the psalmist","wither away","like grass",IB,"paired with the evening-shadow days","v11: 'I WITHER AWAY (yabesh) like grass' - the fading of the sufferer, life drying up like cut grass."),
 (268926,"hold dear (ratsah)","disposition","God's servants","hold dear","the stones of Zion",IB,"paired with pitying her dust","v14: 'For your servants HOLD (ratsah) her stones dear' - the love of God's people for Zion, affection even for her rubble."),
 (268928,"pity (chanan)","disposition","God's servants","have pity / affection","for Zion's dust",IB,"paired with holding her stones dear","v14: 'and have PITY (chanan) on her dust' - the tender regard of the servants for ruined Zion, love for her very dust."),
 (268931,"fear (yare)","disposition","the nations","fear","the name of the LORD",GOD,"paired with the kings fearing his glory","v15: 'Nations will FEAR (yare) the name of the LORD' - the reverence the rebuilt Zion draws from the nations, awe of God's name."),
 (307203,"prayer (tephillah)","action","the destitute","pray","to God",GOD,"paired with God regarding it","v17: 'He regards the PRAYER (tephillah) of the destitute' - the prayer of the stripped-bare, which God does not overlook."),
 (307204,"destitute (arar)","status","the destitute","be stripped bare","yet heard by God",IB,"paired with their prayer regarded","v17: 'He regards the prayer of the DESTITUTE (arar)' - the utterly poor, whose very destitution God honours with regard."),
 (307208,"prayer (tephillah)","action","the destitute","pray","not despised by God",GOD,"paired with the destitute","v17: 'and does not despise their PRAYER (tephillah)' - the prayer of the poor that God will not scorn."),
 (268952,"praise (halal)","action","a people yet to be created","praise","the LORD",GOD,"paired with the recorded testimony","v18: 'so that a people yet to be created may PRAISE (halal) the LORD' - the praise of generations to come, worship recorded for the future."),
 (268981,"groans (enqah)","action","the prisoners","groan","before God",IB,"paired with being set free","v20: 'to hear the GROANS (enqah) of the prisoners' - the sighing of the captives that God stoops to hear."),
 (268988,"declare (saphar)","action","the redeemed","declare","God's name in Zion",GOD,"paired with his praise in Jerusalem","v21: 'that they may DECLARE (saphar) in Zion the name of the LORD' - the proclaiming of God's name by the freed, testimony in Zion."),
 (268993,"praise (tehillah)","action","the redeemed","render praise","to God in Jerusalem",GOD,"paired with declaring his name","v21: 'and in Jerusalem his PRAISE (tehillah)' - the praise of God rising from the restored city."),
 (268998,"worship (abad)","action","peoples and kingdoms","worship / serve","the LORD",GOD,"paired with the gathering of peoples","v22: 'and kingdoms, to WORSHIP (abad) the LORD' - the nations gathering to serve God, worship widened to all peoples."),
]
for a in CH: r.ch(*a)
QU=[
 (268897,"hear (shama)",268898,"v1: 'HEAR (shama) my prayer, O LORD' - God's hearing petitioned. Qualifier."),
 (268965,"hide (sathar)",268978,"v2: 'Do not HIDE (sathar) your face from me' - God's hidden face, asked to be turned. Qualifier."),
 (268971,"incline (natah)",268978,"v2: 'INCLINE (natah) your ear to me' - God's attention petitioned. Qualifier."),
 (268973,"answer (anah)",268978,"v2: 'ANSWER (anah) me speedily!' - God's answer petitioned. Qualifier."),
 (268975,"speedily (maher)",268978,"v2: 'answer me SPEEDILY (maher)' - God's swift response petitioned. Qualifier."),
 (268903,"indignation (zaam)",269024,"v10: 'because of your INDIGNATION (zaam) and anger' - God's displeasure. Qualifier."),
 (268904,"anger (qetseph)",269024,"v10: 'your indignation and ANGER (qetseph)' - God's wrath. Qualifier."),
 (268906,"take up (nasa)",269024,"v10: 'for you have taken me UP (nasa)' - God's raising, then casting down. Qualifier."),
 (268907,"throw down (shalak)",269024,"v10: 'and thrown me DOWN (shalak)' - God's casting down. Qualifier."),
 (268911,"forever (olam)",268931,"v12: 'But you, O LORD, are enthroned FOREVER (olam)' - God's eternity. Qualifier."),
 (268912,"remembered (zeker)",268931,"v12: 'you are REMEMBERED (zeker) throughout all generations' - God's enduring renown. Qualifier."),
 (268916,"arise (qum)",268926,"v13: 'You will ARISE (qum) and have pity on Zion' - God's rising to act. Qualifier."),
 (268917,"pity (racham)",268926,"v13: 'and have PITY (racham) on Zion' - God's compassion on Zion. Qualifier."),
 (268921,"favor (chanan)",268926,"v13: 'it is the time to FAVOUR (chanan) her' - God's favour to Zion. Qualifier."),
 (268932,"name (shem)",268931,"v15: 'Nations will fear the NAME (shem) of the LORD' - God's name. Qualifier."),
 (268938,"glory (kabod)",268931,"v15: 'and all the kings of the earth your GLORY (kabod)' - God's glory. Qualifier."),
 (268941,"build up (banah)",268931,"v16: 'For the LORD BUILDS UP (banah) Zion' - God's rebuilding of Zion. Qualifier."),
 (268943,"appears (raah)",268931,"v16: 'he APPEARS (raah) in his glory' - God's manifestation. Qualifier."),
 (268945,"glory (kabod)",268931,"v16: 'he appears in his GLORY (kabod)' - God's glory. Qualifier."),
 (307202,"regard (panah)",307204,"v17: 'He REGARDS (panah) the prayer of the destitute' - God's attention to the poor. Qualifier."),
 (307206,"despise (bazah, negated)",307204,"v17: 'and does not DESPISE (bazah) their prayer' - God's non-contempt for the poor's prayer. Qualifier."),
 (268947,"recorded (kathab)",268952,"v18: 'Let this be RECORDED (kathab) for a generation to come' - God's word set down for the future. Qualifier."),
 (268951,"created (bara)",268952,"v18: 'so that a people yet to be CREATED (bara)' - God's creating of a future people. Qualifier."),
 (268955,"look down (shaqaph)",268931,"v19: 'For he LOOKED DOWN (shaqaph) from his holy height' - God's looking from heaven. Qualifier."),
 (268957,"holy (qodesh)",268931,"v19: 'from his HOLY (qodesh) height' - God's holy height. Qualifier."),
 (268962,"looked (nabat)",268931,"v19: 'the LORD LOOKED (nabat) from heaven to the earth' - God's regard. Qualifier."),
 (268980,"hear (shama)",268981,"v20: 'to HEAR (shama) the groans of the prisoners' - God's hearing of the captives. Qualifier."),
 (268984,"set free (pathach)",268981,"v20: 'to SET FREE (pathach) those who were doomed to die' - God's liberation. Qualifier."),
 (268990,"name (shem)",268988,"v21: 'declare in Zion the NAME (shem) of the LORD' - God's name. Qualifier."),
 (268995,"gather (qabats)",268998,"v22: 'when peoples GATHER (qabats) together' - the gathering of the nations to God. Qualifier."),
 (269000,"break (anah)",307200,"v23: 'He has BROKEN (anah) my strength in midway' - God's breaking of the sufferer's strength. Qualifier."),
 (269003,"shorten (qatsar)",307200,"v23: 'he has SHORTENED (qatsar) my days' - God's cutting short of life. Qualifier."),
 (269009,"remain (amad)",268931,"v26: 'They will perish, but you will REMAIN (amad)' - God's permanence. Qualifier."),
 (269012,"change (chalaph)",268931,"v26: 'you will CHANGE (chalaph) them like a robe' - God's changing of the heavens. Qualifier."),
 (307230,"no end (tamam)",268931,"v27: 'you are the same, and your years have no END (tamam)' - God's unchanging eternity. Qualifier."),
 (269017,"dwell secure (shakan)",268931,"v28: 'The children of your servants shall DWELL SECURE (shakan)' - God's securing of his servants' children. Qualifier."),
]
for sid,sense,src,d in QU: r.qu(sid,sense,src,d)
ST=[
 (268889,"Prayer (tephillah)","v0 superscription: 'A PRAYER (tephillah) of one afflicted' - the psalm-heading/type. Standalone."),
 (268893,"pour out (shaphak)","v1: 'and POURS OUT (shaphak) his complaint' - the pouring of the lament, manner of the complaint (char, 268894). Standalone."),
 (268970,"distress (tsar)","v2: 'in the day of my DISTRESS (tsar)' - the trouble occasioning the call; circumstance. Standalone."),
 (269025,"smoke (ashan)","v3: 'my days pass away like SMOKE (ashan)' - the vanishing smoke, image of fleeting days. Standalone."),
 (269027,"bones (etsem)","v3: 'my BONES (etsem) burn like a furnace' - the burning bones, image of feverish affliction. Standalone."),
 (269028,"burn (charar)","v3: 'my bones BURN (charar) like a furnace' - the fever of grief, image. Standalone."),
 (269029,"like (kemo)","v3: 'my bones burn LIKE (kemo) a furnace' - the comparison, image. Standalone."),
 (269030,"furnace (moqed)","v3: 'burn like a FURNACE (moqed)' - the hearth, image of the burning affliction. Standalone."),
 (302590,"struck down (nakah)","v4: 'My heart is STRUCK DOWN (nakah) like grass' - the blighted heart, image (char, 302589). Standalone."),
 (302591,"grass (eseb)","v4: 'struck down like GRASS (eseb)' - the withering grass, image of the heart. Standalone."),
 (302595,"eat (akal)","v4: 'I forget to EAT (akal) my bread' - the eating neglected in grief (char forget, 302594). Standalone."),
 (269032,"loud (qol)","v5: 'Because of my LOUD (qol) groaning' - the loudness of the groaning, image. Standalone."),
 (269034,"bones (etsem)","v5: 'my BONES (etsem) cling to my flesh' - the emaciated frame, image. Standalone."),
 (269037,"flesh (basar)","v5: 'my bones cling to my FLESH (basar)' - the wasted body, image of the affliction. Standalone."),
 (307187,"desert owl (qaath)","v6: 'I am like a DESERT OWL (qaath) of the wilderness' - the solitary bird, image of desolation. Standalone."),
 (307190,"owl (kos)","v6: 'like an OWL (kos) of the waste places' - the lonely bird, image. Standalone."),
 (307191,"waste places (chorbah)","v6: 'like an owl of the WASTE PLACES (chorbah)' - the ruins, image of desolation. Standalone."),
 (307192,"lie awake (shaqad)","v7: 'I LIE AWAKE (shaqad)' - the sleepless sufferer, image. Standalone."),
 (307193,"lonely (badad)","v7: 'I am like a LONELY (badad) sparrow' - the solitude of the sufferer, image. Standalone."),
 (307194,"sparrow (tsippor)","v7: 'like a lonely SPARROW (tsippor)' - the isolated bird, image of loneliness. Standalone."),
 (307196,"housetop (gag)","v7: 'a lonely sparrow on the HOUSETOP (gag)' - the exposed perch, image of isolation. Standalone."),
 (269043,"curse (shaba)","v8: 'use my name for a CURSE (shaba)' - the name become a byword, image of the derision (char, 269042). Standalone."),
 (269045,"eat (akal)","v9: 'For I EAT (akal) ashes like bread' - the mourning-diet, image. Standalone."),
 (269046,"ashes (epher)","v9: 'I eat ASHES (epher) like bread' - the ashes of mourning, image of grief. Standalone."),
 (269048,"mingle (masak)","v9: 'and MINGLE (masak) tears with my drink' - the mixing of tears in the cup, image (char tears, 269049). Standalone."),
 (307198,"evening (natah)","v11: 'My days are like an EVENING (natah) shadow' - the lengthening shadow, image of fading life. Standalone."),
 (307199,"shadow (tsel)","v11: 'like an evening SHADOW (tsel)' - the declining shadow, image of transience. Standalone."),
 (307201,"grass (eseb)","v11: 'I wither away like GRASS (eseb)' - the cut grass, image of the withering (char, 307200). Standalone."),
 (268922,"appointed time (moed)","v13: 'the APPOINTED TIME (moed) has come' - the set time for God to favour Zion, image. Standalone."),
 (268982,"prisoners (asir)","v20: 'the groans of the PRISONERS (asir)' - the captives whose groans God hears (char, 268981). Standalone."),
 (268986,"doomed to die (temuthah)","v20: 'those who were DOOMED TO DIE (temuthah)' - the condemned God sets free, object. Standalone."),
 (307214,"midst (chetsi)","v24: 'take me not away in the MIDST (chetsi) of my days' - the middle of life, image of untimely death. Standalone."),
 (307222,"foundation (yasad)","v25: 'Of old you laid the FOUNDATION (yasad) of the earth' - the founded earth, image of creation. Standalone."),
 (307225,"work (maaseh)","v25: 'the heavens are the WORK (maaseh) of your hands' - the created heavens, image. Standalone."),
 (269010,"wear out (balah)","v26: 'they will all WEAR OUT (balah) like a garment' - the aging heavens, image of transience. Standalone."),
 (269011,"garment (beged)","v26: 'wear out like a GARMENT (beged)' - the worn robe, image of the passing creation. Standalone."),
 (269014,"pass away (chalaph)","v26: 'and they will PASS AWAY (chalaph)' - the vanishing heavens, image of transience. Standalone."),
]
for sid,sense,d in ST: r.st(sid,sense,d)
r.write()
