import sys; sys.path.insert(0,'scripts')
from _reread_ledger_lib import Reading, IB, GOD, PER
r=Reading("Psa",19,112,
  note="Ps112 acrostic on the God-fearing man (10v). Char-rich portrait. Arcs: A fear+delight v1 (BLESSED man who FEARS the LORD, DELIGHTS in his commandments); B blessed upright line + enduring RIGHTEOUSNESS v2-3; C character v4-6 (UPRIGHT, GRACIOUS/MERCIFUL/RIGHTEOUS; DEALS-GENEROUSLY, JUSTICE; the RIGHTEOUS never moved); D confidence v7-9 (not AFRAID, HEART firm+TRUSTING, HEART steady; DISTRIBUTED to the poor, RIGHTEOUSNESS endures, HONOR); E the foil v10 (WICKED-MAN sees, ANGRY, GNASHES, MELTS-AWAY, his DESIRE perishes). God's commandments + light-dawns = qualifiers; wealth/horn/temporal = standalone.")
CH=[
 (270643,"praise (halal)","action","the worshipper","praise","the LORD",GOD,"paired with the blessing of the God-fearer",
  "v1: 'PRAISE (halal) the LORD!' - the opening Hallelujah framing the portrait of the blessed man."),
 (270645,"blessed (esher)","state","the God-fearing man","be blessed","in fearing God",IB,"paired with fearing God and delighting in his commandments",
  "v1: 'BLESSED (esher) is the man who fears the LORD' - the happiness of the God-fearer, the beatitude the whole psalm unfolds."),
 (270647,"fear (yare)","disposition","the man","fear / revere","the LORD",GOD,"paired with delighting in his commandments",
  "v1: 'the man who FEARS (yare) the LORD' - the reverence that is the root of the blessed man's whole character."),
 (270650,"delight (chaphets)","disposition","the man","greatly delight","in God's commandments",GOD,"paired with the fear of the LORD",
  "v1: 'who greatly DELIGHTS (chaphets) in his commandments!' - the joy in God's law that marks the God-fearer, obedience loved not merely obeyed."),
 (270666,"upright (yashar)","status","the upright","be blessed","as a generation",IB,"paired with the blessing on their line",
  "v2: 'the generation of the UPRIGHT (yashar) will be blessed' - the upright whose very line is blessed."),
 (270667,"blessed (barak)","state","the upright","be blessed","by God",IB,"paired with the upright",
  "v2: 'the generation of the upright will be BLESSED (barak)' - the blessing resting on the upright and their offspring."),
 (270671,"righteousness (tsedaqah)","disposition","the man","be righteous","enduringly",IB,"paired with the enduring of his righteousness",
  "v3: 'and his RIGHTEOUSNESS (tsedaqah) endures forever' - the lasting rightness of the God-fearer, righteousness that outlasts wealth."),
 (270678,"upright (yashar)","status","the upright","be given light","in darkness",IB,"paired with the light that dawns for them",
  "v4: 'Light dawns in the darkness for the UPRIGHT (yashar)' - the upright for whom light rises even in the dark."),
 (270679,"gracious (chanun)","disposition","the man","be gracious","to others",IB,"paired with being merciful and righteous",
  "v4: 'he is GRACIOUS (chanun), merciful, and righteous' - the God-fearer mirrors God's own grace toward others."),
 (270680,"merciful (rachum)","disposition","the man","be merciful","to others",IB,"paired with being gracious",
  "v4: 'gracious, MERCIFUL (rachum), and righteous' - the compassion of the God-fearer, God's mercy reflected in the man."),
 (270681,"righteous (tsaddiq)","disposition","the man","be righteous","in dealings",IB,"paired with being gracious and merciful",
  "v4: 'gracious, merciful, and RIGHTEOUS (tsaddiq)' - the uprightness of the God-fearer's conduct."),
 (270684,"deal generously (chanan)","action","the man","deal generously","and lend",IB,"paired with conducting affairs with justice",
  "v5: 'It is well with the man who DEALS GENEROUSLY (chanan) and lends' - the open-handed generosity of the God-fearer."),
 (270688,"justice (mishpat)","disposition","the man","conduct affairs","with justice",IB,"paired with dealing generously",
  "v5: 'who conducts his affairs with JUSTICE (mishpat)' - the just ordering of the God-fearer's business, fairness in all dealings."),
 (270690,"righteous (tsaddiq)","status","the righteous","never be moved","being steadfast",IB,"paired with being remembered forever",
  "v6: 'For the RIGHTEOUS (tsaddiq) will never be moved' - the immovable stability of the righteous, rooted in God."),
 (270696,"afraid (yare, negated)","state","the man","not be afraid","of bad news",IB,"paired with the firm, trusting heart",
  "v7: 'He is not AFRAID (yare) of bad news' - the fearlessness of the God-fearer, dread dissolved by trust."),
 (270700,"heart (leb)","faculty","the man","have the heart firm","trusting in God",GOD,"paired with trusting in the LORD",
  "v7: 'his HEART (leb) is firm, trusting in the LORD' - the settled inner self, firmness grounded in trust."),
 (270702,"trust (batach)","disposition","the man","trust","in the LORD",GOD,"paired with the firm heart",
  "v7: 'his heart is firm, TRUSTING (batach) in the LORD' - the reliance on God that steadies the heart against fear."),
 (270704,"heart (leb)","faculty","the man","have the heart steady","unafraid",IB,"paired with not being afraid",
  "v8: 'His HEART (leb) is steady; he will not be afraid' - the unshaken inner self, poised even before adversaries."),
 (270707,"afraid (yare, negated)","state","the man","not be afraid","of adversaries",IB,"paired with the steady heart",
  "v8: 'he will not be AFRAID (yare)' - the composure of the God-fearer, confident until he sees his foes fall."),
 (270712,"distribute freely (pazar)","action","the man","distribute freely","to the poor",IB,"paired with his enduring righteousness",
  "v9: 'He has DISTRIBUTED (pazar) freely; he has given to the poor' - the lavish generosity of the God-fearer, scattering to the needy."),
 (270715,"righteousness (tsedaqah)","disposition","the man","be righteous","enduringly",IB,"paired with the horn exalted in honor",
  "v9: 'his RIGHTEOUSNESS (tsedaqah) endures forever' - the lasting rightness of the generous man, righteousness that stands."),
 (270720,"honor (kabod)","state","the man","be exalted in honor","by God",IB,"paired with the horn exalted",
  "v9: 'his horn is exalted in HONOUR (kabod)' - the dignity God gives the God-fearer, exaltation crowning his righteousness."),
 (270652,"wicked man (rasha)","status","the wicked man","see and rage","at the righteous' blessing",IB,"paired with anger and melting away",
  "v10: 'The WICKED MAN (rasha) sees it and is angry' - the godless foil, galled by the blessing of the righteous."),
 (270654,"angry (kaas)","state","the wicked man","be angry","at the righteous",IB,"paired with gnashing and melting",
  "v10: 'sees it and is ANGRY (kaas)' - the fury of the wicked at the God-fearer's good, envy turned to rage."),
 (270658,"melt away (masas)","state","the wicked man","melt away","in frustration",IB,"paired with the anger and gnashing",
  "v10: 'he gnashes his teeth and MELTS AWAY (masas)' - the wicked man dissolving in impotent frustration."),
 (270659,"desire (taavah)","disposition","the wicked man","have his desire perish","unfulfilled",IB,"paired with the wicked's melting away",
  "v10: 'the DESIRE (taavah) of the wicked will perish' - the craving of the wicked come to nothing, appetite frustrated forever."),
]
for a in CH: r.ch(*a)
QU=[
 (270651,"commandments (mitsvah)",270650,"v1: 'who greatly delights in his COMMANDMENTS (mitsvah)!' - God's commandments, the man's delight. Qualifier."),
 (270675,"dawns (zarach)",270678,"v4: 'Light DAWNS (zarach) in the darkness for the upright' - God-given light rising for the upright. Qualifier."),
]
for sid,sense,src,d in QU: r.qu(sid,sense,src,d)
ST=[
 (270662,"offspring (zera)","v2: 'His OFFSPRING (zera) will be mighty in the land' - the God-fearer's descendants, image of blessing. Standalone."),
 (270663,"mighty (gibbor)","v2: 'will be MIGHTY (gibbor) in the land' - the strength of the offspring, image. Standalone."),
 (270668,"wealth (hon)","v3: 'WEALTH (hon) and riches are in his house' - the God-fearer's prosperity, image of blessing. Standalone."),
 (270669,"riches (osher)","v3: 'wealth and RICHES (osher) are in his house' - the abundance, image. Standalone."),
 (270672,"endures (amad)","v3: 'his righteousness ENDURES (amad) forever' - the permanence of his righteousness (char, 270671); temporal. Standalone."),
 (270674,"light (or)","v4: 'LIGHT (or) dawns in the darkness for the upright' - the light of blessing/relief, image. Standalone."),
 (270676,"darkness (choshek)","v4: 'Light dawns in the DARKNESS (choshek)' - the dark from which the upright are lifted, image. Standalone."),
 (270682,"well (tob)","v5: 'It is WELL (tob) with the man who deals generously' - the good estate of the generous (char, 270684). Standalone."),
 (270685,"lends (lavah)","v5: 'who deals generously and LENDS (lavah)' - the lending, outward act of generosity. Standalone."),
 (270686,"conducts (kul)","v5: 'who CONDUCTS (kul) his affairs with justice' - the ordering of affairs (char justice, 270688). Standalone."),
 (270687,"affairs (dabar)","v5: 'conducts his AFFAIRS (dabar) with justice' - the man's business, image. Standalone."),
 (270692,"moved (mot)","v6: 'the righteous will never be MOVED (mot)' - the unshakeability of the righteous (char, 270690), image. Standalone."),
 (270693,"remembered (zeker)","v6: 'he will be REMEMBERED (zeker) forever' - the lasting memory of the righteous, image. Standalone."),
 (270694,"forever (olam)","v6: 'remembered FOREVER (olam)' - the perpetuity of his memory; temporal. Standalone."),
 (270698,"bad (ra)","v7: 'He is not afraid of BAD (ra) news' - the ill tidings the God-fearer does not dread (char afraid, 270696). Standalone."),
 (270699,"news (shemuah)","v7: 'not afraid of bad NEWS (shemuah)' - the report, image. Standalone."),
 (270701,"firm (kun)","v7: 'his heart is FIRM (kun), trusting in the LORD' - the firmness of the heart (char heart, 270700). Standalone."),
 (270705,"steady (samak)","v8: 'His heart is STEADY (samak)' - the settledness of the heart (char heart, 270704). Standalone."),
 (270709,"looks (raah)","v8: 'until he LOOKS (raah) in triumph on his adversaries' - the God-fearer's vindication, image. Standalone."),
 (270711,"adversaries (tsar)","v8: 'looks in triumph on his ADVERSARIES (tsar)' - the foes he outlasts, object. Standalone."),
 (270713,"given (nathan)","v9: 'he has GIVEN (nathan) to the poor' - the giving to the needy (char distributed, 270712). Standalone."),
 (270714,"poor (ebyon)","v9: 'he has given to the POOR (ebyon)' - the needy recipients of the man's generosity, object. Standalone."),
 (270716,"endures (amad)","v9: 'his righteousness ENDURES (amad) forever' - the permanence of his righteousness (char, 270715); temporal. Standalone."),
 (270718,"horn (qeren)","v9: 'his HORN (qeren) is exalted in honour' - the horn of strength/dignity (char honor, 270720), image. Standalone."),
 (270719,"exalted (rum)","v9: 'his horn is EXALTED (rum) in honour' - the lifting of the horn, image of the man's dignity. Standalone."),
 (270653,"sees (raah)","v10: 'The wicked man SEES (raah) it and is angry' - the wicked's galled gaze (char wicked-man, 270652). Standalone."),
 (270656,"gnashes (charaq)","v10: 'he GNASHES (charaq) his teeth' - the gesture of rage, image (char angry, 270654). Standalone."),
 (270657,"teeth (shen)","v10: 'he gnashes his TEETH (shen)' - the teeth of fury, image. Standalone."),
 (270660,"wicked (rasha)","v10: 'the desire of the WICKED (rasha) will perish' - the wicked (char wicked-man, 270652), whose desire comes to nothing. Standalone."),
 (270661,"perish (abad)","v10: 'the desire of the wicked will PERISH (abad)' - the ending of the wicked's craving (char desire, 270659), image. Standalone."),
]
for sid,sense,d in ST: r.st(sid,sense,d)
r.write()
