import sys; sys.path.insert(0,'scripts')
from _reread_ledger_lib import Reading, IB, GOD, PER
r=Reading("Psa",19,107,
  note="Ps107 great thanksgiving, 4 'cried to the LORD' vignettes (43v, 200 spans). Read by CHAR-ARC. A call v1-3 (GIVE-THANKS). Vig1 wanderers v4-9 (WANDERED, HUNGRY/THIRSTY/SOUL FAINTED -> CRIED -> THANK; the LONGING/HUNGRY SOUL satisfied). Vig2 prisoners v10-16 (AFFLICTION because REBELLED/SPURNED, HEARTS bowed -> CRIED -> THANK). Vig3 sick fools v17-22 (FOOLS through SINFUL-WAYS/INIQUITIES, SUFFERED-AFFLICTION, LOATHED food -> CRIED -> healed -> THANKSGIVING/TELL/JOY). Vig4 sailors v23-32 (SAW deeds, COURAGE MELTED, WITS' end -> CRIED -> GLAD/DESIRED-haven -> EXTOL/PRAISE). Coda v33-43 (EVIL inhabitants; HUNGRY dwell; BROUGHT-LOW/SORROW; princes WANDER; NEEDY raised; UPRIGHT GLAD, WICKEDNESS silenced; WISE ATTEND/CONSIDER his love). God's deliver/satisfy/heal/still-the-storm/reversals = qualifiers; desert/irons/waves/agriculture imagery = standalone.")
V1=270047; V2=269883; V3=269908; V4=269957; CA=269860; CO=270040
CH=[
 (269860,"give thanks (yadah)","action","the redeemed","give thanks","to the LORD",GOD,"paired with the redeemed testifying","v1: 'Oh GIVE THANKS (yadah) to the LORD, for he is good' - the opening call, the frame of the whole thanksgiving."),
 # Vig1 wanderers
 (270011,"wander (taah)","state","the wanderers","wander lost","in desert wastes",IB,"paired with the fainting soul","v4: 'Some WANDERED (taah) in desert wastes, finding no way to a city' - the lost, homeless in the wilderness, the first plight."),
 (270043,"hungry (raeb)","state","the wanderers","be hungry","in the desert",IB,"paired with thirst and the fainting soul","v5: 'HUNGRY (raeb) and thirsty, their soul fainted within them' - the starving wanderers, need pressing on the body."),
 (270044,"thirsty (tsame)","state","the wanderers","be thirsty","in the desert",IB,"paired with hunger","v5: 'hungry and THIRSTY (tsame)' - the parched wanderers, thirst added to hunger."),
 (270045,"soul (nephesh)","faculty","the wanderers","faint","within them",IB,"paired with fainting","v5: 'their SOUL (nephesh) fainted within them' - the inmost self failing under hunger and thirst."),
 (270046,"faint (ataph)","state","the wanderers","faint / grow feeble","from hunger and thirst",IB,"paired with the soul","v5: 'their soul FAINTED (ataph) within them' - the swooning of the wanderers, life ebbing in the waste."),
 (270047,"cry (tsaaq)","action","the wanderers","cry","to the LORD in trouble",GOD,"paired with God's deliverance (refrain)","v6: 'Then they CRIED (tsaaq) to the LORD in their trouble' - the cry of the lost, the refrain-turn from distress to rescue."),
 (270060,"thank (yadah)","action","the wanderers","thank","the LORD for his steadfast love",GOD,"paired with his wondrous works (refrain)","v8: 'Let them THANK (yadah) the LORD for his steadfast love' - the summons to gratitude, the refrain's response to deliverance."),
 (270067,"longing (shaqaq)","disposition","the longing soul","long","for satisfaction",IB,"paired with the soul satisfied","v9: 'For he satisfies the LONGING (shaqaq) soul' - the yearning self God fills, desire met with good."),
 (270068,"soul (nephesh)","faculty","the longing one","be satisfied","by God",IB,"paired with the longing","v9: 'he satisfies the longing SOUL (nephesh)' - the inmost self God contents."),
 (270069,"hungry (raeb)","state","the hungry soul","be hungry","then filled",IB,"paired with the hungry soul filled","v9: 'and the HUNGRY (raeb) soul he fills with good things' - the starving self God feeds."),
 (270070,"soul (nephesh)","faculty","the hungry one","be filled","with good things",IB,"paired with hunger","v9: 'the hungry SOUL (nephesh) he fills with good things' - the inmost self satisfied by God."),
 # Vig2 prisoners
 (269869,"affliction (oni)","state","the prisoners","sit in affliction","and irons",IB,"paired with rebelling against God","v10: 'prisoners in AFFLICTION (oni) and in irons' - the bound and suffering, the second plight."),
 (269871,"rebel (marah)","action","the prisoners","rebel","against the words of God",GOD,"paired with spurning his counsel","v11: 'for they had REBELLED (marah) against the words of God' - the defiance that earned the chains, affliction as the fruit of rebellion."),
 (269874,"spurn (naats)","action","the prisoners","spurn","the counsel of the Most High",GOD,"paired with rebelling","v11: 'and SPURNED (naats) the counsel of the Most High' - the contempt for God's counsel behind the imprisonment."),
 (269877,"hearts (leb)","faculty","the prisoners","have the heart bowed down","with hard labor",IB,"paired with falling with none to help","v12: 'So he bowed their HEARTS (leb) down with hard labour' - the inner self broken by toil, pride humbled in the pit."),
 (269883,"cry (zaaq)","action","the prisoners","cry","to the LORD in trouble",GOD,"paired with God's deliverance (refrain)","v13: 'Then they CRIED (zaaq) to the LORD in their trouble' - the cry of the bound, the refrain-turn to rescue."),
 (269890,"thank (yadah)","action","the prisoners","thank","the LORD for his steadfast love",GOD,"paired with his wondrous works (refrain)","v15: 'Let them THANK (yadah) the LORD for his steadfast love' - the summons to gratitude for the burst bonds."),
 # Vig3 sick fools
 (269896,"fools (evil)","status","the sick","be fools","through sinful ways",IB,"paired with their sinful ways and iniquities","v17: 'Some were FOOLS (evil) through their sinful ways' - the foolish whose sin brought sickness, the third plight."),
 (269898,"sinful ways (pesha)","disposition","the fools","walk in sinful ways","against God",IB,"paired with their iniquities","v17: 'fools through their SINFUL WAYS (pesha)' - the transgressions that made them fools and brought affliction."),
 (269899,"iniquities (avon)","state","the fools","bear iniquities","that brought affliction",IB,"paired with the affliction suffered","v17: 'and because of their INIQUITIES (avon) suffered affliction' - the guilt that issued in sickness."),
 (269900,"suffered affliction (anah)","state","the fools","suffer affliction","for their sin",IB,"paired with the iniquities","v17: 'because of their iniquities SUFFERED AFFLICTION (anah)' - the sickness endured as sin's consequence."),
 (269901,"soul (nephesh)","faculty","the sick","loathe food","drawing near death",IB,"paired with loathing food","v18: 'their SOUL (nephesh) loathed any kind of food' - the inmost self sickened, appetite failing at death's door."),
 (269902,"loathe (taab)","state","the sick","loathe","all food",IB,"paired with the soul near death","v18: 'their soul LOATHED (taab) any kind of food' - the revulsion at food of the mortally sick, life recoiling."),
 (269908,"cry (zaaq)","action","the sick","cry","to the LORD in trouble",GOD,"paired with God's deliverance (refrain)","v19: 'Then they CRIED (zaaq) to the LORD in their trouble' - the cry of the sick, the refrain-turn to healing."),
 (269926,"thank (yadah)","action","the healed","thank","the LORD for his steadfast love",GOD,"paired with his wondrous works (refrain)","v21: 'Let them THANK (yadah) the LORD for his steadfast love' - the summons to gratitude for the sent word that healed."),
 (269934,"thanksgiving (todah)","action","the healed","offer thanksgiving","to God",GOD,"paired with telling his deeds in joy","v22: 'And let them offer sacrifices of THANKSGIVING (todah)' - the thank-offering of the healed, gratitude enacted."),
 (269935,"tell (saphar)","action","the healed","tell / recount","God's deeds in songs",GOD,"paired with thanksgiving and joy","v22: 'and TELL (saphar) of his deeds in songs of joy!' - the recounting of God's works, testimony sung."),
 (269937,"joy (rinnah)","state","the healed","sing with joy","of God's deeds",GOD,"paired with telling his deeds","v22: 'tell of his deeds in songs of JOY (rinnah)!' - the gladness of the healed voiced in song."),
 # Vig4 sailors
 (269939,"see (raah)","action","the sailors","see","the deeds of the LORD in the deep",GOD,"paired with the storm that follows","v24: 'they SAW (raah) the deeds of the LORD, his wondrous works in the deep' - the sailors' witness of God's power on the sea."),
 (269954,"courage (nephesh)","faculty","the sailors","have courage melt","in their plight",IB,"paired with the melting","v26: 'their COURAGE (nephesh) melted away in their evil plight' - the inmost self unnerved, heart failing as the ship heaved."),
 (269955,"melt (mug)","state","the sailors","have courage melt away","in terror",IB,"paired with the courage","v26: 'their courage MELTED (mug) away' - the dissolving of the sailors' nerve before the storm."),
 (307511,"wits (chokmah)","faculty","the sailors","be at their wits' end","in the storm",IB,"paired with reeling and staggering","v27: 'and were at their WITS' (chokmah) end' - the sailors' skill exhausted, seamanship undone by the sea."),
 (269957,"cry (tsaaq)","action","the sailors","cry","to the LORD in trouble",GOD,"paired with God's deliverance (refrain)","v28: 'Then they CRIED (tsaaq) to the LORD in their trouble' - the cry of the storm-tossed, the refrain-turn to calm."),
 (269969,"glad (samach)","state","the sailors","be glad","that the waters were quiet",IB,"paired with the desired haven","v30: 'Then they were GLAD (samach) that the waters were quiet' - the relief of the sailors at the stilled sea."),
 (269973,"desire (chaphets)","disposition","the sailors","long for","their haven",IB,"paired with the gladness","v30: 'and he brought them to their DESIRED (chaphets) haven' - the longed-for harbour, the goal of the storm-tossed."),
 (269975,"thank (yadah)","action","the sailors","thank","the LORD for his steadfast love",GOD,"paired with his wondrous works (refrain)","v31: 'Let them THANK (yadah) the LORD for his steadfast love' - the summons to gratitude for the calmed storm."),
 (269981,"extol (rum)","action","the sailors","extol","God in the congregation",GOD,"paired with praising in the assembly","v32: 'Let them EXTOL (rum) him in the congregation of the people' - the public praise of the delivered, gratitude among the assembly."),
 (269984,"praise (halal)","action","the sailors","praise","God in the assembly of elders",GOD,"paired with extolling","v32: 'and PRAISE (halal) him in the assembly of the elders' - the worship of the delivered before the elders."),
 # Coda
 (269991,"evil (raa)","disposition","the inhabitants","be evil","provoking God's judgment",IB,"paired with the land turned to waste","v34: 'a fruitful land into a salty waste, because of the EVIL (raa) of its inhabitants' - the wickedness that turns fruitfulness to salt."),
 (307527,"hungry (raeb)","status","the hungry","be hungry","then given a home",IB,"paired with being settled in a city","v36: 'And there he lets the HUNGRY (raeb) dwell' - the needy God settles, hunger answered with a home."),
 (270007,"brought low (shachach)","state","the people","be brought low","through oppression",IB,"paired with sorrow","v39: 'When they are diminished and BROUGHT LOW (shachach)' - the abasement of the people through affliction."),
 (270010,"sorrow (yagon)","state","the people","suffer sorrow","in their affliction",IB,"paired with being brought low","v39: 'through oppression, evil, and SORROW (yagon)' - the grief of the afflicted, the low estate of the humbled."),
 (270022,"wander (taah)","state","the princes","wander lost","in trackless wastes",IB,"paired with the contempt poured on them","v40: 'and makes them WANDER (taah) in trackless wastes' - the princes brought low, the mighty made to wander like the lost."),
 (270026,"needy (ebyon)","status","the needy","be raised","out of affliction",IB,"paired with affliction","v41: 'but he raises up the NEEDY (ebyon) out of affliction' - the poor God exalts, the great reversal of the coda."),
 (270031,"upright (yashar)","status","the upright","see and be glad","at God's reversals",IB,"paired with being glad","v42: 'The UPRIGHT (yashar) see it and are glad' - the just who rejoice to see God set things right."),
 (270033,"glad (samach)","state","the upright","be glad","at God's justice",IB,"paired with the upright","v42: 'the upright see it and are GLAD (samach)' - the joy of the righteous at God's vindicating reversals."),
 (270035,"wickedness (evel)","status","all wickedness","be silenced","before God's justice",IB,"paired with shutting its mouth","v42: 'and all WICKEDNESS (evel) shuts its mouth' - the wicked struck dumb, evil silenced by God's justice."),
 (270038,"wise (chakam)","status","whoever is wise","be wise","to attend to God's ways",IB,"paired with attending and considering","v43: 'Whoever is WISE (chakam), let him attend to these things' - the wise who read God's dealings, the coda's charge."),
 (270039,"attend (shamar)","action","the wise","attend to","these things",IB,"paired with considering God's love","v43: 'let him ATTEND (shamar) to these things' - the heeding of God's dealings, wisdom's task."),
 (270040,"consider (bin)","action","the wise","consider","the steadfast love of the LORD",GOD,"paired with attending","v43: 'let them CONSIDER (bin) the steadfast love of the LORD' - the discernment of God's covenant love in all his works, the psalm's closing wisdom."),
]
for a in CH: r.ch(*a)
QU=[
 (269862,"good (tob)",CA,"v1: 'for he is GOOD (tob)' - God's goodness. Qualifier."),
 (269863,"steadfast love (chesed)",CA,"v1: 'for his STEADFAST LOVE (chesed) endures forever!' - God's covenant love. Qualifier."),
 (269915,"redeemed (gaal)",CA,"v2: 'Let the REDEEMED (gaal) of the LORD say so' - God's redemption of his people. Qualifier."),
 (269918,"redeemed (gaal)",CA,"v2: 'whom he has REDEEMED (gaal) from trouble' - God's redeeming. Qualifier."),
 (307482,"gathered (qabats)",CA,"v3: 'and GATHERED (qabats) in from the lands' - God's regathering of the redeemed. Qualifier."),
 (270051,"delivered (natsal)",V1,"v6: 'and he DELIVERED (natsal) them from their distress' - God's rescue of the wanderers (refrain). Qualifier."),
 (270054,"led (darak)",V1,"v7: 'He LED (darak) them by a straight way' - God's leading of the wanderers. Qualifier."),
 (270062,"steadfast love (chesed)",V1,"v8: 'thank the LORD for his STEADFAST LOVE (chesed)' - God's covenant love (refrain). Qualifier."),
 (270063,"wondrous works (pala)",V1,"v8: 'for his WONDROUS WORKS (pala) to the children of man!' - God's wonders (refrain). Qualifier."),
 (270066,"satisfies (saba)",V1,"v9: 'For he SATISFIES (saba) the longing soul' - God's satisfying. Qualifier."),
 (270071,"fills (male)",V1,"v9: 'and FILLS (male) the hungry soul with good things' - God's filling. Qualifier."),
 (270072,"good things (tob)",V1,"v9: 'fills the hungry soul with GOOD THINGS (tob)' - the good God gives. Qualifier."),
 (269875,"counsel (etsah)",V2,"v11: 'and spurned the COUNSEL (etsah) of the Most High' - God's counsel. Qualifier."),
 (269887,"delivered (yasha)",V2,"v13: 'he DELIVERED (yasha) them from their distress' - God's rescue of the prisoners (refrain). Qualifier."),
 (307493,"burst (nathaq)",V2,"v14: 'and BURST (nathaq) their bonds apart' - God's breaking of the chains. Qualifier."),
 (269892,"steadfast love (chesed)",V2,"v15: 'thank the LORD for his STEADFAST LOVE (chesed)' - God's covenant love (refrain). Qualifier."),
 (269893,"wondrous works (pala)",V2,"v15: 'for his WONDROUS WORKS (pala)' - God's wonders (refrain). Qualifier."),
 (307495,"shatters (shabar)",V2,"v16: 'For he SHATTERS (shabar) the doors of bronze' - God's breaking of the prison gates. Qualifier."),
 (269912,"delivered (yasha)",V3,"v19: 'he DELIVERED (yasha) them from their distress' - God's rescue of the sick (refrain). Qualifier."),
 (269920,"sent (shalach)",V3,"v20: 'He SENT (shalach) out his word and healed them' - God's healing word. Qualifier."),
 (269921,"word (dabar)",V3,"v20: 'He sent out his WORD (dabar)' - God's healing word. Qualifier."),
 (269922,"healed (rapha)",V3,"v20: 'and HEALED (rapha) them' - God's healing. Qualifier."),
 (269923,"delivered (malat)",V3,"v20: 'and DELIVERED (malat) them from their destruction' - God's rescue. Qualifier."),
 (269928,"steadfast love (chesed)",V3,"v21: 'thank the LORD for his STEADFAST LOVE (chesed)' - God's covenant love (refrain). Qualifier."),
 (269929,"wondrous works (pala)",V3,"v21: 'for his WONDROUS WORKS (pala)' - God's wonders (refrain). Qualifier."),
 (269936,"deeds (maaseh)",V3,"v22: 'and tell of his DEEDS (maaseh) in songs of joy!' - God's deeds. Qualifier."),
 (269940,"deeds (maaseh)",V4,"v24: 'they saw the DEEDS (maaseh) of the LORD' - God's works. Qualifier."),
 (269942,"wondrous works (pala)",V4,"v24: 'his WONDROUS WORKS (pala) in the deep' - God's wonders. Qualifier."),
 (269945,"raised (amad)",V4,"v25: 'For he commanded and RAISED (amad) the stormy wind' - God's raising the storm. Qualifier."),
 (269963,"distress (metsuqah)",V4,"v28: 'and he delivered them from their DISTRESS (metsuqah)' - the distress God delivered them from (refrain). Qualifier."),
 (269964,"made (qum)",V4,"v29: 'He MADE (qum) the storm be still' - God's stilling of the storm. Qualifier."),
 (269966,"still (demamah)",V4,"v29: 'He made the storm be STILL (demamah)' - God's calm. Qualifier."),
 (269968,"hushed (chashah)",V4,"v29: 'and the waves of the sea were HUSHED (chashah)' - God's hushing of the waves. Qualifier."),
 (269971,"brought (nachah)",V4,"v30: 'and he BROUGHT (nachah) them to their desired haven' - God's guiding to harbour. Qualifier."),
 (269977,"steadfast love (chesed)",V4,"v31: 'thank the LORD for his STEADFAST LOVE (chesed)' - God's covenant love (refrain). Qualifier."),
 (269978,"wondrous works (pala)",V4,"v31: 'for his WONDROUS WORKS (pala)' - God's wonders (refrain). Qualifier."),
 (307513,"turns (sim)",CO,"v33: 'He TURNS (sim) rivers into a desert' - God's reversal of nature. Qualifier."),
 (269988,"fruitful (peri)",CO,"v34: 'a FRUITFUL (peri) land into a salty waste' - the fruitful land God can wither. Qualifier."),
 (307519,"turns (sim)",CO,"v35: 'He TURNS (sim) a desert into pools of water' - God's reversal of nature. Qualifier."),
 (307528,"dwell (yashab)",CO,"v36: 'And there he lets the hungry DWELL (yashab)' - God's settling of the needy. Qualifier."),
 (307529,"establish (kun)",CO,"v36: 'and they ESTABLISH (kun) a city to live in' - God's establishing of the city. Qualifier."),
 (270002,"multiply (rabah)",CO,"v38: 'By his blessing they MULTIPLY (rabah) greatly' - God's blessing of increase. Qualifier."),
 (270001,"blessing (barak)",CO,"v38: 'By his BLESSING (barak) they multiply greatly' - God's blessing. Qualifier."),
 (270005,"diminish (maat)",CO,"v38: 'and he does not let their livestock DIMINISH (maat)' - God's preservation. Qualifier."),
 (270006,"diminished (maat)",CO,"v39: 'When they are DIMINISHED (maat) and brought low' - the reduction God permits. Qualifier."),
 (270018,"pours (shaphak)",CO,"v40: 'He POURS (shaphak) contempt on princes' - God's abasing of the mighty. Qualifier."),
 (270025,"raises up (sagab)",CO,"v41: 'but he RAISES UP (sagab) the needy out of affliction' - God's exalting of the poor. Qualifier."),
 (270028,"makes (sim)",CO,"v41: 'and MAKES (sim) their families like flocks' - God's multiplying of the needy. Qualifier."),
 (270041,"steadfast love (chesed)",CO,"v43: 'let them consider the STEADFAST LOVE (chesed) of the LORD' - God's covenant love. Qualifier."),
]
for sid,sense,src,d in QU: r.qu(sid,sense,src,d)
ST=[
 (269864,"forever (olam)","v1: 'his steadfast love endures FOREVER (olam)' - the perpetuity of God's love; temporal. Standalone."),
 (307485,"east (mizrach)","v3: 'from the EAST (mizrach) and from the west' - the lands of the gathering, image. Standalone."),
 (307486,"west (maarab)","v3: 'and from the WEST (maarab)' - the compass of the regathering, image. Standalone."),
 (307488,"north (tsaphon)","v3: 'from the NORTH (tsaphon) and from the south' - the lands of the exiles, image. Standalone."),
 (270012,"desert (midbar)","v4: 'wandered in DESERT (midbar) wastes' - the wilderness of the lost, image. Standalone."),
 (270014,"finding (matsa)","v4: 'FINDING (matsa) no way to a city' - the fruitless search, image. Standalone."),
 (270015,"way (derek)","v4: 'finding no WAY (derek) to a city' - the road not found, image. Standalone."),
 (270016,"city (ir)","v4: 'no way to a CITY (ir) to dwell in' - the home not reached, image. Standalone."),
 (270017,"dwell (moshab)","v4: 'a city to DWELL (moshab) in' - the settled home the wanderers lack, image. Standalone."),
 (270053,"distress (metsuqah)","v6: 'he delivered them from their DISTRESS (metsuqah)' - the trouble of the wanderers (refrain), image. Standalone."),
 (270055,"straight (yashar)","v7: 'He led them by a STRAIGHT (yashar) way' - the direct road God gave, image. Standalone."),
 (270056,"way (derek)","v7: 'led them by a straight WAY (derek)' - the path to the city, image. Standalone."),
 (270058,"city (ir)","v7: 'till they reached a CITY (ir) to dwell in' - the home God brought them to, image. Standalone."),
 (270059,"dwell in (moshab)","v7: 'a city to DWELL IN (moshab)' - the settled home reached, image. Standalone."),
 (269865,"sat (yashab)","v10: 'Some SAT (yashab) in darkness and in the shadow of death' - the prisoners' dark confinement, image. Standalone."),
 (269866,"darkness (choshek)","v10: 'sat in DARKNESS (choshek)' - the dark of the dungeon, image. Standalone."),
 (269867,"shadow of death (tsalmaveth)","v10: 'and in the SHADOW OF DEATH (tsalmaveth)' - the deathly gloom, image. Standalone."),
 (269868,"prisoners (asir)","v10: 'PRISONERS (asir) in affliction and in irons' - the bound captives (char affliction, 269869). Standalone."),
 (269870,"irons (barzel)","v10: 'in affliction and in IRONS (barzel)' - the fetters, image of bondage. Standalone."),
 (269878,"down (kana)","v12: 'he bowed their hearts DOWN (kana)' - the humbling of the heart, image (char hearts, 269877). Standalone."),
 (269879,"hard labor (amal)","v12: 'bowed their hearts down with HARD LABOUR (amal)' - the toil that broke them, image. Standalone."),
 (269881,"fell down (kashal)","v12: 'they FELL DOWN (kashal), with none to help' - the collapse of the prisoners, image. Standalone."),
 (269882,"help (azar)","v12: 'with none to HELP (azar)' - the absence of aid, image of helplessness. Standalone."),
 (269889,"distress (metsuqah)","v13: 'he delivered them from their DISTRESS (metsuqah)' - the trouble of the prisoners (refrain), image. Standalone."),
 (307491,"darkness (choshek)","v14: 'He brought them out of DARKNESS (choshek)' - the dungeon-dark, image. Standalone."),
 (307492,"shadow of death (tsalmaveth)","v14: 'and the SHADOW OF DEATH (tsalmaveth)' - the deathly gloom, image. Standalone."),
 (307494,"bonds (moserah)","v14: 'and burst their BONDS (moserah) apart' - the chains broken, image. Standalone."),
 (307496,"doors (deleth)","v16: 'he shatters the DOORS (deleth) of bronze' - the prison gates, image. Standalone."),
 (307497,"bronze (nechosheth)","v16: 'the doors of BRONZE (nechosheth)' - the bronze gates, image. Standalone."),
 (307498,"cuts (gada)","v16: 'and CUTS (gada) in two the bars of iron' - the sundered bars, image. Standalone."),
 (307499,"bars (beriach)","v16: 'the BARS (beriach) of iron' - the prison bars, image. Standalone."),
 (307500,"iron (barzel)","v16: 'the bars of IRON (barzel)' - the iron of the prison, image. Standalone."),
 (269897,"through (derek)","v17: 'fools THROUGH (derek) their sinful ways' - the way of the fools, image (char fools, 269896). Standalone."),
 (269904,"food (okel)","v18: 'their soul loathed any kind of FOOD (okel)' - the food the sick refuse, image (char loathed, 269902). Standalone."),
 (269905,"near (naga)","v18: 'and they drew NEAR (naga) to the gates of death' - the approach of death, image. Standalone."),
 (269906,"gates (shaar)","v18: 'to the GATES (shaar) of death' - death's gates, image. Standalone."),
 (269907,"death (maveth)","v18: 'the gates of DEATH (maveth)' - death itself, image. Standalone."),
 (269914,"distress (metsuqah)","v19: 'he delivered them from their DISTRESS (metsuqah)' - the trouble of the sick (refrain), image. Standalone."),
 (269925,"destruction (shechith)","v20: 'and delivered them from their DESTRUCTION (shechith)' - the death-pit, image. Standalone."),
 (269932,"offer (zabach)","v22: 'And let them OFFER (zabach) sacrifices of thanksgiving' - the offering of the char thanksgiving (269934). Standalone."),
 (269933,"sacrifices (zebach)","v22: 'sacrifices (zebach) of thanksgiving' - the thank-offerings, image of worship. Standalone."),
 (307503,"ships (oniyah)","v23: 'Some went down to the sea in SHIPS (oniyah)' - the sailors' vessels, image. Standalone."),
 (307504,"doing (asah)","v23: 'DOING (asah) business on the great waters' - the sailors' trade, image. Standalone."),
 (307505,"business (melakah)","v23: 'doing BUSINESS (melakah) on the great waters' - the sea-trade, image. Standalone."),
 (307506,"great (rab)","v23: 'on the GREAT (rab) waters' - the vast sea, image. Standalone."),
 (307507,"waters (mayim)","v23: 'on the great WATERS (mayim)' - the ocean, image. Standalone."),
 (269943,"deep (metsulah)","v24: 'his wondrous works in the DEEP (metsulah)' - the ocean-depths, image. Standalone."),
 (269946,"stormy (saar)","v25: 'raised the STORMY (saar) wind' - the tempest, image. Standalone."),
 (269947,"wind (ruach)","v25: 'raised the stormy WIND (ruach)' - the storm-wind, image. Standalone."),
 (269948,"lifted up (rum)","v25: 'which LIFTED UP (rum) the waves of the sea' - the towering waves, image. Standalone."),
 (269949,"waves (gal)","v25: 'lifted up the WAVES (gal)' - the sea's breakers, image. Standalone."),
 (269950,"mounted up (alah)","v26: 'They MOUNTED UP (alah) to heaven' - the ship tossed skyward, image. Standalone."),
 (269951,"heaven (shamayim)","v26: 'mounted up to HEAVEN (shamayim)' - the crest of the wave, image. Standalone."),
 (269953,"depths (tehom)","v26: 'they went down to the DEPTHS (tehom)' - the trough of the wave, image. Standalone."),
 (269956,"plight (raa)","v26: 'in their evil PLIGHT (raa)' - the sailors' peril, image. Standalone."),
 (307508,"reeled (chagag)","v27: 'They REELED (chagag) and staggered like drunken men' - the pitching sailors, image. Standalone."),
 (307509,"staggered (nua)","v27: 'reeled and STAGGERED (nua)' - the lurching of the crew, image. Standalone."),
 (307510,"drunken (shikkor)","v27: 'like DRUNKEN (shikkor) men' - the reeling likened to drunkenness, image. Standalone."),
 (307512,"end (bala)","v27: 'and were at their wits' END (bala)' - the exhaustion of skill (char wits, 307511), image. Standalone."),
 (269965,"storm (saar)","v29: 'He made the STORM (saar) be still' - the tempest calmed, image. Standalone."),
 (269967,"waves (gal)","v29: 'the WAVES (gal) of the sea were hushed' - the stilled breakers, image. Standalone."),
 (269970,"quiet (shathaq)","v30: 'glad that the waters were QUIET (shathaq)' - the calmed sea, image (char glad, 269969). Standalone."),
 (269974,"haven (machoz)","v30: 'to their desired HAVEN (machoz)' - the longed-for harbour, image (char desired, 269973). Standalone."),
 (269982,"congregation (qahal)","v32: 'extol him in the CONGREGATION (qahal) of the people' - the assembly of worship, setting. Standalone."),
 (269986,"assembly (moshab)","v32: 'praise him in the ASSEMBLY (moshab) of the elders' - the council of elders, setting. Standalone."),
 (269987,"elders (zaqen)","v32: 'the assembly of the ELDERS (zaqen)' - the elders before whom praise is given. Standalone."),
 (307514,"rivers (nahar)","v33: 'He turns RIVERS (nahar) into a desert' - the dried rivers, image of God's reversal. Standalone."),
 (307515,"desert (midbar)","v33: 'rivers into a DESERT (midbar)' - the wasted land, image. Standalone."),
 (307516,"springs (motsa)","v33: 'the SPRINGS (motsa) of water into thirsty ground' - the dried springs, image. Standalone."),
 (307517,"water (mayim)","v33: 'the springs of WATER (mayim)' - the water withdrawn, image. Standalone."),
 (307518,"thirsty ground (tsimmaon)","v33: 'into THIRSTY GROUND (tsimmaon)' - the parched land, image. Standalone."),
 (269990,"salty waste (melechah)","v34: 'a fruitful land into a SALTY WASTE (melechah)' - the barren salt-flat, image of judgment. Standalone."),
 (269993,"inhabitants (yashab)","v34: 'because of the evil of its INHABITANTS (yashab)' - the wicked dwellers (char evil, 269991). Standalone."),
 (307520,"desert (midbar)","v35: 'He turns a DESERT (midbar) into pools of water' - the transformed wasteland, image. Standalone."),
 (307521,"pools (agam)","v35: 'a desert into POOLS (agam) of water' - the new waters, image of blessing. Standalone."),
 (307522,"water (mayim)","v35: 'pools of WATER (mayim)' - the water given, image. Standalone."),
 (307523,"parched (tsiyyah)","v35: 'a PARCHED (tsiyyah) land into springs of water' - the dry land renewed, image. Standalone."),
 (307525,"springs (motsa)","v35: 'into SPRINGS (motsa) of water' - the new springs, image. Standalone."),
 (307526,"water (mayim)","v35: 'springs of WATER (mayim)' - the water given, image. Standalone."),
 (307530,"city (ir)","v36: 'they establish a CITY (ir) to live in' - the settled city, image. Standalone."),
 (307531,"live in (moshab)","v36: 'a city to LIVE IN (moshab)' - the settled home, image. Standalone."),
 (269994,"sow (zara)","v37: 'they SOW (zara) fields and plant vineyards' - the settled agriculture, image of blessing. Standalone."),
 (269995,"fields (sadeh)","v37: 'they sow FIELDS (sadeh)' - the tilled land, image. Standalone."),
 (269996,"plant (nata)","v37: 'and PLANT (nata) vineyards' - the planting, image. Standalone."),
 (269997,"vineyards (kerem)","v37: 'plant VINEYARDS (kerem)' - the vines, image of settled blessing. Standalone."),
 (269998,"get (asah)","v37: 'and GET (asah) a fruitful yield' - the harvest, image. Standalone."),
 (269999,"fruitful (peri)","v37: 'a FRUITFUL (peri) yield' - the produce, image of blessing. Standalone."),
 (270000,"yield (tebuah)","v37: 'a fruitful YIELD (tebuah)' - the crop-yield, image. Standalone."),
 (270008,"oppression (otser)","v39: 'through OPPRESSION (otser), evil, and sorrow' - the affliction that brings them low (char brought-low, 270007), image. Standalone."),
 (270009,"evil (raa)","v39: 'through oppression, EVIL (raa), and sorrow' - the adversity, image. Standalone."),
 (270019,"contempt (buz)","v40: 'He pours CONTEMPT (buz) on princes' - the scorn poured on the mighty, image. Standalone."),
 (270021,"princes (nadib)","v40: 'He pours contempt on PRINCES (nadib)' - the nobles brought low (char wander, 270022). Standalone."),
 (270023,"trackless (tohu)","v40: 'makes them wander in TRACKLESS (tohu) wastes' - the pathless waste, image. Standalone."),
 (270024,"wastes (derek)","v40: 'in trackless WASTES (derek)' - the roadless waste, image. Standalone."),
 (270027,"affliction (oni)","v41: 'he raises up the needy out of AFFLICTION (oni)' - the affliction the needy are raised from (char needy, 270026). Standalone."),
 (270029,"families (mishpachah)","v41: 'and makes their FAMILIES (mishpachah) like flocks' - the multiplied households, image. Standalone."),
 (270030,"flocks (tson)","v41: 'like FLOCKS (tson)' - the flock-image of the needy's increase. Standalone."),
 (270032,"see (raah)","v42: 'The upright SEE (raah) it and are glad' - the upright's beholding of God's justice (char upright, 270031). Standalone."),
 (270036,"shuts (qaphats)","v42: 'and all wickedness SHUTS (qaphats) its mouth' - the silencing of the wicked (char wickedness, 270035), image. Standalone."),
 (270037,"mouth (peh)","v42: 'shuts its MOUTH (peh)' - the wicked struck dumb, image. Standalone."),
]
for sid,sense,d in ST: r.st(sid,sense,d)
r.write()
