import sys; sys.path.insert(0,'scripts')
from _reread_ledger_lib import Reading, IB, GOD, PER
r=Reading("Psa",19,105,
  note="Ps105 covenant-history hymn (45v, 174 spans). Read by CHAR-ARC. Arcs: A worship-call v1-6 (give-thanks/call/known/sing/sing-praises/tell/glory/seek-hearts/rejoice/seek/seek/remember); B patriarch-sojourners v12+v23; C Joseph's affliction->wisdom v18-22 (HURT with fetters -> at his PLEASURE, TEACH elders wisdom); D Egyptians' hearts turned to HATE + DEAL-CRAFTILY v25; E Moses/Aaron did not REBEL v28; F Egypt GLAD + DREAD at the Exodus v38; G redemption JOY + SINGING -> KEEP/OBSERVE statutes -> PRAISE v43-45. Between = God's covenant ACTS (qualifiers) + plague/Exodus imagery (standalone).")
CH=[
 # Arc A: worship-call (v1-6)
 (269364,"give thanks (yadah)","action","the worshippers","give thanks","to the LORD",GOD,"paired with calling on his name and making known his deeds","v1: 'Oh GIVE THANKS (yadah) to the LORD' - the summons that opens the covenant-hymn, gratitude for God's faithfulness."),
 (269366,"call (qara)","action","the worshippers","call upon","God's name",GOD,"paired with giving thanks","v1: 'CALL (qara) upon his name' - the invoking of God, worship as appeal to his name."),
 (269368,"make known (yada)","action","the worshippers","make known","God's deeds among the peoples",PER,"paired with giving thanks","v1: 'make KNOWN (yada) his deeds among the peoples!' - the proclaiming of God's works to the nations, worship as witness."),
 (269414,"sing (shir)","action","the worshippers","sing","to God",GOD,"paired with singing praises and telling his works","v2: 'SING (shir) to him' - the sung praise of God's covenant faithfulness."),
 (269415,"sing praises (zamar)","action","the worshippers","sing praises","to God",GOD,"paired with singing","v2: 'SING PRAISES (zamar) to him' - the melody of worship."),
 (269416,"tell (siach)","action","the worshippers","tell / muse on","all God's wondrous works",GOD,"paired with singing","v2: 'TELL (siach) of all his wondrous works!' - the recounting of God's marvels, worship as rehearsal."),
 (269471,"glory (halal)","action","the worshippers","glory / boast","in God's holy name",GOD,"paired with seeking hearts rejoicing","v3: 'GLORY (halal) in his holy name' - the exulting in God's name, boasting in him rather than self."),
 (269474,"hearts (leb)","faculty","those who seek God","have the heart rejoice","in seeking God",IB,"paired with seeking and rejoicing","v3: 'let the HEARTS (leb) of those who seek the LORD rejoice!' - the inner self of the seekers gladdened, joy seated in the heart."),
 (269475,"seek (baqash)","action","the worshippers","seek","the LORD",GOD,"paired with the rejoicing heart","v3: 'the hearts of those who SEEK (baqash) the LORD' - the pursuit of God, the disposition of the true worshipper."),
 (269477,"rejoice (samach)","state","the seekers","rejoice","in God",IB,"paired with the seeking heart","v3: 'let the hearts of those who seek the LORD REJOICE (samach)!' - the gladness of those who seek God, joy as seeking's reward."),
 (269494,"seek (darash)","action","the worshippers","seek","the LORD and his strength",GOD,"paired with seeking his presence","v4: 'SEEK (darash) the LORD and his strength' - the resolute seeking of God, worship as constant pursuit."),
 (269497,"seek (baqash)","action","the worshippers","seek","God's presence continually",GOD,"paired with seeking his strength","v4: 'SEEK (baqash) his presence continually!' - the unceasing seeking of God's face."),
 (269539,"remember (zakar)","action","the worshippers","remember","God's wondrous works",GOD,"paired with the wondrous works and covenant","v5: 'REMEMBER (zakar) the wondrous works that he has done' - the deliberate recalling of God's deeds, the hinge into the covenant-recital."),
 # Arc B: patriarch-sojourners
 (307358,"sojourners (gur)","status","the patriarchs","be sojourners / strangers","in the land",IB,"paired with being few in number","v12: 'When they were few in number, and SOJOURNERS (gur) in it' - the pilgrim status of the patriarchs, strangers in the land of promise."),
 (307386,"sojourn (gur)","status","Israel/Jacob","sojourn as a stranger","in the land of Ham",IB,"paired with the patriarch-sojourners (v12)","v23: 'Jacob SOJOURNED (gur) in the land of Ham' - Israel a stranger in Egypt, the sojourning renewed a generation on."),
 # Arc C: Joseph
 (269408,"be hurt (anah)","state","Joseph","be afflicted","his feet hurt with fetters",IB,"paired with his exaltation to bind princes at his pleasure","v18: 'His feet were HURT (anah) with fetters' - Joseph's affliction in the pit of slavery, the low point before the exaltation."),
 (269436,"pleasure / will (nephesh)","faculty","Joseph","exercise his will","binding princes at his pleasure",IB,"paired with his affliction and his teaching","v22: 'to bind his princes at his PLEASURE (nephesh)' - Joseph's own will and discretion, the authority given the once-fettered slave."),
 (269437,"teach (chakam)","action","Joseph","teach wisdom","to Pharaoh's elders",IB,"paired with binding princes at his pleasure","v22: 'and TEACH (chakam) his elders wisdom' - Joseph the wise, instructing Egypt's counsellors, affliction turned to influence."),
 # Arc D: Egyptians' malice
 (269447,"hearts (leb)","faculty","the Egyptians","have the heart turned","to hate God's people",IB,"paired with the hatred and craft","v25: 'He turned their HEARTS (leb) to hate his people' - the Egyptians' inner disposition turned against Israel, hearts bent to enmity."),
 (269448,"hate (sane)","disposition","the Egyptians","hate","God's people",IB,"paired with the turned heart","v25: 'to HATE (sane) his people' - the enmity of the Egyptians, hatred as the ground of the oppression."),
 (269451,"deal craftily (nakal)","action","the Egyptians","deal craftily / scheme","against God's servants",IB,"paired with the hatred","v25: 'to DEAL CRAFTILY (nakal) with his servants' - the cunning malice of the Egyptians, hatred turned to calculated oppression."),
 # Arc E: Moses/Aaron obedience
 (307393,"rebel (marah, negated)","disposition","Moses and Aaron","not rebel","against God's words",GOD,"paired with performing the signs","v28: 'they did not REBEL (marah) against his words' - the obedience of Moses and Aaron, faithful agents who did not resist God's commission."),
 # Arc F: Egypt glad + dread
 (269487,"glad (samach)","state","the Egyptians","be glad","when Israel departed",IB,"paired with the dread that fell on them","v38: 'Egypt was GLAD (samach) when they departed' - the relief of the Egyptians at Israel's exit, gladness born of terror."),
 (269490,"dread (pachad)","state","the Egyptians","be seized with dread","of Israel",IB,"paired with the gladness","v38: 'for DREAD (pachad) of them had fallen upon Egypt' - the terror of the Egyptians after the plagues, fear that made them glad to see Israel go."),
 # Arc G: redemption -> obedience -> praise
 (269522,"joy (sason)","state","God's people","be brought out with joy","from Egypt",IB,"paired with the singing","v43: 'So he brought his people out with JOY (sason)' - the exultation of the redeemed at the Exodus, deliverance crowned with joy."),
 (269525,"singing (rinnah)","action","the chosen ones","sing","at the Exodus",GOD,"paired with the joy","v43: 'his chosen ones with SINGING (rinnah)' - the song of the redeemed, joy voiced in praise."),
 (269533,"keep (shamar)","action","God's people","keep","God's statutes",GOD,"paired with observing his laws","v45: 'that they might KEEP (shamar) his statutes' - the purpose of the whole redemption: an obedient people, deliverance issuing in law-keeping."),
 (269535,"observe (natsar)","action","God's people","observe","God's laws",GOD,"paired with keeping his statutes","v45: 'and OBSERVE (natsar) his laws' - the guarding of God's laws, the covenant's intended fruit in the redeemed."),
 (269537,"praise (halal)","action","the worshippers","praise","the LORD",GOD,"paired with keeping and observing","v45: 'PRAISE (halal) the LORD!' - the closing Hallelujah, the covenant-history sealed with praise."),
]
for a in CH: r.ch(*a)
A=269364; COV=269539; JOS=269408; MAL=269448; EXO=269522  # source anchors by arc
QU=[
 (269367,"name (shem)",A,"v1: 'call upon his NAME (shem)' - God's name. Qualifier."),
 (269370,"deeds (alilah)",A,"v1: 'make known his DEEDS (alilah)' - God's deeds. Qualifier."),
 (269419,"wondrous works (pala)",A,"v2: 'tell of all his WONDROUS WORKS (pala)' - God's marvels. Qualifier."),
 (269472,"holy (qodesh)",A,"v3: 'Glory in his HOLY (qodesh) name' - God's holiness. Qualifier."),
 (269473,"name (shem)",A,"v3: 'in his holy NAME (shem)' - God's name. Qualifier."),
 (269496,"strength (oz)",A,"v4: 'Seek the LORD and his STRENGTH (oz)' - God's strength. Qualifier."),
 (269540,"wondrous works (pala)",COV,"v5: 'Remember the WONDROUS WORKS (pala) that he has done' - God's marvels. Qualifier."),
 (269542,"done (asah)",COV,"v5: 'the wondrous works that he has DONE (asah)' - God's working. Qualifier."),
 (269543,"miracles (mopheth)",COV,"v5: 'his MIRACLES (mopheth)' - God's wonders. Qualifier."),
 (269544,"judgments (mishpat)",COV,"v5: 'and the JUDGMENTS (mishpat) he uttered' - God's judgments. Qualifier."),
 (269545,"uttered (peh)",COV,"v5: 'the judgments he UTTERED (peh)' - God's spoken judgments. Qualifier."),
 (269556,"judgments (mishpat)",COV,"v7: 'his JUDGMENTS (mishpat) are in all the earth' - God's judgments. Qualifier."),
 (269559,"remembers (zakar)",COV,"v8: 'He REMEMBERS (zakar) his covenant forever' - God's faithful remembrance. Qualifier."),
 (269560,"covenant (berith)",COV,"v8: 'He remembers his COVENANT (berith) forever' - God's covenant. Qualifier."),
 (269562,"word (dabar)",COV,"v8: 'the WORD (dabar) that he commanded' - God's word. Qualifier."),
 (269563,"commanded (tsavah)",COV,"v8: 'the word that he COMMANDED (tsavah)' - God's command. Qualifier."),
 (269567,"made (karath)",COV,"v9: 'the covenant that he MADE (karath) with Abraham' - God's covenant-making. Qualifier."),
 (269570,"sworn promise (shebuah)",COV,"v9: 'his SWORN PROMISE (shebuah) to Isaac' - God's oath. Qualifier."),
 (269372,"confirmed (amad)",COV,"v10: 'which he CONFIRMED (amad) to Jacob as a statute' - God's confirming. Qualifier."),
 (269374,"statute (choq)",COV,"v10: 'confirmed to Jacob as a STATUTE (choq)' - God's statute. Qualifier."),
 (269378,"covenant (berith)",COV,"v10: 'an everlasting COVENANT (berith)' - God's covenant. Qualifier."),
 (269381,"give (nathan)",COV,"v11: 'To you I will GIVE (nathan) the land of Canaan' - God's covenant grant. Qualifier."),
 (269386,"allow (nuach, negated)",307358,"v14: 'he ALLOWED (nuach) no one to oppress them' - God's protection of the patriarchs. Qualifier."),
 (269390,"rebuked (yakach)",307358,"v14: 'he REBUKED (yakach) kings on their account' - God's rebuke of kings. Qualifier."),
 (269393,"touch (naga)",307358,"v15: 'TOUCH (naga) not my anointed ones' - God's protective command. Qualifier."),
 (269399,"summoned (qara)",JOS,"v16: 'he SUMMONED (qara) a famine on the land' - God's calling of the famine. Qualifier."),
 (269403,"broke (shabar)",JOS,"v16: 'and BROKE (shabar) all supply of bread' - God's breaking of the food-supply. Qualifier."),
 (307369,"sent (shalach)",JOS,"v17: 'he had SENT (shalach) a man ahead of them, Joseph' - God's providential sending. Qualifier."),
 (307380,"tested (tsaraph)",JOS,"v19: 'the word of the LORD TESTED (tsaraph) him' - God's word proving Joseph. Qualifier."),
 (269421,"sent (shalach)",JOS,"v20: 'The king SENT (shalach) and released him' - God's providence through the king. Qualifier."),
 (269422,"released (nathar)",JOS,"v20: 'and RELEASED (nathar) him' - Joseph freed. Qualifier."),
 (269425,"set free (pathach)",JOS,"v20: 'the ruler of the peoples SET him FREE (pathach)' - Joseph liberated. Qualifier."),
 (269426,"made (sim)",JOS,"v21: 'he MADE (sim) him lord of his house' - God's exaltation of Joseph. Qualifier."),
 (269441,"fruitful (parah)",MAL,"v24: 'the LORD made his people very FRUITFUL (parah)' - God's multiplying of Israel. Qualifier."),
 (269442,"stronger (atsam)",MAL,"v24: 'made them STRONGER (atsam) than their foes' - God's strengthening. Qualifier."),
 (269446,"turned (haphak)",MAL,"v25: 'He TURNED (haphak) their hearts to hate his people' - God's sovereign turning of the Egyptians. Qualifier."),
 (269454,"sent (shalach)",307393,"v26: 'He SENT (shalach) Moses his servant' - God's commissioning of Moses. Qualifier."),
 (269459,"chosen (bachar)",307393,"v26: 'and Aaron, whom he had CHOSEN (bachar)' - God's choosing of Aaron. Qualifier."),
 (269460,"performed (sim)",307393,"v27: 'They PERFORMED (sim) his signs among them' - God's signs done through Moses. Qualifier."),
 (269461,"signs (dabar)",307393,"v27: 'his SIGNS (dabar)' - God's signs. Qualifier."),
 (269462,"miracles (mopheth)",307393,"v27: 'and MIRACLES (mopheth) in the land of Ham' - God's wonders. Qualifier."),
 (307389,"sent (shalach)",307393,"v28: 'He SENT (shalach) darkness, and made the land dark' - God's plague of darkness. Qualifier."),
 (307395,"words (dabar)",307393,"v28: 'they did not rebel against his WORDS (dabar)' - God's words. Qualifier."),
 (269465,"turned (haphak)",EXO,"v29: 'He TURNED (haphak) their waters into blood' - God's plague. Qualifier."),
 (305857,"gave (nathan)",EXO,"v32: 'He GAVE (nathan) them hail for rain' - God's plague of hail. Qualifier."),
 (307409,"struck down (nakah)",EXO,"v33: 'He STRUCK DOWN (nakah) their vines and fig trees' - God's plague. Qualifier."),
 (307412,"shattered (shabar)",EXO,"v33: 'and SHATTERED (shabar) the trees of their country' - God's plague. Qualifier."),
 (269478,"struck down (nakah)",EXO,"v36: 'He STRUCK DOWN (nakah) all the firstborn in their land' - God's climactic plague. Qualifier."),
 (307430,"brought out (yatsa)",EXO,"v37: 'Then he BROUGHT OUT (yatsa) Israel with silver and gold' - God's Exodus deliverance. Qualifier."),
 (307436,"spread (paras)",EXO,"v39: 'He SPREAD (paras) a cloud for a covering' - God's protective cloud. Qualifier."),
 (269501,"brought (bo)",EXO,"v40: 'They asked, and he BROUGHT (bo) quail' - God's provision. Qualifier."),
 (269506,"opened (pathach)",EXO,"v41: 'He OPENED (pathach) the rock, and water gushed out' - God's provision of water. Qualifier."),
 (269514,"remembered (zakar)",EXO,"v42: 'For he REMEMBERED (zakar) his holy promise' - God's faithful remembrance. Qualifier."),
 (269515,"holy (qodesh)",EXO,"v42: 'his HOLY (qodesh) promise' - God's holiness. Qualifier."),
 (269516,"promise (dabar)",EXO,"v42: 'his holy PROMISE (dabar) to Abraham' - God's promise. Qualifier."),
 (269520,"brought out (yatsa)",EXO,"v43: 'So he BROUGHT (yatsa) his people out with joy' - God's Exodus deliverance. Qualifier."),
 (269526,"gave (nathan)",269533,"v44: 'And he GAVE (nathan) them the lands of the nations' - God's gift of the land. Qualifier."),
 (269534,"statutes (choq)",269533,"v45: 'that they might keep his STATUTES (choq)' - God's statutes. Qualifier."),
 (269536,"laws (torah)",269533,"v45: 'and observe his LAWS (torah)' - God's laws. Qualifier."),
]
for sid,sense,src,d in QU: r.qu(sid,sense,src,d)
ST=[
 (269548,"servant (ebed)","v6: 'O offspring of Abraham, his SERVANT (ebed)' - Abraham as God's servant; the covenant-people descriptor. Standalone."),
 (269551,"chosen ones (bachir)","v6: 'children of Jacob, his CHOSEN ONES (bachir)' - Israel as God's elect; descriptor. Standalone."),
 (269561,"forever (olam)","v8: 'He remembers his covenant FOREVER (olam)' - the perpetuity of God's covenant; temporal. Standalone."),
 (269377,"everlasting (olam)","v10: 'an EVERLASTING (olam) covenant' - the endlessness of the covenant; temporal. Standalone."),
 (269384,"portion (chebel)","v11: 'as your PORTION (chebel) for an inheritance' - the measured land, image of the inheritance. Standalone."),
 (269385,"inheritance (nachalah)","v11: 'as your portion for an INHERITANCE (nachalah)' - the promised land, image. Standalone."),
 (307355,"few (mat)","v12: 'When they were FEW (mat) in number' - the smallness of the patriarchs, image (char sojourners, 307358). Standalone."),
 (307356,"number (mispar)","v12: 'few in NUMBER (mispar)' - the small count, image. Standalone."),
 (307366,"kingdom (mamlakah)","v13: 'from one KINGDOM (mamlakah) to another people' - the lands the patriarchs wandered, image. Standalone."),
 (269389,"oppress (ashaq)","v14: 'he allowed no one to OPPRESS (ashaq) them' - the oppression God prevented, image. Standalone."),
 (269395,"anointed ones (mashiach)","v15: 'Touch not my ANOINTED ONES (mashiach)' - the patriarchs as God's anointed, the protected. Standalone."),
 (269396,"prophets (nabi)","v15: 'do my PROPHETS (nabi) no harm!' - the patriarchs as prophets, the protected. Standalone."),
 (269398,"harm (raa)","v15: 'do my prophets no HARM (raa)!' - the harm God forbids, image. Standalone."),
 (269400,"famine (raab)","v16: 'he summoned a FAMINE (raab) on the land' - the famine, image of the providential setup. Standalone."),
 (269405,"supply (matteh)","v16: 'broke all SUPPLY (matteh) of bread' - the staff/store of bread, image. Standalone."),
 (269406,"bread (lechem)","v16: 'all supply of BREAD (lechem)' - the food, image. Standalone."),
 (307373,"sold (makar)","v17: 'Joseph, who was SOLD (makar) as a slave' - Joseph's sale, the event of his abasement. Standalone."),
 (307374,"slave (ebed)","v17: 'sold as a SLAVE (ebed)' - Joseph's servitude, image. Standalone."),
 (269407,"feet (regel)","v18: 'His FEET (regel) were hurt with fetters' - Joseph's fettered feet, image of his affliction (char, 269408). Standalone."),
 (269409,"fetters (kebel)","v18: 'hurt with FETTERS (kebel)' - the shackles, image of bondage. Standalone."),
 (269411,"neck (nephesh)","v18: 'his NECK (nephesh) was put in a collar of iron' - Joseph's iron collar, image of bondage. Standalone."),
 (269412,"put (bo)","v18: 'his neck was PUT (bo) in iron' - the placing in irons, image. Standalone."),
 (269413,"iron (barzel)","v18: 'in a collar of IRON (barzel)' - the iron of the prison, image. Standalone."),
 (307376,"said (imrah)","v19: 'until what he had SAID (imrah) came to pass' - Joseph's word (the dream), image. Standalone."),
 (307377,"came to pass (bo)","v19: 'until what he had said CAME TO PASS (bo)' - the fulfilment, image. Standalone."),
 (269423,"ruler (mashal)","v20: 'the RULER (mashal) of the peoples' - Pharaoh, who freed Joseph. Standalone."),
 (269429,"ruler (mashal)","v21: 'he made him RULER (mashal) of all his possessions' - Joseph's office, image of his exaltation. Standalone."),
 (269432,"possessions (qinyan)","v21: 'ruler of all his POSSESSIONS (qinyan)' - Pharaoh's estate, image. Standalone."),
 (269434,"bind (asar)","v22: 'to BIND (asar) his princes' - Joseph's authority over the princes, image. Standalone."),
 (269435,"princes (sar)","v22: 'to bind his PRINCES (sar)' - Egypt's officials under Joseph, image. Standalone."),
 (269438,"elders (zaqen)","v22: 'and teach his ELDERS (zaqen) wisdom' - Pharaoh's counsellors Joseph taught (char teach, 269437). Standalone."),
 (307383,"came (bo)","v23: 'Then Israel CAME (bo) to Egypt' - Israel's entry into Egypt, event. Standalone."),
 (269445,"foes (tsar)","v24: 'made them stronger than their FOES (tsar)' - the Egyptian adversaries, image. Standalone."),
 (269453,"servants (ebed)","v25: 'to deal craftily with his SERVANTS (ebed)' - Israel as God's servants, the victims of the craft. Standalone."),
 (269456,"servant (ebed)","v26: 'He sent Moses his SERVANT (ebed)' - Moses as God's servant, descriptor. Standalone."),
 (307390,"darkness (choshek)","v28: 'He sent DARKNESS (choshek)' - the plague of darkness, image. Standalone."),
 (307391,"dark (chashak)","v28: 'and made the land DARK (chashak)' - the darkened land, image. Standalone."),
 (269467,"blood (dam)","v29: 'He turned their waters into BLOOD (dam)' - the blood-plague, image. Standalone."),
 (269469,"fish (dagah)","v29: 'and caused their FISH (dagah) to die' - the dead fish, image. Standalone."),
 (269470,"die (muth)","v29: 'caused their fish to DIE (muth)' - the fish killed, image. Standalone."),
 (307397,"swarmed (sharats)","v30: 'Their land SWARMED (sharats) with frogs' - the frog-plague, image. Standalone."),
 (307398,"frogs (tsephardea)","v30: 'swarmed with FROGS (tsephardea)' - the frogs, image. Standalone."),
 (307399,"chambers (cheder)","v30: 'even in the CHAMBERS (cheder) of their kings' - the frogs in the palace, image. Standalone."),
 (307403,"came (bo)","v31: 'He spoke, and there CAME (bo) swarms of flies' - the fly-plague, image. Standalone."),
 (307404,"flies (arob)","v31: 'there came swarms of FLIES (arob)' - the flies, image. Standalone."),
 (307405,"gnats (ken)","v31: 'and GNATS (ken) throughout their country' - the gnats, image. Standalone."),
 (305858,"hail (barad)","v32: 'He gave them HAIL (barad) for rain' - the hail-plague, image. Standalone."),
 (305859,"rain (geshem)","v32: 'hail for RAIN (geshem)' - the storm, image. Standalone."),
 (305860,"fiery (esh)","v32: 'and FIERY (esh) lightning bolts' - the fire in the hail, image. Standalone."),
 (305861,"lightning bolts (lehabah)","v32: 'fiery LIGHTNING BOLTS (lehabah)' - the flames, image. Standalone."),
 (307410,"vines (gephen)","v33: 'He struck down their VINES (gephen)' - the ruined vines, image. Standalone."),
 (307411,"fig trees (teenah)","v33: 'their VINES and FIG TREES (teenah)' - the ruined figs, image. Standalone."),
 (307413,"trees (ets)","v33: 'and shattered the TREES (ets) of their country' - the felled trees, image. Standalone."),
 (307417,"locusts (arbeh)","v34: 'He spoke, and the LOCUSTS (arbeh) came' - the locust-plague, image. Standalone."),
 (307418,"came (bo)","v34: 'and the locusts CAME (bo)' - the locusts arriving, image. Standalone."),
 (307419,"young locusts (yeleq)","v34: 'YOUNG LOCUSTS (yeleq) without number' - the locust-swarm, image. Standalone."),
 (307421,"number (mispar)","v34: 'young locusts without NUMBER (mispar)' - the countless swarm, image. Standalone."),
 (307422,"devoured (akal)","v35: 'which DEVOURED (akal) all the vegetation' - the locusts eating, image. Standalone."),
 (307424,"vegetation (eseb)","v35: 'devoured all the VEGETATION (eseb)' - the eaten plants, image. Standalone."),
 (307426,"ate up (akal)","v35: 'and ATE UP (akal) the fruit of their ground' - the locusts consuming, image. Standalone."),
 (307427,"fruit (peri)","v35: 'the FRUIT (peri) of their ground' - the devoured harvest, image. Standalone."),
 (269480,"firstborn (bekor)","v36: 'all the FIRSTBORN (bekor) in their land' - Egypt's firstborn, struck down; image. Standalone."),
 (269482,"firstfruits (reshith)","v36: 'the FIRSTFRUITS (reshith) of all their strength' - the firstborn as first-strength, image. Standalone."),
 (269485,"strength (on)","v36: 'the firstfruits of all their STRENGTH (on)' - Egypt's vigour struck in the firstborn, image. Standalone."),
 (307431,"silver (keseph)","v37: 'with SILVER (keseph) and gold' - the plunder of Egypt, image. Standalone."),
 (307432,"gold (zahab)","v37: 'with silver and GOLD (zahab)' - the Exodus wealth, image. Standalone."),
 (307434,"tribes (shebet)","v37: 'none among his TRIBES (shebet) stumbled' - the tribes of Israel, image. Standalone."),
 (307435,"stumbled (kashal)","v37: 'none among his tribes STUMBLED (kashal)' - the unfaltering march, image of God's care. Standalone."),
 (269488,"departed (yatsa)","v38: 'Egypt was glad when they DEPARTED (yatsa)' - Israel's exit, event (char glad, 269487). Standalone."),
 (269491,"fallen (naphal)","v38: 'for dread of them had FALLEN (naphal) upon Egypt' - the dread that fell, image (char dread, 269490). Standalone."),
 (307437,"cloud (anan)","v39: 'He spread a CLOUD (anan) for a covering' - the guiding cloud, image. Standalone."),
 (307438,"covering (masak)","v39: 'a cloud for a COVERING (masak)' - the cloud-shade, image. Standalone."),
 (307439,"fire (esh)","v39: 'and FIRE (esh) to give light by night' - the pillar of fire, image. Standalone."),
 (307440,"give light (or)","v39: 'fire to GIVE LIGHT (or) by night' - the night-light, image. Standalone."),
 (269500,"asked (shaal)","v40: 'They ASKED (shaal), and he brought quail' - the people's request for meat, image. Standalone."),
 (269502,"quail (selav)","v40: 'and he brought QUAIL (selav)' - the quail-provision, image. Standalone."),
 (269503,"bread (lechem)","v40: 'gave them BREAD (lechem) of heaven in abundance' - the manna, image. Standalone."),
 (269505,"abundance (saba)","v40: 'the bread of heaven in ABUNDANCE (saba)' - the fullness of provision, image. Standalone."),
 (269507,"rock (tsur)","v41: 'He opened the ROCK (tsur), and water gushed out' - the water-giving rock, image. Standalone."),
 (269509,"gushed out (halak)","v41: 'and water GUSHED OUT (halak)' - the flowing water, image. Standalone."),
 (269511,"desert (tsiyyah)","v41: 'it flowed through the DESERT (tsiyyah) like a river' - the dry land watered, image. Standalone."),
 (269512,"river (nahar)","v41: 'like a RIVER (nahar)' - the desert-stream, image. Standalone."),
 (269519,"servant (ebed)","v42: 'his holy promise to Abraham his SERVANT (ebed)' - Abraham as God's servant, descriptor. Standalone."),
 (269524,"chosen (bachir)","v43: 'his CHOSEN ONES (bachir) with singing' - Israel as God's elect (char singing, 269525). Standalone."),
 (269529,"possession (yarash)","v44: 'they took POSSESSION (yarash) of the fruit of the peoples' toil' - Israel inheriting the land, image. Standalone."),
 (269530,"fruit (amal)","v44: 'the FRUIT (amal) of the peoples' toil' - the nations' labour Israel inherited, image. Standalone."),
]
for sid,sense,d in ST: r.st(sid,sense,d)
r.write()
