import sys; sys.path.insert(0,'scripts')
from _reread_ledger_lib import Reading, IB, GOD, PER
r=Reading("Psa",19,91,
  note="Ps91 the psalm of refuge (16v). Passages: the dweller's confession v1-2; the promises of protection - snare, terror, arrow, pestilence, the angels' guard, victory over beasts v3-13; God's oracle 'because he loves me' v14-16. Human IB is the trusting relationship: ABIDING under God's shadow, taking REFUGE, TRUST, not FEARing the terror, MAKING God one's refuge; and God's oracle naming the one who LOVES / KNOWS his name / CALLS. God's shelter/deliver/cover/command-angels/answer/rescue/satisfy = qualifiers; wings/snare/arrow/pestilence/lion imagery = standalone.")
for a in [
 (307084,"abide (lun)","action","the one who dwells with God","abide / lodge","in the shadow of the Almighty",GOD,"paired with taking refuge","v1: 'He who dwells in the shelter of the Most High will ABIDE (lun) in the shadow of the Almighty' - the settled dwelling under God's protection, trust as taking up residence with him."),
 (285107,"refuge (machseh)","disposition","the psalmist","take as refuge","the LORD",GOD,"paired with trusting God","v2: 'I will say to the LORD, My REFUGE (machseh) and my fortress' - the naming of God as refuge, the confession of where safety is found."),
 (285112,"trust (batach)","disposition","the psalmist","trust","in God",GOD,"paired with taking God as refuge","v2: 'my God, in whom I TRUST (batach)' - the reliance on God that underlies the whole psalm's confidence."),
 (285127,"take refuge (chasah)","action","the trusting one","take refuge","under God's wings",GOD,"paired with God's faithfulness as shield","v4: 'under his wings you will find REFUGE (chasah)' - the sheltering under God like a bird's young, trust as running to his covering."),
 (285133,"fear (yare, negated)","state","the trusting one","not fear","the terrors of night and day",IB,"paired with the terror not feared","v5: 'You will not FEAR (yare) the terror of the night' - the fearlessness of the sheltered, dread dissolved by trust in God's protection."),
 (285148,"make (sim)","action","the trusting one","make God one's refuge","the Most High one's dwelling",GOD,"paired with God as dwelling place","v9: 'Because you have MADE (sim) the LORD your dwelling place' - the deliberate choosing of God as refuge, the act of faith that grounds the promises."),
 (285085,"love / cling (chashaq)","disposition","the one who loves God","hold fast in love","to God",GOD,"paired with knowing God's name","v14: 'Because he holds fast to me in LOVE (chashaq), I will deliver him' - the clinging devotion to God, love as the ground of God's deliverance."),
 (285089,"know (yada)","disposition","the one who loves God","know","God's name",GOD,"paired with holding fast in love","v14: 'I will protect him, because he KNOWS (yada) my name' - the intimate knowledge of God, acquaintance that God honours with protection."),
 (285092,"call (qara)","action","the one who loves God","call","to God in trouble",GOD,"paired with God's answer","v15: 'When he CALLS (qara) to me, I will answer him' - the calling on God that God pledges to answer, prayer met with presence in trouble."),
]: r.ch(*a)
for sid,sense,src,d in [
 (285108,"fortress (metsudah)",285107,"v2: 'my refuge and my FORTRESS (metsudah)' - God as stronghold. Qualifier."),
 (285115,"deliver (natsal)",285127,"v3: 'For he will DELIVER (natsal) you from the snare of the fowler' - God's rescue. Qualifier."),
 (285121,"pestilence (deber)",285127,"v3: 'and from the deadly PESTILENCE (deber)' - the plague God delivers from; God's protective act named by its object. Qualifier."),
 (285123,"cover (sakak)",285127,"v4: 'He will COVER (sakak) you with his pinions' - God's sheltering. Qualifier."),
 (285129,"faithfulness (emeth)",285127,"v4: 'his FAITHFULNESS (emeth) is a shield and buckler' - God's faithfulness as protection. Qualifier."),
 (285062,"befall (anah)",285148,"v10: 'no evil shall be allowed to BEFALL (anah) you' - God's warding off of harm. Qualifier."),
 (285069,"command (tsavah)",285148,"v11: 'For he will COMMAND (tsavah) his angels concerning you' - God's charge to the angels. Qualifier."),
 (285072,"guard (shamar)",285148,"v11: 'to GUARD (shamar) you in all your ways' - God's angelic keeping. Qualifier."),
 (285086,"deliver (palat)",285085,"v14: 'I will DELIVER (palat) him' - God's rescue of the one who loves him. Qualifier."),
 (285087,"protect (sagab)",285089,"v14: 'I will PROTECT (sagab) him, because he knows my name' - God's setting him on high. Qualifier."),
 (285091,"name (shem)",285089,"v14: 'because he knows my NAME (shem)' - God's name. Qualifier."),
 (285093,"answer (anah)",285092,"v15: 'I will ANSWER (anah) him' - God's answer to the one who calls. Qualifier."),
 (285096,"rescue (chalats)",285092,"v15: 'I will RESCUE (chalats) him and honour him' - God's deliverance. Qualifier."),
 (285097,"honor (kabad)",285092,"v15: 'I will rescue him and HONOUR (kabad) him' - God's honouring. Qualifier."),
 (285101,"satisfy (saba)",285092,"v16: 'With long life I will SATISFY (saba) him' - God's satisfying. Qualifier."),
 (285102,"show (raah)",285092,"v16: 'and SHOW (raah) him my salvation' - God's revealing of salvation. Qualifier."),
 (285104,"salvation (yeshuah)",285092,"v16: 'and show him my SALVATION (yeshuah)' - God's salvation. Qualifier."),
]: r.qu(sid,sense,src,d)
for sid,sense,d in [
 (307082,"shelter (sether)","v1: 'He who dwells in the SHELTER (sether) of the Most High' - God's hiding-place, image of protection. Standalone."),
 (307085,"shadow (tsel)","v1: 'will abide in the SHADOW (tsel) of the Almighty' - God's overshadowing, image. Standalone."),
 (285117,"snare (pach)","v3: 'from the SNARE (pach) of the fowler' - the trap, image of hidden danger. Standalone."),
 (285118,"fowler (yaqush)","v3: 'the snare of the FOWLER (yaqush)' - the bird-catcher, image of the enemy. Standalone."),
 (285120,"deadly (havvah)","v3: 'the DEADLY (havvah) pestilence' - the destroying plague, image. Standalone."),
 (285124,"pinions (ebrah)","v4: 'He will cover you with his PINIONS (ebrah)' - the wing-feathers of God, image of shelter. Standalone."),
 (285126,"wings (kanaph)","v4: 'under his WINGS (kanaph) you will find refuge' - the sheltering wings, image. Standalone."),
 (285130,"shield (tsinnah)","v4: 'his faithfulness is a SHIELD (tsinnah)' - the large shield, image of protection. Standalone."),
 (285131,"buckler (socherah)","v4: 'a shield and BUCKLER (socherah)' - the small shield, image. Standalone."),
 (285135,"terror (pachad)","v5: 'the TERROR (pachad) of the night' - the night-dread, image of the danger not feared. Standalone."),
 (285138,"arrow (chets)","v5: 'nor the ARROW (chets) that flies by day' - the daytime peril, image. Standalone."),
 (285139,"flies (uph)","v5: 'the arrow that FLIES (uph) by day' - the speeding shaft, image. Standalone."),
 (307088,"pestilence (deber)","v6: 'the PESTILENCE (deber) that stalks in darkness' - the plague, image of danger. Standalone."),
 (307089,"stalks (halak)","v6: 'the pestilence that STALKS (halak) in darkness' - the prowling plague, image. Standalone."),
 (307090,"darkness (ophel)","v6: 'that stalks in DARKNESS (ophel)' - the dark of danger, image. Standalone."),
 (307092,"destruction (qeteb)","v6: 'nor the DESTRUCTION (qeteb) that wastes at noonday' - the noonday scourge, image. Standalone."),
 (307093,"wastes (shud)","v6: 'the destruction that WASTES (shud) at noonday' - the ravaging plague, image. Standalone."),
 (307096,"fall (naphal)","v7: 'A thousand may FALL (naphal) at your side' - the fallen around the protected one, image. Standalone."),
 (307099,"ten thousand (rebabah)","v7: 'TEN THOUSAND (rebabah) at your right hand' - the multitude fallen, image. Standalone."),
 (307103,"come near (nagash)","v7: 'but it will not COME NEAR (nagash) you' - the danger kept off, image. Standalone."),
 (285142,"look (nabat)","v8: 'You will only LOOK (nabat) with your eyes' - the safe beholding of judgment, image. Standalone."),
 (285144,"see (raah)","v8: 'and SEE (raah) the recompense of the wicked' - the witnessing of justice, image. Standalone."),
 (285145,"recompense (shillumah)","v8: 'the RECOMPENSE (shillumah) of the wicked' - the just requital, image. Standalone."),
 (285146,"wicked (rasha)","v8: 'the recompense of the WICKED (rasha)' - the judged wicked, the object of the recompense. Standalone."),
 (285150,"dwelling place (maon)","v9: 'you have made the LORD... the Most High your DWELLING PLACE (maon)' - God as dwelling, the refuge chosen (the char made, 285148). Standalone."),
 (285152,"refuge (machseh)","v9: 'the Most High your REFUGE (machseh)' - God as refuge, title of the chosen shelter. Standalone."),
 (285061,"evil (ra)","v10: 'no EVIL (ra) shall be allowed to befall you' - the harm averted, image. Standalone."),
 (285064,"plague (nega)","v10: 'no PLAGUE (nega) come near your tent' - the stroke kept off, image. Standalone."),
 (285065,"come near (qarab)","v10: 'no plague COME NEAR (qarab) your tent' - the danger held off, image. Standalone."),
 (285070,"angels (malak)","v11: 'he will command his ANGELS (malak) concerning you' - the guardian angels, God's agents. Standalone."),
 (285078,"bear up (nasa)","v12: 'On their hands they will BEAR YOU UP (nasa)' - the angels' lifting, image of protection. Standalone."),
 (285080,"strike (nagaph)","v12: 'lest you STRIKE (nagaph) your foot against a stone' - the stumble averted, image. Standalone."),
 (285083,"stone (eben)","v12: 'against a STONE (eben)' - the stumbling-stone, image. Standalone."),
 (307104,"tread (darak)","v13: 'You will TREAD (darak) on the lion and the adder' - the victory over beasts, image of triumph over danger. Standalone."),
 (307106,"lion (shachal)","v13: 'You will tread on the LION (shachal)' - the beast of prey, image of peril. Standalone."),
 (307107,"adder (pethen)","v13: 'and the ADDER (pethen)' - the cobra, image of hidden danger. Standalone."),
 (307108,"young lion (kephir)","v13: 'the young LION (kephir)' - the strong beast, image. Standalone."),
 (307109,"serpent (tannin)","v13: 'and the SERPENT (tannin) you will trample' - the dragon/snake, image of danger. Standalone."),
 (307110,"trample underfoot (ramas)","v13: 'you will TRAMPLE UNDERFOOT (ramas)' - the crushing of the beasts, image of triumph. Standalone."),
 (285095,"trouble (tsarah)","v15: 'I will be with him in TROUBLE (tsarah)' - the distress in which God is present; circumstance. Standalone."),
]: r.st(sid,sense,d)
r.write()
