import sys; sys.path.insert(0,'scripts')
from _reread_ledger_lib import Reading, IB, GOD, PER
r=Reading("Psa",19,118,
  note="Ps118 processional thanksgiving, closes the Hallel (29v). Read by CHAR-ARC. A antiphonal call GIVE-THANKS + let those who FEAR say his love endures v1-4; B deliverance+trust v5-9 (CALLED, will not FEAR, HATE, TAKE-REFUGE vs TRUST in man/princes); C surrounded-but-helped v10-14 (God's acts, no chars); D right-hand does valiantly v15-18 (RIGHTEOUS, LIVE not die, RECOUNT his deeds); E entrance liturgy v19-29 (GIVE-THANKS at the gates, RIGHTEOUS enter, THANK, MARVELOUS, REJOICE/GLAD, BLESSED/bless, GIVE-THANKS/EXTOL, GIVE-THANKS). God's good/steadfast-love/answered/helper/strength/right-hand/save = qualifiers; nations-surrounded/stone-cornerstone/festal-sacrifice imagery = standalone.")
A=271039; B=271165; D=271076; E=271141
CH=[
 (271039,"give thanks (yadah)","action","the worshippers","give thanks","to the LORD",GOD,"paired with his enduring steadfast love",
  "v1: 'Oh GIVE THANKS (yadah) to the LORD, for he is good' - the antiphonal call opening the processional psalm."),
 (271157,"fear (yare)","disposition","those who fear God","fear / revere","the LORD",GOD,"paired with confessing his enduring love",
  "v4: 'Let those who FEAR (yare) the LORD say, His steadfast love endures forever' - the reverent joining the antiphon."),
 (271165,"call (qara)","action","the psalmist","call","on the LORD out of distress",GOD,"paired with God's answer",
  "v5: 'Out of my distress I CALLED (qara) on the LORD' - the cry from the strait place, the turn to God that the answer follows."),
 (271172,"fear (yare, negated)","state","the psalmist","not fear","what man can do",IB,"paired with the LORD on his side",
  "v6: 'The LORD is on my side; I will not FEAR (yare). What can man do to me?' - the fearlessness of the God-backed, dread dissolved by God's presence."),
 (271180,"hate (sane)","disposition","the enemies","hate","the psalmist",IB,"paired with the LORD his helper",
  "v7: 'I shall look in triumph on those who HATE (sane) me' - the enemies' enmity, over which the God-helped psalmist prevails."),
 (271183,"take refuge (chasah)","disposition","the psalmist","take refuge","in the LORD",GOD,"paired with the folly of trusting man",
  "v8: 'It is better to TAKE REFUGE (chasah) in the LORD than to trust in man' - reliance on God preferred to reliance on man."),
 (271186,"trust (batach)","disposition","people","trust (wrongly)","in man",IB,"paired with taking refuge in God",
  "v8: 'than to TRUST (batach) in man' - the misplaced confidence in man, weighed against refuge in God and found wanting."),
 (271189,"take refuge (chasah)","disposition","the psalmist","take refuge","in the LORD",GOD,"paired with the folly of trusting princes",
  "v9: 'It is better to TAKE REFUGE (chasah) in the LORD than to trust in princes' - reliance on God preferred to reliance on the powerful."),
 (271192,"trust (batach)","disposition","people","trust (wrongly)","in princes",IB,"paired with taking refuge in God",
  "v9: 'than to TRUST (batach) in princes' - the misplaced confidence in the mighty, against refuge in God."),
 (271061,"righteous (tsaddiq)","status","the righteous","sing glad songs","of salvation",IB,"paired with the songs in their tents",
  "v15: 'Glad songs of salvation are in the tents of the RIGHTEOUS (tsaddiq)' - the just, whose homes ring with the joy of deliverance."),
 (271076,"live (chayah)","state","the psalmist","live and not die","to recount God's deeds",IB,"paired with recounting his deeds",
  "v17: 'I shall not die, but I shall LIVE (chayah), and recount the deeds of the LORD' - the resolve to live for testimony, life spared for praise."),
 (271077,"recount (saphar)","action","the psalmist","recount","the deeds of the LORD",GOD,"paired with living to tell them",
  "v17: 'and RECOUNT (saphar) the deeds of the LORD' - the testimony the spared life exists for, God's works declared."),
 (271090,"give thanks (yadah)","action","the psalmist","give thanks","to the LORD on entering",GOD,"paired with entering the gates of righteousness",
  "v19: 'that I may enter through them and GIVE THANKS (yadah) to the LORD' - the thanksgiving that is the aim of entering the gates."),
 (271101,"righteous (tsaddiq)","status","the righteous","enter","the gate of the LORD",IB,"paired with entering the LORD's gate",
  "v20: 'This is the gate of the LORD; the RIGHTEOUS (tsaddiq) shall enter through it' - the just who alone pass through God's gate."),
 (271104,"thank (yadah)","action","the psalmist","thank","God for answering",GOD,"paired with God's answer and salvation",
  "v21: 'I THANK (yadah) you that you have answered me and have become my salvation' - the personal thanks for the deliverance."),
 (271112,"marvelous (pala)","state","the worshippers","marvel","at the LORD's doing",IB,"paired with the LORD's doing",
  "v23: 'This is the LORD's doing; it is MARVELLOUS (pala) in our eyes' - the wonder of the people at God's reversal, amazement at his work."),
 (271119,"rejoice (gil)","action","the worshippers","rejoice","in the day the LORD has made",IB,"paired with being glad",
  "v24: 'This is the day that the LORD has made; let us REJOICE (gil) and be glad in it' - the exultation of the festal assembly."),
 (271120,"glad (samach)","state","the worshippers","be glad","in the LORD's day",IB,"paired with rejoicing",
  "v24: 'let us rejoice and be GLAD (samach) in it' - the gladness of the day of salvation."),
 (271128,"bless (barak)","action","the worshippers","bless / pronounce blessed","him who comes in the LORD's name",GOD,"paired with blessing from the house of the LORD",
  "v26: 'BLESSED (barak) is he who comes in the name of the LORD!' - the benediction on the one entering, the processional welcome."),
 (271132,"bless (barak)","action","the priests / worshippers","bless","from the house of the LORD",GOD,"paired with the entering blessed",
  "v26: 'We BLESS (barak) you from the house of the LORD' - the blessing spoken from the temple over the coming worshippers."),
 (271137,"give thanks (yadah)","action","the psalmist","give thanks","to God",GOD,"paired with extolling him",
  "v28: 'You are my God, and I will GIVE THANKS (yadah) to you' - the personal thanksgiving to God as his own."),
 (271139,"extol (rum)","action","the psalmist","extol","God",GOD,"paired with giving thanks",
  "v28: 'you are my God; I will EXTOL (rum) you' - the lifting-up of God in worship."),
 (271141,"give thanks (yadah)","action","the worshippers","give thanks","to the LORD",GOD,"paired with his enduring steadfast love",
  "v29: 'Oh GIVE THANKS (yadah) to the LORD, for he is good' - the closing antiphon, the psalm sealed as it began."),
]
for a in CH: r.ch(*a)
QU=[
 (271042,"good (tob)",A,"v1: 'for he is GOOD (tob)' - God's goodness. Qualifier."),
 (271045,"steadfast love (chesed)",A,"v1: 'for his STEADFAST LOVE (chesed) endures forever!' - God's covenant love. Qualifier."),
 (271096,"steadfast love (chesed)",271157,"v2: 'Let Israel say, His STEADFAST LOVE (chesed) endures forever' - God's love confessed. Qualifier."),
 (271154,"steadfast love (chesed)",271157,"v3: 'Let the house of Aaron say, His STEADFAST LOVE (chesed) endures forever' - God's love. Qualifier."),
 (271161,"steadfast love (chesed)",271157,"v4: 'His STEADFAST LOVE (chesed) endures forever' - God's love. Qualifier."),
 (271168,"answered (anah)",B,"v5: 'the LORD ANSWERED (anah) me and set me free' - God's answer. Qualifier."),
 (271169,"set free (merchab)",B,"v5: 'and SET me FREE (merchab, broad place)' - God's deliverance into a broad place. Qualifier."),
 (271177,"helper (azar)",B,"v7: 'The LORD is on my side as my HELPER (azar)' - God as helper. Qualifier."),
 (307654,"name (shem)",B,"v10: 'in the NAME (shem) of the LORD I cut them off!' - God's name, the means of victory. Qualifier."),
 (271050,"name (shem)",B,"v11: 'in the NAME (shem) of the LORD I cut them off!' - God's name. Qualifier."),
 (307663,"name (shem)",B,"v12: 'in the NAME (shem) of the LORD I cut them off!' - God's name. Qualifier."),
 (307670,"helped (azar)",B,"v13: 'but the LORD HELPED (azar) me' - God's help in the fall. Qualifier."),
 (271054,"strength (oz)",B,"v14: 'The LORD is my STRENGTH (oz) and my song' - God as strength. Qualifier."),
 (271057,"salvation (yeshuah)",B,"v14: 'he has become my SALVATION (yeshuah)' - God as salvation. Qualifier."),
 (271059,"salvation (yeshuah)",271061,"v15: 'Glad songs of SALVATION (yeshuah)' - God's salvation. Qualifier."),
 (271062,"right hand (yamin)",271061,"v15: 'the RIGHT HAND (yamin) of the LORD does valiantly' - God's mighty hand. Qualifier."),
 (271064,"does (asah)",271061,"v15: 'the right hand of the LORD DOES (asah) valiantly' - God's mighty action. Qualifier."),
 (271065,"valiantly (chayil)",271061,"v15: 'the right hand of the LORD does VALIANTLY (chayil)' - the valour of God's hand. Qualifier."),
 (271066,"right hand (yamin)",271061,"v16: 'the RIGHT HAND (yamin) of the LORD exalts' - God's mighty hand. Qualifier."),
 (271068,"exalts (rum)",271061,"v16: 'the right hand of the LORD EXALTS (rum)' - God's exalting action. Qualifier."),
 (271069,"right hand (yamin)",271061,"v16: 'the RIGHT HAND (yamin) of the LORD does valiantly' - God's mighty hand. Qualifier."),
 (271071,"does (asah)",271061,"v16: 'the right hand of the LORD DOES (asah) valiantly' - God's action. Qualifier."),
 (271072,"valiantly (chayil)",271061,"v16: 'the right hand of the LORD does VALIANTLY (chayil)' - the valour of God's hand. Qualifier."),
 (271078,"deeds (maaseh)",D,"v17: 'and recount the DEEDS (maaseh) of the LORD' - God's works. Qualifier."),
 (271081,"disciplined (yasar)",D,"v18: 'The LORD has DISCIPLINED (yasar) me severely' - God's chastening. Qualifier."),
 (271082,"severely (yasar)",D,"v18: 'disciplined me SEVERELY (yasar)' - the severity of God's discipline. Qualifier."),
 (271084,"given over (nathan, negated)",D,"v18: 'but he has not GIVEN me OVER (nathan) to death' - God's sparing. Qualifier."),
 (271106,"answered (anah)",271104,"v21: 'that you have ANSWERED (anah) me' - God's answer. Qualifier."),
 (271108,"salvation (yeshuah)",271104,"v21: 'and have become my SALVATION (yeshuah)' - God as salvation. Qualifier."),
 (271118,"made (asah)",271119,"v24: 'This is the day that the LORD has MADE (asah)' - God's making of the day. Qualifier."),
 (271122,"save (yasha)",E,"v25: 'SAVE (yasha) us, we pray, O LORD!' - God's salvation petitioned (Hoshia-na). Qualifier."),
 (271127,"success (tsalach)",E,"v25: 'O LORD, we pray, give us SUCCESS (tsalach)!' - God's prospering petitioned. Qualifier."),
 (271130,"name (shem)",271128,"v26: 'he who comes in the NAME (shem) of the LORD!' - God's name. Qualifier."),
 (307679,"shine (or)",E,"v27: 'The LORD is God, and he has made his light to SHINE (or) upon us' - God's light. Qualifier."),
 (271144,"good (tob)",271141,"v29: 'for he is GOOD (tob)' - God's goodness. Qualifier."),
 (271147,"steadfast love (chesed)",271141,"v29: 'for his STEADFAST LOVE (chesed) endures forever!' - God's covenant love. Qualifier."),
]
for sid,sense,src,d in QU: r.qu(sid,sense,src,d)
ST=[
 (271046,"endures forever (olam)","v1: 'his steadfast love ENDURES FOREVER (olam)!' - the perpetuity of God's love; temporal. Standalone."),
 (271097,"endures forever (olam)","v2: 'His steadfast love ENDURES FOREVER (olam)' - temporal. Standalone."),
 (271155,"endures forever (olam)","v3: 'His steadfast love ENDURES FOREVER (olam)' - temporal. Standalone."),
 (271162,"endures forever (olam)","v4: 'His steadfast love ENDURES FOREVER (olam)' - temporal. Standalone."),
 (271148,"endures forever (olam)","v29: 'his steadfast love ENDURES FOREVER (olam)!' - temporal. Standalone."),
 (271164,"distress (metsar)","v5: 'Out of my DISTRESS (metsar) I called' - the strait place from which he cried; circumstance. Standalone."),
 (271175,"do (asah)","v6: 'What can man DO (asah) to me?' - the powerlessness of man against the God-backed, rhetorical. Standalone."),
 (271179,"look (raah)","v7: 'I shall LOOK (raah) in triumph on those who hate me' - the vindication beheld, image. Standalone."),
 (271182,"better (tob)","v8: 'It is BETTER (tob) to take refuge in the LORD' - the value-judgment (char take-refuge, 271183). Standalone."),
 (271188,"better (tob)","v9: 'It is BETTER (tob) to take refuge in the LORD' - the value-judgment. Standalone."),
 (271193,"princes (nadib)","v9: 'than to trust in PRINCES (nadib)' - the mighty, false object of trust (char trust, 271192). Standalone."),
 (307652,"surrounded (sabab)","v10: 'All nations SURROUNDED (sabab) me' - the encircling foes, image. Standalone."),
 (271047,"surrounded (sabab)","v11: 'They SURROUNDED (sabab) me, surrounded me on every side' - the besieging nations, image. Standalone."),
 (307657,"surrounded (sabab)","v12: 'They SURROUNDED (sabab) me like bees' - the swarming foes, image. Standalone."),
 (307658,"bees (deborah)","v12: 'like BEES (deborah)' - the swarming enemies, image. Standalone."),
 (307659,"went out (daak)","v12: 'they WENT OUT (daak) like a fire among thorns' - the enemies quenched, image. Standalone."),
 (307660,"fire (esh)","v12: 'like a FIRE (esh) among thorns' - the quick-blazing, quick-dying foes, image. Standalone."),
 (307661,"thorns (qots)","v12: 'a fire among THORNS (qots)' - the thorn-fire, image of the foes' brief flare. Standalone."),
 (307666,"pushed (dachah)","v13: 'I was PUSHED (dachah) hard, so that I was falling' - the near-defeat, image. Standalone."),
 (307667,"hard (dachah)","v13: 'I was pushed HARD (dachah)' - the violence of the push, image. Standalone."),
 (307668,"falling (naphal)","v13: 'so that I was FALLING (naphal)' - the near-fall from which God caught him, image. Standalone."),
 (271055,"song (zimrath)","v14: 'The LORD is my strength and my SONG (zimrath)' - God as the theme of praise, image. Standalone."),
 (271058,"glad songs (qol)","v15: 'GLAD SONGS (qol, rinnah) of salvation are in the tents of the righteous' - the songs of the delivered (char righteous, 271061), image. Standalone."),
 (271074,"die (muth)","v17: 'I shall not DIE (muth)' - the death escaped (char live, 271076), image. Standalone."),
 (271085,"death (maveth)","v18: 'but he has not given me over to DEATH (maveth)' - the death from which God spared him, image. Standalone."),
 (271086,"open (pathach)","v19: 'OPEN (pathach) to me the gates of righteousness' - the summons to open the gates, image. Standalone."),
 (271087,"gates (shaar)","v19: 'the GATES (shaar) of righteousness' - the temple gates, place of entry. Standalone."),
 (271088,"righteousness (tsedeq)","v19: 'the gates of RIGHTEOUSNESS (tsedeq)' - the righteous gates through which the just enter, image. Standalone."),
 (271089,"enter (bo)","v19: 'that I may ENTER (bo) through them' - the entering (char give-thanks, 271090). Standalone."),
 (271099,"gate (shaar)","v20: 'This is the GATE (shaar) of the LORD' - God's gate, place. Standalone."),
 (271102,"enter (bo)","v20: 'the righteous shall ENTER (bo) through it' - the entering of the just (char righteous, 271101). Standalone."),
 (307672,"stone (eben)","v22: 'The STONE (eben) that the builders rejected' - the rejected stone, the proverb's image. Standalone."),
 (307673,"builders (banah)","v22: 'that the BUILDERS (banah) rejected' - the builders of the proverb, image. Standalone."),
 (307674,"rejected (maas)","v22: 'that the builders REJECTED (maas)' - the rejection in the proverb, image. Standalone."),
 (307676,"cornerstone (rosh)","v22: 'has become the CORNERSTONE (rosh pinnah)' - the head of the corner, image of God's reversal. Standalone."),
 (271129,"comes (bo)","v26: 'he who COMES (bo) in the name of the LORD' - the one entering, blessed (char blessed, 271128). Standalone."),
 (307680,"bind (asar)","v27: 'BIND (asar) the festal sacrifice with cords' - the ritual command, image of the feast. Standalone."),
 (307681,"festal sacrifice (chag)","v27: 'Bind the FESTAL SACRIFICE (chag)' - the feast-offering, image. Standalone."),
 (307682,"cords (aboth)","v27: 'with CORDS (aboth)' - the cords of the sacrifice, image. Standalone."),
 (307684,"horns (qeren)","v27: 'up to the HORNS (qeren) of the altar!' - the altar-horns, image of the feast. Standalone."),
 (307685,"altar (mizbeach)","v27: 'the horns of the ALTAR (mizbeach)!' - the altar, place of the festal sacrifice. Standalone."),
]
for sid,sense,d in ST: r.st(sid,sense,d)
r.write()
