import sys; sys.path.insert(0,'scripts')
from _reread_ledger_lib import Reading, IB, GOD, PER
r=Reading("Psa",19,115,
  note="Ps115 'Not to us but to your name give glory' (18v). IB: the folly of those who MAKE idols and TRUST in them v8; the threefold summons - Israel/house-of-Aaron/you-who-FEAR trust, TRUST, TRUST in the LORD v9-11; those who FEAR him, blessed v13; the closing vow to BLESS the LORD forevermore + PRAISE v18. God's name/glory/steadfast-love/does-what-he-pleases + all the blessing-acts (remembered/bless x5/increase/made) = qualifiers; the dead-idol catalogue (mouths/eyes/ears/hands but don't work) + shield/silence imagery = standalone.")
CH=[
 (270908,"make (asah)","action","the idolaters","make idols","and become like them",IB,"paired with trusting in them",
  "v8: 'Those who MAKE (asah) them become like them' - the makers of idols, reduced to the deadness of what they fashion; folly self-inflicted."),
 (270911,"trust (batach)","disposition","the idolaters","trust","in idols",IB,"paired with making them",
  "v8: 'so do all who TRUST (batach) in them' - the false trust in dead idols, misplaced reliance that deadens the truster."),
 (270914,"trust (batach)","disposition","Israel","trust","in the LORD",GOD,"paired with God their help and shield",
  "v9: 'O ISRAEL, TRUST (batach) in the LORD!' - the summons to true trust, reliance on the living God against the dead idols."),
 (270830,"trust (batach)","disposition","the house of Aaron","trust","in the LORD",GOD,"paired with God their help and shield",
  "v10: 'O house of Aaron, TRUST (batach) in the LORD!' - the priests summoned to trust the living God."),
 (270836,"fear (yare)","disposition","those who fear God","fear / revere","the LORD",GOD,"paired with trusting in the LORD",
  "v11: 'You who FEAR (yare) the LORD, trust in the LORD!' - the reverent summoned to trust, fear and trust joined."),
 (270838,"trust (batach)","disposition","those who fear God","trust","in the LORD",GOD,"paired with fearing him",
  "v11: 'you who fear the LORD, TRUST (batach) in the LORD!' - the third summons to trust, the God-fearers cast wholly on him."),
 (270854,"fear (yare)","disposition","those who fear God","fear / revere","the LORD",GOD,"paired with God's blessing on them",
  "v13: 'he will bless those who FEAR (yare) the LORD, both the small and the great' - the reverent, small and great, whom God blesses."),
 (270873,"bless (barak)","action","we (the living)","bless","the LORD forevermore",GOD,"paired with the closing praise",
  "v18: 'But we will BLESS (barak) the LORD from this time forth and forevermore' - the living's endless worship, set against the silent dead (v17)."),
 (270878,"praise (halal)","action","the worshippers","praise","the LORD",GOD,"paired with blessing the LORD",
  "v18: 'PRAISE (halal) the LORD!' - the closing Hallelujah of the living who bless God."),
]
for a in CH: r.ch(*a)
BL=270873; TR=270914; FE=270854
QU=[
 (270821,"name (shem)",BL,"v1: 'but to your NAME (shem) give glory' - God's name, to which glory belongs. Qualifier."),
 (270822,"give (nathan)",BL,"v1: 'to your name GIVE (nathan) glory' - the ascription of glory to God. Qualifier."),
 (270823,"glory (kabod)",BL,"v1: 'to your name give GLORY (kabod)' - God's glory. Qualifier."),
 (270825,"steadfast love (chesed)",BL,"v1: 'for the sake of your STEADFAST LOVE (chesed)' - God's covenant love. Qualifier."),
 (270827,"faithfulness (emeth)",BL,"v1: 'and your FAITHFULNESS (emeth)!' - God's faithfulness. Qualifier."),
 (270888,"does (asah)",BL,"v3: 'he DOES (asah) all that he pleases' - God's sovereign action. Qualifier."),
 (270891,"pleases (chaphets)",BL,"v3: 'all that he PLEASES (chaphets)' - God's sovereign will. Qualifier."),
 (270917,"help (ezer)",TR,"v9: 'He is their HELP (ezer) and their shield' - God as help to those who trust. Qualifier."),
 (270833,"help (ezer)",270830,"v10: 'He is their HELP (ezer) and their shield' - God as help to the house of Aaron. Qualifier."),
 (270841,"help (ezer)",270838,"v11: 'He is their HELP (ezer) and their shield' - God as help to the God-fearers. Qualifier."),
 (270845,"remembered (zakar)",FE,"v12: 'The LORD has REMEMBERED (zakar) us; he will bless us' - God's mindful remembrance. Qualifier."),
 (270846,"bless (barak)",FE,"v12: 'he will BLESS (barak) us' - God's blessing. Qualifier."),
 (270847,"bless (barak)",FE,"v12: 'he will BLESS (barak) the house of Israel' - God's blessing of Israel. Qualifier."),
 (270850,"bless (barak)",FE,"v12: 'he will BLESS (barak) the house of Aaron' - God's blessing of the priests. Qualifier."),
 (270853,"bless (barak)",FE,"v13: 'he will BLESS (barak) those who fear the LORD' - God's blessing of the God-fearers. Qualifier."),
 (307620,"give increase (yasaph)",FE,"v14: 'May the LORD give you INCREASE (yasaph), you and your children!' - God's multiplying blessing. Qualifier."),
 (270859,"blessed (barak)",FE,"v15: 'May you be BLESSED (barak) by the LORD, who made heaven and earth!' - God's blessing. Qualifier."),
 (270861,"made (asah)",FE,"v15: 'who MADE (asah) heaven and earth!' - God the creator. Qualifier."),
 (305868,"given (nathan)",FE,"v16: 'but the earth he has GIVEN (nathan) to the children of man' - God's gift of the earth. Qualifier."),
]
for sid,sense,src,d in QU: r.qu(sid,sense,src,d)
ST=[
 (270892,"idols (atsab)","v4: 'Their IDOLS (atsab) are silver and gold' - the dead images (char make, 270908), object. Standalone."),
 (270894,"gold (zahab)","v4: 'silver and GOLD (zahab)' - the material of the idols, image. Standalone."),
 (270895,"work (maaseh)","v4: 'the WORK (maaseh) of human hands' - the man-made idols, image. Standalone."),
 (307606,"mouths (peh)","v5: 'They have MOUTHS (peh), but do not speak' - the idols' dead mouths, image. Standalone."),
 (307608,"speak (dabar)","v5: 'but do not SPEAK (dabar)' - the idols' muteness, image. Standalone."),
 (307611,"see (raah)","v5: 'eyes, but do not SEE (raah)' - the idols' blindness, image. Standalone."),
 (307614,"hear (shama)","v6: 'ears, but do not HEAR (shama)' - the idols' deafness, image. Standalone."),
 (307615,"noses (aph)","v6: 'NOSES (aph), but do not smell' - the idols' dead noses, image. Standalone."),
 (307617,"smell (ruach)","v6: 'but do not SMELL (ruach)' - the idols' lifelessness, image. Standalone."),
 (270900,"feel (mush)","v7: 'They have hands, but do not FEEL (mush)' - the idols' senseless hands, image. Standalone."),
 (270901,"feet (regel)","v7: 'FEET (regel), but do not walk' - the idols' dead feet, image. Standalone."),
 (270903,"walk (halak)","v7: 'but do not WALK (halak)' - the idols' immobility, image. Standalone."),
 (270905,"sound (hagah)","v7: 'and they do not make a SOUND (hagah) in their throat' - the idols' voicelessness, image. Standalone."),
 (270907,"throat (garon)","v7: 'a sound in their THROAT (garon)' - the idols' dead throat, image. Standalone."),
 (270919,"shield (magen)","v9: 'He is their help and their SHIELD (magen)' - God as shield (qual help, 270917), image. Standalone."),
 (270835,"shield (magen)","v10: 'their help and their SHIELD (magen)' - God as shield to the priests, image. Standalone."),
 (270843,"shield (magen)","v11: 'their help and their SHIELD (magen)' - God as shield to the God-fearers, image. Standalone."),
 (270856,"small (qaton)","v13: 'both the SMALL (qaton) and the great' - the whole range of the God-fearers blessed, image. Standalone."),
 (270864,"dead (muth)","v17: 'The DEAD (muth) do not praise the LORD' - the dead who cannot worship, image. Standalone."),
 (270866,"praise (halal)","v17: 'The dead do not PRAISE (halal) the LORD' - the praise absent in death (contrast the living, char bless 270873). Standalone."),
 (270870,"go down (yarad)","v17: 'nor do any who GO DOWN (yarad) into silence' - the descent to death, image. Standalone."),
 (270871,"silence (dumah)","v17: 'who go down into SILENCE (dumah)' - the silent grave, image. Standalone."),
 (270877,"forevermore (olam)","v18: 'from this time forth and FOREVERMORE (olam)' - the perpetuity of the living's blessing; temporal. Standalone."),
]
for sid,sense,d in ST: r.st(sid,sense,d)
r.write()
