import sys; sys.path.insert(0,'scripts')
from _reread_ledger_lib import Reading, IB, GOD, PER
r=Reading("Psa",19,109,
  note="Ps109 imprecatory psalm (31v, ~137 spans). Read by CHAR-ARC. A enemies' assault v1-5 (WICKED/DECEITFUL/LYING mouths, HATE/HATRED, accusing in return for the psalmist's LOVE/GOOD/PRAYER; they reward EVIL for good); B imprecation + the wicked's character v6-20 (WICKED-MAN/ACCUSER, GUILTY/SIN; because he did not REMEMBER to show KINDNESS/PITY but PURSUED the POOR/NEEDY/BROKENHEARTED, LOVED to CURSE, no DELIGHT in blessing); C affliction v22-25 (POOR/NEEDY, HEART stricken, KNEES weak, BODY gaunt, SCORN); D plea->thanks v27-31 (KNOW it's your hand, let them CURSE but you bless, PUT-TO-SHAME/GLAD, ACCUSERS' DISHONOR/SHAME, THANKS/PRAISE, the NEEDY-ONE's SOUL saved). God's deal/steadfast-love/deliver/help/save/bless/stands = qualifiers; mouths/tongues/garment/locust imagery = standalone.")
A=270323; B=270203; CC=270259; D=270302
CH=[
 # Arc A
 (270162,"praise (tehillah)","action","the psalmist","praise","God",GOD,"paired with the plea that God not be silent",
  "v1: 'Be not silent, O God of my PRAISE (tehillah)!' - the psalmist's worship, the God he praises now begged not to stay silent against his slanderers."),
 (270229,"wicked (rasha)","status","the enemies","be wicked","against the psalmist",IB,"paired with deceitful and lying mouths",
  "v2: 'For WICKED (rasha) and deceitful mouths are opened against me' - the godless foes whose mouths assail him."),
 (270230,"deceitful (mirmah)","disposition","the enemies","be deceitful","in speech",IB,"paired with the wicked and lying mouths",
  "v2: 'wicked and DECEITFUL (mirmah) mouths are opened against me' - the treachery of the enemies' speech."),
 (270235,"lying (sheqer)","disposition","the enemies","speak lies","against the psalmist",IB,"paired with the deceit",
  "v2: 'speaking against me with LYING (sheqer) tongues' - the falsehood of the foes' accusations."),
 (270296,"hate (sinah)","disposition","the enemies","hate","the psalmist",IB,"paired with attacking without cause",
  "v3: 'They encircle me with words of HATE (sinah)' - the enmity that surrounds him, hatred without cause."),
 (270320,"love (ahabah)","disposition","the psalmist","love","his accusers",IB,"paired with the accusation returned for it",
  "v4: 'In return for my LOVE (ahabah) they accuse me' - the psalmist's goodwill met with accusation, love repaid with enmity."),
 (270321,"accuse (satan)","action","the enemies","accuse","the psalmist",IB,"paired with the love they repay",
  "v4: 'they ACCUSE (satan) me' - the enemies' adversarial attack, standing against him as accusers."),
 (270323,"prayer (tephillah)","action","the psalmist","give himself to prayer","before God",GOD,"paired with the love returned with accusation",
  "v4: 'but I give myself to PRAYER (tephillah)' - the psalmist's response to hostility: not retaliation but prayer, love answered by devotion to God."),
 (270326,"evil (ra)","disposition","the enemies","render evil","for good",IB,"paired with the good repaid",
  "v5: 'So they reward me EVIL (ra) for good' - the enemies' return of evil for the psalmist's good."),
 (270328,"good (tob)","disposition","the psalmist","do good","to his enemies",IB,"paired with the evil returned",
  "v5: 'they reward me evil for GOOD (tob)' - the psalmist's good, met with evil."),
 (270329,"hatred (sinah)","disposition","the enemies","render hatred","for love",IB,"paired with the love repaid",
  "v5: 'and HATRED (sinah) for my love' - the enemies' hatred returned for the psalmist's love."),
 (270332,"love (ahabah)","disposition","the psalmist","love","his enemies",IB,"paired with the hatred returned",
  "v5: 'and hatred for my LOVE (ahabah)' - the psalmist's love, answered with hatred."),
 # Arc B imprecation + wicked's character
 (270334,"wicked man (rasha)","status","the wicked man","be wicked","set over the enemy",IB,"paired with the accuser at his right hand",
  "v6: 'Appoint a WICKED MAN (rasha) against him' - the imprecation's opening: a wicked adversary invoked over the enemy."),
 (270336,"accuser (satan)","status","the accuser","stand as adversary","at the enemy's right hand",IB,"paired with the wicked man",
  "v6: 'let an ACCUSER (satan) stand at his right hand' - the adversary invoked to accuse the enemy as he accused the psalmist."),
 (270344,"guilty (rasha)","state","the enemy","come out guilty","when tried",IB,"paired with his prayer counted as sin",
  "v7: 'When he is tried, let him come forth GUILTY (rasha)' - the wish that the enemy be condemned at judgment."),
 (270347,"sin (chataah)","state","the enemy","have his prayer counted sin","before God",GOD,"paired with the guilty verdict",
  "v7: 'let his prayer be counted as SIN (chataah)' - the wish that even the enemy's prayer be reckoned guilt."),
 (307549,"fatherless (yathom)","status","the enemy's children","be fatherless","by his death",IB,"paired with the widow and the curse",
  "v9: 'May his children be FATHERLESS (yathom)' - the imprecation reaching the enemy's children, bereaved by his fall."),
 (270172,"kindness (chesed)","disposition","no one","extend kindness","to the enemy",IB,"paired with none to pity his children",
  "v12: 'Let there be none to extend KINDNESS (chesed) to him' - the wish that the merciless man find no mercy."),
 (270174,"pity (chanan)","disposition","no one","pity","the enemy's fatherless children",IB,"paired with the kindness withheld",
  "v12: 'nor any to PITY (chanan) his fatherless children' - the wish that the pitiless find no pity for his own."),
 (270177,"iniquity (avon)","state","the enemy's fathers","bear iniquity","remembered by God",IB,"paired with the mother's sin",
  "v14: 'May the INIQUITY (avon) of his fathers be remembered by the LORD' - the ancestral guilt invoked against the enemy."),
 (270182,"sin (chattath)","state","the enemy's mother","have her sin","not blotted out",IB,"paired with the fathers' iniquity",
  "v14: 'and let not the SIN (chattath) of his mother be blotted out' - the invoked guilt of the enemy's mother."),
 (270195,"remember (zakar, negated)","disposition","the enemy","fail to remember","to show kindness",IB,"paired with pursuing the poor",
  "v16: 'For he did not REMEMBER (zakar) to show kindness' - the ground of the whole curse: the enemy's forgetting of mercy."),
 (270197,"kindness (chesed)","disposition","the enemy","fail to show kindness","to the afflicted",IB,"paired with the failure to remember",
  "v16: 'did not remember to show KINDNESS (chesed)' - the mercy the enemy withheld, the root of his condemnation."),
 (270198,"pursue (radaph)","action","the enemy","pursue","the poor and needy to death",IB,"paired with the poor, needy, brokenhearted",
  "v16: 'but PURSUED (radaph) the poor and needy and brokenhearted, to death' - the enemy's cruel persecution of the afflicted."),
 (270199,"poor (ani)","status","the poor","be pursued","by the enemy",IB,"paired with the needy and brokenhearted",
  "v16: 'pursued the POOR (ani)' - the afflicted victim the enemy hounded."),
 (270200,"needy (ebyon)","status","the needy","be pursued","by the enemy",IB,"paired with the poor",
  "v16: 'the poor and NEEDY (ebyon)' - the destitute the enemy persecuted."),
 (270201,"brokenhearted (kaah)","status","the brokenhearted","be pursued to death","by the enemy",IB,"paired with the poor and needy",
  "v16: 'and the BROKENHEARTED (kaah), to death' - the crushed in spirit the enemy hounded to the grave."),
 (270203,"loved (aheb)","disposition","the enemy","love","to curse",IB,"paired with cursing and the absence of delight in blessing",
  "v17: 'He LOVED (aheb) to curse; let curses come upon him!' - the enemy's delight in cursing, now recoiling on him."),
 (270204,"curse (qelalah)","action","the enemy","curse","others",IB,"paired with loving to curse",
  "v17: 'He loved to CURSE (qelalah)' - the cursing the enemy delighted in."),
 (270207,"delight (chaphets, negated)","disposition","the enemy","not delight","in blessing",IB,"paired with loving to curse",
  "v17: 'he did not DELIGHT (chaphets) in blessing; may it be far from him!' - the enemy's aversion to blessing, blessing now kept far from him."),
 (270213,"cursing (qelalah)","action","the enemy","clothe himself with cursing","as a garment",IB,"paired with loving to curse",
  "v18: 'He clothed himself with CURSING (qelalah) as his coat' - cursing worn like a garment, soaked into his very being."),
 (270239,"accusers (satan)","status","the psalmist's accusers","accuse","the psalmist",IB,"paired with speaking evil against his life",
  "v20: 'May this be the reward of my ACCUSERS (satan) from the LORD' - the adversaries whose recompense the imprecation seeks."),
 (270243,"evil (ra)","disposition","the accusers","speak evil","against the psalmist's life",IB,"paired with the accusers",
  "v20: 'of those who speak EVIL (ra) against my life' - the malice of the accusers' speech."),
 # Arc C affliction
 (270259,"poor (ani)","status","the psalmist","be poor","before God",IB,"paired with being needy and the stricken heart",
  "v22: 'For I am POOR (ani) and needy' - the psalmist's lowliness, his plea's ground, set against his powerful foes."),
 (270260,"needy (ebyon)","status","the psalmist","be needy","before God",IB,"paired with being poor",
  "v22: 'For I am poor and NEEDY (ebyon)' - the destitution the psalmist pleads."),
 (270262,"heart (leb)","faculty","the psalmist","have the heart stricken","within",IB,"paired with the poverty and the wasting body",
  "v22: 'and my HEART (leb) is stricken within me' - the wounded inner self, grief pierced deep."),
 (270265,"knees (berek)","faculty","the psalmist","have the knees weak","from fasting",IB,"paired with the gaunt body",
  "v24: 'My KNEES (berek) are weak through fasting' - the body failing under grief, strength drained from the very legs."),
 (270269,"body (basar)","faculty","the psalmist","waste away","through fasting",IB,"paired with growing gaunt",
  "v24: 'my BODY (basar) has become gaunt' - the flesh wasted by affliction, the toll of grief made visible."),
 (270270,"become gaunt (kachash)","state","the psalmist","grow lean","from fasting",IB,"paired with the wasting body",
  "v24: 'my body has BECOME GAUNT (kachash)' - the leanness of the fasting sufferer, wasted with sorrow."),
 (270275,"scorn (cherpah)","state","the psalmist","be an object of scorn","to his accusers",IB,"paired with the wagging heads",
  "v25: 'I am an object of SCORN (cherpah) to my accusers' - the psalmist's humiliation, mocked by his foes who wag their heads."),
 # Arc D plea -> thanks
 (307576,"know (yada)","action","the enemies","come to know","that it is God's hand",GOD,"paired with God acting",
  "v27: 'Let them KNOW (yada) that this is your hand' - the wish that the foes recognize God's deliverance, vindication made plain."),
 (270280,"curse (qalal)","action","the enemies","curse","the psalmist",IB,"paired with God's blessing that overrules it",
  "v28: 'Let them CURSE (qalal), but you will bless!' - the enemies' cursing, powerless against God's blessing."),
 (270284,"put to shame (bosh)","state","the enemies","be put to shame","when they arise",IB,"paired with the servant's gladness",
  "v28: 'They arise and are PUT TO SHAME (bosh), but your servant will be glad!' - the foes shamed, the servant gladdened."),
 (270286,"glad (samach)","state","the psalmist","be glad","in God's blessing",IB,"paired with the enemies put to shame",
  "v28: 'but your servant will be GLAD (samach)!' - the joy of the vindicated servant, gladness answering the curse."),
 (270287,"accusers (satan)","status","the psalmist's accusers","be clothed with dishonor","and shame",IB,"paired with dishonor and shame",
  "v29: 'May my ACCUSERS (satan) be clothed with dishonour' - the adversaries invoked to wear their own disgrace."),
 (270289,"dishonor (kelimmah)","state","the accusers","be clothed with dishonor","before all",IB,"paired with the accusers and shame",
  "v29: 'be clothed with DISHONOUR (kelimmah)' - the disgrace invoked on the accusers, worn like a garment."),
 (270292,"shame (bosheth)","state","the accusers","be wrapped in shame","as a cloak",IB,"paired with the dishonor",
  "v29: 'and wrapped in their own SHAME (bosheth) as in a cloak' - the shame that covers the accusers, their own disgrace their clothing."),
 (270302,"thanks (yadah)","action","the psalmist","give great thanks","to the LORD",GOD,"paired with praising in the throng",
  "v30: 'With my mouth I will give great THANKS (yadah) to the LORD' - the vow of thanksgiving, the lament turning to praise."),
 (270304,"praise (halal)","action","the psalmist","praise","God in the throng",GOD,"paired with giving thanks",
  "v30: 'I will PRAISE (halal) him in the midst of the throng' - the public praise of the delivered."),
 (270312,"needy one (ebyon)","status","the needy one","be defended","by God at his right hand",IB,"paired with the soul saved",
  "v31: 'For he stands at the right hand of the NEEDY ONE (ebyon)' - the poor whom God defends, standing where the accuser stood (v6)."),
 (270318,"soul (nephesh)","faculty","the needy one","be saved","from those who condemn",IB,"paired with the needy one",
  "v31: 'to save him from those who condemn his SOUL (nephesh)' - the life of the needy God rescues from his judges."),
]
for a in CH: r.ch(*a)
QU=[
 (270160,"silent (charash)",A,"v1: 'Be not SILENT (charash), O God of my praise!' - God asked not to keep silence. Qualifier."),
 (270179,"remembered (zakar)",B,"v14: 'may the iniquity of his fathers be REMEMBERED (zakar) by the LORD' - God's remembrance invoked. Qualifier."),
 (270184,"blotted out (machah)",B,"v14: 'let not the sin of his mother be BLOTTED OUT (machah)' - God's not-erasing invoked. Qualifier."),
 (270189,"cut off (karath)",B,"v15: 'that he may CUT OFF (karath) the memory of them' - God's cutting-off invoked. Qualifier."),
 (270250,"deal (asah)",CC,"v21: 'But you, O God my Lord, DEAL (asah) on my behalf for your name's sake' - God's acting petitioned. Qualifier."),
 (270251,"name (shem)",CC,"v21: 'for your NAME'S (shem) sake' - God's name, the ground of the plea. Qualifier."),
 (270254,"steadfast love (chesed)",CC,"v21: 'because your STEADFAST LOVE (chesed) is good' - God's covenant love. Qualifier."),
 (270255,"good (tob)",CC,"v21: 'because your steadfast love is GOOD (tob)' - the goodness of God's love. Qualifier."),
 (270256,"deliver (natsal)",CC,"v21: 'DELIVER (natsal) me!' - God's deliverance petitioned. Qualifier."),
 (307570,"help (azar)",CC,"v26: 'HELP (azar) me, O LORD my God!' - God's help petitioned. Qualifier."),
 (307573,"save (yasha)",CC,"v26: 'SAVE (yasha) me according to your steadfast love!' - God's salvation petitioned. Qualifier."),
 (307575,"steadfast love (chesed)",CC,"v26: 'according to your STEADFAST LOVE (chesed)!' - God's covenant love. Qualifier."),
 (307582,"done (asah)",D,"v27: 'that you, O LORD, have DONE (asah) it' - God's act of deliverance. Qualifier."),
 (270282,"bless (barak)",D,"v28: 'Let them curse, but you will BLESS (barak)!' - God's blessing that overrules the curse. Qualifier."),
 (270283,"arise (qum)",D,"v28: 'They ARISE (qum) and are put to shame' - the foes' rising, met with shame (God's act). Qualifier."),
 (270309,"stands (amad)",D,"v31: 'For he STANDS (amad) at the right hand of the needy one' - God's standing to defend. Qualifier."),
 (270314,"save (yasha)",D,"v31: 'to SAVE (yasha) him from those who condemn his soul' - God's saving of the needy. Qualifier."),
 (270333,"appoint (paqad)",B,"v6: 'APPOINT (paqad) a wicked man against him' - the imprecation asking God to set an adversary over the enemy. Qualifier."),
]
for sid,sense,src,d in QU: r.qu(sid,sense,src,d)
ST=[
 (270231,"mouths (peh)","v2: 'wicked and deceitful MOUTHS (peh) are opened against me' - the mouths of the foes (char wicked, 270229), image. Standalone."),
 (270232,"opened (pathach)","v2: 'mouths are OPENED (pathach) against me' - the opened mouths of assault, image. Standalone."),
 (270234,"speaking (dabar)","v2: 'SPEAKING (dabar) against me with lying tongues' - the enemies' speech, image. Standalone."),
 (270236,"tongues (lashon)","v2: 'with lying TONGUES (lashon)' - the organ of the lie (char lying, 270235), image. Standalone."),
 (270294,"encircle (sabab)","v3: 'They ENCIRCLE (sabab) me with words of hate' - the surrounding foes, image. Standalone."),
 (270295,"words (dabar)","v3: 'they encircle me with WORDS (dabar) of hate' - the hostile words (char hate, 270296), image. Standalone."),
 (270297,"attack (lacham)","v3: 'and ATTACK (lacham) me without cause' - the enemies' assault, image. Standalone."),
 (270298,"without cause (chinnam)","v3: 'attack me WITHOUT CAUSE (chinnam)' - the groundlessness of the enmity, image. Standalone."),
 (270319,"in return (tachath)","v4: 'In RETURN (tachath) for my love they accuse me' - the exchange of accusation for love, image. Standalone."),
 (270324,"reward (sim)","v5: 'So they REWARD (sim) me evil for good' - the enemies' recompense of evil (char evil, 270326), image. Standalone."),
 (270327,"for (tachath)","v5: 'evil FOR (tachath) good' - the exchange, image. Standalone."),
 (270330,"for (tachath)","v5: 'and hatred FOR (tachath) my love' - the exchange, image. Standalone."),
 (270337,"stand (amad)","v6: 'let an accuser STAND (amad) at his right hand' - the accuser's stance (char accuser, 270336), image. Standalone."),
 (270342,"tried (shaphat)","v7: 'When he is TRIED (shaphat)' - the enemy's judgment, image. Standalone."),
 (270343,"come forth (yatsa)","v7: 'let him COME FORTH (yatsa) guilty' - the verdict (char guilty, 270344), image. Standalone."),
 (270345,"prayer (tephillah)","v7: 'let his PRAYER (tephillah) be counted as sin' - the enemy's prayer condemned (char sin, 270347), image. Standalone."),
 (270351,"take (laqach)","v8: 'may another TAKE (laqach) his office' - the enemy's post given away, image. Standalone."),
 (270352,"office (pequddah)","v8: 'may another take his OFFICE (pequddah)' - the enemy's position, image. Standalone."),
 (270164,"wander (nua)","v10: 'May his children WANDER (nua) about and beg' - the destitute children of the curse, image. Standalone."),
 (270165,"about (nua)","v10: 'wander ABOUT (nua) and beg' - the aimless wandering, image. Standalone."),
 (270166,"beg (shaal)","v10: 'wander about and BEG (shaal)' - the begging children, image. Standalone."),
 (270167,"seeking (darash)","v10: 'SEEKING (darash) food far from the ruins they inhabit' - the children scavenging, image. Standalone."),
 (270169,"inhabit (chorbah)","v10: 'far from the ruins they INHABIT (chorbah)' - the ruined home, image. Standalone."),
 (307552,"creditor (nashah)","v11: 'May the CREDITOR (nashah) seize all that he has' - the creditor of the curse, image. Standalone."),
 (307553,"seize (naqash)","v11: 'May the creditor SEIZE (naqash) all that he has' - the seizure of the estate, image. Standalone."),
 (307555,"strangers (zar)","v11: 'may STRANGERS (zar) plunder the fruits of his toil' - the plunderers, image. Standalone."),
 (307556,"plunder (bazaz)","v11: 'may strangers PLUNDER (bazaz) the fruits of his toil' - the pillaging, image. Standalone."),
 (307558,"toil (yegia)","v11: 'the fruits of his TOIL (yegia)' - the enemy's labour, plundered, image. Standalone."),
 (270171,"extend (mashak)","v12: 'Let there be none to EXTEND (mashak) kindness' - the kindness withheld (char kindness, 270172), image. Standalone."),
 (270176,"fatherless children (yathom)","v12: 'nor any to pity his FATHERLESS CHILDREN (yathom)' - the enemy's bereaved children, image. Standalone."),
 (307559,"posterity (acharith)","v13: 'May his POSTERITY (acharith) be cut off' - the enemy's descendants, image. Standalone."),
 (307560,"cut off (karath)","v13: 'may his posterity be CUT OFF (karath)' - the ending of the line, image. Standalone."),
 (307561,"name (shem)","v13: 'may their NAME (shem) be blotted out' - the enemy's name erased, image. Standalone."),
 (307562,"blotted out (machah)","v13: 'may their name be BLOTTED OUT (machah)' - the erasure of the name, image. Standalone."),
 (270190,"memory (zeker)","v15: 'that he may cut off the MEMORY (zeker) of them from the earth' - the enemy's remembrance ended, image. Standalone."),
 (270193,"for / because (yaan)","v16: 'FOR (yaan) he did not remember to show kindness' - the causal ground of the curse. Standalone."),
 (270196,"show (asah)","v16: 'did not remember to SHOW (asah) kindness' - the showing of kindness withheld (char kindness, 270197). Standalone."),
 (270202,"death (maveth)","v16: 'pursued the poor... to DEATH (maveth)' - the death to which the enemy hounded the afflicted, image. Standalone."),
 (270208,"blessing (berakah)","v17: 'he did not delight in BLESSING (berakah)' - the blessing the enemy spurned (char delight, 270207), image. Standalone."),
 (270209,"far (rachaq)","v17: 'may it be FAR (rachaq) from him!' - the blessing kept far from the enemy, image. Standalone."),
 (270212,"clothed (labesh)","v18: 'He CLOTHED (labesh) himself with cursing as his coat' - the cursing worn as clothing (char cursing, 270213), image. Standalone."),
 (270214,"coat (mad)","v18: 'with cursing as his COAT (mad)' - the garment of cursing, image. Standalone."),
 (270216,"body (qereb)","v18: 'may it soak into his BODY (qereb) like water' - the cursing entering him, image. Standalone."),
 (270217,"water (mayim)","v18: 'like WATER (mayim)' - the cursing soaking in like water, image. Standalone."),
 (270221,"bones (etsem)","v18: 'like oil into his BONES (etsem)' - the cursing penetrating the bones, image. Standalone."),
 (270223,"garment (beged)","v19: 'like a GARMENT (beged) that he wraps around him' - the cursing as clothing, image. Standalone."),
 (270224,"around him (atah)","v19: 'that he wraps AROUND HIM (atah)' - the enveloping cursing, image. Standalone."),
 (270225,"belt (mezach)","v19: 'like a BELT (mezach) that he puts on every day' - the cursing girded daily, image. Standalone."),
 (270226,"puts on (chagar)","v19: 'that he PUTS ON (chagar) every day' - the daily donning of the curse, image. Standalone."),
 (270238,"reward (peullah)","v20: 'May this be the REWARD (peullah) of my accusers' - the recompense invoked (char accusers, 270239), image. Standalone."),
 (270242,"speak (dabar)","v20: 'of those who SPEAK (dabar) evil against my life' - the accusers' speech (char evil, 270243), image. Standalone."),
 (270246,"life (nephesh)","v20: 'evil against my LIFE (nephesh)' - the psalmist's life the foes assail, object. Standalone."),
 (270263,"stricken (chalal)","v22: 'my heart is STRICKEN (chalal) within me' - the wounding of the heart (char heart, 270262), image. Standalone."),
 (270264,"within (qereb)","v22: 'my heart is stricken WITHIN (qereb) me' - the inward seat of the wound, image. Standalone."),
 (307566,"shadow (tsel)","v23: 'I am gone like a SHADOW (tsel) at evening' - the fading sufferer, image of transience. Standalone."),
 (307567,"evening (natah)","v23: 'like a shadow at EVENING (natah)' - the lengthening evening shadow, image. Standalone."),
 (307568,"shaken off (naar)","v23: 'I am SHAKEN OFF (naar) like a locust' - the sufferer flicked away, image. Standalone."),
 (307569,"locust (arbeh)","v23: 'shaken off like a LOCUST (arbeh)' - the locust brushed aside, image of frailty. Standalone."),
 (270266,"weak (kashal)","v24: 'My knees are WEAK (kashal) through fasting' - the weakness of the knees (char knees, 270265), image. Standalone."),
 (270268,"fasting (tsom)","v24: 'weak through FASTING (tsom)' - the fasting that wasted the body, image. Standalone."),
 (270276,"see (raah)","v25: 'when they SEE (raah) me, they wag their heads' - the foes' mocking gaze (char scorn, 270275), image. Standalone."),
 (270277,"wag (nua)","v25: 'they WAG (nua) their heads' - the gesture of scorn, image. Standalone."),
 (270279,"heads (rosh)","v25: 'they wag their HEADS (rosh)' - the heads shaken in mockery, image. Standalone."),
 (270288,"clothed (labesh)","v29: 'May my accusers be CLOTHED (labesh) with dishonour' - the dishonour worn (char dishonor, 270289), image. Standalone."),
 (270290,"wrapped (atah)","v29: 'and WRAPPED (atah) in their own shame as in a cloak' - the shame enveloping the accusers, image. Standalone."),
 (270293,"cloak (meil)","v29: 'as in a CLOAK (meil)' - the cloak of shame, image. Standalone."),
 (270300,"mouth (peh)","v30: 'With my MOUTH (peh) I will give great thanks' - the mouth of thanksgiving (char thanks, 270302), image. Standalone."),
 (270316,"condemn (shaphat)","v31: 'from those who CONDEMN (shaphat) his soul' - the judges of the needy (char soul, 270318), object. Standalone."),
]
for sid,sense,d in ST: r.st(sid,sense,d)
r.write()
