import sys; sys.path.insert(0,'scripts')
from _reread_ledger_lib import Reading, IB, GOD, PER
r=Reading("Psa",19,116,
  note="Ps116 personal thanksgiving (19v). Read by CHAR-ARC. A LOVE+CALL born of God's hearing (LOVE, PLEAS-FOR-MERCY, CALL) v1-2; B distress->cry (SUFFERED/ANGUISH, CALLED, PRAY, deliver SOUL) v3-4; C grace->rest (SIMPLE, BROUGHT-LOW, RETURN O my SOUL to rest) v5-7; D deliverance+faith amid affliction (SOUL from death, TEARS, WALK before the LORD, BELIEVED, AFFLICTED, ALARM, LIARS) v8-11; E grateful response (RENDER, LIFT-UP the cup, CALL, PAY vows, SAINTS, THANKSGIVING, CALL, PAY, PRAISE) v12-19. God's heard/inclined/gracious/preserves/saved/delivered/loosed = qualifiers; snares/Sheol/cup/vows imagery = standalone.")
CH=[
 (270920,"love (aheb)","disposition","the psalmist","love","the LORD",GOD,"paired with God hearing his pleas",
  "v1: 'I LOVE (aheb) the LORD, because he has heard my voice and my pleas for mercy' - the love that answers answered prayer, devotion born of God's hearing."),
 (270926,"pleas for mercy (tachanun)","action","the psalmist","plead for mercy","to God",GOD,"paired with the love and calling",
  "v1: 'he has heard my voice and my PLEAS FOR MERCY (tachanun)' - the supplications God heard, the cry that drew forth love."),
 (270973,"call (qara)","action","the psalmist","call upon","God as long as he lives",GOD,"paired with God inclining his ear",
  "v2: 'therefore I will CALL (qara) on him as long as I live' - the lifelong resolve to pray, gratitude become habit."),
 (270981,"suffer (matsa)","state","the psalmist","suffer","distress and anguish",IB,"paired with the anguish",
  "v3: 'I SUFFERED (matsa) distress and anguish' - the depth of the psalmist's trouble, the low point before the cry."),
 (270983,"anguish (yagon)","state","the psalmist","be in anguish","near death",IB,"paired with the suffering",
  "v3: 'I suffered distress and ANGUISH (yagon)' - the grief of the sufferer, snared by death and Sheol."),
 (270984,"call (qara)","action","the psalmist","call","on the name of the LORD",GOD,"paired with the plea to deliver his soul",
  "v4: 'Then I CALLED (qara) on the name of the LORD' - the cry from the depths, the turn from anguish to God."),
 (270988,"pray (anna)","action","the psalmist","plead","O LORD, deliver my soul!",GOD,"paired with the calling",
  "v4: 'O LORD, I PRAY (anna), deliver my soul!' - the urgent plea, the naked cry for rescue."),
 (270991,"soul (nephesh)","faculty","the psalmist","be delivered","from death",IB,"paired with the plea to deliver",
  "v4: 'O LORD, I pray, deliver my SOUL (nephesh)!' - the self begging rescue, life pleading for its life."),
 (270999,"simple (pethi)","status","the simple","be preserved","by God",IB,"paired with being brought low and saved",
  "v6: 'The LORD preserves the SIMPLE (pethi)' - the artless, the childlike, whom God keeps; the psalmist owns himself among them."),
 (271000,"brought low (dalal)","state","the psalmist","be brought low","then saved",IB,"paired with being saved",
  "v6: 'when I was BROUGHT LOW (dalal), he saved me' - the abasement from which God rescued, low estate met by salvation."),
 (271002,"return (shuv)","action","the psalmist","return","his soul to rest",IB,"paired with the soul at rest",
  "v7: 'RETURN (shuv), O my soul, to your rest' - the self-summons to peace, the soul called home to quiet after deliverance."),
 (271003,"soul (nephesh)","faculty","the psalmist","return to rest","in God",IB,"paired with the returning",
  "v7: 'Return, O my SOUL (nephesh), to your rest' - the inmost self addressed, bidden to settle in God's bounty."),
 (271010,"soul (nephesh)","faculty","the psalmist","be delivered","from death",IB,"paired with eyes from tears, feet from stumbling",
  "v8: 'For you have delivered my SOUL (nephesh) from death' - the self rescued from the grave, the ground of the rest."),
 (271014,"tears (dimah)","state","the psalmist","weep","then be delivered",IB,"paired with the delivered soul",
  "v8: 'my eyes from TEARS (dimah)' - the weeping God turned back, grief dried by deliverance."),
 (271017,"walk (halak)","action","the psalmist","walk","before the LORD in the land of the living",GOD,"paired with the delivered soul",
  "v9: 'I will WALK (halak) before the LORD in the land of the living' - the life of faith resumed, conduct lived out in God's presence."),
 (270927,"believe (aman)","disposition","the psalmist","believe","even in affliction",GOD,"paired with being greatly afflicted",
  "v10: 'I BELIEVED (aman), even when I spoke: I am greatly afflicted' - the faith that held even under affliction, belief speaking through pain."),
 (270930,"afflicted (anah)","state","the psalmist","be greatly afflicted","yet believing",IB,"paired with believing",
  "v10: 'I am greatly AFFLICTED (anah)' - the depth of the suffering the psalmist confessed even as he believed."),
 (307626,"alarm (chaphaz)","state","the psalmist","be in alarm / panic","distrusting man",IB,"paired with judging all men liars",
  "v11: 'I said in my ALARM (chaphaz), All mankind are liars' - the panic of the sufferer, dismay that trusted no man."),
 (307629,"liars (kazab)","status","all mankind","be liars","untrustworthy",IB,"paired with the alarm",
  "v11: 'All mankind are LIARS (kazab)' - the verdict of the alarmed, human faithlessness weighed against God's truth."),
 (307631,"render (shuv)","action","the psalmist","render / repay","to the LORD for his benefits",GOD,"paired with lifting the cup of salvation",
  "v12: 'What shall I RENDER (shuv) to the LORD for all his benefits to me?' - the grateful question, the search for a fitting response."),
 (270931,"lift up (nasa)","action","the psalmist","lift up","the cup of salvation",GOD,"paired with calling on God's name",
  "v13: 'I will LIFT UP (nasa) the cup of salvation' - the thankful gesture, raising the cup in acknowledgement of God's rescue."),
 (270934,"call (qara)","action","the psalmist","call","on the name of the LORD",GOD,"paired with lifting the cup",
  "v13: 'and CALL (qara) on the name of the LORD' - worship joined to the cup, prayer with thanksgiving."),
 (270937,"pay (shalam)","action","the psalmist","pay","his vows to the LORD",GOD,"paired with the presence of all his people",
  "v14: 'I will PAY (shalam) my vows to the LORD in the presence of all his people' - the vows fulfilled, gratitude made public."),
 (270948,"saints (chasid)","status","the saints","be precious to God","in their death",IB,"paired with the preciousness of their death",
  "v15: 'Precious in the sight of the LORD is the death of his SAINTS (chasid)' - the godly, whose very death God holds dear."),
 (270951,"thanksgiving (todah)","action","the psalmist","offer thanksgiving","to God",GOD,"paired with calling on God's name",
  "v17: 'I will offer to you the sacrifice of THANKSGIVING (todah)' - the thank-offering of the delivered, gratitude enacted."),
 (270952,"call (qara)","action","the psalmist","call","on the name of the LORD",GOD,"paired with the thank-offering",
  "v17: 'and CALL (qara) on the name of the LORD' - worship joined to the sacrifice."),
 (270955,"pay (shalam)","action","the psalmist","pay","his vows to the LORD",GOD,"paired with the presence of all his people",
  "v18: 'I will PAY (shalam) my vows to the LORD in the presence of all his people' - the vows fulfilled before the assembly."),
 (270969,"praise (halal)","action","the worshipper","praise","the LORD",GOD,"paired with the whole thanksgiving",
  "v19: 'PRAISE (halal) the LORD!' - the closing Hallelujah, the psalm sealed with praise."),
]
for a in CH: r.ch(*a)
LO=270920; CA=270984; RE=271002; BE=270927; TH=270951
QU=[
 (270923,"heard (shama)",LO,"v1: 'because he has HEARD (shama) my voice' - God's hearing. Qualifier."),
 (270971,"inclined (natah)",270973,"v2: 'Because he INCLINED (natah) his ear to me' - God's attentive bending. Qualifier."),
 (270985,"name (shem)",CA,"v4: 'I called on the NAME (shem) of the LORD' - God's name. Qualifier."),
 (270989,"deliver (malat)",CA,"v4: 'O LORD, I pray, DELIVER (malat) my soul!' - God's rescue petitioned. Qualifier."),
 (270992,"gracious (chanun)",RE,"v5: 'GRACIOUS (chanun) is the LORD, and righteous' - God's grace. Qualifier."),
 (270994,"righteous (tsaddiq)",RE,"v5: 'Gracious is the LORD, and RIGHTEOUS (tsaddiq)' - God's righteousness. Qualifier."),
 (270996,"merciful (racham)",RE,"v5: 'our God is MERCIFUL (racham)' - God's mercy. Qualifier."),
 (270998,"preserves (shamar)",RE,"v6: 'The LORD PRESERVES (shamar) the simple' - God's keeping of the simple. Qualifier."),
 (271001,"saved (yasha)",RE,"v6: 'when I was brought low, he SAVED (yasha) me' - God's salvation. Qualifier."),
 (271006,"dealt bountifully (gamal)",RE,"v7: 'for the LORD has DEALT BOUNTIFULLY (gamal) with you' - God's generosity. Qualifier."),
 (271009,"delivered (chalats)",RE,"v8: 'For you have DELIVERED (chalats) my soul from death' - God's deliverance. Qualifier."),
 (270933,"salvation (yeshuah)",TH,"v13: 'I will lift up the cup of SALVATION (yeshuah)' - God's salvation. Qualifier."),
 (270935,"name (shem)",TH,"v13: 'and call on the NAME (shem) of the LORD' - God's name. Qualifier."),
 (307647,"loosed (pathach)",TH,"v16: 'You have LOOSED (pathach) my bonds' - God's freeing of the psalmist. Qualifier."),
 (270953,"name (shem)",TH,"v17: 'and call on the NAME (shem) of the LORD' - God's name. Qualifier."),
]
for sid,sense,src,d in QU: r.qu(sid,sense,src,d)
ST=[
 (270924,"voice (qol)","v1: 'he has heard my VOICE (qol)' - the psalmist's voice God heard, object. Standalone."),
 (270975,"snares (chebel)","v3: 'The SNARES (chebel) of death encompassed me' - the cords of death, image of peril. Standalone."),
 (270976,"death (maveth)","v3: 'the snares of DEATH (maveth)' - death closing in, image. Standalone."),
 (270977,"encompassed (aphaph)","v3: 'the snares of death ENCOMPASSED (aphaph) me' - the surrounding peril, image. Standalone."),
 (270978,"pangs (metsar)","v3: 'the PANGS (metsar) of Sheol laid hold on me' - the grip of the grave, image of distress. Standalone."),
 (270979,"Sheol (sheol)","v3: 'the pangs of SHEOL (sheol)' - the realm of death, image. Standalone."),
 (270980,"laid hold (matsa)","v3: 'the pangs of Sheol LAID HOLD (matsa) on me' - the seizing distress, image. Standalone."),
 (270982,"distress (tsarah)","v3: 'I suffered DISTRESS (tsarah) and anguish' - the trouble the psalmist suffered (char suffered, 270981), image. Standalone."),
 (271004,"rest (menuchah)","v7: 'Return, O my soul, to your REST (menuchah)' - the peace to which the soul returns (char return, 271002), image. Standalone."),
 (271011,"death (maveth)","v8: 'you have delivered my soul from DEATH (maveth)' - the death the soul was rescued from, image. Standalone."),
 (271016,"stumbling (dechi)","v8: 'my feet from STUMBLING (dechi)' - the fall God prevented, image. Standalone."),
 (270932,"cup (kos)","v13: 'I will lift up the CUP (kos) of salvation' - the cup of thanksgiving, image of the salvation received. Standalone."),
 (270938,"vows (neder)","v14: 'I will pay my VOWS (neder) to the LORD' - the vows fulfilled (char pay, 270937), object. Standalone."),
 (270944,"precious (yaqar)","v15: 'PRECIOUS (yaqar) in the sight of the LORD is the death of his saints' - God's high valuation of the saints' death, God-content descriptor. Standalone."),
 (270947,"death (maveth)","v15: 'is the DEATH (maveth) of his saints' - the death of the godly (char saints, 270948), object. Standalone."),
 (307638,"O LORD (anna)","v16: 'O (anna) LORD, I am your servant' - the address to God, the servant's confession. Standalone."),
 (307649,"bonds (moser)","v16: 'You have loosed my BONDS (moser)' - the chains God freed (qual loosed, 307647), image. Standalone."),
 (270949,"offer (zabach)","v17: 'I will OFFER (zabach) to you the sacrifice of thanksgiving' - the offering of the char thanksgiving (270951). Standalone."),
 (270950,"sacrifice (zebach)","v17: 'the SACRIFICE (zebach) of thanksgiving' - the thank-offering, image of worship. Standalone."),
 (270956,"vows (neder)","v18: 'I will pay my VOWS (neder) to the LORD' - the vows fulfilled (char pay, 270955), object. Standalone."),
 (270963,"courts (chatser)","v19: 'in the COURTS (chatser) of the house of the LORD' - the temple courts, place of the thanksgiving. Standalone."),
]
for sid,sense,d in ST: r.st(sid,sense,d)
r.write()
