import sys; sys.path.insert(0,'scripts')
from _reread_ledger_lib import Reading, IB, GOD, PER
r=Reading("Psa",19,90,
  note="Ps90 Moses on transience vs God's eternity (17v). Passages: God's eternity v1-2; man returned to dust, swept like grass v3-6; consumed by wrath, secret sins exposed, years a sigh of toil v7-11; the prayer - number our days, a heart of wisdom, satisfy us v12-17. IB: the return to DUST; being brought to an END/DISMAYED under wrath; our INIQUITIES + SECRET-SINS; years ended like a sigh, life's span TOIL + TROUBLE; who CONSIDERS God's anger, the FEAR of him; NUMBER our days for a HEART of WISDOM; the plea to REJOICE + be GLAD. God's dwelling/eternity/form/return-to-dust/wrath/teach/satisfy/steadfast-love/establish = qualifiers; grass/watch/flood/dream imagery = standalone.")
for a in [
 (307067,"return to dust (dakka)","state","man / mankind","be turned back to dust","by God","paired with God's word 'Return'",IB,"v3: 'You return man to DUST (dakka)' - the creatureliness and mortality of man, dust to which he is turned back at God's word."),
 (285040,"be consumed / brought to an end (kalah)","state","we (mankind)","be consumed","by God's anger","paired with being dismayed by wrath",IB,"v7: 'For we are brought to an END (kalah) by your anger' - the perishing of frail humanity under God's wrath, consumed like the withering grass."),
 (285044,"be dismayed (bahal)","state","we (mankind)","be terrified / dismayed","by God's wrath","paired with being consumed",IB,"v7: 'by your wrath we are DISMAYED (bahal)' - the terror of mortals before God's anger, dread at their own frailty."),
 (285046,"iniquities (avon)","state","we (mankind)","bear iniquities","exposed before God","paired with the secret sins",IB,"v8: 'You have set our INIQUITIES (avon) before you' - our guilt laid open to God, the hidden ground of the wrath that consumes us."),
 (285048,"secret sins (alum)","state","we (mankind)","bear hidden sins","in the light of God's face","paired with the iniquities set before God",IB,"v8: 'our SECRET SINS (alum) in the light of your presence' - the concealed faults God's face exposes; nothing hidden from him."),
 (285058,"bring to an end (kalah)","state","we (mankind)","end our years","like a sigh","paired with the fleeting sigh",IB,"v9: 'we bring our years to an END (kalah) like a sigh' - the whole of life finished in a breath, our years spent and gone."),
 (284957,"toil (amal)","state","our life","be full of toil","and trouble","paired with trouble",IB,"v10: 'yet their span is but TOIL (amal) and trouble' - the wearying labour that fills even the longest life, existence as hard toil."),
 (284958,"trouble (aven)","state","our life","be full of trouble","and sorrow","paired with toil",IB,"v10: 'their span is but toil and TROUBLE (aven)' - the sorrow that accompanies the toil, life's brevity matched by its hardship."),
 (284963,"consider (yada)","action","whoever is wise","consider / discern","the power of God's anger","paired with the fear due to God",IB,"v11: 'Who CONSIDERS (yada) the power of your anger?' - the rare discernment that reckons with God's wrath, the reflection few make."),
 (284967,"fear (yirah)","disposition","mankind","fear / revere","God","paired with considering his anger",GOD,"v11: 'and your wrath according to the FEAR (yirah) of you' - the reverence God's power should command, wrath measured by the fear due him."),
 (284969,"number (manah)","action","we (mankind)","number / reckon","our days","paired with getting a heart of wisdom",IB,"v12: 'teach us to NUMBER (manah) our days' - the wise reckoning of life's brevity, counting the days so as to spend them well."),
 (284972,"heart (lebab)","faculty","we (mankind)","gain a heart","of wisdom","paired with wisdom",IB,"v12: 'that we may get a HEART (lebab) of wisdom' - the inner self schooled by mortality, the heart that learns wisdom from counting its days."),
 (284973,"wisdom (chokmah)","disposition","we (mankind)","gain wisdom","from numbering our days","paired with the heart",IB,"v12: 'that we may get a heart of WISDOM (chokmah)' - the wisdom that flows from facing death, the fruit of numbering our days."),
 (284985,"rejoice (ranan)","action","we (mankind)","rejoice / sing for joy","in God all our days","paired with being glad",GOD,"v14: 'that we may REJOICE (ranan) and be glad all our days' - the joy sought from God's steadfast love, gladness to answer the years of affliction."),
 (284986,"be glad (samach)","state","we (mankind)","be glad","in God","paired with rejoicing",IB,"v14: 'that we may rejoice and be GLAD (samach) all our days' - the gladness God's love would give, joy for the whole of life."),
 (284990,"be glad (samach)","state","we (mankind)","be made glad","by God","paired with the days of affliction","external:god","v15: 'Make us GLAD (samach) for as many days as you have afflicted us' - the plea that joy might balance the years of suffering, gladness measured against affliction."),
]: r.ch(*a)
for sid,sense,src,d in [
 (307061,"dwelling place (maon)",307067,"v1: 'Lord, you have been our DWELLING PLACE (maon) in all generations' - God the refuge of every age. Qualifier."),
 (285015,"bring forth (yalad)",307067,"v2: 'Before the mountains were BROUGHT FORTH (yalad)' - God's begetting of creation. Qualifier."),
 (285016,"form (chul)",307067,"v2: 'or ever you had FORMED (chul) the earth and the world' - God's forming of the world. Qualifier."),
 (285020,"everlasting (olam)",307067,"v2: 'from EVERLASTING (olam)... you are God' - God's eternity before the world. Qualifier."),
 (285022,"everlasting (olam)",307067,"v2: 'to EVERLASTING (olam) you are God' - God's eternity without end. Qualifier."),
 (307065,"return (shuv)",307067,"v3: 'You RETURN (shuv) man to dust' - God's turning man back to dust. Qualifier."),
 (307069,"return (shuv)",307067,"v3: 'and say, RETURN (shuv), O children of man' - God's word of mortality. Qualifier."),
 (285045,"set (shith)",285046,"v8: 'You have SET (shith) our iniquities before you' - God's placing our sins in view. Qualifier."),
 (285049,"light (maor)",285048,"v8: 'in the LIGHT (maor) of your presence' - the light of God's face that exposes sin. Qualifier."),
 (285041,"anger (aph)",285040,"v7: 'we are brought to an end by your ANGER (aph)' - God's anger. Qualifier."),
 (285043,"wrath (chemah)",285044,"v7: 'by your WRATH (chemah) we are dismayed' - God's wrath. Qualifier."),
 (285056,"wrath (ebrah)",285058,"v9: 'all our days pass away under your WRATH (ebrah)' - God's wrath. Qualifier."),
 (284964,"power (oz)",284963,"v11: 'Who considers the POWER (oz) of your anger?' - God's mighty anger. Qualifier."),
 (284965,"anger (aph)",284963,"v11: 'the power of your ANGER (aph)' - God's anger. Qualifier."),
 (284966,"wrath (ebrah)",284963,"v11: 'and your WRATH (ebrah)' - God's wrath. Qualifier."),
 (284968,"teach (yada)",284969,"v12: 'So TEACH (yada) us to number our days' - God's instruction petitioned. Qualifier."),
 (284974,"return (shuv)",284985,"v13: 'RETURN (shuv), O LORD! How long?' - God's turning back to his people petitioned. Qualifier."),
 (284978,"have pity (nacham)",284985,"v13: 'Have PITY (nacham) on your servants!' - God's compassion petitioned. Qualifier."),
 (284982,"satisfy (saba)",284985,"v14: 'SATISFY (saba) us in the morning with your steadfast love' - God's satisfying petitioned. Qualifier."),
 (284984,"steadfast love (chesed)",284985,"v14: 'satisfy us with your STEADFAST LOVE (chesed)' - God's covenant love. Qualifier."),
 (284992,"afflict (anah)",284990,"v15: 'for as many days as you have AFFLICTED (anah) us' - God's chastening. Qualifier."),
 (284996,"work (poal)",284985,"v16: 'Let your WORK (poal) be shown to your servants' - God's deeds. Qualifier."),
 (284997,"be shown (raah)",284985,"v16: 'Let your work be SHOWN (raah) to your servants' - God's revealing of his work. Qualifier."),
 (285000,"glorious power (hadar)",284985,"v16: 'and your GLORIOUS POWER (hadar) to their children' - God's majesty. Qualifier."),
 (285003,"favor (noam)",284985,"v17: 'Let the FAVOUR (noam) of the Lord our God be upon us' - God's favour petitioned. Qualifier."),
 (285006,"establish (kun)",284985,"v17: 'ESTABLISH (kun) the work of our hands' - God's confirming of our labour petitioned. Qualifier."),
 (285010,"establish (kun)",284985,"v17: 'yes, ESTABLISH (kun) the work of our hands' - God's confirming, repeated. Qualifier."),
]: r.qu(sid,sense,src,d)
for sid,sense,d in [
 (307056,"Prayer (tephillah)","v0 superscription: 'A PRAYER (tephillah) of Moses' - the psalm-heading/type. Standalone."),
 (285018,"world (tebel)","v2: 'or ever you had formed the earth and the WORLD (tebel)' - the created world, object of God's forming. Standalone."),
 (307074,"years (shanah)","v4: 'For a thousand YEARS (shanah) in your sight are but as yesterday' - the measure of time before God, image of his eternity. Standalone."),
 (307078,"past (abar)","v4: 'as yesterday when it is PAST (abar)' - the fleeting day, image of time's brevity before God. Standalone."),
 (307079,"watch (ashmurah)","v4: 'or as a WATCH (ashmurah) in the night' - the night-watch, image of a millennium's brevity to God. Standalone."),
 (285025,"flood / sweep away (zaram)","v5: 'You sweep them away as with a FLOOD (zaram)' - the torrent of mortality, image. Standalone."),
 (285026,"dream (shenah)","v5: 'they are like a DREAM (shenah)' - life as a passing dream, image of transience. Standalone."),
 (285028,"grass (chatsir)","v5: 'like GRASS (chatsir) that is renewed in the morning' - the grass, image of the brief human life. Standalone."),
 (285029,"renewed (chalaph)","v5: 'grass that is RENEWED (chalaph) in the morning' - the grass springing up, image. Standalone."),
 (285033,"flourish (tsuts)","v6: 'in the morning it FLOURISHES (tsuts) and is renewed' - the morning bloom, image of youth. Standalone."),
 (285034,"renewed (chalaph)","v6: 'it flourishes and is RENEWED (chalaph)' - the grass's brief greening, image. Standalone."),
 (285036,"evening (ereb)","v6: 'in the EVENING (ereb) it fades and withers' - the day's end, image of life's close. Standalone."),
 (285037,"fade (malal)","v6: 'in the evening it FADES (malal)' - the grass fading, image of decline. Standalone."),
 (285038,"wither (yabesh)","v6: 'it fades and WITHERS (yabesh)' - the withered grass, image of death (the withering that ends the char consumed, 285040). Standalone."),
 (285055,"pass away (panah)",'v9: "all our days PASS AWAY (panah) under your wrath" - the days turning away and gone, image of transience. Standalone.'),
 (285057,"years (shanah)","v9: 'we bring our YEARS (shanah) to an end' - the years, measure of the fleeting life. Standalone."),
 (285059,"sigh (hegeh)","v9: 'we bring our years to an end like a SIGH (hegeh)' - the moan/breath, image of how quickly life is spent. Standalone."),
 (284951,"years / life (shanah)","v10: 'The YEARS (shanah) of our life are seventy' - the span of life, the reckoning of days. Standalone."),
 (284952,"seventy (shibim)","v10: 'the years of our life are SEVENTY (shibim)' - the typical lifespan, the count of years. Standalone."),
 (284954,"strength (geburah)","v10: 'or even by reason of STRENGTH (geburah) eighty' - the vigour of the long-lived, image. Standalone."),
 (284955,"eighty (shemonim)","v10: 'by reason of strength EIGHTY (shemonim)' - the outer limit of life, the count. Standalone."),
 (284956,"span (rohab)","v10: 'yet their SPAN (rohab) is but toil and trouble' - the extent of life, filled with toil (the char, 284957). Standalone."),
 (284960,"gone (guz)","v10: 'they are soon GONE (guz)' - the swift passing of the years, image. Standalone."),
 (284961,"fly away (uph)","v10: 'and we FLY AWAY (uph)' - life vanishing like a bird, image of transience. Standalone."),
 (284993,"years (shanah)","v15: 'and as many YEARS (shanah) as we have seen evil' - the years of affliction, measure of suffering. Standalone."),
 (284994,"seen (raah)","v15: 'as many years as we have SEEN (raah) evil' - the experience of adversity, image. Standalone."),
 (284995,"evil / adversity (ra)","v15: 'as many years as we have seen EVIL (ra)' - the adversity endured, the affliction to be balanced by gladness. Standalone."),
 (285007,"work (maaseh)","v17: 'establish the WORK (maaseh) of our hands' - the labour of human hands, what is offered for God to confirm. Standalone."),
 (285011,"work (maaseh)","v17: 'the WORK (maaseh) of our hands, establish it' - the repeated plea for the labour to be established. Standalone."),
]: r.st(sid,sense,d)
r.write()
