import sys; sys.path.insert(0,'scripts')
from _reread_ledger_lib import Reading, IB, GOD, PER
r=Reading("Psa",19,94,
  note="Ps94 God of vengeance / plea against wicked oppressors (23v). Passages: plea to the God of vengeance v1-7; rebuke of the senseless (he who planted the ear, hears) v8-11; blessed is the disciplined man v12-15; who stands up for me? the LORD held me up v16-19; can wicked rulers ally with you? the LORD is my stronghold v20-23. IB: the PROUD/WICKED who EXULT, speak ARROGANTly, CRUSH/AFFLICT/KILL/MURDER the helpless; the call to UNDERSTAND (FOOLS, be WISE); man's THOUGHTS known to be breath; BLESSED is the disciplined man given REST; the RIGHTEOUS/UPRIGHT in HEART; the SOUL near silence, the anxious CARES God's consolations cheer the SOUL; wicked rulers who frame INJUSTICE, BAND-TOGETHER, CONDEMN the INNOCENT; their INIQUITY/WICKEDNESS. God's vengeance/judge/discipline/teach/not-forsake/stronghold = qualifiers; pit/silence/statute imagery = standalone.")
CH=[
 (285380,"proud (geeh)","status","the proud","be arrogant","against God's people","paired with what they deserve",IB,"v2: 'repay to the PROUD (geeh) what they deserve!' - the arrogant oppressors, pride that invites God's requital."),
 (302411,"wicked (rasha)","status","the wicked","exult / triumph","in their oppression",IB,"paired with their exulting","v3: 'How long shall the WICKED (rasha), O LORD, how long shall the wicked exult?' - the godless whose long triumph provokes the cry for vengeance."),
 (302415,"exult (alaz)","action","the wicked","exult / triumph","over the oppressed",IB,"paired with the wicked","v3: 'how long shall the wicked EXULT (alaz)?' - the wicked's arrogant triumph, gloating that seems to go unpunished."),
 (285410,"arrogant (athaq)","disposition","the evildoers","speak arrogantly","boasting","paired with their outpoured words",IB,"v4: 'They speak ARROGANTLY (athaq); all the evildoers boast' - the insolent speech of the wicked, pride pouring from the mouth."),
 (285415,"crush (daka)","action","the wicked","crush","God's people",IB,"paired with afflicting the heritage","v5: 'They CRUSH (daka) your people, O LORD' - the violent oppression of the wicked against God's own."),
 (285418,"afflict (anah)","action","the wicked","afflict","God's heritage",IB,"paired with crushing the people","v5: 'and AFFLICT (anah) your heritage' - the tormenting of God's inheritance by the wicked."),
 (307123,"kill (harag)","action","the wicked","kill","the widow and sojourner",IB,"paired with murdering the fatherless","v6: 'They KILL (harag) the widow and the sojourner' - the murder of the defenceless, oppression at its cruelest."),
 (307126,"murder (ratsach)","action","the wicked","murder","the fatherless",IB,"paired with killing the widow","v6: 'and MURDER (ratsach) the fatherless' - the slaying of the orphan, the wicked's contempt for the helpless."),
 (285428,"understand (bin)","action","the senseless people","understand / consider","God who sees and hears",IB,"paired with the call to be wise","v8: 'UNDERSTAND (bin), O dullest of the people!' - the summons to the brutish to consider, the call to sense."),
 (285431,"fools (kesil)","status","the fools","be foolish","refusing to be wise",IB,"paired with the call to be wise","v8: 'FOOLS (kesil), when will you be wise?' - the senseless who think God does not see, folly rebuked."),
 (285433,"be wise (sakal)","disposition","the fools","become wise","toward God",IB,"paired with the folly rebuked","v8: 'when will you be WISE (sakal)?' - the wisdom the fools are urged toward, the discernment they lack."),
 (285314,"thoughts (machashabah)","faculty","man / mankind","have thoughts","known by God to be breath",IB,"paired with God's knowing them","v11: 'The LORD knows the THOUGHTS (machashabah) of man, that they are but a breath' - the vain reasonings of man, all exposed to God and shown to be nothing."),
 (285319,"blessed (esher)","state","the disciplined man","be blessed","under God's discipline",IB,"paired with being taught God's law","v12: 'BLESSED (esher) is the man whom you discipline, O LORD' - the happiness of the one God corrects and teaches, chastening as grace."),
 (285328,"rest (shaqat)","state","the disciplined man","be given rest","from days of trouble",IB,"paired with the pit dug for the wicked","v13: 'to give him REST (shaqat) from days of trouble' - the quiet God grants the disciplined while judgment ripens for the wicked."),
 (285348,"righteous (tsedeq)","status","the righteous","receive justice","from God",IB,"paired with the upright in heart","v15: 'for justice will return to the RIGHTEOUS (tsedeq)' - the righteous to whom judgment will come back round, vindication assured."),
 (285350,"upright (yashar)","status","the upright","follow justice","after God","paired with the upright heart",IB,"v15: 'and all the UPRIGHT (yashar) in heart will follow it' - the upright who pursue the returning justice, aligned with God's verdict."),
 (285351,"heart (leb)","faculty","the upright","be upright","in heart",IB,"paired with the upright","v15: 'all the upright in HEART (leb) will follow it' - the inner rectitude of the upright, uprightness seated in the heart."),
 (302659,"soul (nephesh)","faculty","the psalmist","nearly dwell","in the land of silence",IB,"paired with God his help","v17: 'my SOUL (nephesh) would soon have lived in the land of silence' - the self on the brink of death, saved only because God was his help."),
 (285368,"cares (sarapp)","state","the psalmist","be full of anxious cares","in the heart",IB,"paired with God's consolations","v19: 'When the CARES (sarapp) of my heart are many' - the crowding anxieties within, the multiplied worries God meets with comfort."),
 (285374,"soul (nephesh)","faculty","the psalmist","be cheered","by God's consolations",IB,"paired with the anxious cares","v19: 'your consolations CHEER my SOUL (nephesh)' - the self gladdened by God's comforts, anxiety answered by divine consolation."),
 (285382,"wicked (havvah)","status","wicked rulers","frame injustice","as though allied with God",IB,"paired with framing injustice by statute","v20: 'Can WICKED (havvah) rulers be allied with you?' - the corrupt authorities who legislate evil, wickedness enthroned."),
 (285386,"injustice (amal)","action","wicked rulers","frame injustice","by statute",IB,"paired with the wicked rulers","v20: 'those who frame INJUSTICE (amal) by statute?' - the manufacture of oppression under colour of law, evil made legal."),
 (285389,"band together (gadad)","action","the wicked","band together / conspire","against the righteous",IB,"paired with condemning the innocent","v21: 'They BAND TOGETHER (gadad) against the life of the righteous' - the conspiracy of the wicked, malice organized against the just."),
 (285393,"condemn (rasha)","action","the wicked","condemn","the innocent to death",IB,"paired with banding together","v21: 'and CONDEMN (rasha) the innocent to death' - the judicial murder of the guiltless, the wicked's verdict against the blameless."),
 (285394,"innocent (naqi)","status","the innocent","be condemned","by the wicked",IB,"paired with the condemning","v21: 'and condemn the INNOCENT (naqi) to death' - the guiltless victim, whose very innocence the wicked assail."),
 (285403,"iniquity (aven)","state","the wicked","bear iniquity","brought back by God",IB,"paired with their wickedness","v23: 'He will bring back on them their INIQUITY (aven)' - the guilt of the wicked, returned upon their own heads."),
 (285405,"wickedness (ra)","state","the wicked","bear wickedness","for which they are wiped out",IB,"paired with their iniquity","v23: 'and wipe them out for their WICKEDNESS (ra)' - the evil for which the wicked are destroyed, sin recoiling on the sinner."),
]
for a in CH: r.ch(*a)
QU=[
 (307119,"vengeance (naqam)",302411,"v1: 'O LORD, God of VENGEANCE (naqam)' - God's avenging justice. Qualifier."),
 (307121,"vengeance (naqam)",302411,"v1: 'God of VENGEANCE (naqam), shine forth!' - God's requital invoked. Qualifier."),
 (307122,"shine forth (yapha)",302411,"v1: 'SHINE FORTH (yapha)!' - God's appearing in judgment petitioned. Qualifier."),
 (285375,"rise up (nasa)",285380,"v2: 'RISE UP (nasa), O judge of the earth' - God's rising to judge petitioned. Qualifier."),
 (285376,"judge (shaphat)",285380,"v2: 'O JUDGE (shaphat) of the earth' - God as judge. Qualifier."),
 (285378,"repay (shuv)",285380,"v2: 'REPAY (shuv) to the proud what they deserve' - God's requital petitioned. Qualifier."),
 (285423,"see (raah)",285410,"v7: 'and they say, The LORD does not SEE (raah)' - God's seeing, which the wicked deny. Qualifier."),
 (285427,"perceive (bin)",285410,"v7: 'nor does the God of Jacob PERCEIVE (bin)' - God's perceiving, denied by the wicked. Qualifier."),
 (285434,"planted (nata)",285428,"v9: 'He who PLANTED (nata) the ear, does he not hear?' - God the maker of the ear. Qualifier."),
 (285437,"hear (shama)",285428,"v9: 'He who planted the ear, does he not HEAR (shama)?' - God's hearing. Qualifier."),
 (285438,"formed (yatsar)",285428,"v9: 'He who FORMED (yatsar) the eye, does he not see?' - God the maker of the eye. Qualifier."),
 (285441,"see (nabat)",285428,"v9: 'He who formed the eye, does he not SEE (nabat)?' - God's seeing. Qualifier."),
 (285305,"discipline (yasar)",285319,"v10: 'He who DISCIPLINES (yasar) the nations, does he not rebuke?' - God's chastening of nations. Qualifier."),
 (285308,"rebuke (yakach)",285319,"v10: 'does he not REBUKE (yakach)?' - God's correction. Qualifier."),
 (285309,"teach (lamad)",285319,"v10: 'he who TEACHES (lamad) man knowledge' - God the teacher of mankind. Qualifier."),
 (285311,"knowledge (daath)",285314,"v10: 'he who teaches man KNOWLEDGE (daath)' - God-given knowledge. Qualifier."),
 (285313,"know (yada)",285314,"v11: 'The LORD KNOWS (yada) the thoughts of man' - God's knowledge of the heart. Qualifier."),
 (285322,"discipline (yasar)",285319,"v12: 'Blessed is the man whom you DISCIPLINE (yasar)' - God's chastening. Qualifier."),
 (285324,"teach (lamad)",285319,"v12: 'and whom you TEACH (lamad) out of your law' - God's instruction. Qualifier."),
 (285326,"law (torah)",285319,"v12: 'out of your LAW (torah)' - God's law. Qualifier."),
 (285339,"forsake (natash)",285348,"v14: 'For the LORD will not FORSAKE (natash) his people' - God's steadfast keeping. Qualifier."),
 (285343,"abandon (azab)",285348,"v14: 'he will not ABANDON (azab) his heritage' - God's not-abandoning. Qualifier."),
 (285344,"heritage (nachalah)",285348,"v14: 'he will not abandon his HERITAGE (nachalah)' - God's inheritance, his people. Qualifier."),
 (285419,"heritage (nachalah)",285415,"v5: 'and afflict your HERITAGE (nachalah)' - God's inheritance, the afflicted people. Qualifier."),
 (285346,"justice (mishpat)",285348,"v15: 'for JUSTICE (mishpat) will return to the righteous' - God's justice. Qualifier."),
 (285347,"return (shuv)",285348,"v15: 'justice will RETURN (shuv) to the righteous' - God's justice coming back round. Qualifier."),
 (285354,"rise up (qum)",302659,"v16: 'Who RISES UP (qum) for me against the wicked?' - the defender (God) who rises for the psalmist. Qualifier."),
 (285358,"stand up (yatsab)",302659,"v16: 'Who STANDS UP (yatsab) for me against evildoers?' - the champion (God) who stands for him. Qualifier."),
 (302657,"help (ezrah)",302659,"v17: 'If the LORD had not been my HELP (ezrah)' - God's help. Qualifier."),
 (285365,"steadfast love (chesed)",302659,"v18: 'your STEADFAST LOVE (chesed), O LORD, held me up' - God's covenant love. Qualifier."),
 (285367,"hold up (saad)",302659,"v18: 'your steadfast love HELD ME UP (saad)' - God's upholding. Qualifier."),
 (285371,"consolations (tanchum)",285374,"v19: 'your CONSOLATIONS (tanchum) cheer my soul' - God's comforts. Qualifier."),
 (285372,"cheer (shaa)",285374,"v19: 'your consolations CHEER (shaa) my soul' - God's cheering of the soul. Qualifier."),
 (285397,"stronghold (misgab)",302659,"v22: 'But the LORD has become my STRONGHOLD (misgab)' - God as fortress. Qualifier."),
 (285399,"rock (tsur)",302659,"v22: 'and my God the ROCK (tsur) of my refuge' - God as rock. Qualifier."),
 (285400,"refuge (machseh)",302659,"v22: 'the rock of my REFUGE (machseh)' - God as refuge. Qualifier."),
 (285401,"bring back (shuv)",285403,"v23: 'He will BRING BACK (shuv) on them their iniquity' - God's requital. Qualifier."),
 (285404,"wipe out (tsamath)",285405,"v23: 'and WIPE THEM OUT (tsamath) for their wickedness' - God's destruction of the wicked. Qualifier."),
 (285408,"wipe out (tsamath)",285405,"v23: 'the LORD our God will WIPE THEM OUT (tsamath)' - God's judgment. Qualifier."),
 (285334,"dug (karah)",285328,"v13: 'until a pit is DUG (karah) for the wicked' - God's preparing of judgment. Qualifier."),
]
for sid,sense,src,d in QU: r.qu(sid,sense,src,d)
ST=[
 (285381,"deserve (gemul)","v2: 'repay to the proud what they DESERVE (gemul)' - the due recompense of the proud, the object of the repayment. Standalone."),
 (302414,"wicked (rasha)","v3: 'how long shall the WICKED (rasha) exult?' - the wicked repeated, the doubled cry (char, 302411). Standalone."),
 (285409,"pour out (naba)","v4: 'They POUR OUT (naba) their arrogant words' - the gush of insolent speech, image of the arrogance (char, 285410). Standalone."),
 (285413,"evildoers (paal aven)","v4: 'all the EVILDOERS (paal aven) boast' - the workers of iniquity, parallel to the arrogant. Standalone."),
 (307127,"fatherless (yathom)","v6: 'and murder the FATHERLESS (yathom)' - the orphan victims of the wicked's murder (char, 307126). Standalone."),
 (285429,"dullest (baar)","v8: 'O DULLEST (baar) of the people!' - the brutish epithet for the senseless (char understand, 285428). Standalone."),
 (285331,"trouble (ra)","v13: 'rest from days of TROUBLE (ra)' - the adversity from which rest is given; circumstance. Standalone."),
 (285333,"pit (shachath)","v13: 'until a PIT (shachath) is dug for the wicked' - the grave of judgment, image. Standalone."),
 (285335,"wicked (rasha)","v13: 'until a pit is dug for the WICKED (rasha)' - the wicked doomed to the pit, object. Standalone."),
 (285356,"wicked (raa)","v16: 'Who rises up for me against the WICKED (raa)?' - the wicked, object of the rhetorical question. Standalone."),
 (285360,"evildoers (paal aven)","v16: 'against the EVILDOERS (paal aven)?' - the workers of iniquity, object. Standalone."),
 (302661,"live / dwell (shakan)","v17: 'my soul would soon have LIVED (shakan) in the land of silence' - the dwelling in death, image (char soul, 302659). Standalone."),
 (302662,"silence (dumah)","v17: 'in the land of SILENCE (dumah)' - the realm of death, image. Standalone."),
 (285364,"slip (mot)","v18: 'When I thought, My foot SLIPS (mot)' - the faltering foot, image of near-collapse. Standalone."),
 (285369,"heart (qereb)","v19: 'the cares of my HEART (qereb)' - the inward seat of the anxious cares (char, 285368). Standalone."),
 (285370,"many (rob)","v19: 'when the cares of my heart are MANY (rob)' - the multitude of anxieties, image. Standalone."),
 (285383,"rulers (kisse)","v20: 'Can wicked RULERS (kisse, throne) be allied with you?' - the seats of corrupt authority (char, 285382). Standalone."),
 (285384,"allied (chabar)","v20: 'be ALLIED (chabar) with you?' - the impossible partnership of God with corrupt power, image. Standalone."),
 (285385,"frame (yatsar)","v20: 'those who FRAME (yatsar) injustice by statute' - the fashioning of oppression, image of the injustice (char, 285386). Standalone."),
 (285388,"statute (choq)","v20: 'frame injustice by STATUTE (choq)' - the law twisted into a tool of evil, image. Standalone."),
 (285391,"life (nephesh)","v21: 'against the LIFE (nephesh) of the righteous' - the life the wicked assail, object. Standalone."),
 (285392,"righteous (tsaddiq)","v21: 'against the life of the RIGHTEOUS (tsaddiq)' - the just, here the victims of the conspiracy. Standalone."),
 (285395,"death (dam)","v21: 'and condemn the innocent to DEATH (dam, blood)' - the sentence of death on the innocent, image. Standalone."),
]
for sid,sense,d in ST: r.st(sid,sense,d)
r.write()
