import sys; sys.path.insert(0,'scripts')
from _reread_ledger_lib import Reading, IB, GOD, PER
r=Reading("Psa",19,103,
  note="Ps103 'Bless the LORD, O my soul' (22v). Passages: bless the LORD who forgives/heals/redeems/crowns/satisfies v1-5; his righteousness, merciful+gracious+slow to anger, love toward those who fear him, he knows we are dust v6-14; man like grass, but his love everlasting on those who fear+keep covenant v15-18; his throne, let angels/hosts/works bless him v19-22. IB: the SOUL exhorting itself to BLESS (x3) + not FORGET; the INIQUITY/SINS/TRANSGRESSIONS forgiven; the OPPRESSED; those who FEAR (x3); a father's COMPASSION; our FRAME he knows; those who KEEP covenant + REMEMBER to obey. God's forgive/heal/redeem/crown/merciful/slow-to-anger/steadfast-love = qualifiers; grass/flower transience + the angels/hosts/works who bless (celestial, not human IB) = standalone.")
CH=[
 (269052,"bless (barak)","action","the psalmist","bless","the LORD",GOD,"paired with the soul stirred to bless","v1: 'BLESS (barak) the LORD, O my soul' - the self-summons to praise, the whole person called to bless God."),
 (269054,"soul (nephesh)","faculty","the psalmist","bless the LORD","with all within",IB,"paired with the blessing","v1: 'Bless the LORD, O my SOUL (nephesh), and all that is within me' - the innermost self roused to worship, praise from the depths."),
 (269132,"bless (barak)","action","the psalmist","bless","the LORD",GOD,"paired with not forgetting his benefits","v2: 'BLESS (barak) the LORD, O my soul' - the repeated self-exhortation, the resolve to praise renewed."),
 (269134,"soul (nephesh)","faculty","the psalmist","bless the LORD","not forgetting his benefits",IB,"paired with the blessing and not forgetting","v2: 'Bless the LORD, O my SOUL (nephesh)' - the self again stirred to worship, memory harnessed to praise."),
 (269135,"forget (shakach, negated)","disposition","the psalmist","not forget","all God's benefits",IB,"paired with blessing the LORD","v2: 'and FORGET (shakach) not all his benefits' - the guarded memory of God's goodness, worship that refuses amnesia."),
 (269172,"iniquity (avon)","state","the psalmist / us","have iniquity forgiven","by God",IB,"paired with God's forgiving","v3: 'who forgives all your INIQUITY (avon)' - the guilt God pardons, the first of the benefits not to be forgotten."),
 (269189,"oppressed (ashaq)","status","the oppressed","suffer oppression","vindicated by God",IB,"paired with God working justice","v6: 'and justice for all who are OPPRESSED (ashaq)' - the downtrodden for whom God works righteousness, the wronged he vindicates."),
 (269062,"sins (chet)","state","us","have sins","not repaid by God",IB,"paired with God's mercy","v10: 'He does not deal with us according to our SINS (chet)' - our sins, which God's mercy does not requite as they deserve."),
 (269067,"iniquities (avon)","state","us","have iniquities","not repaid by God",IB,"paired with our sins","v10: 'nor repay us according to our INIQUITIES (avon)' - our guilt, which God graciously does not repay in full."),
 (269074,"fear (yare)","disposition","those who fear God","fear / revere","God",GOD,"paired with God's great steadfast love","v11: 'so great is his steadfast love toward those who FEAR (yare) him' - the reverent, on whom God's boundless love rests."),
 (269082,"transgressions (pesha)","state","us","have transgressions removed","by God",IB,"paired with God removing them far","v12: 'so far does he remove our TRANSGRESSIONS (pesha) from us' - our rebellions, which God puts as far as east from west."),
 (269084,"show compassion (racham)","disposition","a father","show compassion","to his children",IB,"paired with God's compassion on those who fear him","v13: 'As a father SHOWS COMPASSION (racham) to his children' - the tender pity of a human father, the analogy for God's mercy."),
 (269090,"fear (yare)","disposition","those who fear God","fear / revere","God",GOD,"paired with God's compassion","v13: 'so the LORD shows compassion to those who FEAR (yare) him' - the reverent, who receive God's fatherly compassion."),
 (269094,"frame (yetser)","state","man","be of frail frame","known by God",IB,"paired with God knowing and remembering","v14: 'For he knows our FRAME (yetser); he remembers that we are dust' - our make-up and constitution, the frailty God tenderly reckons with."),
 (269115,"fear (yare)","disposition","those who fear God","fear / revere","God",GOD,"paired with God's everlasting love","v17: 'the steadfast love of the LORD is... on those who FEAR (yare) him' - the reverent, on whom God's everlasting love abides."),
 (269120,"keep (shamar)","action","those who keep covenant","keep","God's covenant",GOD,"paired with remembering to obey","v18: 'to those who KEEP (shamar) his covenant' - the faithful who hold God's covenant, heirs of his everlasting love."),
 (269122,"remember (zakar)","action","the faithful","remember","to do God's commandments",GOD,"paired with keeping the covenant","v18: 'and REMEMBER (zakar) to do his commandments' - the mindful obedience of the faithful, memory issuing in doing."),
 (269167,"bless (barak)","action","the psalmist","bless","the LORD",GOD,"paired with the soul","v22: 'BLESS (barak) the LORD, O my soul!' - the closing return to the self-summons, the psalm sealed as it began."),
 (269169,"soul (nephesh)","faculty","the psalmist","bless the LORD","to the last",IB,"paired with the blessing","v22: 'Bless the LORD, O my SOUL (nephesh)!' - the innermost self, first and last called to praise."),
]
for a in CH: r.ch(*a)
QU=[
 (269057,"holy (qodesh)",269052,"v1: 'bless his HOLY (qodesh) name!' - God's holiness. Qualifier."),
 (269058,"name (shem)",269052,"v1: 'bless his holy NAME (shem)!' - God's name. Qualifier."),
 (269139,"benefits (gemul)",269135,"v2: 'forget not all his BENEFITS (gemul)' - God's benefits. Qualifier."),
 (269170,"forgives (salach)",269172,"v3: 'who FORGIVES (salach) all your iniquity' - God's pardon. Qualifier."),
 (269173,"heals (rapha)",269172,"v3: 'who HEALS (rapha) all your diseases' - God's healing. Qualifier."),
 (269177,"redeems (gaal)",269172,"v4: 'who REDEEMS (gaal) your life from the pit' - God's redemption. Qualifier."),
 (269181,"crowns (atar)",269172,"v4: 'who CROWNS (atar) you with steadfast love and mercy' - God's crowning. Qualifier."),
 (269182,"steadfast love (chesed)",269172,"v4: 'crowns you with STEADFAST LOVE (chesed)' - God's covenant love. Qualifier."),
 (269183,"mercy (racham)",269172,"v4: 'with steadfast love and MERCY (racham)' - God's mercy. Qualifier."),
 (307231,"satisfies (saba)",269172,"v5: 'who SATISFIES (saba) you with good' - God's satisfying. Qualifier."),
 (307232,"good (tob)",269172,"v5: 'satisfies you with GOOD (tob)' - God's good gift. Qualifier."),
 (269185,"works (asah)",269189,"v6: 'The LORD WORKS (asah) righteousness' - God's doing of righteousness. Qualifier."),
 (269186,"righteousness (tsedaqah)",269189,"v6: 'the LORD works RIGHTEOUSNESS (tsedaqah)' - God's righteousness. Qualifier."),
 (269187,"justice (mishpat)",269189,"v6: 'and JUSTICE (mishpat) for all who are oppressed' - God's justice. Qualifier."),
 (307236,"made known (yada)",269074,"v7: 'He made KNOWN (yada) his ways to Moses' - God's self-revelation. Qualifier."),
 (307237,"ways (derek)",269074,"v7: 'his WAYS (derek) to Moses' - God's ways. Qualifier."),
 (307240,"acts (alilah)",269074,"v7: 'his ACTS (alilah) to the people of Israel' - God's deeds. Qualifier."),
 (269191,"merciful (rachum)",269074,"v8: 'The LORD is MERCIFUL (rachum) and gracious' - God's mercy. Qualifier."),
 (269192,"gracious (chanun)",269074,"v8: 'merciful and GRACIOUS (chanun)' - God's grace. Qualifier."),
 (269193,"slow (erek)",269074,"v8: 'SLOW (erek) to anger' - God's patience. Qualifier."),
 (269194,"anger (aph)",269074,"v8: 'slow to ANGER (aph)' - God's forbearance. Qualifier."),
 (269196,"steadfast love (chesed)",269074,"v8: 'and abounding in STEADFAST LOVE (chesed)' - God's covenant love. Qualifier."),
 (269199,"chide (rib)",269074,"v9: 'He will not always CHIDE (rib)' - God's restraint in accusing. Qualifier."),
 (269201,"keep anger (natar)",269074,"v9: 'nor will he KEEP (natar) his anger forever' - God's not retaining wrath. Qualifier."),
 (269060,"deal (asah)",269062,"v10: 'He does not DEAL (asah) with us according to our sins' - God's merciful dealing. Qualifier."),
 (269064,"repay (gamal)",269067,"v10: 'nor REPAY (gamal) us according to our iniquities' - God's not requiting. Qualifier."),
 (269072,"great (gabar)",269074,"v11: 'so GREAT (gabar) is his steadfast love' - the greatness of God's love. Qualifier."),
 (269073,"steadfast love (chesed)",269074,"v11: 'so great is his STEADFAST LOVE (chesed)' - God's covenant love. Qualifier."),
 (269080,"remove (rachaq)",269082,"v12: 'so far does he REMOVE (rachaq) our transgressions' - God's removal of sin. Qualifier."),
 (269088,"show compassion (racham)",269090,"v13: 'so the LORD SHOWS COMPASSION (racham) to those who fear him' - God's fatherly mercy. Qualifier."),
 (269093,"knows (yada)",269094,"v14: 'For he KNOWS (yada) our frame' - God's intimate knowledge of our frailty. Qualifier."),
 (269095,"remembers (zakar)",269094,"v14: 'he REMEMBERS (zakar) that we are dust' - God's mindful pity of our mortality. Qualifier."),
 (269108,"steadfast love (chesed)",269115,"v17: 'the STEADFAST LOVE (chesed) of the LORD is from everlasting' - God's covenant love. Qualifier."),
 (269116,"righteousness (tsedaqah)",269115,"v17: 'and his RIGHTEOUSNESS (tsedaqah) to children's children' - God's righteousness. Qualifier."),
 (269121,"covenant (berith)",269120,"v18: 'to those who keep his COVENANT (berith)' - God's covenant. Qualifier."),
 (269124,"commandments (piqqud)",269122,"v18: 'remember to do his COMMANDMENTS (piqqud)' - God's precepts. Qualifier."),
 (269126,"established (kun)",269115,"v19: 'The LORD has ESTABLISHED (kun) his throne in the heavens' - God's establishing of his throne. Qualifier."),
 (269130,"rules (mashal)",269115,"v19: 'and his kingdom RULES (mashal) over all' - God's universal reign. Qualifier."),
]
for sid,sense,src,d in QU: r.qu(sid,sense,src,d)
ST=[
 (269176,"diseases (tachalu)","v3: 'who heals all your DISEASES (tachalu)' - the sicknesses God heals, object. Standalone."),
 (269178,"life (chay)","v4: 'who redeems your LIFE (chay) from the pit' - the life God redeems, object. Standalone."),
 (269180,"pit (shachath)","v4: 'redeems your life from the PIT (shachath)' - the grave from which God redeems, image. Standalone."),
 (307233,"youth (naar)","v5: 'so that your YOUTH (naar) is renewed' - the renewed vigour, image of God's blessing. Standalone."),
 (307234,"renewed (chadash)","v5: 'your youth is RENEWED (chadash) like the eagle's' - the renewal God gives, image. Standalone."),
 (307235,"eagle's (nesher)","v5: 'renewed like the EAGLE'S (nesher)' - the eagle's renewed strength, image of vigour. Standalone."),
 (269202,"forever (netsach)","v9: 'nor will he keep his anger FOREVER (netsach)' - the perpetuity God's anger will not reach; temporal. Standalone."),
 (269070,"above (gabah)","v11: 'as high as the heavens are ABOVE (gabah) the earth' - the height, image of the greatness of God's love. Standalone."),
 (269076,"far (rachaq)","v12: 'as FAR (rachaq) as the east is from the west' - the distance, image of how far God removes sin. Standalone."),
 (269111,"everlasting (olam)","v17: 'from EVERLASTING (olam) to everlasting' - the eternity of God's love; temporal. Standalone."),
 (269113,"everlasting (olam)","v17: 'to EVERLASTING (olam)' - the endlessness of God's love; temporal. Standalone."),
 (269098,"dust (aphar)","v14: 'he remembers that we are DUST (aphar)' - our mortal dust, image of frailty. Standalone."),
 (307245,"grass (chatsir)","v15: 'As for man, his days are like GRASS (chatsir)' - the short-lived grass, image of transience. Standalone."),
 (307246,"flourishes (tsuts)","v15: 'he FLOURISHES (tsuts) like a flower of the field' - the brief blooming, image. Standalone."),
 (307247,"flower (tsits)","v15: 'like a FLOWER (tsits) of the field' - the fading flower, image of man's brevity. Standalone."),
 (307248,"field (sadeh)","v15: 'a flower of the FIELD (sadeh)' - the open field, image. Standalone."),
 (269100,"wind (ruach)","v16: 'for the WIND (ruach) passes over it, and it is gone' - the passing wind, image of death. Standalone."),
 (269101,"passes (abar)","v16: 'the wind PASSES (abar) over it' - the wind's passing, image of transience. Standalone."),
 (269105,"knows (nakar)","v16: 'and its place KNOWS (nakar) it no more' - the place that forgets the flower, image of oblivion. Standalone."),
 (269127,"throne (kisse)","v19: 'The LORD has established his THRONE (kisse) in the heavens' - God's throne, image of his reign. Standalone."),
 (269129,"kingdom (malkuth)","v19: 'and his KINGDOM (malkuth) rules over all' - God's kingdom, image of his dominion. Standalone."),
 (269140,"bless (barak)","v20: 'BLESS (barak) the LORD, O you his angels' - the call to the angels to bless (celestial worship, not human IB). Standalone."),
 (269142,"angels (malak)","v20: 'O you his ANGELS (malak)' - the angelic hosts called to bless. Standalone."),
 (269143,"mighty ones (gibbor)","v20: 'you MIGHTY ONES (gibbor) who do his word' - the mighty angels. Standalone."),
 (269144,"do (asah)","v20: 'who DO (asah) his word' - the angels performing God's word. Standalone."),
 (269145,"word (dabar)","v20: 'who do his WORD (dabar)' - God's word the angels perform. Standalone."),
 (269146,"obeying (shama)","v20: 'OBEYING (shama) the voice of his word' - the angels' obedience (celestial, not human IB). Standalone."),
 (269147,"voice (qol)","v20: 'obeying the VOICE (qol) of his word' - God's voice the angels heed. Standalone."),
 (269149,"word (dabar)","v20: 'the voice of his WORD (dabar)' - God's word. Standalone."),
 (269150,"bless (barak)","v21: 'BLESS (barak) the LORD, all his hosts' - the call to the heavenly hosts to bless. Standalone."),
 (269153,"hosts (tsaba)","v21: 'all his HOSTS (tsaba)' - the heavenly armies called to bless. Standalone."),
 (269155,"ministers (sharath)","v21: 'his MINISTERS (sharath), who do his will' - the celestial ministers. Standalone."),
 (269156,"do (asah)","v21: 'who DO (asah) his will' - the ministers performing God's will. Standalone."),
 (269158,"will (ratson)","v21: 'who do his WILL (ratson)' - God's will the ministers do. Standalone."),
 (269159,"bless (barak)","v22: 'BLESS (barak) the LORD, all his works' - the call to all creation to bless (cosmic, not human IB). Standalone."),
 (269162,"works (maaseh)","v22: 'all his WORKS (maaseh)' - all created things called to bless. Standalone."),
 (269166,"dominion (memshalah)","v22: 'in all places of his DOMINION (memshalah)' - the extent of God's rule, image. Standalone."),
 (269123,"do (asah)","v18: 'remember to DO (asah) his commandments' - the doing of the commandments, outward act of the char remember (269122). Standalone."),
]
for sid,sense,d in ST: r.st(sid,sense,d)
r.write()
