import sys; sys.path.insert(0,'scripts')
from _reread_ledger_lib import Reading, IB, GOD, PER
r=Reading("Psa",19,138,
  note="Ps138 David's thanksgiving (8v). IB: whole-HEART GIVE-THANKS + SING-PRAISE; BOW-DOWN + GIVE-THANKS at the temple; CALLED and answered (the SOUL's strength increased); the kings who will GIVE-THANKS + SING; the operation of God regarding the LOWLY but knowing the HAUGHTY from afar (humility vs pride before God); WALKing through trouble; the enemies' WRATH. God's answered/exalt/regard/deliver/steadfast-love = qualifiers; temple/kings/way imagery = standalone.")
CH=[
 (273310,"give thanks (yadah)","action","the psalmist","give thanks","to God with the whole heart",GOD,"paired with the whole heart and singing",
  "v1: 'I GIVE YOU THANKS (yadah), O LORD, with my whole heart' - undivided thanksgiving, gratitude from the entire self."),
 (273312,"heart (leb)","faculty","the psalmist","give thanks","with the whole heart",IB,"paired with the thanksgiving",
  "v1: 'with my whole HEART (leb)' - the inner self wholly engaged, no part of the heart withheld from the thanks."),
 (273315,"sing praise (zamar)","action","the psalmist","sing praise","before the gods",GOD,"paired with giving thanks",
  "v1: 'before the gods I SING YOUR PRAISE (zamar)' - the bold praise offered even before rival powers."),
 (273316,"bow down (shachah)","action","the psalmist","bow down","toward the holy temple",GOD,"paired with giving thanks to God's name",
  "v2: 'I BOW DOWN (shachah) toward your holy temple' - the prostration of worship, the body enacting the thanks."),
 (273319,"give thanks (yadah)","action","the psalmist","give thanks","to God's name",GOD,"paired with bowing down",
  "v2: 'and GIVE THANKS (yadah) to your name for your steadfast love and your faithfulness' - thanks directed to God's name for his love and truth."),
 (273334,"call (qara)","action","the psalmist","call","to God, and be answered",GOD,"paired with the strengthened soul",
  "v3: 'On the day I CALLED (qara), you answered me' - the cry that God met, prayer answered on the very day."),
 (273338,"soul (nephesh)","faculty","the psalmist","be strengthened","in the soul",IB,"paired with the answered call",
  "v3: 'my strength of SOUL (nephesh) you increased' - the operation of inward reinforcement: the answered prayer flooding the self with new strength."),
 (308052,"give thanks (yadah)","action","the kings of the earth","give thanks","to God",GOD,"paired with hearing his words",
  "v4: 'All the kings of the earth shall GIVE YOU THANKS (yadah), O LORD' - the future homage of kings, thanks that will spread to the powers of the earth."),
 (273340,"sing (shir)","action","the kings","sing","of the ways of the LORD",GOD,"paired with the kings' thanks",
  "v5: 'and they shall SING (shir) of the ways of the LORD' - the kings' song of God's ways and glory."),
 (273351,"lowly (shaphal)","status","the lowly","be regarded","by God",IB,"paired with the haughty God knows from afar",
  "v6: 'For though the LORD is high, he regards the LOWLY (shaphal)' - the operation of divine attention inverting rank: the high God draws near to the low, not the great."),
 (273352,"haughty (gaboah)","status","the haughty","be known from afar","by God",IB,"paired with the lowly he regards",
  "v6: 'but the HAUGHTY (gaboah) he knows from afar' - the proud held at a distance, the operation's other pole: exaltation of self earns God's distance, not his nearness."),
 (273357,"walk (halak)","action","the psalmist","walk","through the midst of trouble",IB,"paired with God preserving his life",
  "v7: 'Though I WALK (halak) in the midst of trouble, you preserve my life' - the operation of preservation-in-passage: not spared trouble but kept alive through it."),
 (273364,"wrath (aph)","state","the enemies","be wrathful","against the psalmist",IB,"paired with God's delivering hand",
  "v7: 'against the WRATH (aph) of my enemies' - the foes' fury, over which God's hand stretches to deliver."),
]
for a in CH: r.ch(*a)
QU=[
 (273335,"answered (anah)",273334,"v3: 'you ANSWERED (anah) me' - God's answer. Qualifier."),
 (273317,"holy (qodesh)",273316,"v2: 'toward your HOLY (qodesh) temple' - God's holiness. Qualifier."),
 (273320,"name (shem)",273319,"v2: 'give thanks to your NAME (shem)' - God's name. Qualifier."),
 (273322,"steadfast love (chesed)",273319,"v2: 'for your STEADFAST LOVE (chesed)' - God's covenant love. Qualifier."),
 (273324,"faithfulness (emeth)",273319,"v2: 'and your FAITHFULNESS (emeth)' - God's faithfulness. Qualifier."),
 (273326,"exalted (gadal)",273319,"v2: 'you have EXALTED (gadal) above all things your name and your word' - God's exalting of his word. Qualifier."),
 (273329,"name (shem)",273319,"v2: 'your NAME (shem) and your word' - God's name. Qualifier."),
 (273339,"increased (rahab)",273338,"v3: 'my strength of soul you INCREASED (rahab)' - God's strengthening of the soul. Qualifier."),
 (308055,"heard (shama)",308052,"v4: 'for they have HEARD (shama) the words of your mouth' - the kings hearing God's word. Qualifier."),
 (273341,"ways (derek)",273340,"v5: 'sing of the WAYS (derek) of the LORD' - God's ways. Qualifier."),
 (273345,"glory (kabod)",273340,"v5: 'for great is the GLORY (kabod) of the LORD' - God's glory. Qualifier."),
 (273349,"high (rum)",273351,"v6: 'though the LORD is HIGH (rum)' - God's exaltation. Qualifier."),
 (273350,"regards (raah)",273351,"v6: 'he REGARDS (raah) the lowly' - God's attention to the low. Qualifier."),
 (273353,"knows (yada)",273352,"v6: 'the haughty he KNOWS (yada) from afar' - God's distant knowledge of the proud. Qualifier."),
 (273360,"preserve life (chayah)",273357,"v7: 'you PRESERVE my life (chayah)' - God's preserving. Qualifier."),
 (273361,"stretch out (shalach)",273357,"v7: 'you STRETCH OUT (shalach) your hand' - God's reaching to save. Qualifier."),
 (273367,"delivers (yasha)",273357,"v7: 'and your right hand DELIVERS (yasha) me' - God's deliverance. Qualifier."),
 (273369,"fulfill (gamar)",273310,"v8: 'The LORD will FULFILL (gamar) his purpose for me' - God's completing purpose. Qualifier."),
 (273371,"steadfast love (chesed)",273310,"v8: 'your STEADFAST LOVE (chesed), O LORD, endures forever' - God's covenant love. Qualifier."),
 (273375,"forsake (raphah)",273310,"v8: 'Do not FORSAKE (raphah) the work of your hands' - God asked not to abandon his work. Qualifier."),
]
for sid,sense,src,d in QU: r.qu(sid,sense,src,d)
for sid,sense,d in [
 (273318,"temple (heikal)","v2: 'toward your holy TEMPLE (heikal)' - the sanctuary of worship (char bow-down, 273316), image. Standalone."),
 (273337,"strength (oz)","v3: 'my STRENGTH (oz) of soul' - the strength given the soul (char soul, 273338), image. Standalone."),
 (308050,"kings (melek)","v4: 'All the KINGS (melek) of the earth' - the rulers who will thank God (char, 308052). Standalone."),
 (308058,"mouth (peh)","v4: 'the words of your MOUTH (peh)' - God's spoken word the kings heard, image. Standalone."),
 (273358,"midst (qereb)","v7: 'in the MIDST (qereb) of trouble' - the thick of the trouble (char walk, 273357), image. Standalone."),
 (273359,"trouble (tsarah)","v7: 'in the midst of TROUBLE (tsarah)' - the distress walked through, image. Standalone."),
 (273355,"afar (merchaq)","v6: 'the haughty he knows from AFAR (merchaq)' - the distance at which the proud are held (char haughty, 273352), image. Standalone."),
 (273373,"endures forever (olam)","v8: 'your steadfast love endures FOREVER (olam)' - the perpetuity of God's love; temporal. Standalone."),
 (273376,"work (maaseh)","v8: 'Do not forsake the WORK (maaseh) of your hands' - the psalmist as God's handiwork, image. Standalone."),
 (273370,"for me (baad)","v8: 'The LORD will fulfil his purpose FOR (baad) me' - the psalmist as the object of God's purpose, image. Standalone."),
]: r.st(sid,sense,d)
r.write()
