import sys; sys.path.insert(0,'scripts')
from _reread_ledger_lib import Reading, IB, GOD, PER
r=Reading("Psa",19,88,
  note="Ps88 the darkest psalm, unrelieved lament (Heman, 18v). Passages: the day-and-night cry v1-2; the soul among the dead v3-7; abandoned by friends v8-9; the questions to the God of the dead v10-12; the morning cry still unanswered v13-18. Human IB is almost all the anguish of the sufferer: CRY-OUT / PRAYER / CRY that gets no answer; SOUL FULL of TROUBLES; COUNTED among the dead, no STRENGTH; a HORROR to friends, SHUT-IN; eye GROWS-DIM with SORROW; AFFLICTED, SUFFERing, HELPLESS. God's wrath/waves/casting-off = qualifiers; pit/Sheol/darkness/estranged-friends imagery = standalone. Ends in darkness, no resolution - read as such.")
for a in [
 (284416,"cry out (tsaaq)","action","the psalmist","cry out","to God day and night","paired with the prayer that comes before God",GOD,"v1: 'I CRY OUT (tsaaq) day and night before you' - the ceaseless cry of the sufferer, prayer that never stops though never answered."),
 (284463,"prayer (tephillah)","action","the psalmist","pray","to God","paired with the cry","external:god","v2: 'let my PRAYER (tephillah) come before you' - the petition begging admittance to God's presence."),
 (284469,"cry (rinnah)","action","the psalmist","cry","to God","paired with the prayer",GOD,"v2: 'incline your ear to my CRY (rinnah)' - the loud plea, the sufferer's voice reaching for God's ear."),
 (284471,"soul (nephesh)","faculty","the psalmist","be full of troubles","near death","paired with the fullness of troubles",IB,"v3: 'For my SOUL (nephesh) is full of troubles' - the whole self saturated with affliction, the sufferer's inner state."),
 (284472,"full (saba)","state","the psalmist","be sated / glutted","with troubles","paired with the soul and troubles",IB,"v3: 'my soul is FULL (saba) of troubles' - satiety of suffering, filled to the brim with grief."),
 (284473,"troubles (ra)","state","the psalmist","be beset by troubles","near Sheol","paired with the full soul",IB,"v3: 'full of TROUBLES (ra)' - the evils crowding the soul, life drawn near to the grave."),
 (284478,"counted (chashab)","state","the psalmist","be reckoned","among the dead","paired with having no strength",IB,"v4: 'I am COUNTED (chashab) among those who go down to the pit' - the sense of being already numbered with the dead, doom felt as present."),
 (284485,"strength (eyal)","state","the psalmist","have no strength","against death","paired with being counted dead",IB,"v4: 'I am a man who has no STRENGTH (eyal)' - the utter powerlessness of the sufferer, vitality gone."),
 (284507,"horror (toebah)","state","the psalmist","be made a horror","to friends","paired with being shut in",IB,"v8: 'you have made me a HORROR (toebah) to them' - the sufferer become repugnant to his own, abandonment sharpened to revulsion."),
 (284508,"shut in (kala)","state","the psalmist","be shut in","without escape","paired with being a horror",IB,"v8: 'I am SHUT IN (kala) so that I cannot escape' - the trapped, walled-in despair, no way out of the affliction."),
 (284512,"grow dim (daab)","state","the psalmist","have the eye grow dim","through sorrow","paired with the sorrow",IB,"v9: 'my eye GROWS DIM (daab) through sorrow' - the wasting of the very sight, grief worn into the body."),
 (284514,"sorrow (oni)","state","the psalmist","suffer sorrow","daily","paired with the dimming eye",IB,"v9: 'my eye grows dim through SORROW (oni)' - the affliction that dims the eyes, unrelenting grief."),
 (284517,"call (qara)","action","the psalmist","call upon","God every day","paired with spreading out the hands",GOD,"v9: 'Every day I CALL (qara) upon you, O LORD' - the daily calling that persists though heaven is silent."),
 (307024,"cry (shava)","action","the psalmist","cry for help","to God","paired with the morning prayer",GOD,"v13: 'But I, O LORD, CRY (shava) to you for help' - the sufferer's persistent cry, faith holding on in the dark."),
 (307027,"prayer (tephillah)","action","the psalmist","pray","to God in the morning","paired with the cry",GOD,"v13: 'in the morning my PRAYER (tephillah) comes before you' - the dawn petition, hope renewed each morning against the night."),
 (302650,"soul (nephesh)","faculty","the psalmist","be cast away","by God","paired with God hiding his face",IB,"v14: 'why do you cast my SOUL (nephesh) away?' - the self flung off, the sufferer's bewildered sense of rejection by God."),
 (284439,"afflicted (ani)","status","the psalmist","be afflicted","from youth","paired with suffering and helplessness",IB,"v15: 'AFFLICTED (ani) and close to death from my youth up' - a lifetime of suffering, affliction as the sufferer's whole history."),
 (284443,"suffer (nasa)","action","the psalmist","bear / suffer","God's terrors","paired with helplessness",IB,"v15: 'I SUFFER (nasa) your terrors; I am helpless' - the bearing of God-sent dread, terror endured to the point of collapse."),
 (284445,"helpless (pun)","state","the psalmist","be helpless / distracted","under terror","paired with the suffering",IB,"v15: 'I am HELPLESS (pun)' - the paralysis of the terrified, undone and without recourse."),
]: r.ch(*a)
for sid,sense,src,d in [
 (284415,"salvation (yeshuah)",284416,"v1: 'O LORD, God of my SALVATION (yeshuah)' - God as saviour, the one address of hope. Qualifier."),
 (284466,"incline (natah)",284463,"v2: 'INCLINE (natah) your ear to my cry' - God's attention petitioned. Qualifier."),
 (284492,"remember (zakar)",284471,"v5: 'like the slain... whom you REMEMBER (zakar) no more' - God's remembering, felt as withdrawn. Qualifier."),
 (284495,"cut off (gazar)",284471,"v5: 'they are CUT OFF (gazar) from your hand' - God's severing, the dead beyond his care. Qualifier."),
 (307016,"put (shith)",284471,"v6: 'You have PUT (shith) me in the depths of the pit' - God's placing the sufferer in the grave-deep. Qualifier."),
 (284497,"wrath (chemah)",284471,"v7: 'Your WRATH (chemah) lies heavy upon me' - God's anger. Qualifier."),
 (284498,"lie heavy (samak)",284471,"v7: 'your wrath LIES HEAVY (samak) upon me' - God's wrath pressing down. Qualifier."),
 (284500,"overwhelm (anah)",284471,"v7: 'you OVERWHELM (anah) me with all your waves' - God's afflicting. Qualifier."),
 (284505,"shun (rachaq)",284507,"v8: 'You have caused my companions to SHUN (rachaq) me' - God's act behind the estrangement. Qualifier."),
 (284506,"make (shith)",284507,"v8: 'you have MADE (shith) me a horror to them' - God's making the sufferer abhorrent. Qualifier."),
 (284421,"work wonders (asah)",284517,"v10: 'Do you WORK (asah) wonders for the dead?' - God's wonder-working, questioned for the grave. Qualifier."),
 (284422,"wonders (pele)",284517,"v10: 'Do you work WONDERS (pele) for the dead?' - God's marvels. Qualifier."),
 (284428,"steadfast love (chesed)",284517,"v11: 'Is your STEADFAST LOVE (chesed) declared in the grave?' - God's love, questioned for Sheol. Qualifier."),
 (284429,"declared (saphar)",284517,"v11: 'Is your steadfast love DECLARED (saphar) in the grave?' - the proclaiming of God's love, absent in death. Qualifier."),
 (284431,"faithfulness (emunah)",284517,"v11: 'or your FAITHFULNESS (emunah) in Abaddon?' - God's faithfulness, questioned for the pit. Qualifier."),
 (284433,"wonders (pele)",284517,"v12: 'Are your WONDERS (pele) known in the darkness?' - God's marvels, unknown in death. Qualifier."),
 (284434,"known (yada)",284517,"v12: 'Are your wonders KNOWN (yada) in the darkness?' - God's deeds made known, absent in the dark. Qualifier."),
 (284436,"righteousness (tsedaqah)",284517,"v12: 'or your RIGHTEOUSNESS (tsedaqah) in the land of forgetfulness?' - God's righteousness, questioned for the grave. Qualifier."),
 (307028,"come before (qadam)",307027,"v13: 'my prayer COMES BEFORE (qadam) you' - the prayer reaching God's presence. Qualifier."),
 (302649,"cast away (zanach)",302650,"v14: 'why do you CAST (zanach) my soul away?' - God's rejection, the anguished question. Qualifier."),
 (302651,"hide (sathar)",302650,"v14: 'why do you HIDE (sathar) your face from me?' - God's hidden face, the heart of the darkness. Qualifier."),
 (284444,"terrors (emim)",284443,"v15: 'I suffer your TERRORS (emim)' - God-sent dreads borne by the sufferer. Qualifier."),
 (284446,"wrath (charon)",284439,"v16: 'Your WRATH (charon) has swept over me' - God's fierce anger. Qualifier."),
 (284447,"sweep over (abar)",284439,"v16: 'your wrath has SWEPT OVER (abar) me' - God's wrath overwhelming. Qualifier."),
 (284449,"dreadful assaults (biuth)",284439,"v16: 'your DREADFUL ASSAULTS (biuth) destroy me' - God-sent terrors. Qualifier."),
 (284450,"destroy (tsamath)",284439,"v16: 'your dreadful assaults DESTROY (tsamath) me' - God's destroying. Qualifier."),
 (284452,"surround (sabab)",284439,"v17: 'They SURROUND (sabab) me like a flood' - the terrors closing in, God-sent. Qualifier."),
 (284456,"close in (naqaph)",284439,"v17: 'they CLOSE IN (naqaph) on me together' - the encircling terrors. Qualifier."),
 (284460,"shun (rachaq)",302650,"v18: 'You have caused my beloved and friend to SHUN (rachaq) me' - God's act behind the final abandonment. Qualifier."),
]: r.qu(sid,sense,src,d)
for sid,sense,d in [
 (284475,"life (chay)","v3: 'my LIFE (chay) draws near to Sheol' - the life ebbing toward death, image. Standalone."),
 (284476,"draw near (naga)","v3: 'my life DRAWS NEAR (naga) to Sheol' - the approach of death, image. Standalone."),
 (284477,"Sheol (sheol)","v3: 'draws near to SHEOL (sheol)' - the realm of death, image. Standalone."),
 (284480,"go down (yarad)","v4: 'those who GO DOWN (yarad) to the pit' - the descent to death, image. Standalone."),
 (284481,"pit (bor)","v4: 'those who go down to the PIT (bor)' - the grave, image. Standalone."),
 (284486,"set loose (chophshi)","v5: 'like one SET LOOSE (chophshi) among the dead' - abandoned among corpses, image. Standalone."),
 (284487,"dead (muth)","v5: 'set loose among the DEAD (muth)' - the corpses, image. Standalone."),
 (284488,"slain (chalal)","v5: 'like the SLAIN (chalal) that lie in the grave' - the killed, image. Standalone."),
 (284489,"lie (shakab)","v5: 'that LIE (shakab) in the grave' - the dead reclining, image. Standalone."),
 (284490,"grave (qeber)","v5: 'that lie in the GRAVE (qeber)' - the tomb, image. Standalone."),
 (307017,"depths (tachti)","v6: 'in the DEPTHS (tachti) of the pit' - the lowest grave, image. Standalone."),
 (307018,"pit (bor)","v6: 'the depths of the PIT (bor)' - the grave, image. Standalone."),
 (307020,"dark places (machshak)","v6: 'in the DARK PLACES (machshak)' - the gloom of death, image. Standalone."),
 (307021,"deep (metsolah)","v6: 'in the DEEPS (metsolah)' - the drowning depths, image. Standalone."),
 (284502,"waves (mishbar)","v7: 'with all your WAVES (mishbar)' - the breakers of affliction, image. Standalone."),
 (284504,"companions (yada)","v8: 'You have caused my COMPANIONS (yada, acquaintances) to shun me' - the estranged friends. Standalone."),
 (284510,"escape (yatsa)","v8: 'I cannot ESCAPE (yatsa)' - the way out that is barred, image of the char shut-in (284508). Standalone."),
 (284519,"spread out (shatach)","v9: 'I SPREAD OUT (shatach) my hands to you' - the imploring gesture of prayer. Standalone."),
 (284423,"dead (rapha)","v10: 'Do the DEAD (rapha, shades) rise up to praise you?' - the shades of the dead, image. Standalone."),
 (284424,"departed (rapha)","v10: 'Do the DEPARTED (rapha) rise up?' - the dead spirits, image. Standalone."),
 (284425,"rise up (qum)","v10: 'do they RISE UP (qum) to praise you?' - the impossible resurrection of the dead to worship, image. Standalone."),
 (284426,"praise (yadah)","v10: 'rise up to PRAISE (yadah) you?' - the praise the dead cannot give, the silence of the grave. Standalone."),
 (284430,"grave (qeber)","v11: 'declared in the GRAVE (qeber)?' - the tomb where God's love goes unproclaimed, image. Standalone."),
 (284432,"Abaddon (abaddon)","v11: 'or your faithfulness in ABADDON (abaddon)?' - the place of destruction, image. Standalone."),
 (284435,"darkness (choshek)","v12: 'known in the DARKNESS (choshek)?' - the dark of death, image. Standalone."),
 (284438,"forgetfulness (neshiyyah)","v12: 'in the land of FORGETFULNESS (neshiyyah)?' - the realm where all is forgotten, image. Standalone."),
 (284440,"death (gava)","v15: 'close to DEATH (gava) from my youth up' - the nearness of death, image. Standalone."),
 (284442,"youth (naar)","v15: 'from my YOUTH (naar) up' - the lifelong span of the affliction; temporal. Standalone."),
 (284453,"flood (mayim)","v17: 'like a FLOOD (mayim) all day long' - the waters of affliction, image. Standalone."),
 (284458,"beloved (aheb)","v18: 'You have caused my BELOVED (aheb) and friend to shun me' - the loved one estranged. Standalone."),
 (284459,"friend (rea)","v18: 'my beloved and FRIEND (rea)' - the companion lost. Standalone."),
 (284461,"companions (yada)","v18: 'my COMPANIONS (yada) have become darkness' - the acquaintances, gone into the dark. Standalone."),
 (284462,"darkness (machshak)","v18: 'my companions have become DARKNESS (machshak)' - the closing image, darkness as the sufferer's only intimate. Standalone."),
]: r.st(sid,sense,d)
r.write()
