import sys; sys.path.insert(0,'scripts')
from _reread_ledger_lib import Reading, IB, GOD, PER
r=Reading("Psa",19,81,
  note="Ps81 festival psalm turning on God's voice (Asaph). Passages: call to worship v1-5b; God's oracle recalling deliverance v5c-7; the appeal to LISTEN v8-10; the grief that they would not v11-12; the wish 'O that my people would listen' + its promise v13-16. Human IB centres on hearing/heeding: SING-ALOUD + JOY; HEAR the oracle; CALLED in distress; the summoned LISTEN/SUBMIT; the STUBBORN HEARTS following their own COUNSELS; the haters who CRINGE; the promised SATISFY. God's statute/decree/relieve/deliver/answer/subdue/feed = qualifiers; instruments/feast/manna imagery = standalone.")
for a in [
 (283788,"sing aloud (ranan)","action","the worshippers","sing aloud / shout","to God our strength","paired with the joyful shout",GOD,
  "v1: 'SING ALOUD (ranan) to God our strength' - the summoned, exuberant praise that opens the feast."),
 (283791,"shout for joy (rua)","action","the worshippers","shout for joy","to the God of Jacob","paired with the singing",GOD,
  "v1: 'shout for JOY (rua) to the God of Jacob' - the glad festal cry, worship as jubilation."),
 (283847,"hear (shama)","action","the psalmist / Israel","hear / receive","a voice/language not known","paired with the oracle that follows",GOD,
  "v5: 'I HEAR (shama) a language I had not known' - the prophetic receiving of God's voice, the hinge where the psalm turns to divine speech."),
 (283859,"call (qara)","action","the people","cry out","to God in distress","paired with the deliverance that answered",GOD,
  "v7: 'In distress you CALLED (qara), and I delivered you' - the people's cry in trouble, recalled by God as the pattern of grace."),
 (283868,"hear (shama)","action","my people","hear / attend","God's admonition","paired with the plea to listen",GOD,
  "v8: 'HEAR (shama), O my people, while I admonish you!' - the summoned attention, God pleading to be heard."),
 (283873,"listen (shama)","disposition","Israel","listen / heed","God","paired with the summons to hear",GOD,
  "v8: 'O Israel, if you would but LISTEN (shama) to me!' - the wistful conditional, the whole tragedy hangs on this heeding."),
 (283879,"bow down (shachah, forbidden)","action","you (Israel)","bow down","to a foreign god","paired with the ban on the strange god",GOD,
  "v9: 'you shall not BOW DOWN (shachah) to a foreign god' - the worship forbidden, exclusive allegiance the first demand."),
 (283796,"listen (shama, failed)","disposition","my people","fail to listen","to God's voice","paired with the refusal to submit",GOD,
  "v11: 'But my people did not LISTEN (shama) to my voice' - the tragic refusal, the summons of v8 met with deafness."),
 (283800,"submit / be willing (abah, failed)","disposition","Israel","refuse to submit","to God","paired with the failed listening",GOD,
  "v11: 'Israel would not SUBMIT (abah) to me' - the unwilling heart, obedience declined."),
 (283803,"stubborn (sheriruth)","status","my people","be stubborn","in heart","paired with their own counsels",IB,
  "v12: 'So I gave them over to their STUBBORN (sheriruth) hearts' - the obstinacy God finally left them to, judgment by abandonment."),
 (283804,"hearts (leb)","faculty","my people","harbour stubbornness","against God","paired with following their own counsels",IB,
  "v12: 'gave them over to their stubborn HEARTS (leb)' - the heart as the seat of the obstinacy, the inner ground of the ruin."),
 (283806,"counsels (moetsah)","faculty","my people","follow their own counsel","instead of God","paired with the stubborn heart",IB,
  "v12: 'to follow their own COUNSELS (moetsah)' - the self-devised plans they preferred to God's ways, autonomy as apostasy."),
 (306919,"listen (shama)","disposition","my people","listen / heed","God","paired with walking in his ways",GOD,
  "v13: 'Oh, that my people would LISTEN (shama) to me' - the divine longing, grief and love in one breath."),
 (306922,"walk (halak)","action","Israel","walk / conduct oneself","in God's ways","paired with the wished-for listening",GOD,
  "v13: 'that Israel would WALK (halak) in my ways!' - the obedience God yearns for, heeding proven by a way of life."),
 (283815,"hate (sane)","disposition","those who hate the LORD","hate","God","paired with their cringing",GOD,
  "v15: 'Those who HATE (sane) the LORD would cringe before him' - the enemies' enmity toward God, hostility that judgment turns to fear."),
 (283817,"cringe (kachash)","action","the haters","cringe / feign submission","before God","paired with the hatred",GOD,
  "v15: 'would CRINGE (kachash) before him' - the forced, feigned submission of the cowed foe, homage without love."),
 (283825,"satisfy (saba)","state","you (Israel)","be satisfied","by God","paired with the finest wheat and honey",IB,
  "v16: 'with honey from the rock I would SATISFY (saba) you' - the full contentment God would give the obedient, blessing withheld only by their refusal."),
]: r.ch(*a)
for sid,sense,src,d in [
 (283790,"strength (oz)",283788,"v1: 'God our STRENGTH (oz)' - God as the people's strength. Qualifier."),
 (283835,"statute (choq)",283873,"v4: 'For it is a STATUTE (choq) for Israel' - God's ordinance. Qualifier."),
 (283837,"rule (mishpat)",283873,"v4: 'a RULE (mishpat) of the God of Jacob' - God's ordinance. Qualifier."),
 (283841,"decree (eduth)",283847,"v5: 'He made it a DECREE (eduth) in Joseph' - God's appointed testimony. Qualifier."),
 (283844,"went out (yatsa)",283847,"v5: 'when he WENT OUT (yatsa) over the land of Egypt' - God's going out in the Exodus. Qualifier."),
 (283851,"relieved (sur)",283859,"v6: 'I RELIEVED (sur) your shoulder of the burden' - God's freeing act. Qualifier."),
 (283855,"freed (abar)",283859,"v6: 'your hands were FREED (abar) from the basket' - God's liberation. Qualifier."),
 (283860,"delivered (chalats)",283859,"v7: 'you called, and I DELIVERED (chalats) you' - God's rescue. Qualifier."),
 (283861,"answered (anah)",283859,"v7: 'I ANSWERED (anah) you in the secret place of thunder' - God's answer. Qualifier."),
 (283864,"tested (bachan)",283859,"v7: 'I TESTED (bachan) you at the waters of Meribah' - God's proving of them. Qualifier."),
 (283870,"admonish (ud)",283868,"v8: 'while I ADMONISH (ud) you' - God's warning. Qualifier."),
 (306909,"brought up (alah)",283796,"v10: 'I am the LORD your God, who BROUGHT YOU UP (alah) from Egypt' - God's deliverance. Qualifier."),
 (306915,"fill (male)",283796,"v10: 'Open your mouth wide, and I will FILL (male) it' - God's provision promised. Qualifier."),
 (283808,"subdue (kana)",283815,"v14: 'I would soon SUBDUE (kana) their enemies' - God's promised conquest. Qualifier."),
 (283810,"turn my hand (shuv)",283815,"v14: 'and TURN (shuv) my hand against their foes' - God's judgment. Qualifier."),
 (283820,"feed (akal)",283825,"v16: 'But he would FEED (akal) you with the finest of the wheat' - God's provision. Qualifier."),
]: r.qu(sid,sense,src,d)
for sid,sense,d in [
 (283827,"raise a song (nasa)","v2: 'RAISE (nasa) a song, sound the tambourine' - the striking-up of music. Standalone."),
 (283828,"song (zimrah)","v2: 'raise a SONG (zimrah)' - the melody, worship-medium. Standalone."),
 (283830,"tambourine (toph)","v2: 'sound the TAMBOURINE (toph)' - the instrument. Standalone."),
 (283831,"sweet (naim)","v2: 'the SWEET (naim) lyre with the harp' - the pleasant music. Standalone."),
 (283833,"harp (nebel)","v2: 'the sweet lyre with the HARP (nebel)' - the instrument. Standalone."),
 (306898,"blow (taqa)","v3: 'BLOW (taqa) the trumpet at the new moon' - the festal signal. Standalone."),
 (306899,"trumpet (shophar)","v3: 'blow the TRUMPET (shophar)' - the ram's horn. Standalone."),
 (306900,"new moon (chodesh)","v3: 'at the NEW MOON (chodesh)' - the feast-time. Standalone."),
 (306902,"full moon (kese)","v3: 'at the FULL MOON (kese), on our feast day' - the feast-time. Standalone."),
 (306904,"feast (chag)","v3: 'on our FEAST (chag) day' - the festival occasion. Standalone."),
 (283848,"language (saphah)","v5: 'I hear a LANGUAGE (saphah) I had not known' - the unfamiliar voice, image of the oracle. Standalone."),
 (283850,"not known (yada)","v5: 'a language I had not KNOWN (yada)' - the strangeness of the divine voice. Standalone."),
 (283852,"shoulder (shekem)","v6: 'I relieved your SHOULDER (shekem) of the burden' - the labouring shoulder, image of bondage. Standalone."),
 (283853,"burden (sebel)","v6: 'relieved your shoulder of the BURDEN (sebel)' - the load of slavery, image. Standalone."),
 (283858,"distress (tsarah)","v7: 'In DISTRESS (tsarah) you called' - the trouble from which they cried; circumstance. Standalone."),
 (283862,"secret place (sether)","v7: 'I answered you in the SECRET PLACE (sether) of thunder' - the hidden place of theophany, image. Standalone."),
 (283863,"thunder (raam)","v7: 'in the secret place of THUNDER (raam)' - the storm-voice at Sinai, image. Standalone."),
 (283876,"strange (zar)","v9: 'There shall be no STRANGE (zar) god among you' - the alien deity forbidden. Standalone."),
 (283880,"foreign (nekar)","v9: 'you shall not bow down to a FOREIGN (nekar) god' - the alien deity. Standalone."),
 (306913,"open wide (rachab)","v10: 'OPEN (rachab) your mouth wide' - the open mouth to be filled, image of expectant receiving. Standalone."),
 (283797,"voice (qol)","v11: 'did not listen to my VOICE (qol)' - God's voice unheeded; the object of the failed listening. Standalone."),
 (283805,"follow / walk (halak)","v12: 'to FOLLOW (halak) their own counsels' - the walking-after self-will, outward form of the stubborn heart (283803). Standalone."),
 (283819,"forever (olam)","v15: 'their fate would last FOREVER (olam)' - the perpetuity of the foes' subjection; temporal. Standalone."),
 (283821,"finest (cheleb)","v16: 'the FINEST (cheleb) of the wheat' - the best of the harvest, image of blessing. Standalone."),
 (283822,"wheat (chittah)","v16: 'the finest of the WHEAT (chittah)' - the grain, image of provision. Standalone."),
 (283823,"honey (debash)","v16: 'with HONEY (debash) from the rock' - the sweetness, image of blessing. Standalone."),
 (283824,"rock (tsur)","v16: 'honey from the ROCK (tsur)' - the unlikely source of sweetness, image. Standalone."),
]: r.st(sid,sense,d)
r.write()
