#!/usr/bin/env python
"""build_script_registry.py — canonical, regenerable registry of the project's scripts.

Read-only. Classifies every top-level script in scripts/ (and scripts/analytics/) by its
naming-convention PREFIX (per docs/file-organisation-rules.md §2 and CLAUDE.md §6), and groups
files by canonical base name (stripping -vN / -YYYYMMDD) so that multiple versions of the same
script surface as SUPERSEDED CANDIDATES (latest kept, older flagged) — the version suffix is the
documented supersession signal, so this is mechanical, not inferred.

It does NOT guess intent. Curated "this is THE reusable generator for X" lives in
docs/reusable-scripts-catalogue.md; this registry is the exhaustive mechanical companion.

Usage:  python scripts/build_script_registry.py --out docs/script-registry-generated-YYYYMMDD.md
"""
import argparse, os, re
from collections import defaultdict

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SCRIPTS = os.path.join(ROOT, "scripts")

# prefix → (class, modifies_db?)  evaluated in order, first match wins
CLASS_RULES = [
    (r"^_tmp_",                                   ("throwaway (delete/archive at session end)", "varies")),
    (r"^(_assess_|_check_|_discover_|_explore_|_probe_|verify_|inspect_)", ("read-only diagnostic (one-off)", "no")),
    (r"^_exploratory_",                           ("read-only exploratory (one-off)", "no")),
    (r"^(build_|generate_|_generate_|_produce_|export_)", ("read-only report / export (REUSABLE)", "no")),
    (r"^word_.*extract",                          ("read-only extract (REUSABLE)", "no")),
    (r"^(_apply_|_repair_|_realign_|_reset_|_extract_|_backfill_|_close_|_remediate_|_relocate_|_rename_|_archive_)", ("DB-MODIFYING (often one-off)", "yes")),
    (r"^_migrate_",                               ("schema MIGRATION", "yes")),
    (r"^_delete_",                                ("DESTRUCTIVE delete", "yes")),
    (r"^_validate_",                              ("validation (read-only)", "no")),
    (r"^_audit_|^audit_",                         ("audit (read-only)", "no")),
    (r"^_keyword_|^_backfill",                    ("process", "yes")),
    (r"^apply_session_patch",                     ("patch applicator (REUSABLE)", "yes")),
    (r"^(backup_|mirror_)",                       ("backup / mirror (REUSABLE)", "writes backups")),
    (r"^(_apply_verse_read|_cc_verse_read)",      ("verse-read pipeline (REUSABLE)", "yes")),
]

VERSION_DATE = re.compile(r"(_v\d+)?(_\d{8})?(\.py|\.ps1)$")
VN = re.compile(r"_v(\d+)")
DT = re.compile(r"_(\d{8})")


def classify(name):
    for pat, res in CLASS_RULES:
        if re.match(pat, name):
            return res
    return ("uncategorised", "?")


def base_name(name):
    """Strip a trailing _vN and/or _YYYYMMDD and the extension to get the canonical base."""
    stem = re.sub(r"\.(py|ps1)$", "", name)
    stem = re.sub(r"_v\d+(_\d{8})?$", "", stem)
    stem = re.sub(r"_\d{8}$", "", stem)
    return stem


def sort_key(name):
    v = VN.search(name); d = DT.search(name)
    return (int(d.group(1)) if d else 0, int(v.group(1)) if v else 0)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", required=True)
    args = ap.parse_args()

    files = [f for f in os.listdir(SCRIPTS) if f.endswith((".py", ".ps1")) and f != "__init__.py"]
    analytics = []
    adir = os.path.join(SCRIPTS, "analytics")
    if os.path.isdir(adir):
        analytics = [f for f in os.listdir(adir) if f.endswith(".py") and f != "__init__.py"]

    # group by base name to find version duplicates
    groups = defaultdict(list)
    for f in files:
        groups[base_name(f)].append(f)

    class_counts = defaultdict(int)
    superseded = []  # (older, current)
    for base, members in groups.items():
        for f in members:
            class_counts[classify(f)[0]] += 1
        if len(members) > 1:
            ms = sorted(members, key=sort_key, reverse=True)
            current, *older = ms
            for o in older:
                superseded.append((o, current))

    lines = []
    lines.append("# Script Registry (generated) — mechanical classification\n")
    lines.append("> Generated by `scripts/build_script_registry.py` (read-only). Classifies every top-level "
                 "`scripts/` file by naming-convention prefix and flags multi-version duplicates as supersession "
                 "candidates. The CURATED canonical reusable list is `docs/reusable-scripts-catalogue.md`; this is "
                 "the exhaustive mechanical companion. Regenerate after adding/removing scripts.\n")
    lines.append(f"_Total top-level scripts: {len(files)} · analytics library: {len(analytics)} · "
                 f"distinct base names: {len(groups)} · supersession candidates: {len(superseded)}._\n")

    lines.append("## Class breakdown\n")
    lines.append("| Class | Count |")
    lines.append("| --- | --- |")
    for cls, n in sorted(class_counts.items(), key=lambda x: -x[1]):
        lines.append(f"| {cls} | {n} |")
    lines.append("")

    lines.append("## Supersession candidates (multiple versions of one base — keep latest, archive older)\n")
    if superseded:
        lines.append("| Older (archive candidate) | Current (latest) |")
        lines.append("| --- | --- |")
        for o, c in sorted(superseded):
            lines.append(f"| `{o}` | `{c}` |")
    else:
        lines.append("_None._")
    lines.append("")
    lines.append("> ⚠ These are *mechanical* candidates from version suffixes. A few may be intentionally kept "
                 "(e.g. per-cluster `_build_m##_phase9_*` are distinct, not versions). Confirm before archiving.\n")

    lines.append("## All scripts by class\n")
    by_class = defaultdict(list)
    for f in files:
        by_class[classify(f)[0]].append(f)
    for cls in sorted(by_class):
        lines.append(f"### {cls}  ({len(by_class[cls])})")
        for f in sorted(by_class[cls]):
            lines.append(f"- `{f}`")
        lines.append("")

    lines.append("## analytics/ library (import, not run)\n")
    for f in sorted(analytics):
        lines.append(f"- `scripts/analytics/{f}`")

    out = os.path.join(ROOT, args.out) if not os.path.isabs(args.out) else args.out
    os.makedirs(os.path.dirname(out), exist_ok=True)
    with open(out, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines))
    print("Wrote", out)
    print(f"  scripts={len(files)} bases={len(groups)} superseded_candidates={len(superseded)}")


if __name__ == "__main__":
    main()
