"""narrative handler — structural validation for inner-being narratives written from a book's
passage debates. Config-governed, matching `handlers/passage.py:validate`'s shape.

**What this checks, and what it deliberately does not** (see `WA-inner-being-narrative-guidance-
v1-2026-07-28.md` §4 for the full reasoning). This is a presence check on one specific,
previously-found failure mode — a narrative silently narrowing its own stated scope by dropping
one of the three channels (non-human<->human, human<->human, physical world<->human) an inner
state can be reached through, found 2026-07-28 when a summary of the second Daniel narrative
narrowed "transfer... from the outside, and other humans" down to person-to-person only. It does
NOT judge whether a narrative's content is good, whether its citations are accurate, or whether it
correctly applies the passage debates it draws from — those remain the researcher's/writer's own
read, the same boundary every other quality-check in this app respects.
"""

from __future__ import annotations

import pathlib
import re

from .base import Ctx, Outcome, ok, fail
from ..lib import narrativegenerate, reportkit

# Fallback only — the real value is `cfg_enum` group `narrative_required_channel` (added
# 2026-07-29, closing a completeness gap: the exact fact this whole check exists to enforce used
# to live only here, in code, with no config counterpart at all). Kept byte-identical so behaviour
# is unchanged whether or not the cfg_enum rows have been approved yet.
_REQUIRED_LABELS_FALLBACK = ("Non-human ↔ human", "Human ↔ human", "Physical world ↔ human")

_SECTION_RE = re.compile(r"^##\s+Scope self-check\s*$", re.IGNORECASE | re.MULTILINE)
_NEXT_H2_RE = re.compile(r"^##\s+\S", re.MULTILINE)
_FILL_IN_MARKER = "<!-- fill in"


class GuidanceDocMissing(Exception):
    """`method.inner_being_narrative_guidance_path` points at a file that isn't on disk."""


def _guidance_doc(cfg) -> pathlib.Path:
    raw = cfg.setting("method.inner_being_narrative_guidance_path")
    if not raw:
        raise GuidanceDocMissing(
            "'method.inner_being_narrative_guidance_path' has no cfg_setting value — run "
            "bootstrap_book_narrative_validate")
    path = pathlib.Path(raw)
    if not path.exists():
        raise GuidanceDocMissing(f"{path} does not exist on disk — the config is stale")
    return path


def _extract_section(text: str) -> str | None:
    m = _SECTION_RE.search(text)
    if not m:
        return None
    body_start = text.index("\n", m.end()) + 1 if "\n" in text[m.end():] else len(text)
    nxt = _NEXT_H2_RE.search(text, body_start)
    return text[body_start: nxt.start() if nxt else len(text)]


def _required_labels(ctx: Ctx) -> tuple[str, ...]:
    return tuple(ctx.cfg.enum("narrative_required_channel")) or _REQUIRED_LABELS_FALLBACK


def _check_labels(section: str, required_labels: tuple[str, ...]) -> dict[str, str]:
    """{label: finding} — finding is 'ok', 'missing', or 'empty' (placeholder never filled in)."""
    findings: dict[str, str] = {}
    for label in required_labels:
        pat = re.compile(
            r"-\s*\*\*" + re.escape(label) + r":\*\*\s*(.*)", re.IGNORECASE)
        m = pat.search(section)
        if not m:
            findings[label] = "missing"
            continue
        content = m.group(1).strip()
        if not content or _FILL_IN_MARKER in content:
            findings[label] = "empty"
        else:
            findings[label] = "ok"
    return findings


def _write_report(cfg, path: pathlib.Path, findings: dict[str, str] | None,
                  section_found: bool) -> pathlib.Path:
    out_path = pathlib.Path(cfg.setting(
        "narrative.scope_check_report_path", "iba/app/reports/book-narrative-scope-check.md"))
    intro = [
        f"> Generated by `report.book_narrative_validate` against `{path}`. Structural presence "
        f"check only — see `WA-inner-being-narrative-guidance-v1-2026-07-28.md` §4 for what this "
        f"does and does not confirm.",
    ]
    if not section_found:
        body = ["**No `## Scope self-check` section found.** All three channel citations missing."]
    else:
        body = [f"- **{label}:** {finding}" for label, finding in findings.items()]
    sections = {"findings": body}
    L = reportkit.render_scaffold(cfg.conn, "report.book_narrative_validate", sections,
                                  intro=intro, path=str(path))
    out_path = reportkit.write_report(cfg.conn, "report.book_narrative_validate", out_path, L)
    return out_path


def validate(ctx: Ctx) -> Outcome:
    try:
        guidance_path = _guidance_doc(ctx.cfg)
    except GuidanceDocMissing as e:
        return fail("guidance-doc-missing", str(e))

    path_param = ctx.params.get("Path")
    if not path_param:
        return fail("no-path-given", "'-Path' is required — the narrative file to check")
    path = pathlib.Path(path_param)
    if not path.exists():
        return fail("narrative-file-missing", f"{path} does not exist on disk")

    text = path.read_text(encoding="utf-8")
    section = _extract_section(text)

    if section is None:
        report_path = _write_report(ctx.cfg, path, None, section_found=False)
        return fail("scope-check-missing",
                   f"no '## Scope self-check' section found in {path} — see {guidance_path} §3; "
                   f"detail in {report_path}")

    required_labels = _required_labels(ctx)
    findings = _check_labels(section, required_labels)
    report_path = _write_report(ctx.cfg, path, findings, section_found=True)
    problems = {label: f for label, f in findings.items() if f != "ok"}
    if problems:
        return fail("scope-check-incomplete",
                   f"{len(problems)} of {len(required_labels)} required channel(s) missing or "
                   f"empty in {path}'s Scope self-check: {problems} — detail in {report_path}")

    return ok(f"all {len(required_labels)} channels present and filled in {path}",
             path=str(report_path))


def generate(ctx: Ctx) -> Outcome:
    """Assemble a book's filled debates + the two governing docs, then make ONE live Anthropic API
    call and file the result. See `lib/narrativegenerate.py`'s module docstring for the full
    cost/config mechanism.

    escalation #798/#799 SS3.4: no longer a pause-continue approval step. `narrative.
    generate_max_cost` is itself the approval, already enforced below as a hard `fail()` when
    exceeded -- asking again for every call that's already within the approved cap added a
    decision that wasn't needed (researcher, 2026-08-22: "if spend above then it is a failure...
    an approved specification is the approval"). Any call within the cap now completes in one
    invocation; only exceeding the cap still needs a decision, and that was already correctly a
    `fail()`, unaffected by this change."""
    book = ctx.params["Book"]
    book_label = ctx.params.get("BookLabel") or book
    try:
        package = narrativegenerate.assemble_package(ctx.cfg, book, book_label)
    except narrativegenerate.NoDebatesFound as e:
        return fail("no-debates-found", str(e))
    except narrativegenerate.MethodDocMissing as e:
        return fail("guidance-doc-missing", str(e))

    max_cost = float(ctx.cfg.setting("narrative.generate_max_cost", 3.00))
    if package["est_cost_usd"] > max_cost:
        return fail("cost-cap-exceeded",
                   f"estimated cost ${package['est_cost_usd']:.2f} exceeds narrative."
                   f"generate_max_cost (${max_cost:.2f}) for {book_label} — raise the cap via "
                   f"configmaint.propose or lower narrative.generate_max_output_tokens")

    missing_note = (f" ({len(package['missing_debates'])} debate file(s) missing on disk, "
                    f"skipped: {package['missing_debates']})" if package["missing_debates"] else "")

    try:
        result = narrativegenerate.call_api(package)
    except narrativegenerate.ApiKeyMissing as e:
        return fail("api-key-missing", str(e))
    except narrativegenerate.ApiCallFailed as e:
        return fail("api-error", str(e))
    rate_in = float(ctx.cfg.setting("narrative.rate_input_per_million", 3.00))
    rate_out = float(ctx.cfg.setting("narrative.rate_output_per_million", 15.00))
    real_cost = (result["input_tokens"] / 1_000_000 * rate_in +
                result["output_tokens"] / 1_000_000 * rate_out)
    out = narrativegenerate.write_narrative(ctx.cfg, book, book_label, result["text"])
    log_path = narrativegenerate.log_usage(
        ctx.cfg, ctx.run_id, book, package["model"], result["input_tokens"],
        result["output_tokens"], real_cost, str(out))
    return ok(f"wrote {out} — {result['input_tokens']:,} in / {result['output_tokens']:,} out "
             f"tokens, ${real_cost:.4f} (logged to {log_path}){missing_note}",
             path=str(out), input_tokens=result["input_tokens"],
             output_tokens=result["output_tokens"], cost_usd=round(real_cost, 4))
