"""purge.py -- app-wide soft-delete purge audit (escalation #1766, researcher approved build
2026-09-19: "Approve to build. Do not run a purge as yet.").

Read-only. For every table with a registered soft-delete column (`cfg_column.name` IN
`deleted`/`delete_flagged`, across BOTH `iba` and `bible_research`), counts soft-deleted rows; for
any table over `purge.unsafe_check_min_soft_deleted`, checks `cfg_column.fk` for a live row
elsewhere still referencing one of its soft-deleted PKs and flags the table UNSAFE if so. Persists
a report every run (governance.reports_must_persist). Removes nothing -- the removal capability is
a separate, not-yet-designed follow-up (dependency-aware purge order / retention window still open).
"""

from __future__ import annotations

import pathlib
import sqlite3

from .base import Ctx, Outcome, ok
from ..lib import reportkit


def _soft_delete_tables(conn: sqlite3.Connection, database: str) -> list[tuple[str, str]]:
    return [(r["table_name"], r["name"]) for r in conn.execute(
        "SELECT table_name, name FROM cfg_column WHERE database=? AND name IN "
        "('deleted','delete_flagged') AND inactive=0", (database,))]


def _pk_col(conn: sqlite3.Connection, database: str, table: str) -> str:
    r = conn.execute("SELECT name FROM cfg_column WHERE database=? AND table_name=? AND is_pk=1",
                     (database, table)).fetchone()
    return r["name"] if r else "id"


def _delete_col_for(conn: sqlite3.Connection, database: str, table: str) -> str | None:
    r = conn.execute("SELECT name FROM cfg_column WHERE database=? AND table_name=? AND name IN "
                     "('deleted','delete_flagged') AND inactive=0", (database, table)).fetchone()
    return r["name"] if r else None


def _fk_referencing(conn: sqlite3.Connection, database: str, target_table: str) -> list[tuple[str, str]]:
    return [(r["table_name"], r["name"]) for r in conn.execute(
        "SELECT table_name, name FROM cfg_column WHERE database=? AND fk LIKE ?",
        (database, f"{target_table}.%"))]


def _audit_database(iba_conn: sqlite3.Connection, data_conn: sqlite3.Connection, database: str,
                    unsafe_threshold: int) -> dict:
    """`iba_conn` always reads cfg_column (config lives in iba.db regardless of which database's
    data is being audited); `data_conn` reads the actual row counts, which for database='bible_research'
    is a SEPARATE connection to that file (sqlite3 does not enforce FKs across attached databases,
    so this checks logical references via cfg_column.fk, not a real FK constraint)."""
    safe: list[dict] = []
    unsafe: list[dict] = []
    for table, col in _soft_delete_tables(iba_conn, database):
        try:
            cnt = data_conn.execute(f'SELECT COUNT(*) FROM "{table}" WHERE "{col}"=1').fetchone()[0]
        except sqlite3.OperationalError:
            continue
        if cnt == 0:
            continue
        pk = _pk_col(iba_conn, database, table)
        if cnt <= unsafe_threshold:
            safe.append({"table": table, "count": cnt, "pk": pk, "checked": False})
            continue
        refs = _fk_referencing(iba_conn, database, table)
        unsafe_refs = []
        for ref_table, ref_col in refs:
            ref_del_col = _delete_col_for(iba_conn, database, ref_table)
            live_clause = f'AND "{ref_del_col}"=0' if ref_del_col else ""
            try:
                at_risk = data_conn.execute(
                    f'SELECT COUNT(*) FROM "{ref_table}" r WHERE r."{ref_col}" IN '
                    f'(SELECT "{pk}" FROM "{table}" WHERE "{col}"=1) {live_clause}'
                ).fetchone()[0]
            except sqlite3.OperationalError:
                continue
            if at_risk > 0:
                unsafe_refs.append({"ref_table": ref_table, "ref_col": ref_col, "at_risk": at_risk})
        row = {"table": table, "count": cnt, "pk": pk, "checked": True}
        if unsafe_refs:
            row["unsafe_refs"] = unsafe_refs
            unsafe.append(row)
        else:
            safe.append(row)
    return {"safe": safe, "unsafe": unsafe}


def _write_report(ctx: Ctx, results: dict) -> str:
    intro = [
        f"> Generated by `purge.audit` (escalation #1766). Read-only -- counts soft-deleted rows "
        f"per registered soft-delete column across both databases, flags a table UNSAFE to bulk-"
        f"purge if a live row elsewhere still references one of its soft-deleted PKs. Removes "
        f"nothing.",
    ]
    lines_safe = ["| database | table | soft_deleted | pk | dependency-checked |",
                  "|---|---|---|---|---|"]
    lines_unsafe = ["| database | table | soft_deleted | referenced by (table.column) | live rows at risk |",
                    "|---|---|---|---|---|"]
    total_safe = total_unsafe = 0
    for database, r in results.items():
        for row in sorted(r["safe"], key=lambda x: -x["count"]):
            lines_safe.append(f"| {database} | {row['table']} | {row['count']:,} | {row['pk']} | "
                              f"{'yes' if row['checked'] else 'no (at/under threshold)'} |")
            total_safe += 1
        for row in sorted(r["unsafe"], key=lambda x: -x["count"]):
            first = True
            for ref in row["unsafe_refs"]:
                table_cell = f"**{row['table']}**" if first else ""
                db_cell = database if first else ""
                cnt_cell = f"{row['count']:,}" if first else ""
                lines_unsafe.append(f"| {db_cell} | {table_cell} | {cnt_cell} | "
                                    f"{ref['ref_table']}.{ref['ref_col']} | {ref['at_risk']:,} |")
                first = False
            total_unsafe += 1
    sections = {
        "summary": [f"{total_safe} table(s) safe to purge, {total_unsafe} table(s) UNSAFE "
                    f"(live dependency risk)."],
        "safe": lines_safe,
        "unsafe": lines_unsafe if total_unsafe else ["_(none)_"],
    }
    path = ctx.cfg.required_setting("purge.audit_report_path")
    L = reportkit.render_scaffold(ctx.db.conn, "purge.audit", sections, intro=intro)
    written = reportkit.write_report(ctx.db.conn, "purge.audit", pathlib.Path(path), L)
    return str(written)


def audit(ctx: Ctx) -> Outcome:
    threshold = int(ctx.cfg.setting("purge.unsafe_check_min_soft_deleted", 10))
    iba_conn = ctx.db.conn

    results = {}
    results["iba"] = _audit_database(iba_conn, iba_conn, "iba", threshold)

    research_path = ctx.cfg.database_path("bible_research")
    research_conn = sqlite3.connect(research_path)
    research_conn.row_factory = sqlite3.Row
    try:
        results["bible_research"] = _audit_database(iba_conn, research_conn, "bible_research",
                                                     threshold)
    finally:
        research_conn.close()

    report_path = _write_report(ctx, results)
    total_safe = sum(len(r["safe"]) for r in results.values())
    total_unsafe = sum(len(r["unsafe"]) for r in results.values())
    return ok(f"{total_safe} table(s) safe to purge, {total_unsafe} UNSAFE -- report written to "
             f"{report_path}", safe_count=total_safe, unsafe_count=total_unsafe)
